import test from "node:test";
import assert from "node:assert/strict";
import { BookingAmendmentManager, type BookingAmendmentDependencies, type BookingContract } from "../domains/shortlet/src/index.js";
import { createPlatformCommandEnvelope, type CommandPrincipal } from "../packages/platform-core/src/index.js";

function contract(): BookingContract { return { contractId: "ctr-amend-1", reservationId: "res-amend-1", offerId: "off-1", unitId: "unit-1", tenantId: "tenant-1", parties: { primaryGuest: { id: "guest-1", name: "Ada" }, operator: { id: "op-1" }, distinctPayer: null }, dates: { checkIn: "2026-08-20", checkOut: "2026-08-25", nights: 5 }, occupants: [{ name: "Ada" }], quote: { allInStayTotalKobo: 50000, refundableSecurityDepositKobo: 10000, currency: "NGN", cancellation: "captured" }, totalAmountDueNowKobo: 50000, policies: { cancellationPolicy: { version: "v1" }, guestConductRules: ["No smoking"] }, paymentDetails: { paymentMethod: "fresh_card", pspReference: "original", amountKobo: 50000, currency: "NGN", paidAt: "2026-08-01T00:00:00Z", cardMetadata: { brand: "Visa", last4: "1234" } }, createdAt: "2026-08-01T00:00:00Z", contractVersion: 1, checkout: { time: "11:00", timezone: "Africa/Lagos", source: "contractual" }, financialSummary: { originalBookingTotalKobo: 50000, currentContractTotalKobo: 50000, currency: "NGN", amendmentAdjustments: [] } }; }
function setup(withSettlement = true) { let current = contract(); const quoteProvider = { quote: ({ resultingDates }: { resultingDates: { nights: number } }) => ({ quoteId: "quote-current", quoteVersion: "2", currency: "NGN" as const, revisedAllInStayTotalKobo: resultingDates.nights === 6 ? 60000 : 50000, financialAdjustment: resultingDates.nights === 6 ? { type: "additional_collection" as const, amountKobo: 10000, currency: "NGN" as const } : { type: "none" as const, amountKobo: 0, currency: "NGN" as const } }) }; const deps = { contractRepository: { getContract: () => current, mutateContract: (_id: string, expected: number, mutation: (c: BookingContract) => BookingContract) => { if (current.contractVersion !== expected) throw new Error("STALE_ACTION"); current = mutation(current); return current; } }, calendar: { getAuthoritativeAvailability: () => ({ isAvailable: true, version: "a1" }), hasSameDayCheckInOnDate: () => false }, inspectionRepository: { isPassedAndValidThrough: () => ({ valid: true, version: "i1" }) }, authorityRepository: { isValidThrough: () => ({ valid: true, version: "m1" }) }, quoteProvider, ...(withSettlement ? { settlementProvider: { settle: ({ amendmentId, contractId, adjustment, quote }: { amendmentId: string; contractId: string; adjustment: { type: "additional_collection" | "refund" | "none"; amountKobo: number; currency: "NGN" }; quote: { quoteId: string; quoteVersion: string | number } }) => ({ settlementId: "set-1", amendmentId, contractId, type: adjustment.type, amountKobo: adjustment.amountKobo, currency: "NGN" as const, status: "settled" as const, quoteId: quote.quoteId, quoteVersion: quote.quoteVersion }) } } : {}) }; return { deps, get: () => current }; }
const guest: CommandPrincipal = { id: "guest-1", role: "guest", tenantId: "tenant-1" };
const system: CommandPrincipal = { id: "settlement-service", role: "system", tenantId: "tenant-1" };
const command = <T>(name: string, principal: CommandPrincipal, payload: T) => createPlatformCommandEnvelope({ commandName: name, principal, payload });
const clock = () => new Date("2026-08-10T10:00:00Z");

test("manager construction fails without quote provider and atomic mutation", () => { const { deps } = setup(); const missing = { ...deps, quoteProvider: undefined }; assert.throws(() => new BookingAmendmentManager(missing as unknown as BookingAmendmentDependencies), /quoteProvider/); const nonAtomic = { ...deps, contractRepository: { getContract: deps.contractRepository.getContract, mutateContract: undefined } }; assert.throws(() => new BookingAmendmentManager(nonAtomic as unknown as BookingAmendmentDependencies), /atomic/); });
test("proposal creation uses only the authoritative quote and does not mutate contract", () => { const s = setup(); const manager = new BookingAmendmentManager(s.deps); const p = manager.requestAmendment(command("booking_amendment.request", guest, { contractId: "ctr-amend-1", changes: { dates: { checkIn: "2026-08-20", checkOut: "2026-08-26" } } }), clock); assert.equal(p.status, "proposed"); assert.equal(p.quote.revisedAllInStayTotalKobo, 60000); assert.equal(s.get().contractVersion, 1); });
test("financial amendment fails closed without trusted settlement and accepts no client settlement result", () => { const s = setup(false); const manager = new BookingAmendmentManager(s.deps); const p = manager.requestAmendment(command("booking_amendment.request", guest, { contractId: "ctr-amend-1", changes: { dates: { checkIn: "2026-08-20", checkOut: "2026-08-26" } } }), clock); manager.acceptAmendment(p.amendmentId, guest, clock); assert.throws(() => manager.commitAmendment(command("booking_amendment.commit", system, { amendmentId: p.amendmentId, settlement: { status: "settled" } }), clock), /Invalid amendment commit payload/); assert.equal(s.get().contractVersion, 1); });
test("accepted amendment revalidates and commits once while preserving booking economics", () => { const s = setup(); const manager = new BookingAmendmentManager(s.deps); const p = manager.requestAmendment(command("booking_amendment.request", guest, { contractId: "ctr-amend-1", changes: { dates: { checkIn: "2026-08-20", checkOut: "2026-08-26" } } }), clock); manager.acceptAmendment(p.amendmentId, guest, clock); const result = manager.commitAmendment(command("booking_amendment.commit", system, { amendmentId: p.amendmentId }), clock); assert.equal(result.newVersion, 2); assert.equal(s.get().quote && (s.get().quote as { allInStayTotalKobo: number }).allInStayTotalKobo, 60000); assert.equal((s.get().quote as { refundableSecurityDepositKobo: number }).refundableSecurityDepositKobo, 10000); assert.equal(s.get().paymentDetails.amountKobo, 50000); assert.throws(() => manager.commitAmendment(command("booking_amendment.commit", system, { amendmentId: p.amendmentId }), clock), /STALE_ACTION/); });
