import test from "node:test";
import assert from "node:assert/strict";
import { createPlatformCommandEnvelope, type CommandPrincipal } from "../packages/platform-core/src/index.js";
import { CardPaymentManager, BankTransferPaymentManager, InMemoryBookingPaymentJourneyRepository, InMemoryBookingStateRepository, InMemorySecurityDepositAccountingRepository, LivePaymentAttemptRegistry, type BookingContract, type ConditionalBookingOffer, type Reservation } from "../domains/shortlet/src/index.js";

const guest: CommandPrincipal = { id: "guest-final", role: "guest", tenantId: "tenant-final" };
const system: CommandPrincipal = { id: "system-final", role: "system", tenantId: "tenant-final" };
const offer = { offerId: "offer-final", offerVersion: 1, requestId: "request-final", inventoryCommitmentId: "commit-final", unitId: "unit-final", tenantId: "tenant-final", parties: { primaryGuest: { id: "guest-final", name: "Guest" }, operator: { id: "operator-final", name: "Operator" }, distinctPayer: null }, unit: { id: "unit-final", title: "Unit", propertyId: "property-final", location: {} }, dates: { checkIn: "2026-09-01", checkOut: "2026-09-03", nights: 2 }, occupants: [{ name: "Guest" }], quote: { allInStayTotalKobo: 18_000_000, currency: "NGN" }, refundableSecurityDepositKobo: 4_000_000, securityDeposit: { policyVersion: "security-deposit/adr-0063-launch-v1", currency: "NGN", accommodationSubtotalKobo: 18_000_000, bedroomBand: "two_bedroom", percentageCapKobo: 4_500_000, unitSizeCapKobo: 15_000_000, unitConfiguredDepositKobo: 4_000_000, amountKobo: 4_000_000, collectionRequired: true }, totalAmountDueNowKobo: 22_000_000, policies: { cancellationPolicy: {}, guestConductRules: [] }, disclosures: [], paymentWindow: { durationMinutes: 20, expiresAt: "2026-09-01T12:20:00.000Z" }, status: "accepted" as const, issuedAt: "2026-09-01T12:00:00.000Z", confirmationToken: "token", tokenUsed: true, aggregateVersions: { offerVersion: 1, pricingVersion: "p", quoteVersion: "q", cancellationPolicyVersion: "c", managementAuthorityVersion: "m", inspectionVersion: "i" } } as unknown as ConditionalBookingOffer;

class FailingBookingState extends InMemoryBookingStateRepository {
  override saveBookingAtomically(_input: { contract: BookingContract; reservation: Reservation }): void { throw new Error("forced BookingState failure"); }
}
function envelope<C extends string, P>(commandName: C, principal: CommandPrincipal, payload: P) { return createPlatformCommandEnvelope({ commandName, principal, payload }); }

test("Card finalization failure after both payments settled releases confirmed inventory and compensates both components", () => {
  const journeys = new InMemoryBookingPaymentJourneyRepository(); const accounting = new InMemorySecurityDepositAccountingRepository(); const state = new FailingBookingState(); let manager: CardPaymentManager; let refunds = 0; let confirmedRelease = 0; let pendingRelease = 0;
  manager = new CardPaymentManager({ offerManager: { getOffer: () => offer }, journeyRepository: journeys, securityDepositAccounting: accounting, bookingState: state, liveAttempts: new LivePaymentAttemptRegistry(), calendar: { transitionPaymentPendingToConfirmedBooking: () => undefined, releaseConfirmedBooking: () => { confirmedRelease++; }, releasePaymentPending: () => { pendingRelease++; } }, securityDepositCapability: { getCapability: () => ({ capabilityVersion: "cap", enabled: true, pspProviderId: "psp", pspApproved: true, counselApproved: true, collectionModel: "separate_actual_charge", paymentMethod: "fresh_card" }) }, pspClient: { verifyTransaction(reference) { const session = manager.getCheckoutSessionByReference(reference)!; return { verified: true, status: "success", amountKobo: session.amountKobo, currency: "NGN", pspReference: reference, payerId: guest.id }; } }, compensationRefundProvider: { refundOrGet: (input) => ({ refundId: `refund-${++refunds}`, status: refunds === 2 ? "pending" : "settled", amountKobo: input.amountKobo, currency: "NGN" }) } });
  const initialize = () => manager.initializeCardCheckout(envelope("card_payment.initialize_checkout", guest, { offerId: offer.offerId })); const verify = (reference: string) => manager.verifyAndConfirmCardPayment(envelope("card_payment.verify_and_confirm", system, { offerId: offer.offerId, pspReference: reference }));
  const stay = initialize(); verify(stay.pspReference); const deposit = initialize(); assert.throws(() => verify(deposit.pspReference), /forced BookingState/);
  const failed = journeys.findByOfferId(offer.offerId)!; assert.equal(failed.compensation.status, "pending"); assert.equal(failed.compensation.deposit.status, "pending"); assert.equal(accounting.getByOfferId(offer.offerId)?.status, "refund_pending"); assert.equal(state.findContractById("ctr_missing"), null); assert.equal(state.findReservationById("res_missing"), null); assert.equal(confirmedRelease, 1); assert.equal(pendingRelease, 0);
  assert.throws(() => verify(deposit.pspReference), /compensation/); const completed = journeys.findByOfferId(offer.offerId)!; assert.equal(completed.compensation.status, "settled"); assert.equal(completed.stage, "compensated"); assert.equal(accounting.journals().length, 2);
});

test("Bank finalization failure after both transfers settled releases confirmed inventory and compensates both components", () => {
  const journeys = new InMemoryBookingPaymentJourneyRepository(); const accounting = new InMemorySecurityDepositAccountingRepository(); const state = new FailingBookingState(); let manager: BankTransferPaymentManager; let refunds = 0; let confirmedRelease = 0; let pendingRelease = 0;
  manager = new BankTransferPaymentManager({ offerManager: { getOffer: () => offer }, journeyRepository: journeys, securityDepositAccounting: accounting, bookingState: state, liveAttempts: new LivePaymentAttemptRegistry(), calendar: { transitionPaymentPendingToConfirmedBooking: () => undefined, releaseConfirmedBooking: () => { confirmedRelease++; }, releasePaymentPending: () => { pendingRelease++; } }, securityDepositCapability: { getCapability: () => ({ capabilityVersion: "cap", enabled: true, pspProviderId: "psp", pspApproved: true, counselApproved: true, collectionModel: "separate_actual_charge", paymentMethod: "bank_transfer" }) }, providerClient: { verifyTransfer(reference) { const session = manager.getSessionByReference(reference)!; return { verified: true, status: "success", amountKobo: session.amountKobo, currency: "NGN", pspReference: reference, payerId: guest.id }; } }, compensationRefundProvider: { refundOrGet: (input) => ({ refundId: `refund-${++refunds}`, status: refunds === 2 ? "pending" : "settled", amountKobo: input.amountKobo, currency: "NGN" }) } });
  const initialize = () => manager.initializeBankTransfer(envelope("bank_transfer.initialize", guest, { offerId: offer.offerId })); const verify = (reference: string) => manager.verifyAndProcessTransfer(envelope("bank_transfer.verify_and_process", system, { transferReference: reference }));
  const stay = initialize(); verify(stay.transferReference); const deposit = initialize(); assert.throws(() => verify(deposit.transferReference), /forced BookingState/);
  const failed = journeys.findByOfferId(offer.offerId)!; assert.equal(failed.compensation.status, "pending"); assert.equal(failed.compensation.deposit.status, "pending"); assert.equal(accounting.getByOfferId(offer.offerId)?.status, "refund_pending"); assert.equal(confirmedRelease, 1); assert.equal(pendingRelease, 0);
  assert.throws(() => verify(deposit.transferReference), /compensation/); const completed = journeys.findByOfferId(offer.offerId)!; assert.equal(completed.compensation.status, "settled"); assert.equal(completed.stage, "compensated"); assert.equal(accounting.journals().length, 2);
});
