import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { AvailabilityCalendar } from "../domains/shortlet/src/availability.js";
import { BankTransferPaymentManager, type BankTransferProviderResult } from "../domains/shortlet/src/bank-transfer.js";
import type { ConditionalBookingOffer } from "../domains/shortlet/src/conditional-offer.js";
import type { PlatformCommandEnvelope, CommandPrincipal } from "../packages/platform-core/src/index.js";

const T0 = new Date("2026-07-22T10:00:00Z");
function offer(id = "offer-11", tenantId: string | undefined = "tenant-11"): ConditionalBookingOffer { return { offerId: id, offerVersion: 1, requestId: "request", inventoryCommitmentId: `commit-${id}`, unitId: "unit-11", tenantId, parties: { primaryGuest: { id: "guest-11", name: "Guest Eleven" }, operator: { id: "operator", name: "Operator" }, distinctPayer: null }, unit: { id: "unit-11", title: "Unit Eleven", propertyId: "property", location: { city: "Lagos" } }, dates: { checkIn: "2026-08-01", checkOut: "2026-08-05", nights: 4 }, occupants: [{ name: "Guest Eleven" }], quote: { breakdown: { accommodationNetKobo: 8_000_000, platformCommissionKobo: 2_000_000 } }, totalAmountDueNowKobo: 12_000_000, refundableSecurityDepositKobo: 2_000_000, policies: { cancellationPolicy: {}, guestConductRules: [] }, disclosures: [], paymentWindow: { durationMinutes: 20, expiresAt: new Date(T0.getTime() + 1_200_000).toISOString() }, status: "accepted", issuedAt: T0.toISOString(), acceptedAt: T0.toISOString(), confirmationToken: "token", tokenUsed: true, aggregateVersions: { offerVersion: 1, pricingVersion: "v1", quoteVersion: "v1", cancellationPolicyVersion: "v1", managementAuthorityVersion: "v1", inspectionVersion: "v1" } }; }
function command<T>(commandName: string, payload: T, principal: CommandPrincipal = { id: "guest-11", role: "guest", tenantId: "tenant-11" }): PlatformCommandEnvelope<T> { return { commandId: `${commandName}-${Math.random()}`, commandName, principal, payload, timestamp: T0.toISOString() }; }
function calendarFor(o: ConditionalBookingOffer): { calendar: AvailabilityCalendar; commitmentId: string } { const c = new AvailabilityCalendar(); const b = c.createBookingRequestBlock({ unitId: o.unitId, holderId: o.parties.primaryGuest.id, start: o.dates.checkIn, end: o.dates.checkOut, clock: () => T0 }); c.transitionBookingRequestBlockToPaymentPending({ commitmentId: b.commitmentId, unitId: o.unitId, start: o.dates.checkIn, end: o.dates.checkOut, clock: () => T0 }); return { calendar: c, commitmentId: b.commitmentId }; }
function success(reference: string, o: ConditionalBookingOffer): BankTransferProviderResult { return { verified: true, status: "success", amountKobo: o.totalAmountDueNowKobo, currency: "NGN", pspReference: reference, payerId: "guest-11" }; }
function setup(o = offer()) { let result: BankTransferProviderResult; const provider = { verifyTransfer: () => { if (!result) throw new Error("fake provider result not configured"); return result; } }; const prepared = calendarFor(o); const authoritativeOffer = { ...o, inventoryCommitmentId: prepared.commitmentId }; const manager = new BankTransferPaymentManager({ offerManager: { getOffer: () => authoritativeOffer }, calendar: prepared.calendar, providerClient: provider }); const session = manager.initializeBankTransfer(command("bank_transfer.initialize", { offerId: o.offerId }), { clock: () => T0 }); return { manager, session, calendar: prepared.calendar, setResult: (r: BankTransferProviderResult) => { result = r; }, o: authoritativeOffer }; }
function server(): CommandPrincipal { return { id: "payment-worker", role: "system", tenantId: "tenant-11" }; }

describe("Issue 11: bank transfer expiry and late refund", () => {
  it("Only one Live Payment Attempt and reference may exist for the offer", () => { const s = setup(); const again = s.manager.initializeBankTransfer(command("bank_transfer.initialize", { offerId: s.o.offerId }), { clock: () => new Date(T0.getTime() + 60_000) }); assert.equal(again.transferReference, s.session.transferReference); assert.throws(() => s.manager.initializeBankTransfer(command("bank_transfer.initialize", { offerId: s.o.offerId }, { id: "operator", role: "operator", tenantId: "tenant-11" }), { clock: () => T0 }), /payer/); });
  it("Initialization fails closed for wrong payer, Operator, wrong tenant, and missing tenant", () => { for (const p of [{ id: "other", role: "guest" as const, tenantId: "tenant-11" }, { id: "operator", role: "operator" as const, tenantId: "tenant-11" }, { id: "guest-11", role: "guest" as const, tenantId: "other" }, { id: "guest-11", role: "guest" as const }]) assert.throws(() => new BankTransferPaymentManager({ offerManager: { getOffer: () => offer() }, providerClient: { verifyTransfer: () => { throw new Error("unused"); } } }).initializeBankTransfer(command("bank_transfer.initialize", { offerId: "offer-11" }, p), { clock: () => T0 }), /payer|tenant/); });
  it("Provider result cannot be supplied by the command and verification uses the injected client", () => { const s = setup(); assert.throws(() => s.manager.verifyAndProcessTransfer({ ...command("bank_transfer.verify_and_process", { transferReference: s.session.transferReference, verified: true } as unknown as { transferReference: string }, server()), principal: server() }), /accepts only transferReference/); s.setResult(success(s.session.transferReference, s.o)); assert.equal(s.manager.verifyAndProcessTransfer({ ...command("bank_transfer.verify_and_process", { transferReference: s.session.transferReference }, server()), principal: server() }, { clock: () => new Date(T0.getTime() + 600_000) }).outcome, "confirmed"); });
  it("Reference is bound to one authoritative offer and provider fields are validated", () => { const s = setup(); s.setResult({ ...success(s.session.transferReference, s.o), amountKobo: 1 }); assert.throws(() => s.manager.verifyAndProcessTransfer({ ...command("bank_transfer.verify_and_process", { transferReference: s.session.transferReference }, server()), principal: server() }, { clock: () => new Date(T0.getTime() + 600_000) }), /Amount/); });
  it("Exact T+20 and legitimate processing grace use pre-deadline provider evidence", () => { const s = setup(offer("grace")); s.setResult({ ...success(s.session.transferReference, s.o), status: "pending", processingStartedAt: new Date(T0.getTime() + 1_140_000).toISOString() }); assert.equal(s.manager.verifyAndProcessTransfer({ ...command("bank_transfer.verify_and_process", { transferReference: s.session.transferReference }, server()), principal: server() }, { clock: () => new Date(T0.getTime() + 1_200_000) }).outcome, "processing_in_grace"); s.setResult(success(s.session.transferReference, s.o)); assert.equal(s.manager.verifyAndProcessTransfer({ ...command("bank_transfer.verify_and_process", { transferReference: s.session.transferReference }, server()), principal: server() }, { clock: () => new Date(T0.getTime() + 1_500_000) }).outcome, "confirmed"); });
  it("Pending without pre-deadline evidence is not granted grace and becomes a late refund", () => { const s = setup(offer("no-grace")); s.setResult({ ...success(s.session.transferReference, s.o), status: "pending", processingStartedAt: new Date(T0.getTime() + 1_201_000).toISOString() }); assert.throws(() => s.manager.verifyAndProcessTransfer({ ...command("bank_transfer.verify_and_process", { transferReference: s.session.transferReference }, server()), principal: server() }, { clock: () => new Date(T0.getTime() + 1_300_000) }), /grace/); });
  it("Expiry at exactly T+30 releases the exact payment-pending commitment and is idempotent", () => { const s = setup(offer("expiry")); const p = server(); const first = s.manager.resolveExpiry(s.o.offerId, p, { clock: () => new Date(T0.getTime() + 1_800_000) }); const second = s.manager.resolveExpiry(s.o.offerId, p, { clock: () => new Date(T0.getTime() + 1_801_000) }); assert.equal(first.status, "expired"); assert.deepEqual(second, first); assert.equal(s.calendar.getAuthoritativeAvailability({ unitId: s.o.unitId, checkIn: s.o.dates.checkIn, checkOut: s.o.dates.checkOut, clock: () => new Date(T0.getTime() + 1_801_000) }).isAvailable, true); });
  it("Late success creates one refund and reconciliation, no Reservation or Booking Contract", () => { const s = setup(offer("late")); s.setResult(success(s.session.transferReference, s.o)); const first = s.manager.verifyAndProcessTransfer({ ...command("bank_transfer.verify_and_process", { transferReference: s.session.transferReference }, server()), principal: server() }, { clock: () => new Date(T0.getTime() + 2_100_000) }); const second = s.manager.verifyAndProcessTransfer({ ...command("bank_transfer.verify_and_process", { transferReference: s.session.transferReference }, server()), principal: server() }, { clock: () => new Date(T0.getTime() + 2_101_000) }); assert.equal(first.outcome, "late_payment_refunded"); assert.equal(second.refundRecord?.refundId, first.refundRecord?.refundId); assert.equal(second.reconciliationRecord?.reconciliationId, first.reconciliationRecord?.reconciliationId); assert.equal(first.reservation, undefined); assert.equal(first.bookingContract, undefined); });
  it("Duplicate confirmed callback returns the same Reservation, Contract, and ledger effects", () => { const s = setup(offer("confirmed")); s.setResult(success(s.session.transferReference, s.o)); const c = { ...command("bank_transfer.verify_and_process", { transferReference: s.session.transferReference }, server()), principal: server() }; const first = s.manager.verifyAndProcessTransfer(c, { clock: () => new Date(T0.getTime() + 600_000) }); const second = s.manager.verifyAndProcessTransfer(c, { clock: () => new Date(T0.getTime() + 601_000) }); assert.equal(second.reservation?.reservationId, first.reservation?.reservationId); assert.equal(second.bookingContract?.paymentDetails.paymentMethod, "bank_transfer"); assert.equal(second.ledgerEntries, first.ledgerEntries); });
});
