import assert from "node:assert/strict";
import test from "node:test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { DatabaseSync } from "node:sqlite";
import { LocalGuestEnvironment } from "../apps/local-guest/src/fixture.js";
import { SqliteGuestContactRepository, normalizeContactEmail, normalizeNigerianPhoneNumber } from "../domains/shortlet/src/index.js";
import { renderGuestContactHtml } from "../apps/local-guest/src/guest-server.js";
import { LocalApartmentOwnerEnvironment } from "../apps/local-owner/src/local-owner-environment.js";

function database() { const dir = mkdtempSync(join(tmpdir(), "guest-contact-")); return { dir, path: join(dir, "guest.sqlite") }; }
function draft(env: LocalGuestEnvironment) { return env.bookingRequestApp.createDraft({ unitId: "unit-lagos-ikoyi-001", primaryGuest: { id: env.config.guestId, name: env.config.guestName }, occupants: env.demoOccupants(2), selfBookingAttestation: env.selfBookingAttestation(), checkIn: "2026-09-10", checkOut: "2026-09-13" }, env.guestPrincipal()); }
function acceptedOffer(env: LocalGuestEnvironment): string { const request = env.bookingRequestApp.disclose(draft(env).draftId, env.guestPrincipal()); const { offerId } = env.simulateOperatorAcceptance(request.requestId); const offer = env.conditionalOfferApp.manager.getOffer(offerId); env.conditionalOfferApp.accept({ offerId, confirmationToken: offer.confirmationToken, expectedVersion: offer.offerVersion, principal: env.guestPrincipal() }); return offerId; }
function clean(env: LocalGuestEnvironment, dir: string) { env.close(); rmSync(dir, { recursive: true, force: true }); }

test("AC1 — Discovery does not require phone or email", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path, initialGuestPhoneNumber: null, initialGuestContactEmail: null }); try { assert.doesNotThrow(() => env.discoveryQuery.search({ city: "Lagos" })); } finally { clean(env, f.dir); } });
test("AC2 — Request Draft creation does not require phone or email", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path, initialGuestPhoneNumber: null, initialGuestContactEmail: null }); try { assert.ok(draft(env).draftId); } finally { clean(env, f.dir); } });
test("AC3 — Booking Request submission requires a valid phone number", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path, initialGuestPhoneNumber: null }); try { const d = draft(env); assert.throws(() => env.bookingRequestApp.disclose(d.draftId, env.guestPrincipal()), /phone number is required/i); } finally { clean(env, f.dir); } });
test("AC4 — Booking Request submission does not require email", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path, initialGuestContactEmail: null }); try { assert.ok(env.bookingRequestApp.disclose(draft(env).draftId, env.guestPrincipal()).requestId); } finally { clean(env, f.dir); } });
test("AC5 — A valid Nigerian local-format phone number is normalized to E.164", () => assert.equal(normalizeNigerianPhoneNumber("0801 234 5678"), "+2348012345678"));
test("AC6 — A valid +234 phone number remains canonical", () => assert.equal(normalizeNigerianPhoneNumber("+2348012345678"), "+2348012345678"));
test("AC7 — Malformed phone numbers are rejected", () => { for (const value of ["", "08012", "0801ABC5678", "08012345678999"]) assert.throws(() => normalizeNigerianPhoneNumber(value)); });
test("AC8 — Non-Nigerian numbers are rejected for the pilot", () => assert.throws(() => normalizeNigerianPhoneNumber("+447911123456")));
test("AC9 — The phone number survives refresh", () => { const db = new DatabaseSync(":memory:"); const repo = new SqliteGuestContactRepository(db); repo.savePhone({ guestId: "g", tenantId: "t", phoneNumber: "08012345678" }); assert.equal(repo.find("g", "t")?.phoneNumber, "+2348012345678"); db.close(); });
test("AC10 — The phone number survives server restart", () => { const f = database(); let env = new LocalGuestEnvironment({ databasePath: f.path, initialGuestPhoneNumber: null }); env.guestContactApp.submitPhone({ phoneNumber: "08012345678" }, env.guestPrincipal()); env.close(); env = new LocalGuestEnvironment({ databasePath: f.path, initialGuestPhoneNumber: null }); try { assert.equal(env.guestContactApp.get(env.guestPrincipal())?.phoneNumber, "+2348012345678"); } finally { clean(env, f.dir); } });
test("AC11 — Operator confirmation does not require email", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path, initialGuestContactEmail: null }); try { const r = env.bookingRequestApp.disclose(draft(env).draftId, env.guestPrincipal()); assert.ok(env.simulateOperatorAcceptance(r.requestId).offerId); } finally { clean(env, f.dir); } });
test("AC12 — Payment continuation requires a valid email", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path, initialGuestContactEmail: null }); try { const offerId = acceptedOffer(env); assert.throws(() => env.cardPaymentApp.initializeCheckout(offerId, env.guestPrincipal()), /email address is required/i); } finally { clean(env, f.dir); } });
test("AC13 — A valid email is stored successfully", () => { const db = new DatabaseSync(":memory:"); const repo = new SqliteGuestContactRepository(db); assert.equal(repo.saveEmail({ guestId: "g", tenantId: "t", contactEmail: " Guest@EXAMPLE.COM " }).contactEmail, "Guest@example.com"); db.close(); });
test("AC14 — Malformed email is rejected", () => { for (const value of ["x", "a@@b.com", "a@localhost", "a@b..com"]) assert.throws(() => normalizeContactEmail(value)); });
test("AC15 — Email survives refresh", () => { const db = new DatabaseSync(":memory:"); const repo = new SqliteGuestContactRepository(db); repo.saveEmail({ guestId: "g", tenantId: "t", contactEmail: "g@example.com" }); assert.equal(repo.find("g", "t")?.contactEmail, "g@example.com"); db.close(); });
test("AC16 — Email survives server restart", () => { const f = database(); let env = new LocalGuestEnvironment({ databasePath: f.path, initialGuestContactEmail: null }); env.guestContactApp.submitEmail({ contactEmail: "g@example.com" }, env.guestPrincipal()); env.close(); env = new LocalGuestEnvironment({ databasePath: f.path, initialGuestContactEmail: null }); try { assert.equal(env.guestContactApp.get(env.guestPrincipal())?.contactEmail, "g@example.com"); } finally { clean(env, f.dir); } });
test("AC17 — The browser cannot use contact submission to change payment amount", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path }); try { assert.equal(Object.hasOwn(env.guestContactApp.submitEmail({ contactEmail: "new@example.com" }, env.guestPrincipal()), "amountKobo"), false); } finally { clean(env, f.dir); } });
test("AC18 — The browser cannot use contact submission to change currency", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path }); try { assert.equal(Object.hasOwn(env.guestContactApp.submitPhone({ phoneNumber: "08099999999" }, env.guestPrincipal()), "currency"), false); } finally { clean(env, f.dir); } });
test("AC19 — Phone number is not emitted in telemetry", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path }); try { env.guestContactApp.submitPhone({ phoneNumber: "08099999999" }, env.guestPrincipal()); assert.doesNotMatch(JSON.stringify(env.telemetry.events()), /2348099999999/); } finally { clean(env, f.dir); } });
test("AC20 — Email is not emitted in telemetry", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path }); try { env.guestContactApp.submitEmail({ contactEmail: "private@example.com" }, env.guestPrincipal()); assert.doesNotMatch(JSON.stringify(env.telemetry.events()), /private@example/); } finally { clean(env, f.dir); } });
test("AC21 — Phone and email are not written to general logs", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path }); try { env.guestContactApp.submitPhone({ phoneNumber: "08099999999" }, env.guestPrincipal()); env.guestContactApp.submitEmail({ contactEmail: "private@example.com" }, env.guestPrincipal()); assert.doesNotMatch(JSON.stringify(env.audit.entries()), /2348099999999|private@example/); } finally { clean(env, f.dir); } });
test("AC22 — Authorized Operator request detail can access the phone only if approved by existing policy", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path }); let owner: LocalApartmentOwnerEnvironment | undefined; try { const r = env.bookingRequestApp.disclose(draft(env).draftId, env.guestPrincipal()); owner = new LocalApartmentOwnerEnvironment({ databasePath: f.path }); assert.equal(owner.operatorRequestDetail(r.requestId, owner.getRepresentativePrincipal()).facts.phoneNumber, "+2348012345678"); } finally { owner?.close(); clean(env, f.dir); } });
test("AC23 — Operator request lists do not expose contact data unnecessarily", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path }); let owner: LocalApartmentOwnerEnvironment | undefined; try { env.bookingRequestApp.disclose(draft(env).draftId, env.guestPrincipal()); owner = new LocalApartmentOwnerEnvironment({ databasePath: f.path }); assert.equal(JSON.stringify(owner.listOperatorRequestArtifacts(owner.getRepresentativePrincipal())).includes("+234"), false); } finally { owner?.close(); clean(env, f.dir); } });
test("AC24 — Operator does not receive Guest email without an explicit requirement", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path }); try { const r = env.bookingRequestApp.disclose(draft(env).draftId, env.guestPrincipal()); assert.equal(JSON.stringify(env.bookingRequestApp.getArtifact(r.requestId, env.representativePrincipal())).includes("guest@example.com"), false); } finally { clean(env, f.dir); } });
test("AC25 — Conventional routes use the same contact data and validation", () => { assert.equal(normalizeNigerianPhoneNumber("2348012345678"), "+2348012345678"); assert.throws(() => normalizeContactEmail("bad")); });
test("AC26 — Phone entry works at 320px", () => { const html = renderGuestContactHtml(null); assert.match(html, /max-width:320px/); assert.match(html, /type="tel" inputmode="tel" autocomplete="tel"/); });
test("AC27 — Email entry works at 320px", () => { const html = renderGuestContactHtml(null); assert.match(html, /max-width:320px/); assert.match(html, /type="email" inputmode="email" autocomplete="email"/); });
test("AC28 — The complete Guest journey passes through Booking Request using phone-only contact", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path, initialGuestContactEmail: null }); try { assert.equal(env.bookingRequestApp.disclose(draft(env).draftId, env.guestPrincipal()).status, "disclosed"); } finally { clean(env, f.dir); } });
test("AC29 — The complete confirmed-offer journey reaches the payment boundary after email is supplied", () => { const f = database(); const env = new LocalGuestEnvironment({ databasePath: f.path }); try { const session = env.cardPaymentApp.initializeCheckout(acceptedOffer(env), env.guestPrincipal()); assert.equal(session.contactEmail, "guest@example.com"); } finally { clean(env, f.dir); } });
