import test from "node:test";
import assert from "node:assert/strict";
import { InMemoryRevenueAccountingRepository, RepositoryEarnedCommissionSource, journal, type RevenueAdjustmentRecord } from "../domains/shortlet/src/revenue-accounting.js";
import { setupRevenueRelease as setup, revenueNow as now, revenuePrincipal as principal } from "./revenue-release-fixtures.js";
test("Production Revenue Release uses authoritative state, exact 24-hour boundary, captured commission, and balanced Fast Payout", () => { const s = setup(); const release = s.app.releaseRevenue("reservation-1", principal); assert.equal(release.releaseId, "revenue-release:reservation-1"); assert.equal(release.commissionRate, 0.08); assert.equal(release.commissionBaseKobo, 123457); assert.equal(release.commissionKobo, 9876); assert.equal(release.operatorNetKobo, 113470); assert.equal(release.payableNowKobo + release.routineReserveTrancheKobo + release.riskHoldKobo, release.operatorNetKobo); assert.equal(s.accounting.findLedgerEntriesForRelease(release.releaseId)[0].balanced, true); assert.equal(new RepositoryEarnedCommissionSource(s.accounting).getEarnedCommission(release.releaseId)?.earnedCommissionKobo, 9876); assert.strictEqual(s.app.releaseRevenue("reservation-1", principal), release); });

test("Production Revenue Release rejects awaiting access and cancelled Reservation", () => { assert.throws(() => setup({ accessStatus: "awaiting_access" }).app.releaseRevenue("reservation-1", principal), /authoritative Verified Access/); assert.throws(() => setup({ status: "cancelled" }).app.releaseRevenue("reservation-1", principal), /confirmed Reservation/); });

test("Full Post-Stay uses effective Checkout and does not make Operator Net payable at Revenue Release", () => { const release = setup({ plan: "full_post_stay", risk: 0 }).app.releaseRevenue("reservation-1", principal); assert.equal(release.payableNowKobo, 0); assert.equal(release.routineReserveTrancheKobo, 0); assert.equal(release.deferredPostStayKobo, release.operatorNetKobo); assert.equal(release.postStayPayableEligibleAt, "2026-09-04T13:00:00.000Z"); });

test("Trusted post-release adjustments are idempotent and do not mutate the historic release", () => { const s = setup(); const release = s.app.releaseRevenue("reservation-1", principal); const adjustment: RevenueAdjustmentRecord = { adjustmentId: "adjustment-1", adjustmentVersion: 1, reservationId: "reservation-1", releaseId: release.releaseId, source: "remedy", sourceReference: "mid-stay-failure:reservation-1", reasonCode: "accepted_remedy", journal: journal({ correlationId: release.releaseId, createdAt: now.toISOString(), lines: [{ lineId: "a", account: "operator_net_recognized", side: "debit", amountKobo: 10, currency: "NGN" }, { lineId: "b", account: "operator_payable", side: "credit", amountKobo: 10, currency: "NGN" }] }) };
  const withAuthority = setup({ adjustment }); const committed = withAuthority.app.releaseRevenue("reservation-1", principal); assert.equal(committed.releaseId, release.releaseId); const posted = withAuthority.app.postAdjustment("adjustment-1", principal); assert.equal(posted.adjustmentId, "adjustment-1"); assert.strictEqual(withAuthority.app.postAdjustment("adjustment-1", principal), posted); assert.equal(release.releaseVersion, 1);
});
