import test from "node:test";
import assert from "node:assert/strict";
import { InMemoryProtectionFundAccountingRepository, calculateRequiredSeedCapital, calculateTargetBalance, PROTECTION_FUND_POLICY } from "../domains/shortlet/src/protection-fund-accounting.js";
import { ProtectionFundApplication } from "../apps/web/src/protection-fund-application.js";
const staff={id:"finance-1",role:"authorized_staff" as const};
function app(availableMetrics={metricsVersion:"m1",projectedP95NetRemedyExposureKobo:100_000_000,projectedNext90DayGbvKobo:40_000_000_000,trailing90DayGbvKobo:2_000_000_000,trailingP95NetRemedyExposureKobo:100_000_000}){const accounting=new InMemoryProtectionFundAccountingRepository();const capital={allocateOrGet:(i:{requiredAmountKobo:number})=>({allocationId:"a1",allocationVersion:"1",status:"settled" as const,amountKobo:i.requiredAmountKobo,currency:"NGN" as const})};const earned={getEarnedCommission:()=>({recordId:"ec1",releaseId:"rel1",reservationId:"res1",commissionPolicyVersion:"rc1",earnedCommissionKobo:10_000_000,currency:"NGN" as const,earnedAt:"2026-01-01T00:00:00.000Z"})};const remedies={getRemedy:()=>({caseVersion:2,reservationId:"res1",status:"relocation_pending_completion" as const,choice:"relocation" as const,responsibleParty:"operator" as const,fundingStatus:"pending_accounting" as const,incidentId:"inc1",bookingId:"book1",decisionId:"dec1",decisionVersion:"dv1",eligibilityId:"elig1",eligibilityVersion:"ev1",approvalVersion:"av1",approvalTier:"routine",fundingVersion:"fv1",liabilityVersion:"lv1",fundingSource:"guest_protection_fund" as const,requiredAmountKobo:1_000_000,operatorLiabilityKobo:1_000_000,platformExposureKobo:0})};const recovery={getRecovery:()=>({recoveryId:"r1",recoveryVersion:"1",fundingRecordId:"gpf-funding:res1",status:"settled" as const,amountKobo:500_000,currency:"NGN" as const,source:"operator_settlement" as const})};return {accounting,application:new ProtectionFundApplication({accounting,metrics:{getMetrics:()=>availableMetrics},capital,commissions:earned,remedies,recovery,financeAuthorization:{canView:()=>true},clock:()=>new Date("2026-01-01T00:00:00.000Z")})};}
test("Versioned seed and target policy use dynamic trusted metrics",()=>{const metrics={metricsVersion:"m",projectedP95NetRemedyExposureKobo:300_000_000,projectedNext90DayGbvKobo:100_000_000_000,trailing90DayGbvKobo:2_000_000_000,trailingP95NetRemedyExposureKobo:400_000_000};assert.equal(calculateRequiredSeedCapital(PROTECTION_FUND_POLICY,metrics),1_000_000_000);assert.equal(calculateTargetBalance(PROTECTION_FUND_POLICY,metrics),1_200_000_000);});
test("Production contribution consumes the earned commission record once",()=>{const x=app();const seeded=x.application.seed(staff);assert.equal(seeded.status,"seeded");const one=x.application.contribute("rel1",staff);const two=x.application.contribute("rel1",staff);assert.equal(one.status,"contributed");assert.equal(two.status,"contributed");assert.equal(x.accounting.snapshot().contributions.length,1);assert.equal(x.accounting.snapshot().totalContributionKobo,1_000_000);});
test("Production reservation is atomic and settlement preserves liability exposure",()=>{const x=app();x.application.seed(staff);const reserved=x.application.reserve({remedyCaseId:"case-1",reservationId:"res1",expectedCaseVersion:2},staff);assert.equal(reserved.status,"reserved");assert.equal(x.accounting.snapshot().availableBalanceKobo,499_000_000);const settled=x.application.settle(reserved.record.fundingRecordId,"replacement-1",staff);assert.equal(settled.status,"settled");assert.equal(x.accounting.snapshot().committedBalanceKobo,0);assert.equal(x.accounting.snapshot().outstandingOperatorLiabilityKobo,1_000_000);const recovery=x.application.recover("ref",staff);assert.equal("amountKobo" in recovery,true);if("amountKobo" in recovery)assert.equal(recovery.amountKobo,500_000);assert.equal(x.accounting.snapshot().availableBalanceKobo,499_500_000);});
