import test from "node:test";
import assert from "node:assert/strict";
import { GuestConductApplication } from "../apps/web/src/guest-conduct-application.js";
import { createGuestConductPolicySnapshot } from "../domains/shortlet/src/index.js";
import type { BookingContract } from "../domains/shortlet/src/card-payment.js";
const policy = createGuestConductPolicySnapshot({ unitId: "unit-20", capacity: 4 });
const contract: BookingContract = { contractId: "contract-20", reservationId: "reservation-20", offerId: "offer-20", unitId: "unit-20", tenantId: "tenant-20", parties: { primaryGuest: { id: "guest-20", name: "Guest" }, operator: { id: "operator-20", name: "Operator" }, distinctPayer: null }, dates: { checkIn: "2026-09-01", checkOut: "2026-09-03", nights: 2 }, occupants: [{ name: "Guest" }], quote: {}, totalAmountDueNowKobo: 100, policies: { cancellationPolicy: {}, guestConductPolicy: policy, guestConductRules: policy.rules.map((r) => r.summary) }, paymentDetails: { paymentMethod: "bank_transfer", transferReference: "transfer", amountKobo: 100, currency: "NGN", paidAt: "2026-08-01T00:00:00Z" }, createdAt: "2026-08-01T00:00:00Z", contractVersion: 1 };
function setup() { const manager = { assess: ({ referenceIds }: { referenceIds: readonly string[] }) => ({ evidenceSetId: referenceIds[0], version: "e1", status: "accepted" as const, count: referenceIds.length, category: "conduct" as const, assessment: "remediable" as const }) }; const app = new GuestConductApplication({ contracts: { getContract: () => contract, getContractByReservation: () => contract }, evidence: manager }); return app; }
test("application derives allegation authority from contract and provides one redacted artifact", () => { const app = setup(); const artifact = app.reportAllegation({ reservationId: "reservation-20", ruleId: "quiet_hours", evidenceReferenceIds: ["opaque-evidence"], safeSummary: "Noise was assessed during quiet hours.", commandId: "report-1", principal: { id: "operator-20", role: "operator", tenantId: "tenant-20" } }); assert.equal(artifact.facts.ruleVersion, policy.ruleVersion); assert.equal(artifact.facts.allegation?.ruleId, "quiet_hours"); const serialized = JSON.stringify(artifact); assert.doesNotMatch(serialized, /opaque-evidence|tenant-20|http|responder/); });
test("guest, distinct payer, wrong tenant, and other operator cannot view conduct", () => { const app = setup(); assert.ok(app.getArtifact("reservation-20", { id: "guest-20", role: "guest", tenantId: "tenant-20" })); for (const principal of [{ id: "payer", role: "guest" as const, tenantId: "tenant-20" }, { id: "other", role: "operator" as const, tenantId: "tenant-20" }, { id: "operator-20", role: "operator" as const, tenantId: "other" }]) assert.throws(() => app.getArtifact("reservation-20", principal)); });
