import test from "node:test";
import assert from "node:assert/strict";
import { InMemoryBookingStateRepository } from "../domains/shortlet/src/booking-state.js";
import { InMemorySecurityDepositAccountingRepository } from "../domains/shortlet/src/security-deposit-accounting.js";
import { calculateSecurityDepositPolicySnapshot } from "../domains/shortlet/src/security-deposit.js";
import { InMemoryDepositClaimRepository } from "../domains/shortlet/src/deposit-claim.js";
import { DepositClaimApplication } from "../apps/web/src/deposit-claim-application.js";
import { createDepositClaimWebAgentAdapter } from "../apps/web-agent/src/presentation.js";
import { resolveDepositClaimServerEvent } from "../apps/web/src/deposit-claim-actions.js";
import { depositClaimArtifact } from "../apps/web/src/deposit-claim-artifact.js";
import type { BookingContract, Reservation } from "../domains/shortlet/src/card-payment.js";

const clock = { now: new Date("2026-09-02T10:00:00.000Z") };
function setup(checkoutDate = "2026-09-02", failAllocation = false) {
  const reservation: Reservation = { reservationId: "r26", contractId: "c26", unitId: "u26", primaryGuestId: "g26", dates: { checkIn: "2026-09-01", checkOut: "2026-09-02" }, status: "confirmed", confirmedAt: "2026-08-01T00:00:00.000Z" };
  const snapshot = calculateSecurityDepositPolicySnapshot({ accommodationSubtotalKobo: 80_000_000, bedrooms: 3, configuredDepositKobo: 20_000_000 });
  const contract: BookingContract = { contractId: "c26", reservationId: "r26", offerId: "o26", unitId: "u26", tenantId: "t26", parties: { primaryGuest: { id: "g26", name: "Guest" }, operator: { id: "op26" }, distinctPayer: { id: "payer26", name: "Payer" } }, dates: { checkIn: "2026-09-01", checkOut: "2026-09-02", nights: 1 }, occupants: [{ name: "Guest" }], quote: {}, totalAmountDueNowKobo: 100_000_000, securityDeposit: { policyVersion: snapshot.policyVersion, amountKobo: snapshot.amountKobo, currency: "NGN", collectionId: "security-deposit:o26", status: "held" }, policies: { cancellationPolicy: {}, guestConductRules: [] }, paymentDetails: { paymentMethod: "fresh_card", pspReference: "stay-ref", amountKobo: 80_000_000, currency: "NGN", paidAt: "2026-08-01T00:00:00.000Z" }, createdAt: "2026-08-01T00:00:00.000Z", contractVersion: 1, checkout: { time: "11:00", timezone: "Africa/Lagos", source: "contractual" } };
  let shouldFail = failAllocation; const claims = new InMemoryDepositClaimRepository(); const booking = new InMemoryBookingStateRepository({ contracts: [contract], reservations: [reservation] }); const accounting = new class extends InMemorySecurityDepositAccountingRepository { override allocateClaim(input: Parameters<InMemorySecurityDepositAccountingRepository["allocateClaim"]>[0]) { if (shouldFail) throw new Error("injected allocation failure"); return super.allocateClaim(input); } }(); accounting.createOrGet({ offerId: "o26", snapshot, paymentMethod: "fresh_card" }); accounting.recordCollection("security-deposit:o26", { providerReference: "deposit-ref", collectedAt: "2026-08-01T00:00:00.000Z" }); accounting.bind("security-deposit:o26", { reservationId: "r26", contractId: "c26" });
  let notification: "queued" | "delivered" = "queued"; let decisionVersion = "1"; const refunds: string[] = []; const app = new DepositClaimApplication({ booking, accounting, claims, terms: { getTerms: () => ({ reservationId: "r26", checkoutDate, checkoutTime: "11:00", source: "contractual", termVersion: "term-1" }) }, policy: { validate: ({ reservationId, item, evidence, depositPolicyVersion }) => ({ policyVersion: depositPolicyVersion, reservationId, itemId: item.itemId, evidenceVersion: evidence.evidenceVersion, permittedCategory: true, covered: true, specific: true, quantified: true, excluded: false }) }, evidence: { resolve: ({ reservationId, item }) => ({ evidenceSetId: "set-1", evidenceVersion: "ev-1", reservationId, itemId: item.itemId, references: [{ evidenceReferenceId: "e-1", type: "photo", capturedAt: "2026-09-02T09:00:00Z", classification: "post_checkout", safeDescription: "Damage photo" }], validation: "approved", occurrenceDuringReservation: "supported", causation: "supported" }) }, notifications: { resolve: ({ claimId, guestId, tenantId }) => ({ claimId, guestId, tenantId, notificationVersion: "n-1", status: notification, ...(notification === "delivered" ? { deliveredAtIso: "2026-09-03T10:00:00Z", deliveryEvidenceId: "delivery-1" } : {}) }) }, refunds: { refundOrGet: (input) => { refunds.push(`${input.obligationId}:${input.amountKobo}`); return { refundId: `refund-${input.obligationId}`, status: "settled", amountKobo: input.amountKobo, currency: "NGN" }; } }, decisions: { get: ({ claimId }) => ({ decisionId: "d1", decisionVersion, claimId, claimVersion: 4, policyVersion: snapshot.policyVersion, evidenceVersion: "ev-1", reviewerId: "human", reviewerAuthorityVersion: "tenant-deposit-v1", evaluations: [{ itemId: "damage", approvedAmountKobo: 2_000_000, explanation: "Supported", balanceOfEvidence: "operator_met" }], valid: true }) }, clock: () => clock.now }); return { app, accounting, claims, refunds, setAllocationFailure: (value: boolean) => { shouldFail = value; }, setNotification: (value: "queued" | "delivered") => { notification = value; }, setDecisionVersion: (value: string) => { decisionVersion = value; }, operator: { id: "op26", role: "operator" as const, tenantId: "t26" }, guest: { id: "g26", role: "guest" as const, tenantId: "t26" } };
}
function item() { return [{ itemId: "damage", description: "Broken lamp", claimedAmountKobo: 5_000_000, evidenceReferenceIds: ["e-1"] }]; }

test("Timely allocation-pending claim recovers after the deadline and creates exactly one surplus refund", () => { const s = setup("2026-09-02", true); clock.now = new Date("2026-09-03T10:00:00.000Z"); assert.throws(() => s.app.submitClaim("r26", s.operator, item()), /injected allocation failure/); assert.equal(s.claims.findByReservationId("r26")?.status, "allocation_pending"); assert.equal(s.accounting.allocation("deposit-claim:r26"), null); assert.equal(s.refunds.length, 0); s.setAllocationFailure(false); clock.now = new Date("2026-09-04T10:00:00.001Z"); const recovered = s.app.submitClaim("r26", s.operator, item()); assert.equal(recovered.status, "validated_notification_pending"); assert.equal(s.accounting.allocation("deposit-claim:r26")?.amountKobo, 5_000_000); assert.equal(s.refunds.length, 1); assert.equal(s.app.reconcileClaimWindow("r26", { id: "system", role: "system", tenantId: "t26" }).status, "validated_notification_pending"); });
test("Issue 26 uses authoritative EffectiveCheckout checkoutDate instead of stale Reservation date", () => { const s = setup("2026-09-03"); clock.now = new Date("2026-09-04T10:00:00.000Z"); const claim = s.app.submitClaim("r26", s.operator, item()); assert.equal(claim.effectiveCheckoutIso, "2026-09-03T10:00:00.000Z"); assert.equal(claim.claimDeadlineIso, "2026-09-04T10:00:00.000Z"); });
test("Issue 26 uses authoritative BookingState and real held deposit, with exact claim boundary", () => { const s = setup(); clock.now = new Date("2026-09-03T10:00:00.000Z"); const claim = s.app.submitClaim("r26", s.operator, item()); assert.equal(claim.claimId, "deposit-claim:r26"); assert.equal(claim.depositAmountKobo, 20_000_000); assert.equal(claim.claimedAmountKobo, 5_000_000); assert.equal(s.refunds[0], "deposit-claim:r26:surplus:15000000"); });
test("Issue 26 rejects guest, payer, wrong operator, wrong tenant, and injected authority", () => { const s = setup(); clock.now = new Date("2026-09-03T10:00:00.000Z"); for (const principal of [{ id: "g26", role: "guest" as const, tenantId: "t26" }, { id: "payer26", role: "guest" as const, tenantId: "t26" }, { id: "other", role: "operator" as const, tenantId: "t26" }, { id: "op26", role: "operator" as const, tenantId: "wrong" }, { id: "staff", role: "authorized_staff" as const, tenantId: "t26" }]) assert.throws(() => s.app.submitClaim("r26", principal, item()), /ACTION_NOT_AUTHORIZED/); assert.throws(() => s.app.submitClaim("r26", s.operator, [{ ...item()[0], claimedAmountKobo: 1, depositAmountKobo: 20_000_000 } as never]), /Claim item/); });
test("Only positive notification starts the exact response window and replay is stable", () => { const s = setup(); clock.now = new Date("2026-09-03T10:00:00.000Z"); s.app.submitClaim("r26", s.operator, item()); assert.equal(s.app.notify("deposit-claim:r26").responseWindowStartIso, null); s.setNotification("delivered"); const notified = s.app.notify("deposit-claim:r26"); assert.equal(notified.responseWindowStartIso, "2026-09-03T10:00:00.000Z"); assert.equal(notified.responseWindowEndIso, "2026-09-05T10:00:00.000Z"); assert.deepEqual(s.app.notify("deposit-claim:r26").responseWindowEndIso, notified.responseWindowEndIso); });
test("Human Balance-of-Evidence decision releases only the unapproved claim balance", () => { const s = setup(); clock.now = new Date("2026-09-03T10:00:00.000Z"); s.app.submitClaim("r26", s.operator, item()); s.setNotification("delivered"); s.app.notify("deposit-claim:r26"); s.app.respond("deposit-claim:r26", s.guest, "dispute"); const result = s.app.applyReviewedDecision("deposit-claim:r26", { id: "reviewer", role: "authorized_staff", tenantId: "t26" }, { expectedClaimVersion: 4, decisionId: "d1", decisionVersion: "1", evidenceVersion: "ev-1", policyVersion: "security-deposit/adr-0063-launch-v1" }); assert.equal(result.approvedOperatorAwardKobo, 2_000_000); assert.equal(s.accounting.summary("r26")?.claimReservedKobo, 2_000_000); assert.equal(s.accounting.summary("r26")?.refundSettledKobo, 18_000_000); });
test("No-claim reconciliation is a durable case and blocks later claims", () => { const s = setup(); clock.now = new Date("2026-09-03T10:00:00.001Z"); const result = s.app.reconcileClaimWindow("r26", { id: "system", role: "system", tenantId: "t26" }); assert.equal(result.status, "settled"); assert.equal(depositClaimArtifact(s.app, "r26", s.guest).facts.status, "no_claim_refunded"); assert.throws(() => s.app.submitClaim("r26", s.operator, item()), /CLAIM_WINDOW_CLOSED/); });
test("No-claim Weaver projection uses the no-claim refund obligation", () => { const s = setup(); clock.now = new Date("2026-09-03T10:00:00.001Z"); s.app.reconcileClaimWindow("r26", { id: "system", role: "system", tenantId: "t26" }); const view = createDepositClaimWebAgentAdapter({ application: s.app, principal: s.guest, createSurfaceId: (id) => `surface:${id}` }).get("r26"); assert.equal(view.artifact.facts.noClaimRefundStatus, "settled"); assert.equal(view.artifact.facts.surplusRefundStatus, "not_applicable"); assert.equal(view.artifact.actions.length, 0); assert.match(JSON.stringify(view.a2uiMessages), /No Security Deposit Claim was filed in time/); });
test("Generated Weaver Apply event binds the reviewed decision and rejects a changed decision", () => { const s = setup(); clock.now = new Date("2026-09-03T10:00:00.000Z"); s.app.submitClaim("r26", s.operator, item()); s.setNotification("delivered"); s.app.notify("deposit-claim:r26"); s.app.respond("deposit-claim:r26", s.guest, "dispute"); const rendered = createDepositClaimWebAgentAdapter({ application: s.app, principal: { id: "staff", role: "authorized_staff", tenantId: "t26" }, createSurfaceId: (id) => `surface:${id}` }).get("r26"); const update = rendered.a2uiMessages.find((message) => "updateComponents" in message); assert.ok(update && "updateComponents" in update); const button = update.updateComponents.components.find((component) => component.component === "Button" && String(component.id).includes("apply-reviewed")); assert.ok(button && "action" in button); const event = (button.action as unknown as { event: { name: string; context: Record<string, unknown> } }).event; s.setDecisionVersion("2"); const stale = resolveDepositClaimServerEvent({ event: { message: { action: event } } as never, application: s.app, principal: { id: "staff", role: "authorized_staff", tenantId: "t26" } }); assert.equal(stale.ok, false); assert.equal(!stale.ok && stale.code, "STALE_ACTION"); });
test("Generated Weaver Dispute event enters human review without guest evidence", () => { const s = setup(); clock.now = new Date("2026-09-03T10:00:00.000Z"); s.app.submitClaim("r26", s.operator, item()); s.setNotification("delivered"); s.app.notify("deposit-claim:r26"); const rendered = createDepositClaimWebAgentAdapter({ application: s.app, principal: s.guest, createSurfaceId: (id) => `surface:${id}` }).get("r26"); const update = rendered.a2uiMessages.find((message) => "updateComponents" in message); assert.ok(update && "updateComponents" in update); const button = update.updateComponents.components.find((component) => component.component === "Button" && String(component.id).includes("dispute")); assert.ok(button && "action" in button); const event = (button.action as unknown as { event: unknown }).event; const result = resolveDepositClaimServerEvent({ event: { message: { action: event } } as never, application: s.app, principal: s.guest }); assert.equal(result.ok, true); assert.equal(result.ok && result.artifact.facts.status, "human_review"); assert.doesNotMatch(JSON.stringify(result), /deposit-ref|stay-ref|https?:\/\/|SecurityContext|session|device|fraud|private/i); });
test("Generated Weaver Accept event reaches the same strict resolver and application", () => { const s = setup(); clock.now = new Date("2026-09-03T10:00:00.000Z"); s.app.submitClaim("r26", s.operator, item()); s.setNotification("delivered"); s.app.notify("deposit-claim:r26"); const rendered = createDepositClaimWebAgentAdapter({ application: s.app, principal: s.guest, createSurfaceId: (id) => `surface:${id}` }).get("r26"); const update = rendered.a2uiMessages.find((message) => "updateComponents" in message); assert.ok(update && "updateComponents" in update); const button = update.updateComponents.components.find((component) => component.component === "Button" && String(component.id).includes("accept")); assert.ok(button && "action" in button); const event = (button.action as unknown as { event: unknown }).event; const result = resolveDepositClaimServerEvent({ event: { message: { action: event } } as never, application: s.app, principal: s.guest }); assert.equal(result.ok, true); assert.equal(result.ok && result.artifact.facts.guestResponse, "accept"); assert.equal(result.ok && result.artifact.facts.initialApprovedAmountKobo, 5_000_000); assert.equal(result.ok && result.artifact.facts.currentClaimReserveKobo, 5_000_000); });
