import test from "node:test";
import assert from "node:assert/strict";
import { CancellationNoShowManager } from "../domains/shortlet/src/index.js";
import { InMemoryBookingStateRepository } from "../domains/shortlet/src/booking-state.js";
import type { BookingContract, Reservation } from "../domains/shortlet/src/card-payment.js";
import { CancellationApplication } from "../apps/web/src/cancellation-application.js";

const contract: BookingContract = { contractId: "c1", reservationId: "r1", offerId: "o1", unitId: "u1", tenantId: "t1", parties: { primaryGuest: { id: "g1", name: "Guest" }, operator: { id: "op" }, distinctPayer: null }, dates: { checkIn: "2026-09-01", checkOut: "2026-09-03", nights: 2 }, occupants: [{ name: "Guest" }], quote: {}, totalAmountDueNowKobo: 10000, policies: { cancellationPolicy: { type: "flexible", version: "A", policySummary: "Flexible" }, guestConductRules: [] }, paymentDetails: { paymentMethod: "fresh_card", pspReference: "backend-card-ref", amountKobo: 10000, currency: "NGN", paidAt: "2026-08-01T00:00:00Z" }, createdAt: "2026-08-01T00:00:00Z", contractVersion: 1 };
const reservation: Reservation = { reservationId: "r1", contractId: "c1", unitId: "u1", primaryGuestId: "g1", dates: { checkIn: "2026-09-01", checkOut: "2026-09-03" }, status: "confirmed", confirmedAt: "2026-08-01T00:00:00Z", inventoryCommitmentId: "commit-1" };
function setup() { const state = new InMemoryBookingStateRepository({ contracts: [contract], reservations: [reservation] }); const calls: string[] = []; const app = new CancellationApplication({ state, manager: new CancellationNoShowManager(), timing: { getWindow: () => ({ startIso: "2026-09-01T13:00:00.000Z", timezone: "Africa/Lagos" }) }, economics: { getEconomics: () => ({ version: "econ-2", currency: "NGN", cancellationBaseKobo: 8000, refundableCleaningKobo: 500, refundableUnprovidedServicesKobo: 250, refundableSecurityDepositKobo: 1000, refundableAttributableTaxKobo: 100, refundableDuplicatePaymentKobo: 50, commissionRate: .12 }) }, arrival: { getState: () => ({ status: "awaiting_access", version: "arrival-1" }) }, refunds: { initiateOrGetRefund: (input) => { calls.push(`refund:${input.originalPaymentReference}:${input.amountKobo}`); return { refundId: "ref-1", status: "pending", amountKobo: input.amountKobo, currency: "NGN" }; } }, ledger: { postCancellation: (input) => { calls.push(`ledger:${input.cancellationId}`); return { ledgerRecordId: "led-1", status: "posted" }; } }, availability: { releaseConfirmedBooking: (input) => calls.push(`release:${input.commitmentId}`) }, clock: () => new Date("2026-08-29T13:00:00.000Z") }); return { app, state, calls }; }

test("CancellationApplication uses authoritative economics, commits the Reservation, releases the exact commitment, and refunds the original source", () => { const { app, state, calls } = setup(); const artifact = app.cancel("r1", { id: "g1", role: "guest", tenantId: "t1" }); assert.equal(state.findReservationById("r1")?.status, "cancelled"); assert.deepEqual(calls, ["ledger:cancellation:r1", "release:commit-1", "refund:backend-card-ref:9900"]); assert.equal(artifact.facts.case?.refundStatus, "pending"); assert.equal(artifact.actions.length, 0); });

test("CancellationApplication fails closed for wrong guest and missing tenant", () => { const { app } = setup(); assert.throws(() => app.cancel("r1", { id: "other", role: "guest", tenantId: "t1" }), /Access denied/); assert.throws(() => app.cancel("r1", { id: "g1", role: "guest" }), /Access denied/); });
