import test from "node:test";
import assert from "node:assert/strict";
import { InMemoryMidStayIncidentRepository } from "../domains/shortlet/src/index.js";
import { resolveMidStayFailureServerEvent } from "../apps/web/src/mid-stay-failure-actions.js";
import { generatedEvent, makeApplication, principal, staff } from "./mid-stay-fixtures.js";

test("Application and repository share authoritative incident state across generated guest action flow", () => { const { app, repository, getOwned } = makeApplication(false); const artifact = app.reportFailure({ reservationId: "reservation-1", evidenceReferenceIds: ["opaque-evidence-1"] }, principal); assert.equal(artifact.actions[0].type, "request_human_support"); const result = resolveMidStayFailureServerEvent({ event: generatedEvent(app, principal), application: app, principal }); assert.equal(result.ok, true); assert.equal(getOwned(), true); assert.equal(repository.findByReservationId("reservation-1")?.incidentVersion, 1); });
test("Authorized support applies the generated reviewed decision and returns a refreshed artifact", () => { const { app, repository } = makeApplication(true); app.reportFailure({ reservationId: "reservation-1", evidenceReferenceIds: ["opaque-evidence-1"] }, principal); const supportArtifact = app.getArtifact("reservation-1", staff); assert.equal(supportArtifact.actions[0].type, "apply_reviewed_decision"); const result = resolveMidStayFailureServerEvent({ event: generatedEvent(app, staff), application: app, principal: staff }); assert.equal(result.ok, true); assert.equal(repository.findByReservationId("reservation-1")?.status, "remedy_determined"); assert.equal(repository.findByReservationId("reservation-1")?.incidentVersion, 2); });
test("Stale generated decisions and economics fail closed", () => { const decisionCase = makeApplication(true); decisionCase.app.reportFailure({ reservationId: "reservation-1", evidenceReferenceIds: ["opaque-evidence-1"] }, principal); const oldDecisionEvent = generatedEvent(decisionCase.app, staff); decisionCase.changeDecision(); const decisionResult = resolveMidStayFailureServerEvent({ event: oldDecisionEvent, application: decisionCase.app, principal: staff }); assert.equal(decisionResult.ok, false); assert.equal(decisionResult.code, "STALE_ACTION"); assert.equal(decisionCase.repository.findByReservationId("reservation-1")?.incidentVersion, 1); const economicsCase = makeApplication(false); economicsCase.app.reportFailure({ reservationId: "reservation-1", evidenceReferenceIds: ["opaque-evidence-1"] }, principal); const oldEconomicsEvent = generatedEvent(economicsCase.app, principal); economicsCase.changeEconomics(); const economicsResult = resolveMidStayFailureServerEvent({ event: oldEconomicsEvent, application: economicsCase.app, principal }); assert.equal(economicsResult.ok, false); assert.equal(economicsResult.code, "STALE_ACTION"); });
test("Generated action contexts reject type and malformed binding fields", () => { const { app } = makeApplication(false); app.reportFailure({ reservationId: "reservation-1", evidenceReferenceIds: ["opaque-evidence-1"] }, principal); const event = generatedEvent(app, principal); const context = event.message.action.context as unknown as Record<string, unknown>; const invalidEvent = { message: { action: { name: event.message.action.name, context: { ...context, type: "request_human_support" } } } } as unknown as typeof event; const result = resolveMidStayFailureServerEvent({ event: invalidEvent, application: app, principal }); assert.equal(result.ok, false); assert.equal(result.code, "INVALID_CONTEXT"); });
test("Cross-reservation incident updates are identity-safe", () => { const repository = new InMemoryMidStayIncidentRepository(); const first = { incidentId: "incident-a", reservationId: "a", contractVersion: 1, incidentVersion: 1, status: "cure_pending" as const, reportedAt: "2026-01-01", evidenceSetId: "e", evidenceVersion: "e1", evidenceStatus: "sufficient" as const, humanOwned: false }; const second = { ...first, incidentId: "incident-b", reservationId: "b" }; repository.createIfAbsent(first); repository.createIfAbsent(second); repository.update("incident-b", 1, (current) => ({ ...current, incidentVersion: 2 })); assert.equal(repository.findByIncidentId("incident-a")?.incidentVersion, 1); assert.equal(repository.findByIncidentId("incident-b")?.incidentVersion, 2); assert.throws(() => repository.update("incident-b", 1, (current) => ({ ...current, incidentVersion: 2 })), /STALE_ACTION/); });
