import test from "node:test";
import assert from "node:assert/strict";
import { ConditionalOfferApplication } from "../apps/web/src/conditional-offer-application.js";
import { createBankTransferPaymentApplication } from "../apps/web/src/bank-transfer-application.js";
import { ConditionalOfferManager, InMemoryBookingStateRepository } from "../domains/shortlet/src/index.js";
import { AvailabilityCalendar } from "../domains/shortlet/src/availability.js";
import { getConventionalBankTransferView } from "../apps/web/src/presentation.js";

const offer = { offerId: "bank-offer", offerVersion: 1, requestId: "request", inventoryCommitmentId: "unused", unitId: "unit", tenantId: "tenant", parties: { primaryGuest: { id: "guest", name: "Guest" }, operator: { id: "operator", name: "Operator" }, distinctPayer: null }, unit: { id: "unit", title: "Unit", propertyId: "property", location: {} }, dates: { checkIn: "2026-08-10", checkOut: "2026-08-12", nights: 2 }, occupants: [{ name: "Guest" }], quote: {}, refundableSecurityDepositKobo: 0, totalAmountDueNowKobo: 10000, policies: { cancellationPolicy: {}, guestConductRules: [] }, disclosures: [], paymentWindow: { durationMinutes: 20, expiresAt: "2026-08-01T12:20:00.000Z" }, status: "accepted" as const, issuedAt: "2026-08-01T12:00:00.000Z", acceptedAt: "2026-08-01T12:00:00.000Z", confirmationToken: "token", tokenUsed: true, aggregateVersions: { offerVersion: 1, pricingVersion: "p", quoteVersion: "q", cancellationPolicyVersion: "c", managementAuthorityVersion: "m", inspectionVersion: "i" } };
const payer = { id: "guest", role: "guest" as const, tenantId: "tenant" };
const server = { id: "worker", role: "system" as const, tenantId: "tenant" };
function setup() { let now = new Date("2026-08-01T12:05:00.000Z"); const conditional = new ConditionalOfferApplication(Object.assign(new ConditionalOfferManager(), { getOffer: () => offer } as unknown as ConditionalOfferManager), () => new Date("2026-08-01T12:05:00.000Z")); const calendar = new AvailabilityCalendar(); const block = calendar.createBookingRequestBlock({ unitId: "unit", holderId: "guest", start: "2026-08-10", end: "2026-08-12", clock: () => new Date("2026-08-01T12:00:00Z") }); calendar.transitionBookingRequestBlockToPaymentPending({ commitmentId: block.commitmentId, unitId: "unit", start: "2026-08-10", end: "2026-08-12", clock: () => new Date("2026-08-01T12:00:00Z") }); const calls: string[] = []; let providerResult = (reference: string) => ({ verified: true as const, status: "success" as const, amountKobo: 10000, currency: "NGN", pspReference: reference, payerId: "guest" }); const application = createBankTransferPaymentApplication({ conditionalOfferApplication: new ConditionalOfferApplication(Object.assign(new ConditionalOfferManager(), { getOffer: () => ({ ...offer, inventoryCommitmentId: block.commitmentId }) } as unknown as ConditionalOfferManager), () => new Date("2026-08-01T12:05:00.000Z")), calendar, bookingState: new InMemoryBookingStateRepository(), clock: () => now, providerClient: { verifyTransfer(reference) { calls.push(reference); return providerResult(reference); } } }); return { application, calendar, calls, setProvider: (f: typeof providerResult) => { providerResult = f; }, setNow: (value: string) => { now = new Date(value); } }; }

test("Bank transfer application reuses the Conditional Offer manager and shares conventional/provider authority", () => { const s = setup(); assert.equal(s.application.manager !== undefined, true); const session = s.application.initializeTransfer("bank-offer", payer); assert.equal(getConventionalBankTransferView(s.application, "bank-offer", payer).artifact.facts.status, "transfer_initiated"); const result = s.application.verifyAndProcess(session.transferReference, server); assert.equal(result.outcome, "confirmed"); assert.equal(s.calls[0], session.transferReference); assert.equal(s.application.getArtifact("bank-offer", payer).facts.status, "confirmed"); assert.equal(s.application.getArtifact("bank-offer", payer).facts.contractId, result.bookingContract?.contractId); });

test("Bank transfer application exposes no client provider result and resolves exact expiry", () => { const s = setup(); const session = s.application.initializeTransfer("bank-offer", payer); assert.throws(() => s.application.manager.verifyAndProcessTransfer({ commandId: "x", commandName: "bank_transfer.verify_and_process", principal: server, payload: { transferReference: session.transferReference, verified: true }, timestamp: "now" } as never), /accepts only/); s.setNow("2026-08-01T12:30:00.000Z"); const expiry = s.application.resolveExpiry("bank-offer", server); assert.equal(expiry.status, "expired"); });
