import test from "node:test";
import assert from "node:assert/strict";
import { createPlatformCommandEnvelope, type CommandPrincipal } from "../packages/platform-core/src/index.js";
import { BankTransferPaymentManager, InMemoryBookingPaymentJourneyRepository, InMemorySecurityDepositAccountingRepository, InMemoryBookingStateRepository, LivePaymentAttemptRegistry, type ConditionalBookingOffer } from "../domains/shortlet/src/index.js";
import { ConditionalOfferApplication } from "../apps/web/src/conditional-offer-application.js";
import { createBankTransferPaymentApplication } from "../apps/web/src/bank-transfer-application.js";

const guest: CommandPrincipal = { id: "guest-bank-25", role: "guest", tenantId: "tenant-bank-25" };
const system: CommandPrincipal = { id: "system-bank-25", role: "system", tenantId: "tenant-bank-25" };
const offer: ConditionalBookingOffer = { offerId: "offer-bank-stage-25", offerVersion: 1, requestId: "request-bank-25", inventoryCommitmentId: "commit-bank-25", unitId: "unit-bank-25", tenantId: guest.tenantId, parties: { primaryGuest: { id: guest.id, name: "Guest" }, operator: { id: "operator-bank-25", name: "Operator" }, distinctPayer: null }, unit: { id: "unit-bank-25", title: "Unit", propertyId: "property-bank-25", location: {} }, dates: { checkIn: "2026-09-01", checkOut: "2026-09-03", nights: 2 }, occupants: [{ name: "Guest" }], quote: { allInStayTotalKobo: 18_234_567, currency: "NGN" }, refundableSecurityDepositKobo: 4_321_000, securityDeposit: { policyVersion: "security-deposit/adr-0063-launch-v1", currency: "NGN", accommodationSubtotalKobo: 18_234_567, bedroomBand: "two_bedroom", percentageCapKobo: 4_558_641, unitSizeCapKobo: 15_000_000, unitConfiguredDepositKobo: 4_321_000, amountKobo: 4_321_000, collectionRequired: true }, totalAmountDueNowKobo: 22_555_567, policies: { cancellationPolicy: {}, guestConductRules: [] }, disclosures: [], paymentWindow: { durationMinutes: 20, expiresAt: "2099-09-01T12:20:00.000Z" }, status: "accepted", issuedAt: "2026-09-01T12:00:00.000Z", confirmationToken: "token", tokenUsed: true, aggregateVersions: { offerVersion: 1, pricingVersion: "p1", quoteVersion: "q1", cancellationPolicyVersion: "c1", managementAuthorityVersion: "m1", inspectionVersion: "i1" } };

test("Bank staged journey uses two exact expiring references and confirms after both transfers", () => {
  const journeys = new InMemoryBookingPaymentJourneyRepository(); const accounting = new InMemorySecurityDepositAccountingRepository(); const amounts: number[] = []; let manager: BankTransferPaymentManager;
  manager = new BankTransferPaymentManager({ offerManager: { getOffer: () => offer }, journeyRepository: journeys, securityDepositAccounting: accounting, bookingState: new InMemoryBookingStateRepository(), securityDepositCapability: { getCapability: () => ({ capabilityVersion: "cap-bank-25", enabled: true, pspProviderId: "approved-bank-psp", pspApproved: true, counselApproved: true, collectionModel: "separate_actual_charge", paymentMethod: "bank_transfer" }) }, liveAttempts: new LivePaymentAttemptRegistry(), calendar: { transitionPaymentPendingToConfirmedBooking: () => undefined }, providerClient: { verifyTransfer(reference) { const session = manager.getSessionByReference(reference)!; amounts.push(session.amountKobo); return { verified: true, status: "success", amountKobo: session.amountKobo, currency: "NGN", pspReference: reference, payerId: guest.id }; } } });
  const command = (payload: { offerId: string }) => createPlatformCommandEnvelope({ commandName: "bank_transfer.initialize", principal: guest, payload });
  const verify = (reference: string) => manager.verifyAndProcessTransfer(createPlatformCommandEnvelope({ commandName: "bank_transfer.verify_and_process", principal: system, payload: { transferReference: reference } }), { clock: () => new Date("2026-09-01T12:04:00Z") });
  const stay = manager.initializeBankTransfer(command({ offerId: offer.offerId }), { clock: () => new Date("2026-09-01T12:01:00Z") }); const first = verify(stay.transferReference); assert.equal(first.outcome, "deposit_required"); assert.equal(manager.getBookingContract(offer.offerId), undefined);
  const deposit = manager.initializeBankTransfer(command({ offerId: offer.offerId }), { clock: () => new Date("2026-09-01T12:03:00Z") }); const result = verify(deposit.transferReference);
  assert.deepEqual(amounts, [18_234_567, 4_321_000]); assert.notEqual(stay.transferReference, deposit.transferReference); assert.equal(result.outcome, "confirmed"); assert.equal(result.bookingContract?.paymentDetails.amountKobo, 18_234_567); assert.equal(result.bookingContract?.securityDeposit?.amountKobo, 4_321_000); assert.equal(accounting.journals().length, 1);
});

test("Bank production factory wires the shared staged authorities", () => {
  const journeys = new InMemoryBookingPaymentJourneyRepository(); const accounting = new InMemorySecurityDepositAccountingRepository(); let manager: BankTransferPaymentManager;
  const conditional = new ConditionalOfferApplication(Object.assign({ getOffer: () => offer }, { manager: { getOffer: () => offer } }) as unknown as ConstructorParameters<typeof ConditionalOfferApplication>[0]);
  const app = createBankTransferPaymentApplication({ conditionalOfferApplication: conditional, journeyRepository: journeys, securityDepositAccounting: accounting, bookingState: new InMemoryBookingStateRepository(), securityDepositCapability: { getCapability: () => ({ capabilityVersion: "cap-factory-bank", enabled: true, pspProviderId: "psp", pspApproved: true, counselApproved: true, collectionModel: "separate_actual_charge", paymentMethod: "bank_transfer" }) }, liveAttempts: new LivePaymentAttemptRegistry(), calendar: { transitionPaymentPendingToConfirmedBooking: () => undefined }, providerClient: { verifyTransfer(reference) { const session = manager.getSessionByReference(reference)!; return { verified: true, status: "success", amountKobo: session.amountKobo, currency: "NGN", pspReference: reference, payerId: guest.id }; } } });
  manager = app.manager; const session = app.initializeTransfer(offer.offerId, guest); const result = app.verifyAndProcess(session.transferReference, system);
  assert.equal(result.outcome, "deposit_required"); assert.equal(app.getArtifact(offer.offerId, guest).facts.status, "deposit_required");
});
