import test from "node:test";
import assert from "node:assert/strict";
import { InMemoryProtectionFundAccountingRepository, calculateRequiredSeedCapital, calculateTargetBalance, PROTECTION_FUND_POLICY } from "../domains/shortlet/src/protection-fund-accounting.js";
import { ProtectionFundApplication } from "../apps/web/src/protection-fund-application.js";
import type { CommandPrincipal } from "../packages/platform-core/src/index.js";
const staff={id:"finance-1",role:"authorized_staff" as const};
function app(availableMetrics={metricsVersion:"m1",projectedP95NetRemedyExposureKobo:100_000_000,projectedNext90DayGbvKobo:40_000_000_000,trailing90DayGbvKobo:2_000_000_000,trailingP95NetRemedyExposureKobo:100_000_000}, canView:(principal:CommandPrincipal)=>boolean=()=>true){const accounting=new InMemoryProtectionFundAccountingRepository();const capital={allocateOrGet:(i:{requiredAmountKobo:number})=>({allocationId:"a1",allocationVersion:"1",status:"settled" as const,amountKobo:i.requiredAmountKobo,currency:"NGN" as const})};const earned={getEarnedCommission:(releaseId:string)=>({recordId:`ec:${releaseId}`,releaseId,reservationId:"res1",commissionPolicyVersion:"rc1",earnedCommissionKobo:10_000_000,currency:"NGN" as const,earnedAt:"2026-01-01T00:00:00.000Z"})};const remedies={getRemedy:()=>({caseVersion:2,reservationId:"res1",status:"relocation_pending_completion" as const,choice:"relocation" as const,responsibleParty:"operator" as const,fundingStatus:"pending_accounting" as const,incidentId:"inc1",bookingId:"book1",decisionId:"dec1",decisionVersion:"dv1",eligibilityId:"elig1",eligibilityVersion:"ev1",approvalVersion:"av1",approvalTier:"routine",fundingVersion:"fv1",liabilityVersion:"lv1",fundingSource:"guest_protection_fund" as const,requiredAmountKobo:1_000_000,operatorLiabilityKobo:1_000_000,platformExposureKobo:0})};const recovery={getRecovery:()=>({recoveryId:"r1",recoveryVersion:"1",fundingRecordId:"gpf-funding:res1",status:"settled" as const,amountKobo:500_000,currency:"NGN" as const,source:"operator_settlement" as const})};return {accounting,application:new ProtectionFundApplication({accounting,metrics:{getMetrics:()=>availableMetrics},capital,commissions:earned,remedies,recovery,financeAuthorization:{canView},clock:()=>new Date("2026-01-01T00:00:00.000Z")})};}
test("Versioned seed and target policy use dynamic trusted metrics",()=>{const metrics={metricsVersion:"m",projectedP95NetRemedyExposureKobo:300_000_000,projectedNext90DayGbvKobo:100_000_000_000,trailing90DayGbvKobo:2_000_000_000,trailingP95NetRemedyExposureKobo:400_000_000};assert.equal(calculateRequiredSeedCapital(PROTECTION_FUND_POLICY,metrics),1_000_000_000);assert.equal(calculateTargetBalance(PROTECTION_FUND_POLICY,metrics),1_200_000_000);});
test("Production contribution consumes the earned commission record once",()=>{const x=app();const seeded=x.application.seed(staff);assert.equal(seeded.status,"seeded");const one=x.application.contribute("rel1",staff);const two=x.application.contribute("rel1",staff);assert.equal(one.status,"contributed");assert.equal(two.status,"contributed");assert.equal(x.accounting.snapshot().contributions.length,1);assert.equal(x.accounting.snapshot().totalContributionKobo,1_000_000);});
test("Production reservation is atomic and settlement preserves liability exposure",()=>{const x=app();x.application.seed(staff);const reserved=x.application.reserve({remedyCaseId:"case-1",reservationId:"res1",expectedCaseVersion:2},staff);assert.equal(reserved.status,"reserved");assert.equal(x.accounting.snapshot().availableBalanceKobo,499_000_000);const settled=x.application.settle(reserved.record.fundingRecordId,"replacement-1",staff);assert.equal(settled.status,"settled");assert.equal(x.accounting.snapshot().committedBalanceKobo,0);assert.equal(x.accounting.snapshot().outstandingOperatorLiabilityKobo,1_000_000);const recovery=x.application.recover("ref",staff);assert.equal("amountKobo" in recovery,true);if("amountKobo" in recovery)assert.equal(recovery.amountKobo,500_000);assert.equal(x.accounting.snapshot().availableBalanceKobo,499_500_000);});

function netByAccount(journals: ReturnType<InMemoryProtectionFundAccountingRepository["journals"]>): Map<string, number> {
  const result = new Map<string, number>();
  for (const journal of journals) for (const line of journal.lines) result.set(line.account, (result.get(line.account) ?? 0) + (line.side === "debit" ? line.amountKobo : -line.amountKobo));
  return result;
}
test("Production account-level reserve and settlement journals prove debit and credit effects", () => { const x=app(); x.application.seed(staff); const reserved=x.application.reserve({remedyCaseId:"case-1",reservationId:"res1",expectedCaseVersion:2},staff); assert.equal(reserved.status,"reserved"); x.application.settle(reserved.record.fundingRecordId,"replacement",staff); const journals=x.accounting.journals(); const reserveNet=netByAccount([journals[1]]); const settleNet=netByAccount([journals[2]]); assert.equal(reserveNet.get("gpf_committed_remedy"),1_000_000); assert.equal(reserveNet.get("gpf_available_balance"),-1_000_000); assert.equal(settleNet.get("gpf_committed_remedy"),-1_000_000); assert.equal(settleNet.get("gpf_remedy_expense"),0); assert.equal(settleNet.get("operator_liability_receivable"),1_000_000); });
test("Production Finance authorization permits Finance staff and admin but denies ordinary staff, non-Finance admin, Operator, guest, and agent", () => { const allowed=(p:CommandPrincipal)=>p.id.startsWith("finance-"); const x=app(undefined,allowed); const authorized={id:"finance-staff",role:"authorized_staff" as const}; const admin={id:"finance-admin",role:"admin" as const}; assert.doesNotThrow(()=>x.application.getSnapshot(authorized)); assert.doesNotThrow(()=>x.application.getSnapshot(admin)); for(const p of [{id:"staff",role:"authorized_staff" as const},{id:"admin",role:"admin" as const},{id:"operator",role:"operator" as const},{id:"guest",role:"guest" as const},{id:"agent",role:"agent" as const}]) assert.throws(()=>x.application.getSnapshot(p),/Finance access denied/); assert.throws(()=>x.application.seed({id:"staff",role:"authorized_staff",tenantId:"t"}),/Finance authority required/); });
test("Production automated system may reserve without Finance UI visibility", () => { const x=app(undefined,p=>p.id.startsWith("finance-")); x.application.seed({id:"finance-staff",role:"authorized_staff",tenantId:"t"}); assert.throws(()=>x.application.getSnapshot({id:"system",role:"system",tenantId:"t"}),/Finance access denied/); assert.equal(x.application.reserve({remedyCaseId:"case-1",reservationId:"res1",expectedCaseVersion:2},{id:"system",role:"system",tenantId:"t"}).status,"reserved"); });
test("Production contribution rate uses dynamic target at below, exact, and above boundaries", () => { const metrics={metricsVersion:"target",projectedP95NetRemedyExposureKobo:0,projectedNext90DayGbvKobo:100_000_000_000,trailing90DayGbvKobo:100_000_000_000,trailingP95NetRemedyExposureKobo:0}; const belowMetrics={...metrics,projectedNext90DayGbvKobo:40_000_000_000}; const below=app(belowMetrics); below.application.seed(staff); const belowResult=below.application.contribute("rel1",staff); assert.equal(belowResult.status,"contributed"); if(belowResult.status==="contributed") assert.equal(belowResult.record.contributionRate,.10); const exact=app(metrics); exact.application.seed(staff); assert.equal(exact.accounting.snapshot().availableBalanceKobo,1_000_000_000); const exactResult=exact.application.contribute("rel1",staff); assert.equal(exactResult.status,"contributed"); if(exactResult.status==="contributed") assert.equal(exactResult.record.contributionRate,.02); const above=app(metrics); above.application.seed(staff); above.application.contribute("rel1",staff); const aboveResult=above.application.contribute("rel2",staff); assert.equal(aboveResult.status,"contributed"); if(aboveResult.status==="contributed") assert.equal(aboveResult.record.contributionRate,.02); });
test("Production settled recovery is bounded, idempotent, and rejected before settlement", () => { const x=app(); x.application.seed(staff); const pending=x.application.reserve({remedyCaseId:"case-1",reservationId:"res1",expectedCaseVersion:2},staff); assert.equal(pending.status,"reserved"); assert.throws(()=>x.application.recover("ref",staff),/Recovery requires settled Fund remedy/); x.application.settle(pending.record.fundingRecordId,"replacement",staff); const first=x.application.recover("ref",staff); const duplicate=x.application.recover("ref",staff); assert.equal("amountKobo" in first,true); assert.strictEqual(duplicate,first); assert.equal(x.accounting.snapshot().totalRecoveredKobo,500_000); });
