import test from "node:test";
import assert from "node:assert/strict";
import { createPlatformCommandEnvelope, type CommandPrincipal } from "../packages/platform-core/src/index.js";
import { CardPaymentManager, InMemoryBookingPaymentJourneyRepository, InMemorySecurityDepositAccountingRepository, LivePaymentAttemptRegistry, type ConditionalBookingOffer } from "../domains/shortlet/src/index.js";
import { ConditionalOfferApplication } from "../apps/web/src/conditional-offer-application.js";
import { createCardPaymentApplication } from "../apps/web/src/card-payment-application.js";
import { cardPaymentArtifactToA2UI } from "../apps/web-agent/src/card-payment-a2ui.js";
import { resolveCardPaymentServerEvent } from "../apps/web/src/card-payment-actions.js";

const guest: CommandPrincipal = { id: "guest-25", role: "guest", tenantId: "tenant-25" };
const system: CommandPrincipal = { id: "system-25", role: "system", tenantId: "tenant-25" };
const offer: ConditionalBookingOffer = { offerId: "offer-stage-25", offerVersion: 1, requestId: "request-25", inventoryCommitmentId: "commit-25", unitId: "unit-25", tenantId: "tenant-25", parties: { primaryGuest: { id: guest.id, name: "Guest" }, operator: { id: "operator-25", name: "Operator" }, distinctPayer: null }, unit: { id: "unit-25", title: "Unit", propertyId: "property-25", location: {} }, dates: { checkIn: "2026-09-01", checkOut: "2026-09-03", nights: 2 }, occupants: [{ name: "Guest" }], quote: { allInStayTotalKobo: 18_234_567, currency: "NGN" }, refundableSecurityDepositKobo: 4_321_000, securityDeposit: { policyVersion: "security-deposit/adr-0063-launch-v1", currency: "NGN", accommodationSubtotalKobo: 18_234_567, bedroomBand: "two_bedroom", percentageCapKobo: 4_558_641, unitSizeCapKobo: 15_000_000, unitConfiguredDepositKobo: 4_321_000, amountKobo: 4_321_000, collectionRequired: true }, totalAmountDueNowKobo: 22_555_567, policies: { cancellationPolicy: {}, guestConductRules: [] }, disclosures: [], paymentWindow: { durationMinutes: 20, expiresAt: "2026-09-01T12:20:00.000Z" }, status: "accepted", issuedAt: "2026-09-01T12:00:00.000Z", confirmationToken: "token", tokenUsed: true, aggregateVersions: { offerVersion: 1, pricingVersion: "p1", quoteVersion: "q1", cancellationPolicyVersion: "c1", managementAuthorityVersion: "m1", inspectionVersion: "i1" } };

test("Card staged journey charges stay then deposit separately and confirms only after both settle", () => {
  const journeyRepository = new InMemoryBookingPaymentJourneyRepository(); const accounting = new InMemorySecurityDepositAccountingRepository(); const refs: Array<{ reference: string; amount: number }> = [];
  const manager = new CardPaymentManager({ offerManager: { getOffer: () => offer }, journeyRepository, securityDepositAccounting: accounting, securityDepositCapability: { getCapability: () => ({ capabilityVersion: "cap-25", enabled: true, pspProviderId: "approved-psp", pspApproved: true, counselApproved: true, collectionModel: "separate_actual_charge", paymentMethod: "fresh_card" }) }, liveAttempts: new LivePaymentAttemptRegistry(), calendar: { transitionPaymentPendingToConfirmedBooking: () => undefined }, pspClient: { verifyTransaction(reference) { const session = manager.getCheckoutSessionByReference(reference)!; refs.push({ reference, amount: session.amountKobo }); return { verified: true, status: "success", amountKobo: session.amountKobo, currency: "NGN", pspReference: reference, payerId: guest.id }; } } });
  const stay = manager.initializeCardCheckout(createPlatformCommandEnvelope({ commandName: "card_payment.initialize_checkout", principal: guest, payload: { offerId: offer.offerId } }), { clock: () => new Date("2026-09-01T12:01:00Z") });
  const first = manager.verifyAndConfirmCardPayment(createPlatformCommandEnvelope({ commandName: "card_payment.verify_and_confirm", principal: system, payload: { offerId: offer.offerId, pspReference: stay.pspReference } }), { clock: () => new Date("2026-09-01T12:02:00Z") });
  assert.equal((first as unknown as { outcome: string }).outcome, "deposit_required"); assert.equal(manager.getBookingContract(offer.offerId), undefined);
  const deposit = manager.initializeCardCheckout(createPlatformCommandEnvelope({ commandName: "card_payment.initialize_checkout", principal: guest, payload: { offerId: offer.offerId } }), { clock: () => new Date("2026-09-01T12:03:00Z") });
  const result = manager.verifyAndConfirmCardPayment(createPlatformCommandEnvelope({ commandName: "card_payment.verify_and_confirm", principal: system, payload: { offerId: offer.offerId, pspReference: deposit.pspReference } }), { clock: () => new Date("2026-09-01T12:04:00Z") });
  assert.deepEqual(refs.map((r) => r.amount), [18_234_567, 4_321_000]); assert.notEqual(stay.pspReference, deposit.pspReference); assert.equal((result as { bookingContract: { totalAmountDueNowKobo: number; paymentDetails: { amountKobo: number }; securityDeposit?: { amountKobo: number; status: string } } }).bookingContract.paymentDetails.amountKobo, 18_234_567); assert.equal((result as { bookingContract: { securityDeposit?: { amountKobo: number; status: string } } }).bookingContract.securityDeposit?.status, "held"); assert.equal(accounting.journals().length, 1); assert.equal(accounting.journals()[0].lines[0].amountKobo, 4_321_000);
});

test("Card production factory wires the shared staged authorities", () => {
  const journeys = new InMemoryBookingPaymentJourneyRepository(); const accounting = new InMemorySecurityDepositAccountingRepository(); let manager: CardPaymentManager;
  const conditional = new ConditionalOfferApplication(Object.assign({ getOffer: () => offer }, { manager: { getOffer: () => offer } }) as unknown as ConstructorParameters<typeof ConditionalOfferApplication>[0], () => new Date("2026-09-01T12:00:00Z"));
  const app = createCardPaymentApplication({ conditionalOfferApplication: conditional, journeyRepository: journeys, securityDepositAccounting: accounting, securityDepositCapability: { getCapability: () => ({ capabilityVersion: "cap-factory", enabled: true, pspProviderId: "psp", pspApproved: true, counselApproved: true, collectionModel: "separate_actual_charge", paymentMethod: "fresh_card" }) }, liveAttempts: new LivePaymentAttemptRegistry(), calendar: { transitionPaymentPendingToConfirmedBooking: () => undefined }, pspClient: { verifyTransaction(reference) { const session = manager.getCheckoutSessionByReference(reference)!; return { verified: true, status: "success", amountKobo: session.amountKobo, currency: "NGN", pspReference: reference, payerId: guest.id }; } } });
  manager = app.manager;
  const initial = app.getArtifact(offer.offerId, guest); const initialButton = cardPaymentArtifactToA2UI({ artifact: initial, surfaceId: "surface-card-25" })[1]; assert.ok("updateComponents" in initialButton); const stayComponent = initialButton.updateComponents.components.find((component) => component.component === "Button"); assert.ok(stayComponent && "action" in stayComponent); const stayAction = stayComponent.action as unknown as { event: unknown }; const stayEvent = { message: { action: stayAction.event } } as never; const initialized = resolveCardPaymentServerEvent({ event: stayEvent, application: app, principal: guest }); assert.equal(initialized.ok, true); const stay = app.manager.getCheckoutSession(offer.offerId)!; const result = app.verifyAndConfirm(stay.pspReference, system);
  assert.equal((result as unknown as { outcome: string }).outcome, "deposit_required"); const depositArtifact = app.getArtifact(offer.offerId, guest); assert.equal(depositArtifact.facts.status, "deposit_required"); const stale = resolveCardPaymentServerEvent({ event: stayEvent, application: app, principal: guest }); assert.equal(stale.ok, false); const depositButton = cardPaymentArtifactToA2UI({ artifact: depositArtifact, surfaceId: "surface-card-25" })[1]; assert.ok("updateComponents" in depositButton); const depositComponent = depositButton.updateComponents.components.find((component) => component.component === "Button"); assert.ok(depositComponent && "action" in depositComponent); const depositAction = depositComponent.action as unknown as { event: unknown }; const depositEvent = { message: { action: depositAction.event } } as never; const initializedDeposit = resolveCardPaymentServerEvent({ event: depositEvent, application: app, principal: guest }); assert.equal(initializedDeposit.ok, true); const depositSession = app.manager.getCheckoutSession(offer.offerId)!; assert.equal(depositSession.purpose, "security_deposit"); const confirmed = app.verifyAndConfirm(depositSession.pspReference, system); assert.equal((confirmed as unknown as { outcome: string }).outcome, "confirmed"); assert.equal(app.getArtifact(offer.offerId, guest).facts.status, "confirmed");
});
