import { test } from "node:test";
import assert from "node:assert/strict";
import { InMemoryBookingStateRepository } from "../domains/shortlet/src/booking-state.js";
import type { BookingContract, Reservation } from "../domains/shortlet/src/card-payment.js";
import { InMemoryRelocationRemedyRepository, RelocationApplication } from "../apps/web/src/relocation-application.js";
const contract: BookingContract={contractId:"c",reservationId:"r",offerId:"o",unitId:"u",tenantId:"t",parties:{primaryGuest:{id:"g",name:"Guest"},operator:{id:"op"}},dates:{checkIn:"2026-09-01",checkOut:"2026-09-03",nights:2},occupants:[],quote:{},totalAmountDueNowKobo:10000,policies:{cancellationPolicy:{},guestConductRules:[]},paymentDetails:{paymentMethod:"fresh_card",pspReference:"psp-private",amountKobo:10000,currency:"NGN",paidAt:"2026-08-01"},createdAt:"2026-08-01",contractVersion:1};
const reservation:Reservation={reservationId:"r",contractId:"c",unitId:"u",primaryGuestId:"g",dates:contract.dates,status:"confirmed",confirmedAt:"2026-08-01"};
function setup(){const cases=new InMemoryRelocationRemedyRepository();let refunds=0;const candidate={candidateId:"replacement-a",candidateVersion:"v1",termsVersion:"terms-1",neighborhood:"Ikoyi",entirePlace:true,capacity:2,bedrooms:1,beds:1,requiredAmenities:["wifi"],accessibilityCompatible:true,inspectionCurrent:true,safetyEligible:true,verificationCurrent:true,managementAuthorityCurrent:true,locationComparable:true,qualityComparable:true,checkInTimingComparable:true,operatorAcceptable:true,dates:{checkIn:"2026-09-01",checkOut:"2026-09-03"},replacementRemainingStayAccommodationKobo:10000,materialDisclosures:["second floor"],availability:{available:true,commitmentId:"hold-a",version:"av1"},priceCurrency:"NGN" as const};const app=new RelocationApplication({bookingState:new InMemoryBookingStateRepository({contracts:[contract],reservations:[reservation]}),eligibility:{getEligibility:()=>({eligible:true,eligibilityId:"e",eligibilityVersion:"ev1",source:"failed_access",failureActor:"operator",currentGuestRemedy:"relocation_or_refund",remainingStay:{checkIn:"2026-09-01",checkOut:"2026-09-03",nights:2}})},candidates:{getCandidates:()=>({candidateSetVersion:"set1",candidates:[candidate]}),getCandidate:()=>candidate},comparability:{compare:()=>({comparabilityVersion:"cmp1",comparable:true,dimensions:{capacity:true,bedrooms:true,beds:true,remaining_dates:true,required_amenities:true,entire_place:true,accessibility:true,inspection:true,safety:true,verification:true,management_authority:true,practical_location:true,quality:true,checkin_timing:true,operator_acceptability:true,material_disclosures:true},reasons:[]})},economics:{get:()=>({economicsVersion:"econ1",originalRemainingStayAccommodationKobo:10000,currency:"NGN"})},transport:{get:()=>({quoteVersion:"t1",costKobo:0})},approvals:{getApprovalState:()=>({policyVersion:"policy1",approvalVersion:"ap1",tier:"routine",approved:true,approvals:[]})},funding:{get:()=>({fundingVersion:"fund1",source:"guest_protection_fund",status:"pending_accounting"})},obligations:{get:()=>({obligationId:"ob1",obligationVersion:"obv1",scope:"full_booking",amountKobo:10000,currency:"NGN"})},refunds:{initiateOrGetRefund:()=>{refunds++;return {refundId:"ref1",status:"settled",amountKobo:10000,currency:"NGN"}}},fulfilment:{completeReplacement:()=>({status:"completed",replacementReservationId:"rr",replacementBookingReference:"RB-1"})},liability:{get:()=>({liabilityVersion:"l1",responsibleParty:"operator",operatorLiabilityKobo:0,platformExposureKobo:0})},policyVersion:"policy1",consequence:{record:()=>{},isAccommodationActive:()=>false},cases});return{app,getRefunds:()=>refunds,cases}}
test("Primary Guest choice uses shared versioned case and completion port idempotently",()=>{const s=setup();const p={id:"g",role:"guest" as const,tenantId:"t"};const a=s.app.getArtifact("r",p);const action=a.actions.find(x=>x.type==="choose_relocation_candidate");assert.ok(action);const result=s.app.chooseRelocation("r",p,action);assert.equal(result.facts.caseStatus,"relocated");assert.equal(s.cases.findByReservationId("r")?.replacementBookingReference,"RB-1");assert.equal(s.getRefunds(),0);});
test("Only authenticated Primary Guest can choose and refund remains original-source and idempotent",()=>{const s=setup();assert.throws(()=>s.app.getArtifact("r",{id:"payer",role:"guest",tenantId:"t"}),/Access denied/);const p={id:"g",role:"guest" as const,tenantId:"t"};const action=s.app.getArtifact("r",p).actions.find(x=>x.type==="choose_refund");assert.ok(action);s.app.chooseRefund("r",p,action);assert.equal(s.getRefunds(),1);assert.equal(s.cases.findByReservationId("r")?.refundId,"ref1");});
