import test from "node:test";
import assert from "node:assert/strict";
import { InMemoryBookingStateRepository } from "../domains/shortlet/src/booking-state.js";
import { InMemoryDepositClaimRepository, type DepositClaimProductionRecord } from "../domains/shortlet/src/deposit-claim.js";
import { InMemorySecurityDepositAccountingRepository } from "../domains/shortlet/src/security-deposit-accounting.js";
import { DepositClaimApplication } from "../apps/web/src/deposit-claim-application.js";
import type { BookingContract, Reservation } from "../domains/shortlet/src/card-payment.js";
import { depositClaimArtifact } from "../apps/web/src/deposit-claim-artifact.js";
import { createDepositClaimWebAgentAdapter } from "../apps/web-agent/src/presentation.js";

const guest = { id: "guest-27", role: "guest" as const, tenantId: "tenant-27" };
const staff = { id: "staff-27", role: "authorized_staff" as const, tenantId: "tenant-27" };
function setup() {
  const reservation: Reservation = { reservationId: "res-27", contractId: "contract-27", unitId: "unit-27", primaryGuestId: guest.id, dates: { checkIn: "2026-09-01", checkOut: "2026-09-02" }, status: "confirmed", confirmedAt: "2026-08-01T00:00:00.000Z" };
  const contract: BookingContract = { contractId: reservation.contractId, reservationId: reservation.reservationId, offerId: "offer-27", unitId: reservation.unitId, tenantId: guest.tenantId, parties: { primaryGuest: { id: guest.id, name: "Guest" }, operator: { id: "operator-27" } }, dates: { checkIn: "2026-09-01", checkOut: "2026-09-02", nights: 1 }, occupants: [{ name: "Guest" }], quote: {}, totalAmountDueNowKobo: 1, securityDeposit: { policyVersion: "deposit-v1", amountKobo: 2_000_000, currency: "NGN", collectionId: "security-deposit:offer-27", status: "held" }, policies: { cancellationPolicy: {}, guestConductRules: [] }, paymentDetails: { paymentMethod: "fresh_card", pspReference: "stay", amountKobo: 1, currency: "NGN", paidAt: "2026-08-01T00:00:00.000Z" }, createdAt: "2026-08-01T00:00:00.000Z", contractVersion: 1, checkout: { time: "11:00", timezone: "Africa/Lagos", source: "contractual" } };
  const accounting = new InMemorySecurityDepositAccountingRepository();
  const snapshot = { policyVersion: "deposit-v1", amountKobo: 2_000_000, currency: "NGN" as const } as never;
  accounting.createOrGet({ offerId: "offer-27", snapshot, paymentMethod: "fresh_card" }); accounting.recordCollection("security-deposit:offer-27", { providerReference: "deposit-source", collectedAt: "2026-08-01T00:00:00.000Z" }); accounting.bind("security-deposit:offer-27", { reservationId: reservation.reservationId, contractId: contract.contractId });
  const claim: DepositClaimProductionRecord = { claimId: "deposit-claim:res-27", reservationId: reservation.reservationId, contractId: contract.contractId, tenantId: guest.tenantId, operatorId: "operator-27", guestId: guest.id, policyVersion: "deposit-v1", claimPolicyVersion: "deposit-v1", evidenceVersion: "evidence-v1", depositAmountKobo: 2_000_000, claimedAmountKobo: 1_000_000, effectiveCheckoutIso: "2026-09-02T10:00:00.000Z", claimDeadlineIso: "2026-09-03T10:00:00.000Z", submittedAtIso: "2026-09-02T10:00:00.000Z", claimVersion: 1, status: "adjudicated", items: [], notification: { status: "delivered", notificationVersion: "claim-notice", deliveredAtIso: "2026-09-03T10:00:00.000Z", evidenceId: "claim-delivery" }, responseWindowStartIso: "2026-09-03T10:00:00.000Z", responseWindowEndIso: "2026-09-05T10:00:00.000Z", guestResponse: null, initialReservedOperatorAwardKobo: 1_000_000, initialApprovedAmountKobo: 1_000_000, approvedOperatorAwardKobo: 1_000_000, unapprovedRefundKobo: 1_000_000, adjudicationSnapshot: { decisionId: "decision-27", decisionVersion: "v1", claimId: "deposit-claim:res-27", claimVersion: 1, policyVersion: "deposit-v1", evidenceVersion: "evidence-v1", reviewerId: "human-27", reviewerAuthorityVersion: "authority-v1", approvedOperatorAwardKobo: 1_000_000, decidedAtIso: "2026-09-03T10:00:00.000Z", evaluations: [] }, finality: { finalityVersion: 1, status: "reserved", cause: null, finalizedAtIso: null, appealWindowStartsAt: null, appealWindowEndsAt: null }, history: [] };
  const claims = new InMemoryDepositClaimRepository(); claims.createIfAbsent(claim); accounting.allocateClaim({ reservationId: reservation.reservationId, claimId: claim.claimId, amountKobo: claim.claimedAmountKobo, expectedCollectionVersion: 3 });
  let now = new Date("2026-09-03T10:00:00.000Z"); const app = new DepositClaimApplication({ booking: new InMemoryBookingStateRepository({ contracts: [contract], reservations: [reservation] }), accounting, claims, terms: { getTerms: () => ({ reservationId: reservation.reservationId, checkoutDate: "2026-09-02", checkoutTime: "11:00", source: "contractual", termVersion: "term" }) }, evidence: { resolve: () => { throw new Error("unused") } }, policy: { validate: () => { throw new Error("unused") } }, notifications: { resolve: () => { throw new Error("unused") } }, refunds: { refundOrGet: (input) => ({ refundId: input.obligationId, status: "settled" as const, amountKobo: input.amountKobo, currency: "NGN" }) }, decisions: { get: () => { throw new Error("unused") } }, decisionNotices: { resolve: (input) => ({ ...input, noticeVersion: "full-v1", status: "delivered" as const, deliveredAtIso: "2026-09-03T10:00:00.000Z", deliveryEvidenceId: "full-delivery" }) }, clock: () => now });
  return { app, claims, accounting, setNow: (iso: string) => { now = new Date(iso); } };
}

test("Production full-decision receipt is separate from Issue 26 notice and direct viewing is replay-safe", () => { const s = setup(); const before = s.claims.findByClaimId("deposit-claim:res-27")!; assert.equal(before.finality?.appealWindowStartsAt, null); assert.equal(s.app.recordDecisionNotice(before.claimId, "guest", { id: "system-27", role: "system", tenantId: "tenant-27" }).finality?.appealWindowStartsAt, "2026-09-03T10:00:00.000Z"); const viewed = s.app.recordDecisionViewed(before.claimId, "guest", guest); assert.equal(viewed.finality?.appealWindowStartsAt, "2026-09-03T10:00:00.000Z"); assert.equal(s.app.recordDecisionViewed(before.claimId, "guest", guest).claimVersion, viewed.claimVersion); assert.equal(new Date(viewed.finality!.appealWindowEndsAt!).getTime() - new Date(viewed.finality!.appealWindowStartsAt!).getTime(), 7 * 24 * 60 * 60 * 1000); });

test("Canonical Issue 27 artifact uses deterministic WAT facts and Weaver Basic Catalog without provider leakage", () => { const s = setup(); const claim = s.claims.findByClaimId("deposit-claim:res-27")!; s.app.recordDecisionNotice(claim.claimId, "guest", { id: "system-27", role: "system", tenantId: "tenant-27" }); const artifact = depositClaimArtifact(s.app, "res-27", guest); const rendered = createDepositClaimWebAgentAdapter({ application: s.app, principal: guest, createSurfaceId: (id) => `surface:${id}` }).get("res-27"); assert.equal(rendered.artifact.projectionVersion, artifact.projectionVersion); assert.match(artifact.facts.appealDeadlineWAT ?? "", /2026/); assert.match(JSON.stringify(rendered.a2uiMessages), /v0.9.1/); assert.doesNotMatch(JSON.stringify(artifact), /deposit-source|providerReference|SecurityContext|session|device|auth token|private URL/i); });

test("Production guest acceptance is not a waiver and only a specific authenticated waiver grants finality", () => { const s = setup(); const claim = s.claims.findByClaimId("deposit-claim:res-27")!; assert.throws(() => s.app.waiveAppeal(claim.claimId, guest, { decisionId: "decision-27", decisionVersion: "v1" }), /STALE_ACTION/); s.app.recordDecisionNotice(claim.claimId, "guest", { id: "system-27", role: "system", tenantId: "tenant-27" }); const artifactBefore = s.app.getArtifact("res-27", guest); assert.equal(artifactBefore.finality?.status, "appeal_window_open"); const waived = s.app.waiveAppeal(claim.claimId, guest, { decisionId: "decision-27", decisionVersion: "v1" }); assert.equal(waived.finality?.cause, "guest_specific_waiver"); assert.equal(s.app.waiveAppeal(claim.claimId, guest, { decisionId: "decision-27", decisionVersion: "v1" }).claimVersion, waived.claimVersion); assert.throws(() => s.app.advanceClaimFinality(claim.claimId, { id: "other", role: "authorized_staff", tenantId: "other" }), /ACTION_NOT_AUTHORIZED/); void staff; });
