import test from "node:test";
import assert from "node:assert/strict";
import { CancellationNoShowManager } from "../domains/shortlet/src/index.js";
import { InMemoryBookingStateRepository } from "../domains/shortlet/src/booking-state.js";
import type { BookingContract, Reservation } from "../domains/shortlet/src/card-payment.js";
import { CancellationApplication, InMemoryCancellationCaseRepository } from "../apps/web/src/cancellation-application.js";
import { createCancellationWebAgentAdapter } from "../apps/web-agent/src/presentation.js";
import { resolveCancellationServerEvent } from "../apps/web/src/cancellation-actions.js";
import type { WebServerEventHandoff } from "@weaver/web";

const contract: BookingContract = { contractId: "c1", reservationId: "r1", offerId: "o1", unitId: "u1", tenantId: "t1", parties: { primaryGuest: { id: "g1", name: "Guest" }, operator: { id: "op" }, distinctPayer: null }, dates: { checkIn: "2026-09-01", checkOut: "2026-09-03", nights: 2 }, occupants: [{ name: "Guest" }], quote: {}, totalAmountDueNowKobo: 10000, policies: { cancellationPolicy: { type: "flexible", version: "A", policySummary: "Flexible" }, guestConductRules: [] }, paymentDetails: { paymentMethod: "fresh_card", pspReference: "backend-card-ref", amountKobo: 10000, currency: "NGN", paidAt: "2026-08-01T00:00:00Z" }, createdAt: "2026-08-01T00:00:00Z", contractVersion: 1 };
const reservation: Reservation = { reservationId: "r1", contractId: "c1", unitId: "u1", primaryGuestId: "g1", dates: { checkIn: "2026-09-01", checkOut: "2026-09-03" }, status: "confirmed", confirmedAt: "2026-08-01T00:00:00Z", inventoryCommitmentId: "commit-1" };
function setup(arrivalStatus: "awaiting_access" | "verified_access" | "late_voluntary_arrival" | "failed_access" | "under_human_review" = "awaiting_access", clockIso = "2026-08-29T13:00:00.000Z", contactVersion?: string) { const state = new InMemoryBookingStateRepository({ contracts: [contract], reservations: [reservation] }); const cases = new InMemoryCancellationCaseRepository(); const calls: string[] = []; const app = new CancellationApplication({ state, manager: new CancellationNoShowManager(), timing: { getWindow: () => ({ startIso: "2026-09-01T13:00:00.000Z", timezone: "Africa/Lagos" }) }, economics: { getEconomics: () => ({ version: "econ-2", currency: "NGN", cancellationBaseKobo: 8000, refundableCleaningKobo: 500, refundableUnprovidedServicesKobo: 250, refundableSecurityDepositKobo: 1000, refundableAttributableTaxKobo: 100, refundableDuplicatePaymentKobo: 50, commissionRate: .12 }) }, arrival: { getState: () => ({ status: arrivalStatus, version: "arrival-1" }) }, refunds: { initiateOrGetRefund: (input) => { calls.push(`refund:${input.originalPaymentReference}:${input.amountKobo}`); return { refundId: "ref-1", status: "pending", amountKobo: input.amountKobo, currency: "NGN" }; } }, ledger: { postCancellation: (input) => { calls.push(`ledger:${input.cancellationId}`); return { ledgerRecordId: "led-1", status: "posted" }; } }, availability: { releaseConfirmedBooking: (input) => calls.push(`release:${input.commitmentId}`) }, ...(contactVersion ? { contacts: { getStatus: () => ({ version: contactVersion, requiredAttemptsCompleted: true, contactFailed: true }) } } : {}), cases, clock: () => new Date(clockIso) }); return { app, state, calls, cases }; }

test("CancellationApplication uses authoritative economics, commits the Reservation, releases the exact commitment, and refunds the original source", () => { const { app, state, calls } = setup(); const artifact = app.cancel("r1", { id: "g1", role: "guest", tenantId: "t1" }); assert.equal(state.findReservationById("r1")?.status, "cancelled"); assert.deepEqual(calls, ["ledger:cancellation:r1", "release:commit-1", "refund:backend-card-ref:9900"]); assert.equal(artifact.facts.case?.refundStatus, "pending"); assert.equal(artifact.actions.length, 0); });

test("Generated Web Agent cancellation event resolves through the real server boundary and shared case repository", () => { const { app, state, cases, calls } = setup(); const principal = { id: "g1", role: "guest" as const, tenantId: "t1" }; const adapter = createCancellationWebAgentAdapter({ application: app, principal, createSurfaceId: (id) => `surface:${id}` }); const rendered = adapter.get("r1"); const message = rendered.a2uiMessages[1]; assert.ok("updateComponents" in message); const button = message.updateComponents.components.find((component) => component.component === "Button"); assert.ok(button && "action" in button); const action = button.action as unknown as { event: { name: string; context: unknown } }; const event = { message: { action: action.event } } as unknown as WebServerEventHandoff; const result = resolveCancellationServerEvent({ event, application: app, principal }); assert.equal(result.ok, true); assert.equal(state.findReservationById("r1")?.status, "cancelled"); assert.equal(cases.findByReservationId("r1")?.refundStatus, "pending"); assert.equal(calls.filter((call) => call.startsWith("ledger")).length, 1); assert.equal(result.ok && result.artifact.actions.length, 0); });

test("Active or contradictory arrival states remove ordinary guest cancellation", () => { for (const status of ["verified_access", "late_voluntary_arrival", "failed_access", "under_human_review"] as const) { const { app } = setup(status); const principal = { id: "g1", role: "guest" as const, tenantId: "t1" }; assert.equal(app.getArtifact("r1", principal).actions.length, 0); assert.throws(() => app.cancel("r1", principal), /STALE_ACTION/); } });

test("Authorized staff can confirm an eligible No-Show while guests cannot", () => { const { app, state } = setup("awaiting_access", "2026-09-02T09:00:00.000Z", "contact-1"); const guest = { id: "g1", role: "guest" as const, tenantId: "t1" }; const staff = { id: "s1", role: "authorized_staff" as const, tenantId: "t1" }; assert.equal(app.getArtifact("r1", guest).actions.some((action) => action.type === "confirm_no_show"), false); assert.equal(app.getArtifact("r1", staff).actions[0]?.type, "confirm_no_show"); app.confirmNoShow("r1", staff, app.getArtifact("r1", staff).actions[0]); assert.equal(state.findReservationById("r1")?.status, "no_show"); const { app: missingTenant } = setup("awaiting_access", "2026-09-02T09:00:00.000Z", "contact-1"); assert.throws(() => missingTenant.getArtifact("r1", { id: "s1", role: "authorized_staff", tenantId: "other" }), /Access denied/); assert.throws(() => missingTenant.confirmNoShow("r1", { id: "s1", role: "authorized_staff" }), /Access denied/); });

test("CancellationApplication fails closed for wrong guest and missing tenant", () => { const { app } = setup(); assert.throws(() => app.cancel("r1", { id: "other", role: "guest", tenantId: "t1" }), /Access denied/); assert.throws(() => app.cancel("r1", { id: "g1", role: "guest" }), /Access denied/); });
