import test from "node:test";
import assert from "node:assert/strict";
import { InteractionThreadManager, type SecurityContext } from "../packages/platform-core/src/index.js";
import { HumanHandoffApplication } from "../apps/web/src/human-handoff-application.js";
import { resolveHumanHandoffServerEvent, HUMAN_HANDOFF_STOP_EVENT } from "../apps/web/src/human-handoff-actions.js";
const subject: SecurityContext = { principalId: "guest", tenantId: "tenant", sessionId: "session" };
const staff = { id: "staff-1", role: "authorized_staff" as const, tenantId: "tenant" };
function setup() { const threads = new InteractionThreadManager(); const { threadId } = threads.createThread(subject); threads.startAgentRun(threadId, subject, { intent: "help" }); const app = new HumanHandoffApplication({ threadManager: threads, threadAuthority: { getSubjectContext: () => subject }, matterContext: { getContext: () => ({ activeStay: false, category: "general_support" }) }, assignment: { assign: () => ({ responderId: "staff-1", responderRole: "authorized_staff" }) }, resolution: { getResolution: () => ({ resolved: true }) } }); return { threads, threadId, app }; }
test("Human Handoff application preserves subject isolation and resolves the current run server-side", () => { const { threads, threadId, app } = setup(); assert.equal(app.getArtifact(threadId, subject).facts.currentRunStatus, "running"); assert.throws(() => app.getArtifact(threadId, { ...subject, principalId: "other" })); const before = app.getArtifact(threadId, subject); const event = { message: { action: { name: HUMAN_HANDOFF_STOP_EVENT, context: { artifactId: before.id, threadId, expectedMode: "automated", projectionVersion: before.projectionVersion } } } } as never; const stopped = resolveHumanHandoffServerEvent({ event, application: app, context: subject }); assert.equal(stopped.ok, true); assert.equal(app.getArtifact(threadId, subject).facts.currentRunStatus, "stopped"); assert.equal(threads.getActiveRun(threadId, subject), null); });
test("Trusted assignment, deliberate handback, fresh projection and a new run share one manager", () => { const { threads, threadId, app } = setup(); app.requestHumanSupport(threadId, subject); app.assignHumanOwner({ threadId, actor: staff }); const pending = app.prepareHandback({ threadId, actor: staff, userNotice: "Support has resolved this matter." }); assert.equal(pending.facts.mode, "resume-pending"); assert.equal(pending.facts.automationSuppressed, true); const old = threads.getCurrentRunStatus(threadId, subject).runId; const resumed = app.completeHandback(threadId); assert.equal(resumed.facts.mode, "automated"); assert.notEqual(threads.getCurrentRunStatus(threadId, subject).runId, old); assert.throws(() => app.assignHumanOwner({ threadId, actor: { id: "guest", role: "guest", tenantId: "tenant" } })); });
