import type { WebServerEventHandoff } from "@weaver/web";
import type { BookingContract, MidStayFailureAssessment } from "../domains/shortlet/src/index.js";
import { InMemoryBookingStateRepository } from "../domains/shortlet/src/booking-state.js";
import { InMemoryMidStayIncidentRepository } from "../domains/shortlet/src/index.js";
import { MidStayFailureApplication } from "../apps/web/src/mid-stay-failure-application.js";
import { createMidStayFailureWebAgentAdapter } from "../apps/web-agent/src/presentation.js";
export const principal = { id: "guest-1", role: "guest" as const, tenantId: "tenant-1" };
export const staff = { id: "staff-1", role: "authorized_staff" as const, tenantId: "tenant-1" };
const contract: BookingContract = { contractId: "contract-1", reservationId: "reservation-1", offerId: "offer-1", unitId: "unit-1", tenantId: "tenant-1", parties: { primaryGuest: { id: "guest-1", name: "Guest" }, operator: { id: "operator-1", name: "Operator" } }, dates: { checkIn: "2026-09-01", checkOut: "2026-09-03", nights: 2 }, occupants: [], quote: {}, totalAmountDueNowKobo: 25000000, policies: { cancellationPolicy: {}, guestConductRules: [] }, paymentDetails: { paymentMethod: "bank_transfer", transferReference: "transfer-1", amountKobo: 25000000, currency: "NGN", paidAt: "2026-08-30T00:00:00.000Z" }, createdAt: "2026-08-30T00:00:00.000Z", contractVersion: 1 };
const assessment = (materialIncident: boolean): MidStayFailureAssessment => ({ reservationId: "reservation-1", evidenceSetId: "evidence-set-1", contractVersion: 1, assessmentVersion: "assessment-1", category: materialIncident ? "safety_access_habitability" : "essential_amenity", failureStartedAt: "2026-09-01T00:00:00.000Z", affectedNightDates: ["2026-09-01"], unusedNightDates: materialIncident ? ["2026-09-02"] : [], materiallyUnusableNightDates: [], overnightImpact: false, materialIncident, causationVersion: "cause-1", causationStatus: "established", reportingDelayExcused: false, currentImpact: "ongoing", repeatedOrMaterialMinor: false });
export function makeApplication(materialIncident: boolean) { const booking = new InMemoryBookingStateRepository({ contracts: [contract], reservations: [{ reservationId: "reservation-1", contractId: contract.contractId, unitId: contract.unitId, primaryGuestId: "guest-1", dates: { checkIn: contract.dates.checkIn, checkOut: contract.dates.checkOut }, status: "confirmed", confirmedAt: contract.createdAt }] }); const repository = new InMemoryMidStayIncidentRepository(); let owned = false; let decisionVersion = "decision-1"; let economicsVersion = "economics-1"; const app = new MidStayFailureApplication({ bookingState: booking, repository, activeStay: { getStatus: () => ({ status: "verified_access", version: "arrival-1" }) }, evidence: { assessEvidence: () => ({ evidenceSetId: "evidence-set-1", evidenceVersion: "evidence-1", status: "sufficient" as const }) }, assessment: { assess: () => assessment(materialIncident) }, cure: { getStatus: () => ({ cureVersion: "cure-1", status: "cured" as const, curedAt: "2026-09-01T08:00:00.000Z" }) }, economics: { getEconomics: () => ({ economicsVersion, currency: "NGN" as const, nightlyLineItems: [{ nightDateIso: "2026-09-01", rateKobo: 10000000 }, { nightDateIso: "2026-09-02", rateKobo: 15000000 }], attributableUndeliveredChargesKobo: 100, attributableRefundableTaxKobo: 50 }) }, humanDecision: { getDecision: () => materialIncident ? ({ decisionId: "decision-1", decisionVersion, incidentId: "mid-stay-failure:reservation-1", incidentVersion: 1, assessmentVersion: "assessment-1", evidenceVersion: "evidence-1", economicsVersion: "economics-1", decision: "accept_remedy" as const, valid: true }) : null }, handoff: { requestHumanSupport: () => { owned = true; }, isHumanOwned: () => owned }, clock: () => new Date("2026-09-01T08:00:00.000Z") }); return { app, repository, getOwned: () => owned, changeDecision: () => { decisionVersion = "decision-2"; }, changeEconomics: () => { economicsVersion = "economics-2"; } }; }
export function generatedEvent(app: MidStayFailureApplication, viewer: typeof principal | typeof staff): WebServerEventHandoff { const rendered = createMidStayFailureWebAgentAdapter({ application: app, principal: viewer, createSurfaceId: (id) => `surface:${id}` }).get("reservation-1"); const update = rendered.a2uiMessages[1]; if (!("updateComponents" in update)) throw new Error("missing component update"); const button = update.updateComponents.components.find((component) => component.id === "midstay-action"); if (!button || !("action" in button) || !button.action) throw new Error("missing generated action"); const event = button.action as unknown as { event: unknown }; return { message: { action: event.event } } as unknown as WebServerEventHandoff; }
