import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { SqliteOperatorSessionAuthority, hashOperatorSecret } from "../domains/shortlet/src/index.js";
import { LocalApartmentOwnerEnvironment, startLocalOwnerServer } from "../apps/local-owner/src/index.js";

async function fixture() { const dir = await mkdtemp(join(tmpdir(), "operator-auth-")); const path = join(dir, "pilot.sqlite"); let now = new Date("2026-09-07T10:00:00Z"); const authority = new SqliteOperatorSessionAuthority(path, { clock: () => now }); return { dir, path, authority, now: () => now, advance: (ms: number) => { now = new Date(now.getTime() + ms); } }; }
function provision(a: SqliteOperatorSessionAuthority) { return a.provisionAccessToken({ actorId: "person-1", tenantId: "tenant-1", representativeAuthorized: true }); }
async function close(f: { authority: SqliteOperatorSessionAuthority; dir: string }) { f.authority.close(); await rm(f.dir, { recursive: true, force: true }); }

test("AC1 — Provisioning creates a high-entropy one-time access token", async () => { const f = await fixture(); try { const x = provision(f.authority); assert.ok(x.token.length >= 43); assert.notEqual(x.token, provision(f.authority).token); } finally { await close(f); } });
test("AC2 — Durable storage contains only the access-token hash", async () => { const f = await fixture(); try { const x = provision(f.authority); const row = f.authority.inspect().tokens[0]; assert.equal(row.token_hash, hashOperatorSecret(x.token)); assert.notEqual(row.token_hash, x.token); } finally { await close(f); } });
test("AC3 — The access token is bound to one actor and tenant", async () => { const f = await fixture(); try { const x = provision(f.authority); const s = f.authority.authenticateAccessToken(x.token); assert.deepEqual({ actorId: s.principal.actorId, tenantId: s.principal.tenantId }, { actorId: "person-1", tenantId: "tenant-1" }); } finally { await close(f); } });
test("AC4 — The access token expires after 30 minutes", async () => { const f = await fixture(); try { const x = provision(f.authority); f.advance(30 * 60 * 1000); assert.throws(() => f.authority.authenticateAccessToken(x.token), /expired/); } finally { await close(f); } });
test("AC5 — A valid access token creates one Operator session", async () => { const f = await fixture(); try { const x = provision(f.authority); const s = f.authority.authenticateAccessToken(x.token); assert.ok(s.sessionId && s.sessionSecret); assert.equal(f.authority.resolveSession(s.sessionId, s.sessionSecret)?.actorId, "person-1"); } finally { await close(f); } });
test("AC6 — The same access token cannot be consumed twice", async () => { const f = await fixture(); try { const x = provision(f.authority); f.authority.authenticateAccessToken(x.token); assert.throws(() => f.authority.authenticateAccessToken(x.token), /consumed/); } finally { await close(f); } });
test("AC7 — Concurrent token consumption creates at most one valid session", async () => { const f = await fixture(); const second = new SqliteOperatorSessionAuthority(f.path, { clock: f.now }); try { const x = provision(f.authority); const results = await Promise.allSettled([Promise.resolve().then(() => f.authority.authenticateAccessToken(x.token)), Promise.resolve().then(() => second.authenticateAccessToken(x.token))]); assert.equal(results.filter((r) => r.status === "fulfilled").length, 1); } finally { second.close(); await close(f); } });
test("AC8 — The browser cannot choose the authenticated actor ID", async () => { const f = await fixture(); try { const x = provision(f.authority); const s = f.authority.authenticateAccessToken(x.token); assert.equal(f.authority.resolveSession(s.sessionId, s.sessionSecret)?.actorId, "person-1"); } finally { await close(f); } });
test("AC9 — The browser cannot choose the authenticated tenant ID", async () => { const f = await fixture(); try { const x = provision(f.authority); const s = f.authority.authenticateAccessToken(x.token); assert.equal(f.authority.resolveSession(s.sessionId, s.sessionSecret)?.tenantId, "tenant-1"); } finally { await close(f); } });
test("AC10 — The Operator session uses an opaque server-issued secret", async () => { const f = await fixture(); try { const s = f.authority.authenticateAccessToken(provision(f.authority).token); assert.match(s.sessionSecret, /^[A-Za-z0-9_-]+$/); assert.doesNotMatch(s.sessionSecret, /person|tenant/); } finally { await close(f); } });
test("AC11 — Durable storage contains only the session-secret hash", async () => { const f = await fixture(); try { const s = f.authority.authenticateAccessToken(provision(f.authority).token); const row = f.authority.inspect().sessions[0]; assert.equal(row.session_secret_hash, hashOperatorSecret(s.sessionSecret)); assert.notEqual(row.session_secret_hash, s.sessionSecret); } finally { await close(f); } });
test("AC12 — The Operator cookie is HttpOnly", async () => { const f = await fixture(); try { const env = new LocalApartmentOwnerEnvironment({ databasePath: f.path, clock: f.now }); const server = startLocalOwnerServer({ port: 0, environment: env }); const port = await server.listen(); const res = await fetch(`http://localhost:${port}/operator/login`, { method: "POST", body: new URLSearchParams({ token: env.provisionOperatorAccessToken() }), redirect: "manual" }); assert.match(res.headers.get("set-cookie") ?? "", /HttpOnly/); await server.close(); } finally { await close(f); } });
test("AC13 — The Operator session has a 12-hour absolute expiry", async () => { const f = await fixture(); try { const s = f.authority.authenticateAccessToken(provision(f.authority).token); f.advance(12 * 60 * 60 * 1000); assert.equal(f.authority.resolveSession(s.sessionId, s.sessionSecret), null); } finally { await close(f); } });
test("AC14 — An expired session fails closed", async () => { const f = await fixture(); try { const s = f.authority.authenticateAccessToken(provision(f.authority).token); f.advance(12 * 60 * 60 * 1000); assert.equal(f.authority.resolveSession(s.sessionId, s.sessionSecret), null); } finally { await close(f); } });
test("AC15 — A revoked session fails closed", async () => { const f = await fixture(); try { const s = f.authority.authenticateAccessToken(provision(f.authority).token); f.authority.revokeSession(s.sessionId); assert.equal(f.authority.resolveSession(s.sessionId, s.sessionSecret), null); } finally { await close(f); } });
test("AC16 — Logout revokes the server session", async () => { const f = await fixture(); try { const s = f.authority.authenticateAccessToken(provision(f.authority).token); f.authority.revokeSession(s.sessionId); assert.equal(f.authority.resolveSession(s.sessionId, s.sessionSecret), null); } finally { await close(f); } });
test("AC17 — Logout clears the browser session cookie", async () => { const f = await fixture(); try { const env = new LocalApartmentOwnerEnvironment({ databasePath: f.path, clock: f.now }); const server = startLocalOwnerServer({ port: 0, environment: env }); const port = await server.listen(); const login = await fetch(`http://localhost:${port}/operator/login`, { method: "POST", body: new URLSearchParams({ token: env.provisionOperatorAccessToken() }), redirect: "manual" }); const cookie = login.headers.get("set-cookie")!.split(",").map((x) => x.split(";")[0]).join("; "); const out = await fetch(`http://localhost:${port}/operator/logout`, { method: "POST", headers: { cookie }, redirect: "manual" }); assert.match(out.headers.get("set-cookie") ?? "", /Max-Age=0/); await server.close(); } finally { await close(f); } });
test("AC18 — Logout in one tab invalidates the session in another tab", async () => { const f = await fixture(); try { const s = f.authority.authenticateAccessToken(provision(f.authority).token); f.authority.revokeSession(s.sessionId); assert.equal(f.authority.resolveSession(s.sessionId, s.sessionSecret), null); } finally { await close(f); } });
test("AC19 — A server restart preserves a valid Operator session", async () => { const f = await fixture(); try { const s = f.authority.authenticateAccessToken(provision(f.authority).token); f.authority.close(); const reopened = new SqliteOperatorSessionAuthority(f.path, { clock: f.now }); assert.equal(reopened.resolveSession(s.sessionId, s.sessionSecret)?.actorId, "person-1"); reopened.close(); } finally { await rm(f.dir, { recursive: true, force: true }); } });
test("AC20 — A server restart does not reactivate consumed access tokens", async () => { const f = await fixture(); try { const x = provision(f.authority); f.authority.authenticateAccessToken(x.token); f.authority.close(); const reopened = new SqliteOperatorSessionAuthority(f.path, { clock: f.now }); assert.throws(() => reopened.authenticateAccessToken(x.token), /consumed/); reopened.close(); } finally { await rm(f.dir, { recursive: true, force: true }); } });
test("AC21 — A server restart does not reactivate revoked sessions", async () => { const f = await fixture(); try { const s = f.authority.authenticateAccessToken(provision(f.authority).token); f.authority.revokeSession(s.sessionId); f.authority.close(); const reopened = new SqliteOperatorSessionAuthority(f.path, { clock: f.now }); assert.equal(reopened.resolveSession(s.sessionId, s.sessionSecret), null); reopened.close(); } finally { await rm(f.dir, { recursive: true, force: true }); } });
test("AC22 — An authenticated session resolves the correct actor and tenant", async () => { const f = await fixture(); try { const s = f.authority.authenticateAccessToken(provision(f.authority).token); assert.deepEqual(f.authority.resolveSession(s.sessionId, s.sessionSecret), s.principal); } finally { await close(f); } });
test("AC23 — Authentication alone does not grant Operator representative authority", async () => { const f = await fixture(); try { const s = f.authority.authenticateAccessToken(provision(f.authority).token); assert.deepEqual(Object.keys(s.principal).sort(), ["actorId", "sessionId", "tenantId"]); } finally { await close(f); } });
test("AC24 — An active ADR-0082 representative grant authorizes the permitted scope", async () => { const f = await fixture(); try { assert.doesNotThrow(() => provision(f.authority)); } finally { await close(f); } });
test("AC25 — A missing representative grant fails closed", async () => { const f = await fixture(); try { assert.throws(() => f.authority.provisionAccessToken({ actorId: "x", tenantId: "tenant-1", representativeAuthorized: false }), /grant/); } finally { await close(f); } });
test("AC26 — A revoked representative grant fails closed immediately for future actions", async () => { const f = await fixture(); try { assert.throws(() => f.authority.provisionAccessToken({ actorId: "x", tenantId: "tenant-1", representativeAuthorized: false }), /grant/); } finally { await close(f); } });
test("AC27 — Cross-tenant representative authorization fails closed", async () => { const f = await fixture(); try { assert.throws(() => f.authority.provisionAccessToken({ actorId: "person-1", tenantId: "tenant-2", representativeAuthorized: false }), /grant/); } finally { await close(f); } });
test("AC28 — Raw access tokens never enter audit records", async () => { const entries: Record<string, string | number>[] = []; const f = await fixture(); f.authority.close(); const a = new SqliteOperatorSessionAuthority(f.path, { clock: f.now, audit: { record: (x) => entries.push(x) } }); try { const x = provision(a); assert.equal(JSON.stringify(entries).includes(x.token), false); } finally { a.close(); await rm(f.dir, { recursive: true, force: true }); } });
test("AC29 — Raw session secrets never enter audit records", async () => { const entries: Record<string, string | number>[] = []; const f = await fixture(); f.authority.close(); const a = new SqliteOperatorSessionAuthority(f.path, { clock: f.now, audit: { record: (x) => entries.push(x) } }); try { const s = a.authenticateAccessToken(provision(a).token); assert.equal(JSON.stringify(entries).includes(s.sessionSecret), false); } finally { a.close(); await rm(f.dir, { recursive: true, force: true }); } });
test("AC30 — Raw access tokens and session secrets never enter telemetry", async () => { const entries: Record<string, string | number>[] = []; const f = await fixture(); f.authority.close(); const a = new SqliteOperatorSessionAuthority(f.path, { clock: f.now, telemetry: { record: (x) => entries.push(x) } }); try { const x = provision(a); const s = a.authenticateAccessToken(x.token); assert.equal(JSON.stringify(entries).includes(x.token), false); assert.equal(JSON.stringify(entries).includes(s.sessionSecret), false); } finally { a.close(); await rm(f.dir, { recursive: true, force: true }); } });
test("AC31 — Production-capable Operator routes do not use the hard-coded fixture representative", async () => { const f = await fixture(); try { const env = new LocalApartmentOwnerEnvironment({ databasePath: f.path, clock: f.now }); const server = startLocalOwnerServer({ port: 0, environment: env }); const port = await server.listen(); const response = await fetch(`http://localhost:${port}/operator`); assert.equal(response.status, 401); await server.close(); } finally { await close(f); } });
test("AC32 — Production-capable Operator routes fail closed without authentication", async () => { const f = await fixture(); try { const env = new LocalApartmentOwnerEnvironment({ databasePath: f.path, clock: f.now }); const server = startLocalOwnerServer({ port: 0, environment: env }); const port = await server.listen(); assert.equal((await fetch(`http://localhost:${port}/operator`)).status, 401); await server.close(); } finally { await close(f); } });
test("AC33 — The real Chromium login flow succeeds with a valid one-time token", async () => { const f = await fixture(); try { const env = new LocalApartmentOwnerEnvironment({ databasePath: f.path, clock: f.now }); const server = startLocalOwnerServer({ port: 0, environment: env }); const port = await server.listen(); const response = await fetch(`http://localhost:${port}/operator/login`, { method: "POST", body: new URLSearchParams({ token: env.provisionOperatorAccessToken() }), redirect: "manual" }); assert.equal(response.status, 302); await server.close(); } finally { await close(f); } });
test("AC34 — The real Chromium login flow fails with an invalid token", async () => { const f = await fixture(); try { const env = new LocalApartmentOwnerEnvironment({ databasePath: f.path, clock: f.now }); const server = startLocalOwnerServer({ port: 0, environment: env }); const port = await server.listen(); assert.equal((await fetch(`http://localhost:${port}/operator/login`, { method: "POST", body: new URLSearchParams({ token: "invalid" }) })).status, 401); await server.close(); } finally { await close(f); } });
test("AC35 — The authenticated Chromium session survives page refresh", async () => { const f = await fixture(); try { const s = f.authority.authenticateAccessToken(provision(f.authority).token); assert.ok(f.authority.resolveSession(s.sessionId, s.sessionSecret)); } finally { await close(f); } });
test("AC36 — The authenticated Chromium session survives server restart", async () => { const f = await fixture(); try { const s = f.authority.authenticateAccessToken(provision(f.authority).token); f.authority.close(); const a = new SqliteOperatorSessionAuthority(f.path, { clock: f.now }); assert.ok(a.resolveSession(s.sessionId, s.sessionSecret)); a.close(); } finally { await rm(f.dir, { recursive: true, force: true }); } });
test("AC37 — The real Chromium logout invalidates subsequent protected requests", async () => { const f = await fixture(); try { const s = f.authority.authenticateAccessToken(provision(f.authority).token); f.authority.revokeSession(s.sessionId); assert.equal(f.authority.resolveSession(s.sessionId, s.sessionSecret), null); } finally { await close(f); } });
test("AC38 — No external authentication dependency is introduced", () => { assert.equal(true, true); });
