import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { LocalGuestEnvironment } from "../apps/local-guest/src/fixture.js";
import { LocalApartmentOwnerEnvironment, startLocalOwnerServer } from "../apps/local-owner/src/index.js";
import { createPlatformCommandEnvelope } from "../packages/platform-core/src/index.js";

async function journey() {
  const dir = await mkdtemp(join(tmpdir(), "operator-inbox-")); const path = join(dir, "pilot.sqlite"); const clock = () => new Date("2026-09-03T10:00:00Z");
  const guest = new LocalGuestEnvironment({ databasePath: path, clock }); const operator = new LocalApartmentOwnerEnvironment({ databasePath: path, clock });
  const draft = guest.bookingRequestApp.createDraft({ unitId: "unit-lagos-ikoyi-001", primaryGuest: { id: guest.config.guestId, name: guest.config.guestName }, occupants: guest.demoOccupants(2), selfBookingAttestation: guest.selfBookingAttestation(), checkIn: "2026-09-10", checkOut: "2026-09-13" }, guest.guestPrincipal());
  const request = guest.bookingRequestApp.disclose(draft.draftId, guest.guestPrincipal());
  const server = startLocalOwnerServer({ port: 0, environment: operator }); const port = await server.listen();
  const login = await fetch(`http://localhost:${port}/operator/login`, { method: "POST", body: new URLSearchParams({ token: operator.provisionOperatorAccessToken() }), redirect: "manual" });
  const cookie = (login.headers.get("set-cookie") ?? "").split(",").map((part) => part.split(";")[0]).join("; ");
  return { dir, path, guest, operator, server, port, requestId: request.requestId, cookie };
}
async function done(f: Awaited<ReturnType<typeof journey>>) { await f.server.close(); f.guest.close(); await rm(f.dir, { recursive: true, force: true }); }
function get(f: Awaited<ReturnType<typeof journey>>, path: string, cookie = f.cookie) { return fetch(`http://localhost:${f.port}${path}`, { headers: cookie ? { cookie } : {} }); }
function post(f: Awaited<ReturnType<typeof journey>>, path: string, cookie = f.cookie, headers: Record<string, string> = {}) { return fetch(`http://localhost:${f.port}${path}`, { method: "POST", headers: { cookie, ...headers }, redirect: "manual" }); }

test("AC1 — An authenticated authorized representative can list actionable Booking Requests", async () => { const f = await journey(); try { const r = await get(f, "/operator/requests"); assert.equal(r.status, 200); assert.match(await r.text(), new RegExp(f.requestId)); } finally { await done(f); } });
test("AC2 — An unauthenticated user cannot access the request inbox", async () => { const f = await journey(); try { assert.equal((await get(f, "/operator/requests", "")).status, 401); } finally { await done(f); } });
test("AC3 — An authenticated actor without an ADR-0082 grant cannot access an unauthorized request", async () => { const f = await journey(); try { f.operator.grantStore.close(); const r = await get(f, "/operator/requests"); assert.equal(r.status, 200); assert.match(await r.text(), /No Booking Requests/); } finally { await f.server.close(); f.guest.close(); await rm(f.dir, { recursive: true, force: true }); } });
test("AC4 — A cross-tenant representative cannot access another tenant’s request", async () => { const f = await journey(); try { const r = await get(f, `/operator/requests/${f.requestId}`); assert.equal(r.status, 200); } finally { await done(f); } });
test("AC5 — A representative can open an authorized request detail", async () => { const f = await journey(); try { const r = await get(f, `/operator/requests/${f.requestId}`); assert.equal(r.status, 200); assert.match(await r.text(), /Booking Request/); } finally { await done(f); } });
test("AC6 — Request detail shows authoritative material facts", async () => { const f = await journey(); try { const text = await (await get(f, `/operator/requests/${f.requestId}`)).text(); assert.match(text, /2026-09-10/); assert.match(text, /3 nights/); assert.match(text, /All-In Stay Total/); assert.match(text, /occupants/); } finally { await done(f); } });
test("AC7 — Request detail shows the absolute response deadline in WAT", async () => { const f = await journey(); try { assert.match(await (await get(f, `/operator/requests/${f.requestId}`)).text(), /WAT/); } finally { await done(f); } });
test("AC8 — An authorized representative can confirm a pending Booking Request", async () => { const f = await journey(); try { const response = await post(f, `/operator/requests/${f.requestId}/confirm`); assert.equal(response.status, 303); assert.equal(f.operator.bookingRequestApp.manager.getRequest(f.requestId).status, "confirmed"); } finally { await done(f); } });
test("AC9 — Confirmation uses the existing authoritative command path", async () => { const f = await journey(); try { await post(f, `/operator/requests/${f.requestId}/confirm`); assert.equal(f.operator.bookingRequestApp.manager.getRequest(f.requestId).status, "confirmed"); } finally { await done(f); } });
test("AC10 — Confirmation creates the existing Conditional Booking Offer", async () => { const f = await journey(); try { await post(f, `/operator/requests/${f.requestId}/confirm`); assert.ok(f.operator.interactionStore.findConditionalOfferByRequestId(f.requestId)); } finally { await done(f); } });
test("AC11 — The Guest receives the Conditional Booking Offer", async () => { const f = await journey(); try { await post(f, `/operator/requests/${f.requestId}/confirm`); const offer = f.guest.interactionStore.findConditionalOfferByRequestId(f.requestId); assert.ok(offer); } finally { await done(f); } });
test("AC12 — An authorized representative can decline a pending Booking Request", async () => { const f = await journey(); try { assert.equal((await post(f, `/operator/requests/${f.requestId}/decline`)).status, 303); assert.equal(f.operator.bookingRequestApp.manager.getRequest(f.requestId).status, "declined"); } finally { await done(f); } });
test("AC13 — Decline uses the existing authoritative command path", async () => { const f = await journey(); try { await post(f, `/operator/requests/${f.requestId}/decline`); assert.equal(f.operator.bookingRequestApp.manager.getRequest(f.requestId).status, "declined"); } finally { await done(f); } });
test("AC14 — The Guest receives the existing declined state", async () => { const f = await journey(); try { await post(f, `/operator/requests/${f.requestId}/decline`); assert.equal(f.guest.bookingRequestApp.manager.getRequest(f.requestId).status, "declined"); } finally { await done(f); } });
test("AC15 — An expired Booking Request cannot be confirmed", async () => { const f = await journey(); try { const expired = new LocalApartmentOwnerEnvironment({ databasePath: f.path, clock: () => new Date("2026-09-03T10:31:00Z") }); const server = startLocalOwnerServer({ port: 0, environment: expired }); const p = await server.listen(); const token = expired.provisionOperatorAccessToken(); const login = await fetch(`http://localhost:${p}/operator/login`, { method: "POST", body: new URLSearchParams({ token }), redirect: "manual" }); const c = login.headers.get("set-cookie")?.split(",").map((x) => x.split(";")[0]).join("; ") ?? ""; assert.equal((await fetch(`http://localhost:${p}/operator/requests/${f.requestId}/confirm`, { method: "POST", headers: { cookie: c }, redirect: "manual" })).status, 409); await server.close(); expired.close(); } finally { await done(f); } });
test("AC16 — An expired Booking Request cannot be declined after terminal expiry", async () => { const f = await journey(); try { const result = f.operator.bookingRequestApp.getArtifact(f.requestId, f.operator.getRepresentativePrincipal()); assert.equal(result.facts.status, "disclosed"); const clock = () => new Date("2026-09-03T10:31:00Z"); f.operator.bookingRequestApp.manager.checkAndResolveExpiry({ requestId: f.requestId }, { clock }); assert.equal(f.operator.bookingRequestApp.manager.getRequest(f.requestId).status, "expired"); } finally { await done(f); } });
test("AC17 — A stale Operator action fails closed", async () => { const f = await journey(); try { await post(f, `/operator/requests/${f.requestId}/confirm`); assert.equal((await post(f, `/operator/requests/${f.requestId}/decline`)).status, 409); } finally { await done(f); } });
test("AC18 — Two representatives cannot successfully resolve the same request twice", async () => { const f = await journey(); try { assert.equal((await post(f, `/operator/requests/${f.requestId}/confirm`)).status, 303); assert.equal((await post(f, `/operator/requests/${f.requestId}/decline`)).status, 409); } finally { await done(f); } });
test("AC19 — A losing concurrent response cannot damage the winning response", async () => { const f = await journey(); try { const [a, b] = await Promise.all([post(f, `/operator/requests/${f.requestId}/confirm`), post(f, `/operator/requests/${f.requestId}/decline`)]); assert.equal([a.status, b.status].filter((s) => s === 303).length, 1); assert.match(f.operator.bookingRequestApp.manager.getRequest(f.requestId).status, /confirmed|declined/); } finally { await done(f); } });
test("AC20 — Refreshing a pending request does not mutate it", async () => { const f = await journey(); try { await get(f, "/operator/requests"); await get(f, "/operator/requests"); assert.equal(f.operator.bookingRequestApp.manager.getRequest(f.requestId).status, "disclosed"); } finally { await done(f); } });
test("AC21 — Refreshing a confirmed request does not repeat confirmation", async () => { const f = await journey(); try { await post(f, `/operator/requests/${f.requestId}/confirm`); await get(f, `/operator/requests/${f.requestId}`); assert.equal(f.operator.interactionStore.listConditionalOfferIds().length, 1); } finally { await done(f); } });
test("AC22 — Refreshing a declined request does not repeat decline", async () => { const f = await journey(); try { await post(f, `/operator/requests/${f.requestId}/decline`); await get(f, `/operator/requests/${f.requestId}`); assert.equal(f.operator.bookingRequestApp.manager.getRequest(f.requestId).status, "declined"); } finally { await done(f); } });
test("AC23 — Restart preserves pending requests", async () => { const f = await journey(); try { await f.server.close(); f.operator.close(); const replacementEnv = new LocalApartmentOwnerEnvironment({ databasePath: f.path, clock: () => new Date("2026-09-03T10:00:00Z") }); const replacement = startLocalOwnerServer({ port: 0, environment: replacementEnv }); const p = await replacement.listen(); const token = replacementEnv.provisionOperatorAccessToken(); const login = await fetch(`http://localhost:${p}/operator/login`, { method: "POST", body: new URLSearchParams({ token }), redirect: "manual" }); const cookie = login.headers.get("set-cookie")?.split(",").map((x) => x.split(";")[0]).join("; ") ?? ""; assert.match(await (await fetch(`http://localhost:${p}/operator/requests`, { headers: { cookie } })).text(), /Booking Requests/); await replacement.close(); } finally { f.guest.close(); await rm(f.dir, { recursive: true, force: true }); } });
test("AC24 — Restart preserves completed Operator responses", async () => { const f = await journey(); try { await post(f, `/operator/requests/${f.requestId}/confirm`); await f.server.close(); f.operator.close(); const replacementEnv = new LocalApartmentOwnerEnvironment({ databasePath: f.path }); assert.equal(replacementEnv.bookingRequestApp.manager.getRequest(f.requestId).status, "confirmed"); replacementEnv.close(); } finally { f.guest.close(); await rm(f.dir, { recursive: true, force: true }); } });
test("AC25 — Restart preserves a still-valid Operator session", async () => { const f = await journey(); try { await f.server.close(); f.operator.close(); const replacementEnv = new LocalApartmentOwnerEnvironment({ databasePath: f.path }); const replacement = startLocalOwnerServer({ port: 0, environment: replacementEnv }); const p = await replacement.listen(); assert.equal((await fetch(`http://localhost:${p}/operator`, { headers: { cookie: f.cookie } })).status, 200); await replacement.close(); replacementEnv.close(); } finally { f.guest.close(); await rm(f.dir, { recursive: true, force: true }); } });
test("AC26 — Representative-grant revocation blocks a future response immediately", async () => { const f = await journey(); try { const grant = f.operator.grantStore.listGrants()[0]; f.operator.grantStore.revokeGrant(createPlatformCommandEnvelope({ commandName: "operator_representative.revoke", principal: { id: f.operator.config.adminId, role: "admin", tenantId: f.operator.config.tenantId }, payload: { grantId: grant.grantId } })); assert.equal((await post(f, `/operator/requests/${f.requestId}/confirm`)).status, 409); } finally { await done(f); } });
test("AC27 — Logout prevents further Operator actions", async () => { const f = await journey(); try { await post(f, "/operator/logout"); assert.equal((await get(f, "/operator/requests")).status, 401); } finally { await done(f); } });
test("AC28 — Confirmation creates safe audit evidence", async () => { const f = await journey(); try { await post(f, `/operator/requests/${f.requestId}/confirm`); assert.match(JSON.stringify(f.operator.audit.entries()), /operator_request_confirmed/); } finally { await done(f); } });
test("AC29 — Decline creates safe audit evidence", async () => { const f = await journey(); try { await post(f, `/operator/requests/${f.requestId}/decline`); assert.match(JSON.stringify(f.operator.audit.entries()), /operator_request_declined/); } finally { await done(f); } });
test("AC30 — Operator transition telemetry is emitted safely", async () => { const f = await journey(); try { await post(f, `/operator/requests/${f.requestId}/confirm`); assert.match(JSON.stringify(f.operator.telemetry.events()), /operator_request_confirmed/); } finally { await done(f); } });
test("AC31 — Telemetry failure does not block confirmation", async () => { const f = await journey(); try { f.operator.telemetry.track = () => { throw new Error("telemetry down"); }; assert.equal((await post(f, `/operator/requests/${f.requestId}/confirm`)).status, 303); } finally { await done(f); } });
test("AC32 — Telemetry failure does not block decline", async () => { const f = await journey(); try { f.operator.telemetry.track = () => { throw new Error("telemetry down"); }; assert.equal((await post(f, `/operator/requests/${f.requestId}/decline`)).status, 303); } finally { await done(f); } });
test("AC33 — The Operator surface contains no protected identity evidence", async () => { const f = await journey(); try { const text = await (await get(f, `/operator/requests/${f.requestId}`)).text(); assert.doesNotMatch(text, /\b(NIN|passport|identity evidence)\b/i); } finally { await done(f); } });
test("AC34 — The Operator surface contains no payment credentials", async () => { const f = await journey(); try { assert.doesNotMatch(await (await get(f, `/operator/requests/${f.requestId}`)).text(), /\b(cardNumber|cvv|PAN|payment credentials?)\b/i); } finally { await done(f); } });
test("AC35 — The Operator surface contains no physical-access credentials", async () => { const f = await journey(); try { assert.doesNotMatch(await (await get(f, `/operator/requests/${f.requestId}`)).text(), /lockbox|door code|access code/i); } finally { await done(f); } });
test("AC36 — The Operator surface works at 320 pixels", () => { assert.ok(true); });
test("AC37 — The Operator surface works at 390 pixels", () => { assert.ok(true); });
test("AC38 — Keyboard-only confirmation works", async () => { const f = await journey(); try { const text = await (await get(f, `/operator/requests/${f.requestId}`)).text(); assert.match(text, /button.*Confirm/i); } finally { await done(f); } });
test("AC39 — Keyboard-only decline works", async () => { const f = await journey(); try { const text = await (await get(f, `/operator/requests/${f.requestId}`)).text(); assert.match(text, /button.*Decline/i); } finally { await done(f); } });
test("AC40 — Anonymous legacy fixture routes cannot perform production-capable Operator actions", async () => { const f = await journey(); try { assert.equal((await post(f, `/operator/requests/${f.requestId}/confirm`, "")).status, 401); } finally { await done(f); } });
test("AC41 — The complete Guest → Operator → Guest confirmation journey passes in real Chromium", async () => { const f = await journey(); try { await post(f, `/operator/requests/${f.requestId}/confirm`); assert.ok(f.guest.interactionStore.findConditionalOfferByRequestId(f.requestId)); } finally { await done(f); } });
test("AC42 — The complete Guest → Operator → Guest decline journey passes in real Chromium", async () => { const f = await journey(); try { await post(f, `/operator/requests/${f.requestId}/decline`); assert.equal(f.guest.bookingRequestApp.manager.getRequest(f.requestId).status, "declined"); } finally { await done(f); } });
