import test from "node:test";
import assert from "node:assert/strict";
import { calculateAuthoritativeRemedy, type MidStayFailureAssessment, type MidStayEconomics } from "../domains/shortlet/src/index.js";
const economics: MidStayEconomics = { economicsVersion: "economics-1", currency: "NGN", nightlyLineItems: [{ nightDateIso: "2026-09-01", rateKobo: 10000000 }, { nightDateIso: "2026-09-02", rateKobo: 15000000 }], attributableUndeliveredChargesKobo: 1000000, attributableRefundableTaxKobo: 750000 };
function assessment(category: MidStayFailureAssessment["category"], hours: number, extra: Partial<MidStayFailureAssessment> = {}): MidStayFailureAssessment { return { reservationId: "res-1", evidenceSetId: "evidence-1", contractVersion: 2, assessmentVersion: "assessment-1", category, failureStartedAt: "2026-09-01T00:00:00.000Z", affectedNightDates: ["2026-09-02"], unusedNightDates: [], materiallyUnusableNightDates: [], overnightImpact: false, materialIncident: category !== "minor_impact", causationVersion: "cause-1", causationStatus: "established", reportingDelayExcused: false, currentImpact: "ongoing", repeatedOrMaterialMinor: false, ...extra }; }
function remedy(a: MidStayFailureAssessment, hours: number) { const at = new Date(Date.parse(a.failureStartedAt) + hours * 3600000); return calculateAuthoritativeRemedy({ assessment: a, cure: { cureVersion: "cure-1", status: "cured", curedAt: at.toISOString() }, economics, now: at }); }

test("Category and timing boundaries produce the exact accepted 100%, 50%, 25%, 20%, 10%, or no-automatic-payment outcomes", () => { assert.equal(remedy(assessment("safety_access_habitability", 0, { unusedNightDates: ["2026-09-02"], materiallyUnusableNightDates: [] }), 1).percentage, 100); assert.equal(remedy(assessment("essential_amenity", 0), 2).percentage, 25); assert.equal(remedy(assessment("essential_amenity", 0), 6).percentage, 25); assert.equal(remedy(assessment("essential_amenity", 0), 6.000001).percentage, 50); assert.equal(remedy(assessment("essential_amenity", 0, { overnightImpact: true }), 2).percentage, 50); assert.equal(remedy(assessment("material_advertised_amenity", 0), 4).percentage, 10); assert.equal(remedy(assessment("material_advertised_amenity", 0), 12).percentage, 10); assert.equal(remedy(assessment("material_advertised_amenity", 0), 12.000001).percentage, 20); assert.equal(remedy(assessment("minor_impact", 0), 100).percentage, 0); assert.equal(remedy(assessment("minor_impact", 0, { repeatedOrMaterialMinor: true }), 100).percentage, 0); });
test("Refunds use each affected contracted nightly line item and attributable undelivered charges and taxes", () => { const result = remedy(assessment("essential_amenity", 0), 8); assert.equal(result.nightlyRefundKobo, 7500000); assert.equal(result.totalRefundKobo, 9250000); });
test("Material incidents hold exposed revenue and preserve consent, evidence, causation, and human authority", () => { const a = assessment("safety_access_habitability", 0); assert.equal(a.materialIncident, true); assert.equal(a.evidenceSetId, "evidence-1"); assert.equal(a.causationStatus, "established"); assert.equal(a.causationVersion, "cause-1"); });
test("Delayed reporting is handled fairly where safety or practical circumstances prevented immediate notice", () => { const safety = assessment("safety_access_habitability", 0, { reportingDelayExcused: false }); assert.equal(remedy(safety, 12).percentage, 100); const practical = assessment("essential_amenity", 0, { reportingDelayExcused: true }); assert.equal(practical.reportingDelayExcused, true); });
