import { test } from "node:test";
import assert from "node:assert/strict";
import { relocationArtifactToA2UI } from "../apps/web-agent/src/relocation-a2ui.js";
import { A2UI_V091_BASIC_CATALOG_ID } from "@weaver/core";
import { createRelocationWebAgentAdapter } from "../apps/web-agent/src/presentation.js";
import { resolveRelocationServerEvent } from "../apps/web/src/relocation-actions.js";
import { setup } from "./integrate-relocation-application.test.js";
const action={type:"choose_refund" as const,artifactId:"relocation-remedy:r",reservationId:"r",caseId:"relocation-remedy:r",expectedCaseVersion:1,expectedContractVersion:1,eligibilityVersion:"e",remainingStayEconomicsVersion:"x",relocationPolicyVersion:"p",refundObligationVersion:"o",liabilityVersion:"l",projectionVersion:"v"};
test("Relocation artifact renders all guest choices through Weaver Basic Catalog",()=>{const artifact={id:"relocation-remedy:r",kind:"shortlet.relocation-remedy" as const,schema:"shortlet.relocation-remedy/v1" as const,projectionVersion:"v",facts:{reservationId:"r",eligibility:{source:"failed_access"},refund:{scope:"full_booking",amountKobo:1000},candidates:[{candidateId:"a",candidateVersion:"v1",dates:{checkIn:"2026-01-01",checkOut:"2026-01-02"},neighborhood:"Ikoyi",entirePlace:true,capacity:2,bedrooms:1,beds:1,requiredAmenities:["wifi"],materialDisclosures:["floor"]}]},actions:[action]};const messages=relocationArtifactToA2UI({artifact,surfaceId:"surface"});assert.ok("createSurface" in messages[0]);assert.equal(messages[0].createSurface.catalogId,A2UI_V091_BASIC_CATALOG_ID);const text=JSON.stringify(messages);assert.match(text,/Choose refund/);assert.match(text,/Your accommodation remedy/);assert.doesNotMatch(text,/psp|address|access code/i);});

test("Generated Primary Guest refund and candidate events resolve through the real application",()=>{const principal={id:"g",role:"guest" as const,tenantId:"t"};for(const expected of ["choose_refund","choose_relocation_candidate"] as const){const s=setup();const rendered=createRelocationWebAgentAdapter({application:s.app,principal,createSurfaceId:id=>`surface:${id}`});const view=rendered.get("r");const update=view.a2uiMessages.find(m=>"updateComponents" in m);assert.ok(update&&"updateComponents" in update);const button=update.updateComponents.components.find(c=>c.component==="Button"&&String(c.id).includes(expected==="choose_refund"?"refund":"candidate"));assert.ok(button&&"action" in button);const actionButton=button as unknown as {action:{event:{name:string;context:unknown}}};const event={message:{action:actionButton.action.event}};if(expected==="choose_relocation_candidate"){const context=actionButton.action.event.context as Record<string,unknown>;assert.equal(typeof context.candidateId,"string");assert.equal(typeof context.termsVersion,"string");assert.equal(typeof context.approvalVersion,"string");assert.equal(typeof context.comparabilityVersion,"string");assert.equal(typeof context.availabilityVersion,"string");assert.equal("candidate" in context,false);assert.equal("approvals" in context,false);assert.equal("principal" in context,false);assert.equal("tenantId" in context,false);}const result=resolveRelocationServerEvent({event: event as never,application:s.app,principal});assert.equal(result.ok,true);if(expected==="choose_refund")assert.equal(s.getRefunds(),1);}});
