import { InMemoryBookingStateRepository } from "../domains/shortlet/src/booking-state.js";
import type { BookingContract, Reservation } from "../domains/shortlet/src/card-payment.js";
import { RevenueReleaseManager } from "../domains/shortlet/src/revenue-release.js";
import { InMemoryRevenueAccountingRepository, type RevenueAdjustmentRecord } from "../domains/shortlet/src/revenue-accounting.js";
import { RevenueReleaseApplication } from "../apps/web/src/revenue-release-application.js";
export const revenueNow = new Date("2026-09-02T12:00:00.000Z");
export const revenuePrincipal = { id: "system", role: "system" as const, tenantId: "tenant" };
export function setupRevenueRelease(overrides: Partial<{ status: Reservation["status"]; accessStatus: "awaiting_access" | "verified_access"; plan: "fast_payout" | "full_post_stay"; risk: number; adjustment: RevenueAdjustmentRecord }> = {}) {
  const contract: BookingContract = { contractId: "contract-1", reservationId: "reservation-1", offerId: "offer-1", unitId: "unit-1", tenantId: "tenant", parties: { primaryGuest: { id: "guest-1", name: "Guest" }, operator: { id: "operator-1", name: "Operator" }, distinctPayer: null }, dates: { checkIn: "2026-09-01", checkOut: "2026-09-03", nights: 2 }, occupants: [{ name: "Guest" }], quote: {}, totalAmountDueNowKobo: 100000, policies: { cancellationPolicy: {}, guestConductRules: [] }, paymentDetails: { paymentMethod: "fresh_card", pspReference: "provider-reference", amountKobo: 100000, currency: "NGN", paidAt: "2026-09-01T10:00:00.000Z" }, createdAt: "2026-09-01T10:00:00.000Z", contractVersion: 1, checkout: { time: "11:00", timezone: "Africa/Lagos", source: "contractual" } };
  const reservation: Reservation = { reservationId: "reservation-1", contractId: contract.contractId, unitId: contract.unitId, primaryGuestId: "guest-1", dates: { checkIn: "2026-09-01", checkOut: "2026-09-03" }, status: overrides.status ?? "confirmed", confirmedAt: "2026-09-01T10:00:00.000Z" };
  const state = new InMemoryBookingStateRepository({ contracts: [contract], reservations: [reservation] }); const accounting = new InMemoryRevenueAccountingRepository();
  const app = new RevenueReleaseApplication({ bookingState: state, manager: new RevenueReleaseManager(), accounting, access: { getAccess: () => ({ version: "access-1", status: overrides.accessStatus ?? "verified_access", verifiedAt: "2026-09-01T12:00:00.000Z", protectionWindowStartsAt: "2026-09-01T12:00:00.000Z" }) }, complaints: { hasUnresolvedBlockingComplaint: () => false }, holds: { getHold: () => ({ holdVersion: "hold-1", blocked: false, reasonCodes: [] }) }, accounts: { getStatus: () => ({ version: "account-1", active: true }) }, economics: { getEconomics: () => ({ economicsVersion: "economics-1", currency: "NGN", commissionPolicyVersion: "adr-0062-launch-v1", capturedCommissionRate: 0.08, commissionableOperatorRevenueKobo: 123457, operatorBorneProcessorCostsKobo: 101, applicableWithholdingKobo: 7, preReleaseRefundOrCreditKobo: 0, bookingOffsetsKobo: 3, securityDepositKobo: 9000, platformRemittedTaxesKobo: 8000, platformOwnedFeesKobo: 600, passThroughKobo: 600, undeliveredExtrasKobo: 0 }) }, payoutPlans: { getPlan: () => ({ planVersion: "plan-1", plan: overrides.plan ?? "fast_payout" }) }, checkout: { getTerms: () => ({ checkoutIso: "2026-09-03T13:00:00.000Z", version: "checkout-1" }) }, risk: { getHold: () => ({ version: "risk-1", amountKobo: overrides.risk ?? 1000 }) }, adjustments: { getAdjustment: () => { if (!overrides.adjustment) throw new Error("fixture only"); return overrides.adjustment; } }, clock: () => revenueNow });
  return { app, accounting, contract, reservation };
}
