import test from "node:test";
import assert from "node:assert/strict";
import { InMemorySecurityDepositAccountingRepository } from "../domains/shortlet/src/security-deposit-accounting.js";
import { calculateSecurityDepositPolicySnapshot } from "../domains/shortlet/src/security-deposit.js";
function repo() { const accounting = new InMemorySecurityDepositAccountingRepository(); const snapshot = calculateSecurityDepositPolicySnapshot({ accommodationSubtotalKobo: 80_000_000, bedrooms: 3, configuredDepositKobo: 20_000_000 }); accounting.createOrGet({ offerId: "o", snapshot, paymentMethod: "fresh_card" }); accounting.recordCollection("security-deposit:o", { providerReference: "deposit-source", collectedAt: "2026-01-01T00:00:00Z" }); accounting.bind("security-deposit:o", { reservationId: "r", contractId: "c" }); return accounting; }
test("Issue 26 accounting allocates a claim and derives the complete invariant", () => { const a = repo(); const held = a.getByReservationId("r"); assert.ok(held); a.allocateClaim({ reservationId: "r", claimId: "deposit-claim:r", amountKobo: 5_000_000, expectedCollectionVersion: held.collectionVersion }); const s = a.summary("r"); assert.deepEqual(s && { originalCollectedKobo: s.originalCollectedKobo, claimReservedKobo: s.claimReservedKobo, unallocatedHeldKobo: s.unallocatedHeldKobo }, { originalCollectedKobo: 20_000_000, claimReservedKobo: 5_000_000, unallocatedHeldKobo: 15_000_000 }); });
test("Issue 26 surplus and unapproved refunds share the real collection identity", () => { const a = repo(); const held = a.getByReservationId("r"); assert.ok(held); a.allocateClaim({ reservationId: "r", claimId: "deposit-claim:r", amountKobo: 5_000_000, expectedCollectionVersion: held.collectionVersion }); a.ensureRefundObligation({ obligationId: "deposit-claim:r:surplus", reservationId: "r", claimId: "deposit-claim:r", amountKobo: 15_000_000 }); a.markRefundResult({ obligationId: "deposit-claim:r:surplus", status: "settled", settledAt: "2026-01-02T00:00:00Z" }); a.prepareClaimOutcome({ claimId: "deposit-claim:r", approvedReserveKobo: 2_000_000, refundObligationId: "deposit-claim:r:unapproved", refundAmountKobo: 3_000_000 }); a.markRefundResult({ obligationId: "deposit-claim:r:unapproved", status: "settled", settledAt: "2026-01-02T00:00:00Z" }); const summary = a.summary("r"); assert.equal(summary?.refundSettledKobo, 18_000_000); assert.equal(summary?.claimReservedKobo, 2_000_000); assert.equal(summary?.unallocatedHeldKobo, 0); assert.deepEqual(a.journals().slice(-2).map((journal) => journal.collectionId), ["security-deposit:o", "security-deposit:o"]); });
test("Issue 26 refund replay is idempotent and pending can settle once", () => { const a = repo(); a.ensureRefundObligation({ obligationId: "x", reservationId: "r", claimId: null, amountKobo: 20_000_000 }); a.markRefundResult({ obligationId: "x", status: "pending", settledAt: "2026-01-02T00:00:00Z" }); a.markRefundResult({ obligationId: "x", status: "settled", settledAt: "2026-01-03T00:00:00Z" }); a.markRefundResult({ obligationId: "x", status: "settled", settledAt: "2026-01-04T00:00:00Z" }); assert.equal(a.journals().filter((j) => j.obligationId === "x").length, 1); assert.equal(a.refundObligation("x")?.status, "settled"); });
test("Issue 26 failed refund is terminal reconciliation and does not become settled", () => { const a = repo(); a.ensureRefundObligation({ obligationId: "x", reservationId: "r", claimId: null, amountKobo: 20_000_000 }); a.markRefundResult({ obligationId: "x", status: "reconciliation_required", settledAt: "2026-01-02T00:00:00Z" }); a.markRefundResult({ obligationId: "x", status: "settled", settledAt: "2026-01-03T00:00:00Z" }); assert.equal(a.refundObligation("x")?.status, "reconciliation_required"); assert.equal(a.journals().filter((j) => j.obligationId === "x").length, 0); });
test("Issue 26 accounting rejects over-allocation and refund identity conflicts", () => { const a = repo(); const held = a.getByReservationId("r"); assert.ok(held); a.allocateClaim({ reservationId: "r", claimId: "c1", amountKobo: 20_000_000, expectedCollectionVersion: held.collectionVersion }); assert.throws(() => a.allocateClaim({ reservationId: "r", claimId: "c2", amountKobo: 1, expectedCollectionVersion: held.collectionVersion }), /exceeds/); assert.throws(() => a.ensureRefundObligation({ obligationId: "refund", reservationId: "r", claimId: "c1", amountKobo: 1 }), /available/); });
test("Issue 26 reconciliation refunds remain encumbered and block new allocation or refund", () => { const a = repo(); const held = a.getByReservationId("r"); assert.ok(held); a.allocateClaim({ reservationId: "r", claimId: "claim", amountKobo: 5_000_000, expectedCollectionVersion: held.collectionVersion }); a.ensureRefundObligation({ obligationId: "claim:surplus", reservationId: "r", claimId: "claim", amountKobo: 15_000_000 }); a.markRefundResult({ obligationId: "claim:surplus", status: "reconciliation_required", settledAt: "2026-01-02T00:00:00Z" }); assert.deepEqual(a.summary("r") && { claimReservedKobo: a.summary("r")!.claimReservedKobo, refundPendingKobo: a.summary("r")!.refundPendingKobo, refundSettledKobo: a.summary("r")!.refundSettledKobo, refundReconciliationKobo: a.summary("r")!.refundReconciliationKobo, unallocatedHeldKobo: a.summary("r")!.unallocatedHeldKobo }, { claimReservedKobo: 5_000_000, refundPendingKobo: 0, refundSettledKobo: 0, refundReconciliationKobo: 15_000_000, unallocatedHeldKobo: 0 }); assert.throws(() => a.allocateClaim({ reservationId: "r", claimId: "another", amountKobo: 1, expectedCollectionVersion: held.collectionVersion }), /exceeds|STALE/); assert.throws(() => a.ensureRefundObligation({ obligationId: "another-refund", reservationId: "r", claimId: null, amountKobo: 1 }), /available/); });
test("Issue 26 same claim allocation replay is idempotent and conflicting allocation is rejected", () => { const a = repo(); const held = a.getByReservationId("r"); assert.ok(held); assert.deepEqual(a.allocateClaim({ reservationId: "r", claimId: "c", amountKobo: 1_000, expectedCollectionVersion: held.collectionVersion }).amountKobo, a.allocateClaim({ reservationId: "r", claimId: "c", amountKobo: 1_000, expectedCollectionVersion: held.collectionVersion }).amountKobo); assert.throws(() => a.allocateClaim({ reservationId: "r", claimId: "c", amountKobo: 2_000, expectedCollectionVersion: held.collectionVersion }), /identity/); });
