import type { CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { BankTransferCheckoutSession, BankTransferRefundRecord, BankTransferReconciliationRecord, BookingContract, BookingPaymentJourney } from "../../../domains/shortlet/src/index.js";

export const BANK_TRANSFER_ARTIFACT_KIND = "shortlet.bank-transfer";
export const BANK_TRANSFER_SCHEMA_VERSION = "shortlet.bank-transfer/v1";
export type BankTransferStatus = "ready" | "transfer_initiated" | "processing_in_grace" | "deposit_required" | "confirmed" | "expired" | "late_payment_refund_pending" | "late_payment_refunded";
export interface BankTransferAction { readonly type: "initialize_transfer"; readonly artifactId: string; readonly offerId: string; readonly expectedStatus: "ready" | "deposit_required"; readonly expectedPurpose?: "stay" | "security_deposit"; readonly expectedJourneyVersion?: number; readonly expectedStage?: string; readonly depositPolicyVersion?: string; readonly projectionVersion: number; }
export interface BankTransferArtifact {
  readonly id: string; readonly kind: typeof BANK_TRANSFER_ARTIFACT_KIND; readonly schemaVersion: typeof BANK_TRANSFER_SCHEMA_VERSION; readonly projectionVersion: number;
  readonly facts: { readonly offerId: string; readonly status: BankTransferStatus; readonly unit: string; readonly unitId: string; readonly checkIn: string; readonly checkOut: string; readonly amountDueNowKobo: number; readonly allInStayTotalKobo?: number; readonly refundableSecurityDepositKobo?: number; readonly depositPolicyVersion?: string; readonly currentComponent?: "stay" | "security_deposit"; readonly currentComponentAmountKobo?: number; readonly journeyVersion?: number; readonly journeyStage?: string; readonly currency: "NGN"; readonly paymentWindowExpiresAt: string; readonly graceEndsAt: string; readonly expectedPayerName?: string; readonly bankName?: string; readonly accountNumber?: string; readonly transferReference?: string; readonly reservationId?: string; readonly contractId?: string; readonly contractVersion?: number; readonly amountPaidKobo?: number; readonly paidAt?: string; readonly refundId?: string; readonly reconciliationId?: string; readonly reconciliationStatus?: string; };
  readonly actions: readonly BankTransferAction[]; readonly sensitivity: "booking-sensitive";
}
export function bankTransferArtifactId(offerId: string): string { return `bank-transfer:${offerId}`; }
export function bankTransferArtifactFromState({ offer, viewer, session, contract, journey, refundRecord, reconciliationRecord, now }: { readonly offer: { offerId: string; unitId: string; unit: { title: string }; dates: { checkIn: string; checkOut: string }; totalAmountDueNowKobo: number; refundableSecurityDepositKobo?: number; securityDeposit?: { policyVersion: string }; quote?: { allInStayTotalKobo?: number }; paymentWindow: { expiresAt: string }; status: string; parties: { primaryGuest: { id: string; name: string }; distinctPayer?: { id: string; name: string } | null }; tenantId?: string }; readonly viewer: CommandPrincipal; readonly session?: BankTransferCheckoutSession; readonly contract?: BookingContract; readonly refundRecord?: BankTransferRefundRecord; readonly reconciliationRecord?: BankTransferReconciliationRecord; readonly now: Date; readonly journey?: BookingPaymentJourney | null }): BankTransferArtifact {
  const payer = offer.parties.distinctPayer ?? offer.parties.primaryGuest; const authorized = viewer.role === "guest" && !!viewer.id && viewer.id === payer.id && !!viewer.tenantId && !!offer.tenantId && viewer.tenantId === offer.tenantId;
  const expired = now.getTime() >= new Date(offer.paymentWindow.expiresAt).getTime();
  const status: BankTransferStatus = contract ? "confirmed" : journey?.stage === "stay_settled" ? "deposit_required" : refundRecord?.status === "completed" ? "late_payment_refunded" : refundRecord ? "late_payment_refund_pending" : session?.status === "processing_in_grace" ? "processing_in_grace" : session?.status === "initiated" ? (expired ? "expired" : "transfer_initiated") : session?.status === "expired" || expired ? "expired" : "ready";
  const facts: BankTransferArtifact["facts"] = { offerId: offer.offerId, status, unit: offer.unit.title, unitId: offer.unitId, checkIn: offer.dates.checkIn, checkOut: offer.dates.checkOut, amountDueNowKobo: offer.totalAmountDueNowKobo, ...(offer.quote?.allInStayTotalKobo === undefined ? {} : { allInStayTotalKobo: offer.quote.allInStayTotalKobo }), ...(offer.refundableSecurityDepositKobo === undefined ? {} : { refundableSecurityDepositKobo: offer.refundableSecurityDepositKobo }), ...(offer.securityDeposit ? { depositPolicyVersion: offer.securityDeposit.policyVersion } : {}), ...(session || journey?.stage === "stay_settled" ? { currentComponent: journey?.stage === "stay_settled" ? "security_deposit" as const : session!.purpose, currentComponentAmountKobo: journey?.stage === "stay_settled" ? journey.deposit.amountKobo : session!.amountKobo } : {}), ...(journey ? { journeyVersion: journey.journeyVersion, journeyStage: journey.stage } : {}), currency: "NGN", paymentWindowExpiresAt: offer.paymentWindow.expiresAt, graceEndsAt: session?.graceEndsAt ?? new Date(new Date(offer.paymentWindow.expiresAt).getTime() + 600000).toISOString(), ...(authorized ? { expectedPayerName: payer.name } : {}), ...(authorized && session && (status === "transfer_initiated" || status === "processing_in_grace") ? { bankName: session.bankName, accountNumber: session.accountNumber, transferReference: session.transferReference } : {}), ...(contract ? { reservationId: contract.reservationId, contractId: contract.contractId, contractVersion: contract.contractVersion, amountPaidKobo: contract.paymentDetails.amountKobo, paidAt: contract.paymentDetails.paidAt } : {}), ...(refundRecord ? { refundId: refundRecord.refundId } : {}), ...(reconciliationRecord ? { reconciliationId: reconciliationRecord.reconciliationId, reconciliationStatus: reconciliationRecord.status } : {}) };
  const projectionVersion = { ready: 1, transfer_initiated: 2, processing_in_grace: 3, deposit_required: 4, confirmed: 5, expired: 6, late_payment_refund_pending: 7, late_payment_refunded: 8 }[status];
  const actions = authorized && (status === "ready" || status === "deposit_required") ? [{ type: "initialize_transfer" as const, artifactId: bankTransferArtifactId(offer.offerId), offerId: offer.offerId, expectedStatus: status === "ready" ? "ready" as const : "deposit_required" as const, expectedPurpose: status === "deposit_required" ? "security_deposit" as const : "stay" as const, expectedJourneyVersion: journey?.journeyVersion, expectedStage: journey?.stage, depositPolicyVersion: offer.securityDeposit?.policyVersion, projectionVersion }] : [];
  return Object.freeze({ id: bankTransferArtifactId(offer.offerId), kind: BANK_TRANSFER_ARTIFACT_KIND, schemaVersion: BANK_TRANSFER_SCHEMA_VERSION, projectionVersion, facts: Object.freeze(facts), actions: Object.freeze(actions), sensitivity: "booking-sensitive" as const });
}
