import { createPlatformCommandEnvelope, type CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { BookingContract } from "../../../domains/shortlet/src/card-payment.js";
import type { BookingAmendmentChanges, BookingAmendmentManager, BookingAmendmentResult } from "../../../domains/shortlet/src/booking-amendment.js";
import { bookingAmendmentArtifactFromState, type BookingAmendmentArtifact } from "./booking-amendment-artifact.js";
export interface BookingAmendmentApplicationOptions { readonly manager: BookingAmendmentManager; readonly contracts: { getContract(id: string): BookingContract }; readonly clock?: () => Date; }
export class BookingAmendmentApplication { readonly #o: BookingAmendmentApplicationOptions; constructor(options: BookingAmendmentApplicationOptions) { this.#o = options; }
  getArtifact(contractId: string, principal: CommandPrincipal): BookingAmendmentArtifact { const envelope = createPlatformCommandEnvelope({ commandName: "booking_amendment.get_artifact", principal, payload: { contractId } }); let contract: BookingContract; try { contract = this.#o.contracts.getContract(contractId); } catch { throw new Error("Access denied or resource not found"); } if (!contract || envelope.principal.role !== "guest" || !envelope.principal.id || envelope.principal.id !== contract.parties.primaryGuest.id || !contract.tenantId || !envelope.principal.tenantId || envelope.principal.tenantId !== contract.tenantId) throw new Error("Access denied or resource not found"); return bookingAmendmentArtifactFromState(contract, this.#o.manager.getLatestForContract(contractId)); }
  requestAmendment(contractId: string, changes: BookingAmendmentChanges, principal: CommandPrincipal): BookingAmendmentArtifact { this.#o.manager.requestAmendment(createPlatformCommandEnvelope({ commandName: "booking_amendment.request", principal, payload: { contractId, changes } }), this.#o.clock); return this.getArtifact(contractId, principal); }
  acceptAmendment(amendmentId: string, principal: CommandPrincipal) { return this.#o.manager.acceptAmendment(amendmentId, principal, this.#o.clock); }
  finalizeSettlement(amendmentId: string, principal: CommandPrincipal): BookingAmendmentResult { return this.#o.manager.commitAmendment(createPlatformCommandEnvelope({ commandName: "booking_amendment.commit", principal, payload: { amendmentId } }), this.#o.clock); }
}
