import type { WebServerEventHandoff } from "@weaver/web";
import type { CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { BookingAmendmentApplication } from "./booking-amendment-application.js";
import type { BookingAmendmentArtifact } from "./booking-amendment-artifact.js";

export const BOOKING_AMENDMENT_ACCEPT_EVENT = "shortlet.booking-amendment.accept";
export interface BookingAmendmentAcceptContext { readonly artifactId: string; readonly contractId: string; readonly amendmentId: string; readonly amendmentVersion: number; readonly expectedContractVersion: number; readonly quoteId: string; readonly quoteVersion: string | number; readonly projectionVersion: string; }
export type BookingAmendmentActionResult = { readonly ok: true; readonly artifact: BookingAmendmentArtifact } | { readonly ok: false; readonly code: "UNSUPPORTED_ACTION" | "INVALID_CONTEXT" | "STALE_ACTION" | "ACTION_NOT_AUTHORIZED"; readonly message: string };
const keys = ["artifactId", "contractId", "amendmentId", "amendmentVersion", "expectedContractVersion", "quoteId", "quoteVersion", "projectionVersion"] as const;
function contextOf(event: WebServerEventHandoff): BookingAmendmentAcceptContext | undefined { const value: unknown = event?.message?.action?.context; if (!value || typeof value !== "object" || Array.isArray(value)) return undefined; const record = value as Record<string, unknown>; if (Object.keys(record).length !== keys.length || keys.some((key) => !(key in record))) return undefined; if (typeof record.artifactId !== "string" || typeof record.contractId !== "string" || typeof record.amendmentId !== "string" || typeof record.amendmentVersion !== "number" || !Number.isInteger(record.amendmentVersion) || typeof record.expectedContractVersion !== "number" || !Number.isInteger(record.expectedContractVersion) || typeof record.quoteId !== "string" || (typeof record.quoteVersion !== "string" && typeof record.quoteVersion !== "number") || typeof record.projectionVersion !== "string") return undefined; return record as unknown as BookingAmendmentAcceptContext; }
export function isBookingAmendmentAcceptContext(value: unknown): value is BookingAmendmentAcceptContext { if (!value || typeof value !== "object" || Array.isArray(value)) return false; const record = value as Record<string, unknown>; return keys.length === Object.keys(record).length && keys.every((key) => key in record) && typeof record.artifactId === "string" && typeof record.contractId === "string" && typeof record.amendmentId === "string" && typeof record.amendmentVersion === "number" && typeof record.expectedContractVersion === "number" && typeof record.quoteId === "string" && (typeof record.quoteVersion === "string" || typeof record.quoteVersion === "number") && typeof record.projectionVersion === "string"; }
export function resolveBookingAmendmentServerEvent({ event, application, principal }: { readonly event: WebServerEventHandoff; readonly application: BookingAmendmentApplication; readonly principal: CommandPrincipal }): BookingAmendmentActionResult { if (event?.message?.action?.name !== BOOKING_AMENDMENT_ACCEPT_EVENT) return { ok: false, code: "UNSUPPORTED_ACTION", message: "The action is not supported." }; const context = contextOf(event); if (!context) return { ok: false, code: "INVALID_CONTEXT", message: "The action context is invalid." }; let current: BookingAmendmentArtifact; try { current = application.getArtifact(context.contractId, principal); } catch { return { ok: false, code: "ACTION_NOT_AUTHORIZED", message: "The action is not authorized." }; } const proposal = current.facts.proposal; if (!proposal || context.artifactId !== current.id || context.contractId !== current.facts.contractId || context.amendmentId !== proposal.amendmentId || context.amendmentVersion !== proposal.amendmentVersion || context.expectedContractVersion !== current.facts.currentContractVersion || context.quoteId !== proposal.quoteId || String(context.quoteVersion) !== String(proposal.quoteVersion) || context.projectionVersion !== current.projectionVersion) return { ok: false, code: "STALE_ACTION", message: "The amendment action is stale; refresh the current proposal." }; try { application.acceptAmendment(context.amendmentId, principal); return { ok: true, artifact: application.getArtifact(context.contractId, principal) }; } catch (error) { return { ok: false, code: error instanceof Error && error.message === "STALE_ACTION" ? "STALE_ACTION" : "ACTION_NOT_AUTHORIZED", message: "The amendment action was rejected." }; } }
