import { createPlatformCommandEnvelope, type CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import { CancellationNoShowManager, type CancellationArrivalStateProvider, type CancellationEconomicsProvider, type CancellationLiability, type CancellationLiabilityAuthority, type ContractualCheckInWindowProvider, type NoShowContactAttemptProvider, validateCancellationPolicy } from "../../../domains/shortlet/src/cancellation-noshow.js";
import type { BookingContract, Reservation } from "../../../domains/shortlet/src/card-payment.js";
import type { BookingStateRepository } from "../../../domains/shortlet/src/booking-state.js";
import { cancellationArtifactId, cancellationProjectionVersion, type CancellationArtifact } from "./cancellation-artifact.js";

interface RefundProvider { initiateOrGetRefund(input: { cancellationId: string; reservationId: string; paymentMethod: "fresh_card" | "bank_transfer"; originalPaymentReference: string; amountKobo: number; currency: "NGN" }): { refundId: string; status: "pending" | "settled" | "failed"; amountKobo: number; currency: "NGN" }; }
interface LedgerPort { postCancellation(input: { cancellationId: string; reservationId: string; liability: string; amountKobo: number; retainedCancellationBaseKobo: number; retainedCommissionKobo: number; currency: "NGN" }): { ledgerRecordId: string; status: "posted" }; }
interface ReleasePort { releaseConfirmedBooking(input: { commitmentId: string; unitId: string; start: string; end: string }): void; }
interface Case { cancellationId: string; caseVersion: number; outcome: "guest_cancellation" | "reviewed_cancellation" | "no_show"; refundStatus: "not_started" | "pending" | "settled" | "failed"; inventoryReleaseStatus: "pending" | "released" | "reconciliation_required"; ledgerStatus: "pending" | "posted" | "reconciliation_required"; }
export interface CancellationApplicationOptions { readonly state: BookingStateRepository; readonly manager: CancellationNoShowManager; readonly timing: ContractualCheckInWindowProvider; readonly economics: CancellationEconomicsProvider; readonly arrival: CancellationArrivalStateProvider; readonly liability?: CancellationLiabilityAuthority; readonly contacts?: NoShowContactAttemptProvider; readonly refunds: RefundProvider; readonly ledger: LedgerPort; readonly availability: ReleasePort; readonly audit?: { record(entry: Record<string, unknown>): void }; readonly clock?: () => Date; }
function guestAuthorized(contract: BookingContract, reservation: Reservation, principal: CommandPrincipal): void { if (principal.role !== "guest" || !principal.id || principal.id !== contract.parties.primaryGuest.id || !contract.tenantId || !principal.tenantId || principal.tenantId !== contract.tenantId || reservation.contractId !== contract.contractId) throw new Error("Access denied or resource not found"); }
function viewerAuthorized(contract: BookingContract, reservation: Reservation, principal: CommandPrincipal): void { if (principal.role === "authorized_staff" || principal.role === "admin") { if (!principal.tenantId || !contract.tenantId || principal.tenantId !== contract.tenantId) throw new Error("Access denied or resource not found"); return; } guestAuthorized(contract, reservation, principal); }
export class CancellationApplication {
  readonly #o: CancellationApplicationOptions; readonly #cases = new Map<string, Case>();
  constructor(options: CancellationApplicationOptions) { this.#o = options; }
  getArtifact(reservationId: string, principal: CommandPrincipal): CancellationArtifact {
    const reservation = this.#o.state.findReservationById(reservationId); const contract = reservation ? this.#o.state.findContractById(reservation.contractId) : null;
    if (!reservation || !contract) throw new Error("Access denied or resource not found"); viewerAuthorized(contract, reservation, principal);
    const policy = validateCancellationPolicy(contract.policies.cancellationPolicy); const window = this.#o.timing.getWindow(reservationId, contract); const economics = this.#o.economics.getEconomics({ reservationId, contract });
    const arrival = this.#o.arrival.getState(reservationId); const estimate = this.#o.manager.calculateAuthoritative({ reservationId, contract, economics, policy, checkInWindowStartIso: window.startIso, at: this.#o.clock?.() ?? new Date(), liability: "guest" });
    const caseState = this.#cases.get(reservationId); const id = cancellationArtifactId(reservationId);
    const markers = { reservationStatus: reservation.status, contractVersion: contract.contractVersion, policyVersion: policy.version, economicsVersion: economics.version, estimate: { percentage: estimate.refundPercentage, total: estimate.totalRefundKobo }, arrivalVersion: arrival.version, caseState };
    const projectionVersion = cancellationProjectionVersion(markers); const actions: Array<CancellationArtifact["actions"][number]> = reservation.status === "confirmed" ? [{ type: "cancel_booking", artifactId: id, reservationId, expectedReservationStatus: "confirmed", expectedContractVersion: contract.contractVersion, policyVersion: policy.version, economicsVersion: economics.version, projectionVersion }] : [];
    let noShow: CancellationArtifact["facts"]["noShow"];
    if (this.#o.contacts) { const contact = this.#o.contacts.getStatus(reservationId); const eligible = reservation.status === "confirmed" && this.#o.clock ? (() => { try { this.#o.manager.assertNoShowEligible({ reservation, checkInDate: contract.dates.checkIn, now: this.#o.clock!(), arrival, contact }); return true; } catch { return false; } })() : false; noShow = { deadline: this.#o.manager.noShowDeadline(contract.dates.checkIn), eligible }; if ((principal.role === "authorized_staff" || principal.role === "admin") && eligible) actions.push({ type: "confirm_no_show", artifactId: id, reservationId, expectedReservationStatus: "confirmed", expectedContractVersion: contract.contractVersion, policyVersion: policy.version, economicsVersion: economics.version, projectionVersion }); }
    return Object.freeze({ id, kind: "shortlet.cancellation", schemaVersion: "shortlet.cancellation/v1", projectionVersion, facts: Object.freeze({ reservationId, contractId: contract.contractId, reservationStatus: reservation.status, contractVersion: contract.contractVersion, policy, contractualCheckInWindowStart: window.startIso, timezone: "Africa/Lagos" as const, economicsVersion: economics.version, currentRefundEstimate: estimate, ...(caseState ? { case: caseState } : {}), ...(noShow ? { noShow } : {}) }), actions: Object.freeze(actions) });
  }
  cancel(reservationId: string, principal: CommandPrincipal): CancellationArtifact { const reservation = this.#o.state.findReservationById(reservationId); if (!reservation) throw new Error("Access denied or resource not found"); const contract = this.#o.state.findContractById(reservation.contractId); if (!contract) throw new Error("Access denied or resource not found"); guestAuthorized(contract, reservation, principal); if (this.#cases.has(reservationId)) return this.getArtifact(reservationId, principal); const before = this.getArtifact(reservationId, principal); const command = createPlatformCommandEnvelope({ commandName: "shortlet.cancellation.cancel", principal, payload: { reservationId, expectedReservationStatus: "confirmed", expectedContractVersion: before.facts.contractVersion, policyVersion: before.facts.policy.version, economicsVersion: before.facts.economicsVersion, projectionVersion: before.projectionVersion } }); void command;
    const current = this.#o.state.transitionReservationStatus(reservationId, "confirmed", "cancelled"); return this.#complete(reservationId, contract, current, "guest_cancellation", "guest"); }
  processReviewedCancellation(reservationId: string, principal: CommandPrincipal): CancellationArtifact { if (principal.role !== "authorized_staff" && principal.role !== "admin") throw new Error("Authorized human staff is required"); const reservation = this.#o.state.findReservationById(reservationId); if (!reservation) throw new Error("Access denied or resource not found"); const contract = this.#o.state.findContractById(reservation.contractId); if (!contract) throw new Error("Access denied or resource not found"); if (!principal.tenantId || principal.tenantId !== contract.tenantId) throw new Error("Access denied or resource not found"); const decision = this.#o.liability?.getDecision({ reservationId }); if (!decision || !decision.valid) throw new Error("Trusted cancellation liability decision is required"); if (this.#cases.has(reservationId)) return this.getArtifact(reservationId, principal); const current = this.#o.state.transitionReservationStatus(reservationId, "confirmed", "cancelled"); return this.#complete(reservationId, contract, current, "reviewed_cancellation", decision.liability); }
  confirmNoShow(reservationId: string, principal: CommandPrincipal): CancellationArtifact { if (principal.role !== "authorized_staff" && principal.role !== "admin") throw new Error("Authorized human staff is required"); const reservation = this.#o.state.findReservationById(reservationId); if (!reservation) throw new Error("Access denied or resource not found"); const contract = this.#o.state.findContractById(reservation.contractId); if (!contract) throw new Error("Access denied or resource not found"); const arrival = this.#o.arrival.getState(reservationId); const contact = this.#o.contacts?.getStatus(reservationId); if (!contact) throw new Error("Trusted contact status is required"); this.#o.manager.assertNoShowEligible({ reservation, checkInDate: contract.dates.checkIn, now: this.#o.clock?.() ?? new Date(), arrival, contact }); const current = this.#o.state.transitionReservationStatus(reservationId, "confirmed", "no_show"); return this.#complete(reservationId, contract, current, "no_show", "guest"); }
  #complete(reservationId: string, contract: BookingContract, reservation: Reservation, outcome: Case["outcome"], liability: CancellationLiability): CancellationArtifact { const economics = this.#o.economics.getEconomics({ reservationId, contract }); const policy = validateCancellationPolicy(contract.policies.cancellationPolicy); const window = this.#o.timing.getWindow(reservationId, contract); const estimate = this.#o.manager.calculateAuthoritative({ reservationId, contract, economics, policy, checkInWindowStartIso: window.startIso, at: this.#o.clock?.() ?? new Date(), liability: outcome === "no_show" ? "guest" : liability }); const cancellationId = `cancellation:${reservationId}`; const ledger = this.#o.ledger.postCancellation({ cancellationId, reservationId, liability, amountKobo: estimate.totalRefundKobo, retainedCancellationBaseKobo: estimate.retainedCancellationBaseKobo, retainedCommissionKobo: estimate.retainedCommissionKobo, currency: "NGN" }); let inventoryReleaseStatus: Case["inventoryReleaseStatus"] = "released"; try { if (!reservation.inventoryCommitmentId) throw new Error("Reservation commitment is missing"); this.#o.availability.releaseConfirmedBooking({ commitmentId: reservation.inventoryCommitmentId, unitId: reservation.unitId, start: reservation.dates.checkIn, end: reservation.dates.checkOut }); } catch { inventoryReleaseStatus = "reconciliation_required"; } const payment = contract.paymentDetails; const source = payment.paymentMethod === "fresh_card" ? payment.pspReference : payment.transferReference; const refund = this.#o.refunds.initiateOrGetRefund({ cancellationId, reservationId, paymentMethod: payment.paymentMethod, originalPaymentReference: source, amountKobo: estimate.totalRefundKobo, currency: "NGN" }); if (refund.amountKobo !== estimate.totalRefundKobo || refund.currency !== "NGN") throw new Error("Refund provider result does not match the authoritative obligation"); const refundStatus = refund.status; this.#cases.set(reservationId, { cancellationId, caseVersion: 1, outcome, refundStatus, inventoryReleaseStatus, ledgerStatus: ledger.status }); this.#o.audit?.record({ type: outcome === "no_show" ? "no_show.confirmed" : "cancellation.committed", reservationId, cancellationId, contractVersion: contract.contractVersion, policyVersion: policy.version, economicsVersion: economics.version, liability, refundStatus, inventoryReleaseStatus, ledgerRecordId: ledger.ledgerRecordId, recordedAt: (this.#o.clock?.() ?? new Date()).toISOString() }); return this.getArtifact(reservationId, { id: contract.parties.primaryGuest.id, role: "guest", tenantId: contract.tenantId }); }
}
