import { createPlatformCommandEnvelope, type CommandPrincipal, type PlatformCommandEnvelope } from "../../../packages/platform-core/src/index.js";
import { CancellationNoShowManager, type CancellationArrivalStateProvider, type CancellationEconomicsProvider, type CancellationLiability, type CancellationLiabilityAuthority, type ContractualCheckInWindowProvider, type NoShowContactAttemptProvider, validateCancellationPolicy } from "../../../domains/shortlet/src/cancellation-noshow.js";
import type { BookingContract, Reservation } from "../../../domains/shortlet/src/card-payment.js";
import type { BookingStateRepository } from "../../../domains/shortlet/src/booking-state.js";
import { cancellationArtifactId, cancellationProjectionVersion, type CancellationArtifact } from "./cancellation-artifact.js";
import type { CancellationActionContext } from "./cancellation-actions.js";

interface RefundProvider { initiateOrGetRefund(input: { cancellationId: string; reservationId: string; paymentMethod: "fresh_card" | "bank_transfer"; originalPaymentReference: string; amountKobo: number; currency: "NGN" }): { refundId: string; status: "pending" | "settled" | "failed"; amountKobo: number; currency: "NGN" }; }
export interface SecurityDepositCancellationRefundPort { initiateOrGetRefund(input: { cancellationId: string; reservationId: string; collectionId: string; amountKobo: number; currency: "NGN" }): { refundId: string; status: "pending" | "settled" | "failed"; amountKobo: number; currency: "NGN" }; }
interface LedgerPort { postCancellation(input: { cancellationId: string; reservationId: string; liability: string; amountKobo: number; retainedCancellationBaseKobo: number; retainedCommissionKobo: number; currency: "NGN" }): { ledgerRecordId: string; status: "posted" }; }
interface ReleasePort { releaseConfirmedBooking(input: { commitmentId: string; unitId: string; start: string; end: string }): void; }
export interface CancellationCase { readonly cancellationId: string; readonly reservationId: string; readonly caseVersion: number; readonly outcome: "guest_cancellation" | "reviewed_cancellation" | "no_show"; readonly refundStatus: "not_started" | "pending" | "settled" | "failed"; readonly depositRefundStatus?: "not_applicable" | "pending" | "settled" | "failed" | "reconciliation_required"; readonly depositRefundId?: string; readonly inventoryReleaseStatus: "pending" | "released" | "reconciliation_required"; readonly ledgerStatus: "pending" | "posted" | "reconciliation_required"; readonly ledgerRecordId?: string; readonly refundId?: string; }
export interface CancellationCaseRepository { findByReservationId(reservationId: string): CancellationCase | null; createIfAbsent(value: CancellationCase): CancellationCase; update(reservationId: string, expectedCaseVersion: number, mutation: (current: CancellationCase) => CancellationCase): CancellationCase; }
export class InMemoryCancellationCaseRepository implements CancellationCaseRepository { readonly #cases = new Map<string, CancellationCase>(); findByReservationId(id: string): CancellationCase | null { return this.#cases.get(id) ?? null; } createIfAbsent(value: CancellationCase): CancellationCase { const current = this.#cases.get(value.reservationId); if (current) return current; this.#cases.set(value.reservationId, value); return value; } update(id: string, expected: number, mutation: (current: CancellationCase) => CancellationCase): CancellationCase { const current = this.#cases.get(id); if (!current || current.caseVersion !== expected) throw new Error("STALE_ACTION"); const next = mutation(current); if (next.caseVersion !== expected + 1) throw new Error("Invalid cancellation case version"); this.#cases.set(id, next); return next; } }
export interface CancellationApplicationOptions { readonly state: BookingStateRepository; readonly manager: CancellationNoShowManager; readonly timing: ContractualCheckInWindowProvider; readonly economics: CancellationEconomicsProvider; readonly arrival: CancellationArrivalStateProvider; readonly liability?: CancellationLiabilityAuthority; readonly contacts?: NoShowContactAttemptProvider; readonly refunds: RefundProvider; readonly depositRefunds?: SecurityDepositCancellationRefundPort; readonly ledger: LedgerPort; readonly availability: ReleasePort; readonly cases?: CancellationCaseRepository; readonly audit?: { record(entry: Record<string, unknown>): void }; readonly clock?: () => Date; }
function guestAuthorized(contract: BookingContract, reservation: Reservation, principal: CommandPrincipal): void { if (principal.role !== "guest" || !principal.id || principal.id !== contract.parties.primaryGuest.id || !contract.tenantId || !principal.tenantId || principal.tenantId !== contract.tenantId || reservation.contractId !== contract.contractId) throw new Error("Access denied or resource not found"); }
function staffAuthorized(contract: BookingContract, principal: CommandPrincipal): void { if (principal.role !== "authorized_staff" && principal.role !== "admin") throw new Error("Authorized human staff is required"); if (!contract.tenantId || !principal.tenantId || principal.tenantId !== contract.tenantId) throw new Error("Access denied or resource not found"); }
export class CancellationApplication {
  readonly #o: CancellationApplicationOptions; readonly #cases: CancellationCaseRepository;
  constructor(options: CancellationApplicationOptions) { this.#o = options; this.#cases = options.cases ?? new InMemoryCancellationCaseRepository(); }
  getArtifact(reservationId: string, principal: CommandPrincipal): CancellationArtifact {
    const reservation = this.#o.state.findReservationById(reservationId); const contract = reservation ? this.#o.state.findContractById(reservation.contractId) : null;
    if (!reservation || !contract) throw new Error("Access denied or resource not found");
    const isStaff = principal.role === "authorized_staff" || principal.role === "admin"; if (isStaff) staffAuthorized(contract, principal); else guestAuthorized(contract, reservation, principal);
    const policy = validateCancellationPolicy(contract.policies.cancellationPolicy); const window = this.#o.timing.getWindow(reservationId, contract); const economics = this.#o.economics.getEconomics({ reservationId, contract }); const arrival = this.#o.arrival.getState(reservationId); const contact = this.#o.contacts?.getStatus(reservationId);
    const estimate = this.#o.manager.calculateAuthoritative({ reservationId, contract, economics, policy, checkInWindowStartIso: window.startIso, at: this.#o.clock?.() ?? new Date(), liability: "guest" }); const existing = this.#cases.findByReservationId(reservationId); const id = cancellationArtifactId(reservationId);
    const markers = { reservationStatus: reservation.status, contractVersion: contract.contractVersion, policyVersion: policy.version, economicsVersion: economics.version, estimate: { percentage: estimate.refundPercentage, total: estimate.totalRefundKobo }, arrivalVersion: arrival.version, contactAttemptVersion: contact?.version, caseState: existing };
    const projectionVersion = cancellationProjectionVersion(markers); const actions: Array<CancellationArtifact["actions"][number]> = [];
    const preStay = arrival.status === "awaiting_access";
    if (!isStaff && principal.role === "guest" && reservation.status === "confirmed" && preStay) actions.push({ type: "cancel_booking", artifactId: id, reservationId, expectedReservationStatus: "confirmed", expectedContractVersion: contract.contractVersion, policyVersion: policy.version, economicsVersion: economics.version, arrivalVersion: arrival.version, projectionVersion });
    let noShow: CancellationArtifact["facts"]["noShow"];
    if (contact) { let eligible = false; try { this.#o.manager.assertNoShowEligible({ reservation, checkInDate: contract.dates.checkIn, now: this.#o.clock?.() ?? new Date(), arrival, contact }); eligible = true; } catch { /* projection remains safe and non-actionable */ } noShow = { deadline: this.#o.manager.noShowDeadline(contract.dates.checkIn), eligible }; if (isStaff && eligible) actions.push({ type: "confirm_no_show", artifactId: id, reservationId, expectedReservationStatus: "confirmed", expectedContractVersion: contract.contractVersion, policyVersion: policy.version, economicsVersion: economics.version, arrivalVersion: arrival.version, contactAttemptVersion: contact.version, projectionVersion }); }
    return Object.freeze({ id, kind: "shortlet.cancellation", schemaVersion: "shortlet.cancellation/v1", projectionVersion, facts: Object.freeze({ reservationId, contractId: contract.contractId, reservationStatus: reservation.status, contractVersion: contract.contractVersion, policy, contractualCheckInWindowStart: window.startIso, timezone: "Africa/Lagos" as const, economicsVersion: economics.version, arrivalVersion: arrival.version, ...(contact ? { contactAttemptVersion: contact.version } : {}), currentRefundEstimate: estimate, ...(existing ? { case: existing } : {}), ...(noShow ? { noShow } : {}) }), actions: Object.freeze(actions) });
  }
  cancel(reservationId: string, principal: CommandPrincipal, context?: CancellationActionContext): CancellationArtifact { const reservation = this.#o.state.findReservationById(reservationId); if (!reservation) throw new Error("Access denied or resource not found"); const contract = this.#o.state.findContractById(reservation.contractId); if (!contract) throw new Error("Access denied or resource not found"); guestAuthorized(contract, reservation, principal); const current = this.getArtifact(reservationId, principal); const envelope = createPlatformCommandEnvelope({ commandName: "shortlet.cancellation.cancel", principal, payload: { reservationId, ...(context ?? { artifactId: current.id, expectedReservationStatus: "confirmed", expectedContractVersion: current.facts.contractVersion, policyVersion: current.facts.policy.version, economicsVersion: current.facts.economicsVersion, arrivalVersion: current.facts.arrivalVersion, projectionVersion: current.projectionVersion }) } }); return this.commitGuestCancellation(envelope, principal); }
  commitGuestCancellation(envelope: PlatformCommandEnvelope<unknown>, principal: CommandPrincipal): CancellationArtifact { const payload = envelope.payload as unknown as CancellationActionContext & { reservationId: string }; const reservation = this.#o.state.findReservationById(payload.reservationId); if (!reservation) throw new Error("Access denied or resource not found"); const contract = this.#o.state.findContractById(reservation.contractId); if (!contract) throw new Error("Access denied or resource not found"); guestAuthorized(contract, reservation, principal); const current = this.getArtifact(payload.reservationId, principal); if (!current.actions.some((action) => action.type === "cancel_booking") || payload.artifactId !== current.id || payload.expectedReservationStatus !== current.facts.reservationStatus || payload.expectedContractVersion !== current.facts.contractVersion || payload.policyVersion !== current.facts.policy.version || payload.economicsVersion !== current.facts.economicsVersion || payload.arrivalVersion !== current.facts.arrivalVersion || payload.projectionVersion !== current.projectionVersion) throw new Error("STALE_ACTION"); const changed = this.#o.state.transitionReservationStatus(payload.reservationId, "confirmed", "cancelled"); return this.#complete(payload.reservationId, contract, changed, "guest_cancellation", "guest", principal); }
  processReviewedCancellation(reservationId: string, principal: CommandPrincipal, context?: CancellationActionContext): CancellationArtifact { const reservation = this.#o.state.findReservationById(reservationId); if (!reservation) throw new Error("Access denied or resource not found"); const contract = this.#o.state.findContractById(reservation.contractId); if (!contract) throw new Error("Access denied or resource not found"); staffAuthorized(contract, principal); const decision = this.#o.liability?.getDecision({ reservationId }); if (!decision?.valid) throw new Error("Trusted cancellation liability decision is required"); if (context && context.decisionVersion !== decision.decisionVersion) throw new Error("STALE_ACTION"); const existing = this.#cases.findByReservationId(reservationId); if (existing) return this.getArtifact(reservationId, principal); const changed = this.#o.state.transitionReservationStatus(reservationId, "confirmed", "cancelled"); return this.#complete(reservationId, contract, changed, "reviewed_cancellation", decision.liability, principal); }
  confirmNoShow(reservationId: string, principal: CommandPrincipal, context?: CancellationActionContext): CancellationArtifact { const reservation = this.#o.state.findReservationById(reservationId); if (!reservation) throw new Error("Access denied or resource not found"); const contract = this.#o.state.findContractById(reservation.contractId); if (!contract) throw new Error("Access denied or resource not found"); staffAuthorized(contract, principal); const arrival = this.#o.arrival.getState(reservationId); const contact = this.#o.contacts?.getStatus(reservationId); if (!contact || (context && context.contactAttemptVersion !== contact.version)) throw new Error("STALE_ACTION"); this.#o.manager.assertNoShowEligible({ reservation, checkInDate: contract.dates.checkIn, now: this.#o.clock?.() ?? new Date(), arrival, contact }); const existing = this.#cases.findByReservationId(reservationId); if (existing) return this.getArtifact(reservationId, principal); const changed = this.#o.state.transitionReservationStatus(reservationId, "confirmed", "no_show"); return this.#complete(reservationId, contract, changed, "no_show", "guest", principal); }
  #complete(reservationId: string, contract: BookingContract, reservation: Reservation, outcome: CancellationCase["outcome"], liability: CancellationLiability, viewer: CommandPrincipal): CancellationArtifact { const economics = this.#o.economics.getEconomics({ reservationId, contract }); const policy = validateCancellationPolicy(contract.policies.cancellationPolicy); const window = this.#o.timing.getWindow(reservationId, contract); const estimate = this.#o.manager.calculateAuthoritative({ reservationId, contract, economics, policy, checkInWindowStartIso: window.startIso, at: this.#o.clock?.() ?? new Date(), liability: outcome === "no_show" ? "guest" : liability }); const cancellationId = `cancellation:${reservationId}`; let current = this.#cases.createIfAbsent({ cancellationId, reservationId, caseVersion: 1, outcome, refundStatus: "not_started", inventoryReleaseStatus: "pending", ledgerStatus: "pending" });
    try { const ledger = this.#o.ledger.postCancellation({ cancellationId, reservationId, liability, amountKobo: estimate.totalRefundKobo, retainedCancellationBaseKobo: estimate.retainedCancellationBaseKobo, retainedCommissionKobo: estimate.retainedCommissionKobo, currency: "NGN" }); current = this.#cases.update(reservationId, current.caseVersion, (value) => ({ ...value, caseVersion: value.caseVersion + 1, ledgerStatus: ledger.status, ledgerRecordId: ledger.ledgerRecordId })); } catch { current = this.#cases.update(reservationId, current.caseVersion, (value) => ({ ...value, caseVersion: value.caseVersion + 1, ledgerStatus: "reconciliation_required" })); return this.getArtifact(reservationId, viewer); }
    try { if (!reservation.inventoryCommitmentId) throw new Error("Reservation commitment is missing"); this.#o.availability.releaseConfirmedBooking({ commitmentId: reservation.inventoryCommitmentId, unitId: reservation.unitId, start: reservation.dates.checkIn, end: reservation.dates.checkOut }); current = this.#cases.update(reservationId, current.caseVersion, (value) => ({ ...value, caseVersion: value.caseVersion + 1, inventoryReleaseStatus: "released" })); } catch { current = this.#cases.update(reservationId, current.caseVersion, (value) => ({ ...value, caseVersion: value.caseVersion + 1, inventoryReleaseStatus: "reconciliation_required" })); }
    const payment = contract.paymentDetails; const source = payment.paymentMethod === "fresh_card" ? payment.pspReference : payment.transferReference; try { const refund = this.#o.refunds.initiateOrGetRefund({ cancellationId, reservationId, paymentMethod: payment.paymentMethod, originalPaymentReference: source, amountKobo: estimate.totalRefundKobo, currency: "NGN" }); if (refund.amountKobo !== estimate.totalRefundKobo || refund.currency !== "NGN") throw new Error("Refund provider result does not match the authoritative obligation"); current = this.#cases.update(reservationId, current.caseVersion, (value) => ({ ...value, caseVersion: value.caseVersion + 1, refundStatus: refund.status, refundId: refund.refundId })); } catch { current = this.#cases.update(reservationId, current.caseVersion, (value) => ({ ...value, caseVersion: value.caseVersion + 1, refundStatus: "failed" })); }
    if (contract.securityDeposit && contract.securityDeposit.amountKobo > 0) {
      if (!this.#o.depositRefunds) current = this.#cases.update(reservationId, current.caseVersion, (value) => ({ ...value, caseVersion: value.caseVersion + 1, depositRefundStatus: "reconciliation_required" }));
      else { try { const refund = this.#o.depositRefunds.initiateOrGetRefund({ cancellationId, reservationId, collectionId: contract.securityDeposit.collectionId ?? `security-deposit:${contract.offerId}`, amountKobo: contract.securityDeposit.amountKobo, currency: "NGN" }); if (refund.amountKobo !== contract.securityDeposit.amountKobo || refund.currency !== "NGN") throw new Error("Deposit refund obligation mismatch"); current = this.#cases.update(reservationId, current.caseVersion, (value) => ({ ...value, caseVersion: value.caseVersion + 1, depositRefundStatus: refund.status, depositRefundId: refund.refundId })); } catch { current = this.#cases.update(reservationId, current.caseVersion, (value) => ({ ...value, caseVersion: value.caseVersion + 1, depositRefundStatus: "reconciliation_required" })); } }
    } else current = this.#cases.update(reservationId, current.caseVersion, (value) => ({ ...value, caseVersion: value.caseVersion + 1, depositRefundStatus: "not_applicable" }));
    this.#o.audit?.record({ type: outcome === "no_show" ? "no_show.confirmed" : "cancellation.committed", reservationId, cancellationId, contractVersion: contract.contractVersion, policyVersion: policy.version, economicsVersion: economics.version, liability, refundStatus: current.refundStatus, depositRefundStatus: current.depositRefundStatus, inventoryReleaseStatus: current.inventoryReleaseStatus, ledgerStatus: current.ledgerStatus, recordedAt: (this.#o.clock?.() ?? new Date()).toISOString() }); return this.getArtifact(reservationId, viewer); }
}
