import { createHash } from "node:crypto";
import type { CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { CheckoutOverstayApplication, EffectiveCheckoutTerms, CheckoutReservation } from "./checkout-overstay-application.js";
export const CHECKOUT_ARTIFACT_KIND = "shortlet.checkout";
export const CHECKOUT_ARTIFACT_SCHEMA = "shortlet.checkout/v1";
export type CheckoutGuestAction = "accept_late_checkout";
export interface CheckoutArtifact {
  readonly id: string; readonly kind: typeof CHECKOUT_ARTIFACT_KIND; readonly schema: typeof CHECKOUT_ARTIFACT_SCHEMA; readonly projectionVersion: string;
  readonly facts: { readonly reservationId: string; readonly checkoutDate: string; readonly timezone: "Africa/Lagos"; readonly effectiveCheckoutTime: EffectiveCheckoutTerms["checkoutTime"]; readonly effectiveCheckoutIso: string; readonly checkoutSource: EffectiveCheckoutTerms["source"]; readonly termVersion: string; readonly accessExpiryIso: string; readonly turnoverStartIso: string; readonly depositClaimDeadlineIso: string; readonly remindersIso: readonly string[]; readonly lateCheckoutAvailable: boolean; readonly lateCheckoutOptions: readonly { readonly requestedTime: "12:00" | "13:00" | "14:00"; readonly quoteId: string; readonly feeKobo: number; readonly currency: "NGN" }[]; readonly overstayStatus: "none" | "open" | "escalated"; readonly overstayRemedyBasis?: string; readonly humanSupportRequested: boolean; readonly humanOwned: boolean };
  readonly actions: readonly { readonly type: CheckoutGuestAction; readonly artifactId: string; readonly reservationId: string; readonly requestedTime: "12:00" | "13:00" | "14:00"; readonly quoteId: string; readonly expectedCheckoutTime: EffectiveCheckoutTerms["checkoutTime"]; readonly expectedTermVersion: string; readonly projectionVersion: string }[];
  readonly sensitivity: "booking-sensitive";
}
export function checkoutArtifactId(reservationId: string): string { return `checkout:${reservationId}`; }
export function checkoutArtifactFromApplication(application: CheckoutOverstayApplication, reservation: CheckoutReservation, principal: CommandPrincipal, term: EffectiveCheckoutTerms): CheckoutArtifact {
  const schedule = application.manager.calculateCheckoutSchedule({ reservationId: reservation.reservationId, checkoutDate: reservation.checkoutDate, contractualCheckoutTime: term.checkoutTime });
  const options = application.currentOptions(reservation, term);
  const incident = application.currentIncident(reservation.reservationId);
  const markers = [reservation.reservationId, reservation.status, term.termVersion, term.checkoutTime, term.amendmentVersion ?? "", ...options.flatMap((o) => [o.requestedTime, o.quoteId, String(o.feeKobo), o.policyVersion]), incident?.incidentId ?? "", incident?.remedyBasis ?? "", incident?.status ?? "", application.humanStatus(reservation.reservationId)];
  const projectionVersion = createHash("sha256").update(markers.join("|")).digest("hex").slice(0, 16);
  const actions = principal.role === "guest" ? options.map((option) => ({ type: "accept_late_checkout" as const, artifactId: checkoutArtifactId(reservation.reservationId), reservationId: reservation.reservationId, requestedTime: option.requestedTime, quoteId: option.quoteId, expectedCheckoutTime: term.checkoutTime, expectedTermVersion: term.termVersion, projectionVersion })) : [];
  return Object.freeze({ id: checkoutArtifactId(reservation.reservationId), kind: CHECKOUT_ARTIFACT_KIND, schema: CHECKOUT_ARTIFACT_SCHEMA, projectionVersion, facts: Object.freeze({ reservationId: reservation.reservationId, checkoutDate: reservation.checkoutDate, timezone: "Africa/Lagos" as const, effectiveCheckoutTime: term.checkoutTime, effectiveCheckoutIso: schedule.contractualCheckoutIso, checkoutSource: term.source, termVersion: term.termVersion, accessExpiryIso: schedule.accessExpiryIso, turnoverStartIso: schedule.turnoverStartIso, depositClaimDeadlineIso: schedule.depositClaimDeadlineIso, remindersIso: schedule.remindersIso, lateCheckoutAvailable: options.length > 0, lateCheckoutOptions: Object.freeze(options.map(({ policyVersion: _policyVersion, ...safe }) => safe)), overstayStatus: incident?.status === "escalated" ? "escalated" as const : incident ? "open" as const : "none" as const, ...(incident ? { overstayRemedyBasis: incident.remedyBasis } : {}), humanSupportRequested: application.humanStatus(reservation.reservationId) === "handoff-requested", humanOwned: application.humanStatus(reservation.reservationId) === "human-owned" }), actions: Object.freeze(actions), sensitivity: "booking-sensitive" as const });
}
