import { createPlatformCommandEnvelope, type CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import { CheckoutOverstayManager, type CheckoutTime, type LateCheckoutTime, type OverstayIncident, type SafeEvidenceReference } from "../../../domains/shortlet/src/checkout-overstay.js";
import { checkoutArtifactFromApplication, type CheckoutArtifact } from "./checkout-overstay-artifact.js";
export interface CheckoutReservation { readonly reservationId: string; readonly contractId: string; readonly unitId: string; readonly primaryGuestId: string; readonly tenantId: string; readonly status: "confirmed" | "cancelled" | "revoked"; readonly checkoutDate: string; }
export interface CheckoutReservationProvider { getReservation(reservationId: string): CheckoutReservation | null; }
export interface EffectiveCheckoutTerms { readonly reservationId: string; readonly checkoutDate: string; readonly checkoutTime: CheckoutTime; readonly source: "contractual" | "checkout_amendment"; readonly termVersion: string; readonly amendmentId?: string; readonly amendmentVersion?: number | string; }
export interface EffectiveCheckoutTermsProvider { getTerms(reservationId: string): EffectiveCheckoutTerms; }
export interface LateCheckoutQuote { readonly quoteId: string; readonly feeKobo: number; readonly currency: "NGN"; readonly policyVersion: string; }
export interface LateCheckoutQuoteProvider { getQuote(input: { reservationId: string; requestedTime: LateCheckoutTime }): LateCheckoutQuote; }
export interface CheckoutEligibilityProvider { hasSameDayArrival(reservationId: string, checkoutDate: string): boolean; hasMaintenanceOrInspection(reservationId: string, checkoutDate: string): boolean; hasTurnoverCapacity(reservationId: string, checkoutDate: string): boolean; hasSupportAvailability(reservationId: string, checkoutDate: string): boolean; operatorApproved(reservationId: string, requestedTime: LateCheckoutTime): boolean; }
export interface CheckoutAmendmentPort { acceptLateCheckout(input: { reservationId: string; requestedTime: LateCheckoutTime; quoteId: string; expectedEffectiveTermVersion: string; principal: CommandPrincipal; command: ReturnType<typeof createPlatformCommandEnvelope> }): { amendmentId: string; amendmentVersion: number | string; effectiveCheckoutTime: LateCheckoutTime; quoteId: string; feeKobo: number; currency: "NGN" }; }
export interface OverstayEvidenceProvider { getOccupancyEvidence(input: { reservationId: string; effectiveCheckoutIso: string }): { occupancyContinues: boolean; references: readonly SafeEvidenceReference[] }; }
export interface OverstaySafetyAssessmentProvider { getAssessment(incidentId: string): { requiresHumanSafetyEscalation: boolean; assessmentVersion: string }; }
export interface CheckoutOverstayHumanHandoffPort { requestMandatoryHandoff(input: { reservationId: string; actor: CommandPrincipal }): void; getStatus?(reservationId: string): "automated" | "handoff-requested" | "human-owned"; }
export interface CheckoutOverstayApplicationOptions { readonly manager: CheckoutOverstayManager; readonly reservations: CheckoutReservationProvider; readonly terms: EffectiveCheckoutTermsProvider; readonly quotes: LateCheckoutQuoteProvider; readonly eligibility: CheckoutEligibilityProvider; readonly amendments: CheckoutAmendmentPort; readonly evidence: OverstayEvidenceProvider; readonly safety?: OverstaySafetyAssessmentProvider; readonly handoff?: CheckoutOverstayHumanHandoffPort; readonly audit?: { record(entry: Record<string, string | number>): void }; readonly clock?: () => Date; }
function assertGuest(reservation: CheckoutReservation | null, principal: CommandPrincipal): asserts reservation is CheckoutReservation { if (!reservation || reservation.status !== "confirmed" || principal.role !== "guest" || !principal.id || principal.id !== reservation.primaryGuestId || !principal.tenantId || principal.tenantId !== reservation.tenantId) throw new Error("Checkout action is not authorized"); }
function validQuote(quote: LateCheckoutQuote): void { if (!quote.quoteId || !quote.policyVersion || quote.currency !== "NGN" || !Number.isInteger(quote.feeKobo) || quote.feeKobo < 0) throw new Error("Authoritative late checkout quote is malformed"); }
export class CheckoutOverstayApplication {
  readonly manager: CheckoutOverstayManager; readonly #o: CheckoutOverstayApplicationOptions; readonly #clock: () => Date; readonly #incidents = new Map<string, OverstayIncident>(); readonly #accepted = new Map<string, { requestedTime: LateCheckoutTime; quoteId: string }>();
  constructor(options: CheckoutOverstayApplicationOptions) { this.#o = options; this.manager = options.manager; this.#clock = options.clock ?? (() => new Date()); }
  #reservation(id: string, principal: CommandPrincipal): CheckoutReservation { const reservation = this.#o.reservations.getReservation(id); assertGuest(reservation, principal); return reservation; }
  currentOptions(reservation: CheckoutReservation, term: EffectiveCheckoutTerms): readonly (LateCheckoutQuote & { requestedTime: LateCheckoutTime })[] { if (reservation.status !== "confirmed") return []; return (["12:00", "13:00", "14:00"] as const).filter((time) => time > term.checkoutTime).flatMap((requestedTime) => { const eligibility = this.#o.eligibility; if (eligibility.hasSameDayArrival(reservation.reservationId, reservation.checkoutDate) || eligibility.hasMaintenanceOrInspection(reservation.reservationId, reservation.checkoutDate) || !eligibility.hasTurnoverCapacity(reservation.reservationId, reservation.checkoutDate) || !eligibility.hasSupportAvailability(reservation.reservationId, reservation.checkoutDate) || !eligibility.operatorApproved(reservation.reservationId, requestedTime)) return []; const result = this.#o.manager.evaluateLateCheckoutEligibility({ reservationId: reservation.reservationId, requestedTime, checkoutDate: reservation.checkoutDate, currentCheckoutTime: term.checkoutTime }); if (!result.eligible) return []; const quote = this.#o.quotes.getQuote({ reservationId: reservation.reservationId, requestedTime }); try { validQuote(quote); } catch { return []; } return [{ ...quote, requestedTime }]; }); }
  getArtifact(reservationId: string, principal: CommandPrincipal): CheckoutArtifact { const reservation = this.#reservation(reservationId, principal); const term = this.#o.terms.getTerms(reservationId); if (term.reservationId !== reservationId || term.checkoutDate !== reservation.checkoutDate) throw new Error("Authoritative checkout term does not match reservation"); return checkoutArtifactFromApplication(this, reservation, principal, term); }
  acceptLateCheckout(reservationId: string, requestedTime: LateCheckoutTime, principal: CommandPrincipal, expected?: { quoteId?: string; expectedTermVersion?: string; termVersion?: string; projectionVersion?: string }): CheckoutArtifact {
    const reservation = this.#reservation(reservationId, principal); const term = this.#o.terms.getTerms(reservationId); const current = this.getArtifact(reservationId, principal); if (expected && (expected.projectionVersion !== current.projectionVersion || (expected.expectedTermVersion ?? expected.termVersion) !== term.termVersion)) throw new Error("STALE_ACTION");
    const replay = this.#accepted.get(reservationId); if (replay?.requestedTime === requestedTime && (!expected?.quoteId || replay.quoteId === expected.quoteId)) return current;
    const option = current.actions.find((action) => action.requestedTime === requestedTime && (!expected?.quoteId || action.quoteId === expected.quoteId)); if (!option) throw new Error("CURRENT_ACTION_NOT_AUTHORIZED");
    const quote = this.#o.quotes.getQuote({ reservationId, requestedTime }); validQuote(quote); if (quote.quoteId !== option.quoteId) throw new Error("STALE_ACTION");
    const command = createPlatformCommandEnvelope({ commandName: "shortlet.checkout.accept-late-checkout", principal, payload: { reservationId, requestedTime, quoteId: quote.quoteId }, expectedVersion: term.termVersion });
    const committed = this.#o.amendments.acceptLateCheckout({ reservationId, requestedTime, quoteId: quote.quoteId, expectedEffectiveTermVersion: term.termVersion, principal, command });
    if (committed.quoteId !== quote.quoteId || committed.effectiveCheckoutTime !== requestedTime || committed.feeKobo !== quote.feeKobo || committed.currency !== quote.currency) throw new Error("Checkout Amendment response is inconsistent");
    const after = this.#o.terms.getTerms(reservationId); if (after.checkoutTime !== requestedTime || after.source !== "checkout_amendment") throw new Error("Authoritative effective checkout term did not update");
    this.#accepted.set(reservationId, { requestedTime, quoteId: quote.quoteId }); const recordedAt = this.#clock().toISOString(); this.#o.audit?.record({ type: "late_checkout.accepted", reservationId, requestedTime, quoteId: quote.quoteId, actorId: principal.id, recordedAt }); this.#o.audit?.record({ type: "checkout.effective_term_changed", reservationId, termVersion: after.termVersion, effectiveCheckoutTime: after.checkoutTime, amendmentId: after.amendmentId ?? "", recordedAt }); return this.getArtifact(reservationId, principal);
  }
  enforceOverstay(reservationId: string, actor: CommandPrincipal): OverstayIncident | undefined { if (!["system", "authorized_staff", "admin"].includes(actor.role)) throw new Error("Trusted detector actor required"); const reservation = this.#o.reservations.getReservation(reservationId); if (!reservation || reservation.status !== "confirmed") return undefined; const term = this.#o.terms.getTerms(reservationId); const schedule = this.manager.calculateCheckoutSchedule({ reservationId, checkoutDate: reservation.checkoutDate, contractualCheckoutTime: term.checkoutTime }); if (this.#clock().getTime() <= new Date(schedule.contractualCheckoutIso).getTime()) return undefined; const evidence = this.#o.evidence.getOccupancyEvidence({ reservationId, effectiveCheckoutIso: schedule.contractualCheckoutIso }); if (!evidence.occupancyContinues) return undefined; const incident = this.manager.openOverstayIncident({ reservationId, checkoutDate: reservation.checkoutDate, contractualCheckoutTime: term.checkoutTime, currentIso: this.#clock().toISOString(), evidenceReferences: evidence.references }); this.#incidents.set(reservationId, incident); this.#o.audit?.record({ type: "overstay.detected", reservationId, incidentId: incident.incidentId, actorId: actor.id, recordedAt: this.#clock().toISOString() }); return incident; }
  escalateOverstaySafety(reservationId: string, actor: CommandPrincipal): OverstayIncident { if (!["system", "authorized_staff", "admin"].includes(actor.role) || !this.#o.safety) throw new Error("Trusted safety assessment required"); const incident = this.#incidents.get(reservationId); if (!incident) throw new Error("Incident not found"); const assessment = this.#o.safety.getAssessment(incident.incidentId); const updated = this.manager.escalateOverstaySafetyIncident(incident.incidentId, assessment); if (assessment.requiresHumanSafetyEscalation) { this.#o.handoff?.requestMandatoryHandoff({ reservationId, actor }); this.#o.audit?.record({ type: "overstay.safety_escalated", reservationId, incidentId: incident.incidentId, actorId: actor.id, recordedAt: this.#clock().toISOString() }); } this.#incidents.set(reservationId, updated); return updated; }
  currentIncident(reservationId: string): OverstayIncident | undefined { return this.#incidents.get(reservationId); }
  humanStatus(reservationId: string): "automated" | "handoff-requested" | "human-owned" { return this.#o.handoff?.getStatus?.(reservationId) ?? "automated"; }
}
