import type { WebServerEventHandoff } from "@weaver/web";
import type { CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { CheckoutOverstayApplication } from "./checkout-overstay-application.js";
import type { CheckoutArtifact } from "./checkout-overstay-artifact.js";
export const CHECKOUT_ACCEPT_LATE_CHECKOUT_EVENT = "shortlet.checkout.accept-late-checkout";
type Context = { readonly artifactId: string; readonly reservationId: string; readonly requestedTime: "12:00" | "13:00" | "14:00"; readonly quoteId: string; readonly expectedCheckoutTime: string; readonly expectedTermVersion: string; readonly projectionVersion: string };
export type CheckoutActionResult = { readonly ok: true; readonly artifact: CheckoutArtifact } | { readonly ok: false; readonly code: "UNSUPPORTED_ACTION" | "INVALID_CONTEXT" | "STALE_ACTION" | "ACTION_NOT_AUTHORIZED"; readonly message: string };
function contextOf(event: WebServerEventHandoff): Context | undefined { const value: unknown = event?.message?.action?.context; if (!value || typeof value !== "object" || Array.isArray(value)) return undefined; const record = value as Record<string, unknown>; const allowed = ["artifactId", "reservationId", "requestedTime", "quoteId", "expectedCheckoutTime", "expectedTermVersion", "projectionVersion"]; const required = allowed; if (Object.keys(record).some((key) => !allowed.includes(key)) || required.some((key) => typeof record[key] !== "string")) return undefined; if (!/^(12|13|14):00$/.test(record.requestedTime as string)) return undefined; return record as Context; }
export function resolveCheckoutServerEvent(input: { readonly event: WebServerEventHandoff; readonly application: CheckoutOverstayApplication; readonly principal: CommandPrincipal }): CheckoutActionResult { if (input.event?.message?.action?.name !== CHECKOUT_ACCEPT_LATE_CHECKOUT_EVENT) return { ok: false, code: "UNSUPPORTED_ACTION", message: "The action is not supported." }; const context = contextOf(input.event); if (!context) return { ok: false, code: "INVALID_CONTEXT", message: "The action context is invalid." }; try { const current = input.application.getArtifact(context.reservationId, input.principal); const action = current.actions.find((candidate) => candidate.requestedTime === context.requestedTime); if (context.artifactId !== current.id || context.reservationId !== current.facts.reservationId || context.projectionVersion !== current.projectionVersion || context.expectedCheckoutTime !== current.facts.effectiveCheckoutTime || context.expectedTermVersion !== current.facts.termVersion || !action || action.quoteId !== context.quoteId) return { ok: false, code: "STALE_ACTION", message: "The checkout action is stale; refresh the current checkout." }; return { ok: true, artifact: input.application.acceptLateCheckout(context.reservationId, context.requestedTime, input.principal, context) }; } catch { return { ok: false, code: "ACTION_NOT_AUTHORIZED", message: "The checkout action was rejected." }; } }
