import { createPlatformCommandEnvelope, type CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { BookingStateRepository } from "../../../domains/shortlet/src/booking-state.js";
import type { BookingContract, Reservation } from "../../../domains/shortlet/src/card-payment.js";
import type { SecurityDepositAccountingRepository } from "../../../domains/shortlet/src/security-deposit-accounting.js";
import type { DepositClaimAssertionItem, DepositClaimEvidenceAuthority, DepositClaimProductionItem, DepositClaimProductionRecord, DepositClaimRepository } from "../../../domains/shortlet/src/deposit-claim.js";
import type { EffectiveCheckoutTermsProvider } from "./checkout-overstay-application.js";

export interface DepositClaimPolicyResult { readonly policyVersion: string; readonly reservationId: string; readonly itemId: string; readonly evidenceVersion: string; readonly permittedCategory: boolean; readonly covered: boolean; readonly specific: boolean; readonly quantified: boolean; readonly excluded: boolean; readonly exclusionReason?: "ordinary_wear" | "routine_cleaning" | "turnover" | "utilities" | "maintenance" | "deterioration" | "pre_existing" | "undisclosed_penalty" | "vague_inconvenience" | "future_revenue"; }
export interface DepositClaimPolicyProvider { validate(input: { reservationId: string; item: DepositClaimAssertionItem; evidence: DepositClaimEvidenceAuthority; depositPolicyVersion: string }): DepositClaimPolicyResult; }
export interface DepositClaimEvidenceProvider { resolve(input: { reservationId: string; item: DepositClaimAssertionItem }): DepositClaimEvidenceAuthority; }
export interface DepositClaimNotificationProvider { resolve(input: { claimId: string; guestId: string; tenantId: string }): { claimId: string; guestId: string; tenantId: string; notificationVersion: string; status: "queued" | "sent" | "accepted_by_api" | "delivered" | "failed"; deliveredAtIso?: string; deliveryEvidenceId?: string }; }
export interface DepositClaimRefundProvider { refundOrGet(input: { obligationId: string; offerId: string; paymentMethod: "fresh_card" | "bank_transfer"; originalPaymentReference: string; amountKobo: number; currency: "NGN" }): { refundId: string; status: "pending" | "settled" | "failed" | "reconciliation_required"; amountKobo: number; currency: string }; }
export interface DepositClaimHumanDecisionProvider { get(input: { claimId: string }): { decisionId: string; decisionVersion: string; claimId: string; claimVersion: number; policyVersion: string; evidenceVersion: string; reviewerId: string; reviewerAuthorityVersion: string; evaluations: readonly { itemId: string; approvedAmountKobo: number; explanation: string }[]; valid: boolean }; }
export interface DepositClaimHandoff { request(input: { reservationId: string; reason: "dispute" | "silence" | "notification_failure" | "refund_reconciliation" }): void; }
export interface DepositClaimApplicationOptions { readonly booking: BookingStateRepository; readonly accounting: SecurityDepositAccountingRepository; readonly terms: EffectiveCheckoutTermsProvider; readonly claims: DepositClaimRepository; readonly evidence: DepositClaimEvidenceProvider; readonly policy: DepositClaimPolicyProvider; readonly notifications: DepositClaimNotificationProvider; readonly refunds: DepositClaimRefundProvider; readonly decisions: DepositClaimHumanDecisionProvider; readonly handoff?: DepositClaimHandoff; readonly clock?: () => Date; readonly audit?: { record(entry: Record<string, string | number>): void }; }

const HOUR = 3_600_000;
function checkoutIso(reservation: Reservation, term: ReturnType<EffectiveCheckoutTermsProvider["getTerms"]>): string { const [h, m] = term.checkoutTime.split(":").map(Number); return new Date(Date.UTC(Number(reservation.dates.checkOut.slice(0, 4)), Number(reservation.dates.checkOut.slice(5, 7)) - 1, Number(reservation.dates.checkOut.slice(8, 10)), h - 1, m)).toISOString(); }
function operatorAllowed(contract: BookingContract, principal: CommandPrincipal): void { if (principal.role !== "operator" || !principal.id || principal.id !== contract.parties.operator.id || !principal.tenantId || principal.tenantId !== contract.tenantId) throw new Error("ACTION_NOT_AUTHORIZED"); }
function guestAllowed(contract: BookingContract, reservation: Reservation, principal: CommandPrincipal): void { if (principal.role !== "guest" || !principal.id || principal.id !== reservation.primaryGuestId || principal.id !== contract.parties.primaryGuest.id || !principal.tenantId || principal.tenantId !== contract.tenantId) throw new Error("ACTION_NOT_AUTHORIZED"); }
function safeItem(item: DepositClaimAssertionItem): void { if (Object.keys(item as object).some((key) => !["itemId", "description", "claimedAmountKobo", "evidenceReferenceIds"].includes(key))) throw new Error("Claim item contains unknown fields"); if (!item.itemId || !item.description.trim() || !Number.isInteger(item.claimedAmountKobo) || item.claimedAmountKobo <= 0 || item.claimedAmountKobo !== Math.trunc(item.claimedAmountKobo) || !Array.isArray(item.evidenceReferenceIds) || item.evidenceReferenceIds.length === 0) throw new Error("Claim item is invalid"); }

export class DepositClaimApplication {
  readonly #o: DepositClaimApplicationOptions; readonly #clock: () => Date;
  constructor(options: DepositClaimApplicationOptions) { this.#o = options; this.#clock = options.clock ?? (() => new Date()); }
  #booking(reservationId: string): { reservation: Reservation; contract: BookingContract } { const reservation = this.#o.booking.findReservationById(reservationId); const contract = reservation ? this.#o.booking.findContractById(reservation.contractId) : null; if (!reservation || !contract || contract.reservationId !== reservationId) throw new Error("Booking not found"); return { reservation, contract }; }
  submitClaim(reservationId: string, principal: CommandPrincipal, items: readonly DepositClaimAssertionItem[], expected?: { readonly contractVersion?: number; readonly termVersion?: string }): DepositClaimProductionRecord {
    const { reservation, contract } = this.#booking(reservationId); operatorAllowed(contract, principal); if (expected?.contractVersion !== undefined && expected.contractVersion !== contract.contractVersion) throw new Error("STALE_ACTION"); const term = this.#o.terms.getTerms(reservationId); if (expected?.termVersion !== undefined && expected.termVersion !== term.termVersion) throw new Error("STALE_ACTION"); const checkout = checkoutIso(reservation, term); const now = this.#clock().getTime(); const deadline = new Date(checkout).getTime() + 24 * HOUR; if (now < new Date(checkout).getTime() || now > deadline) throw new Error("CLAIM_WINDOW_CLOSED");
    const held = this.#o.accounting.getByReservationId(reservationId); if (!held || held.status !== "held" || held.currency !== "NGN" || held.amountKobo <= 0 || contract.securityDeposit?.collectionId !== held.collectionId || contract.securityDeposit.amountKobo !== held.amountKobo || contract.securityDeposit.policyVersion !== held.policyVersion) throw new Error("Held security deposit invariant failed");
    if (!Array.isArray(items) || items.length === 0) throw new Error("Claim requires itemized entries"); const ids = new Set<string>(); let total = 0; const resolved: DepositClaimProductionItem[] = items.map((item) => { safeItem(item); if (ids.has(item.itemId)) throw new Error("Duplicate claim item"); ids.add(item.itemId); total += item.claimedAmountKobo; const evidence = this.#o.evidence.resolve({ reservationId, item }); if (evidence.reservationId !== reservationId || evidence.itemId !== item.itemId || evidence.validation !== "approved" || evidence.references.length === 0 || evidence.occurrenceDuringReservation !== "supported" || evidence.causation !== "supported") throw new Error("Claim evidence is insufficient"); const policy = this.#o.policy.validate({ reservationId, item, evidence, depositPolicyVersion: held.policyVersion }); if (policy && (policy.reservationId !== reservationId || policy.itemId !== item.itemId || policy.evidenceVersion !== evidence.evidenceVersion || policy.policyVersion !== held.policyVersion || !policy.permittedCategory || !policy.covered || !policy.specific || !policy.quantified || policy.excluded)) throw new Error("Claim policy validation failed"); if (evidence.references.some((r) => r.classification === "other" && /month|old|historical/i.test(r.safeDescription))) throw new Error("Historical inspection is insufficient alone"); return { ...item, evidence }; }); if (total <= 0 || total > held.refundableBalanceKobo || resolved.some((item) => item.claimedAmountKobo > held.amountKobo)) throw new Error("Claim exceeds held deposit");
    const claimId = `deposit-claim:${reservationId}`; const existing = this.#o.claims.findByReservationId(reservationId); if (existing) { const same = existing.claimedAmountKobo === total && JSON.stringify(existing.items.map((i) => ({ itemId: i.itemId, description: i.description, claimedAmountKobo: i.claimedAmountKobo, evidenceReferenceIds: i.evidenceReferenceIds }))) === JSON.stringify(resolved.map((i) => ({ itemId: i.itemId, description: i.description, claimedAmountKobo: i.claimedAmountKobo, evidenceReferenceIds: i.evidenceReferenceIds }))); if (!same) throw new Error("Conflicting second claim"); if (existing.status === "allocation_pending" && !this.#o.accounting.allocation(claimId)) { this.#o.accounting.allocateClaim({ reservationId, claimId, amountKobo: total, expectedCollectionVersion: held.collectionVersion }); return this.#o.claims.update(claimId, existing.claimVersion, (c) => ({ ...c, status: "validated_notification_pending", claimVersion: c.claimVersion + 1 })); } this.#refund(reservationId, contract, claimId + ":surplus", held.amountKobo - total, claimId); return existing; }
    const command = createPlatformCommandEnvelope({ commandName: "shortlet.deposit-claim.submit", principal, payload: { reservationId, itemCount: resolved.length } }); const record: DepositClaimProductionRecord = { claimId, reservationId, contractId: contract.contractId, tenantId: contract.tenantId ?? "", operatorId: contract.parties.operator.id, guestId: reservation.primaryGuestId, policyVersion: held.policyVersion, evidenceVersion: resolved.map((item) => item.evidence.evidenceVersion).join("|") || "none", depositAmountKobo: held.amountKobo, claimedAmountKobo: total, effectiveCheckoutIso: checkout, claimDeadlineIso: new Date(deadline).toISOString(), submittedAtIso: this.#clock().toISOString(), claimVersion: 1, status: "validated_notification_pending", items: resolved, notification: { status: "pending", notificationVersion: "0", deliveredAtIso: null, evidenceId: null }, responseWindowStartIso: null, responseWindowEndIso: null, guestResponse: null, initialReservedOperatorAwardKobo: total, approvedOperatorAwardKobo: null, unapprovedRefundKobo: 0, history: [{ action: "claim_submitted", at: this.#clock().toISOString(), commandId: command.commandId }] };
    const created = this.#o.claims.createIfAbsent({ ...record, status: "allocation_pending" }); this.#o.accounting.allocateClaim({ reservationId, claimId, amountKobo: total, expectedCollectionVersion: held.collectionVersion }); const allocated = this.#o.claims.update(claimId, created.claimVersion, (c) => ({ ...c, status: "validated_notification_pending", claimVersion: c.claimVersion + 1 })); this.#audit("claim_validated", created, principal); this.#refund(reservationId, contract, claimId + ":surplus", held.amountKobo - total, claimId); return allocated;
  }
  reconcileClaimWindow(reservationId: string, actor: CommandPrincipal): { readonly status: string; readonly amountKobo: number } {
    if (!(actor.role === "system" || actor.role === "authorized_staff" || actor.role === "admin") || !actor.id) throw new Error("Trusted reconciliation actor required"); const command = createPlatformCommandEnvelope({ commandName: "shortlet.deposit-claim.reconcile-window", principal: actor, payload: { reservationId } });
    void command; const { reservation, contract } = this.#booking(reservationId); const existing = this.#o.claims.findByReservationId(reservationId); if (existing && existing.status !== "no_claim_refund_pending") return { status: existing.status, amountKobo: existing.depositAmountKobo };
    const term = this.#o.terms.getTerms(reservationId); if (this.#clock().getTime() <= new Date(checkoutIso(reservation, term)).getTime() + 24 * HOUR) throw new Error("Claim window is still open");
    const collection = this.#o.accounting.getByReservationId(reservationId); if (!collection || (collection.status !== "held" && collection.status !== "refund_pending")) throw new Error("No refundable held deposit");
    const source = this.#o.accounting.getByCollectionId(collection.collectionId); if (!source?.providerReference) throw new Error("Successful deposit payment source is missing"); const obligationId = `deposit-claim:${reservationId}:no-claim`; const obligation = this.#o.accounting.ensureRefundObligation({ obligationId, reservationId, claimId: null, amountKobo: collection.amountKobo });
    let status: "pending" | "settled" | "reconciliation_required"; try { const result = this.#o.refunds.refundOrGet({ obligationId, offerId: source.offerId, paymentMethod: source.paymentMethod, originalPaymentReference: source.providerReference, amountKobo: obligation.amountKobo, currency: "NGN" }); if (!result.refundId || result.amountKobo !== obligation.amountKobo || result.currency !== "NGN") throw new Error("Refund mismatch"); status = result.status === "settled" ? "settled" : result.status === "pending" ? "pending" : "reconciliation_required"; } catch { status = "reconciliation_required"; }
    this.#o.accounting.markRefundResult({ obligationId, status, settledAt: this.#clock().toISOString() }); const caseStatus = status === "pending" ? "no_claim_refund_pending" : status === "settled" ? "no_claim_refunded" : "reconciliation_required"; if (existing) this.#o.claims.update(existing.claimId, existing.claimVersion, (c) => ({ ...c, status: caseStatus, claimVersion: c.claimVersion + 1 })); else this.#o.claims.createIfAbsent(this.#noClaimRecord(reservation, contract, collection.amountKobo, caseStatus)); return { status, amountKobo: collection.amountKobo };
  }
  notify(claimId: string): DepositClaimProductionRecord { const claim = this.#required(claimId); const result = this.#o.notifications.resolve({ claimId, guestId: claim.guestId, tenantId: claim.tenantId }); if (result.claimId !== claim.claimId || result.guestId !== claim.guestId || result.tenantId !== claim.tenantId) throw new Error("Notification identity mismatch"); if (result.status !== "delivered" || !result.deliveredAtIso || !result.deliveryEvidenceId) { if (result.status === "failed") this.#o.handoff?.request({ reservationId: claim.reservationId, reason: "notification_failure" }); return this.#o.claims.update(claimId, claim.claimVersion, (c) => ({ ...c, claimVersion: c.claimVersion + 1, notification: { status: result.status === "failed" ? "failed" : "pending", notificationVersion: result.notificationVersion, deliveredAtIso: null, evidenceId: null }, history: [...c.history, { action: result.status === "failed" ? "notification_failed" : "notification_pending", at: this.#clock().toISOString() }] })); } const existingStart = claim.responseWindowStartIso; if (existingStart) return claim; const start = new Date(result.deliveredAtIso).toISOString(); return this.#o.claims.update(claimId, claim.claimVersion, (c) => ({ ...c, claimVersion: c.claimVersion + 1, status: "response_open", notification: { status: "delivered", notificationVersion: result.notificationVersion, deliveredAtIso: start, evidenceId: result.deliveryEvidenceId ?? null }, responseWindowStartIso: start, responseWindowEndIso: new Date(new Date(start).getTime() + 48 * HOUR).toISOString(), history: [...c.history, { action: "successful_notification", at: start }] })); }
  respond(claimId: string, principal: CommandPrincipal, type: "accept" | "dispute", statement?: string): DepositClaimProductionRecord { const command = createPlatformCommandEnvelope({ commandName: `shortlet.deposit-claim.${type}`, principal, payload: { claimId, type } }); const claim = this.#required(claimId); const { reservation, contract } = this.#booking(claim.reservationId); guestAllowed(contract, reservation, principal); if (!claim.responseWindowStartIso || !claim.responseWindowEndIso || this.#clock().getTime() > new Date(claim.responseWindowEndIso).getTime() || claim.notification.status !== "delivered") throw new Error("STALE_ACTION"); if (claim.guestResponse) { if (claim.guestResponse.type !== type) throw new Error("STALE_ACTION"); return claim; } const next = this.#o.claims.update(claimId, claim.claimVersion, (c) => ({ ...c, claimVersion: c.claimVersion + 1, status: type === "accept" ? "guest_accepted" : "human_review", guestResponse: { type, ...(statement ? { statement } : {}), respondedAtIso: this.#clock().toISOString() }, history: [...c.history, { action: `guest_${type}`, at: this.#clock().toISOString(), commandId: command.commandId }] })); if (type === "dispute") this.#o.handoff?.request({ reservationId: claim.reservationId, reason: "dispute" }); return next; }
  advanceResponseWindow(claimId: string, actor: CommandPrincipal): DepositClaimProductionRecord { if (!(actor.role === "system" || actor.role === "authorized_staff" || actor.role === "admin") || !actor.id) throw new Error("Trusted deadline actor required"); const command = createPlatformCommandEnvelope({ commandName: "shortlet.deposit-claim.advance-response-window", principal: actor, payload: { claimId } }); const claim = this.#required(claimId); if (!claim.responseWindowEndIso || this.#clock().getTime() <= new Date(claim.responseWindowEndIso).getTime() || claim.guestResponse) return claim; this.#o.handoff?.request({ reservationId: claim.reservationId, reason: "silence" }); return this.#o.claims.update(claimId, claim.claimVersion, (c) => ({ ...c, claimVersion: c.claimVersion + 1, status: "human_review", history: [...c.history, { action: "response_window_expired", at: this.#clock().toISOString(), commandId: command.commandId }] })); }
  applyReviewedDecision(claimId: string, principal: CommandPrincipal): DepositClaimProductionRecord { const command = createPlatformCommandEnvelope({ commandName: "shortlet.deposit-claim.apply-reviewed-decision", principal, payload: { claimId } }); if (!(principal.role === "authorized_staff" || principal.role === "admin") || !principal.id) throw new Error("ACTION_NOT_AUTHORIZED"); const claim = this.#required(claimId); const booking = this.#booking(claim.reservationId); if (!principal.tenantId || principal.tenantId !== booking.contract.tenantId) throw new Error("ACTION_NOT_AUTHORIZED"); if (claim.status !== "human_review") throw new Error("Human review required"); const decision = this.#o.decisions.get({ claimId }); if (!decision.valid || decision.claimVersion !== claim.claimVersion || decision.claimId !== claimId || decision.policyVersion !== claim.policyVersion || decision.evidenceVersion !== claim.evidenceVersion || !decision.reviewerAuthorityVersion || decision.reviewerId === "system" || decision.reviewerId === "agent") throw new Error("STALE_ACTION"); const expected = new Set(claim.items.map((i) => i.itemId)); const seen = new Set<string>(); let approved = 0; for (let evaluation of decision.evaluations) { if (!expected.has(evaluation.itemId) || seen.has(evaluation.itemId) || !Number.isInteger(evaluation.approvedAmountKobo) || evaluation.approvedAmountKobo < 0) throw new Error("Invalid item decision"); seen.add(evaluation.itemId); const item = claim.items.find((i) => i.itemId === evaluation.itemId); if (!item || evaluation.approvedAmountKobo > item.claimedAmountKobo) throw new Error("Invalid item decision"); const evidence = item.evidence; if (evidence.validation !== "approved" || evidence.occurrenceDuringReservation !== "supported" || evidence.causation !== "supported") evaluation = { ...evaluation, approvedAmountKobo: 0 }; approved += evaluation.approvedAmountKobo; } if (seen.size !== expected.size || approved > claim.claimedAmountKobo) throw new Error("Missing item decision"); const refund = claim.claimedAmountKobo - approved; const next = this.#o.claims.update(claimId, claim.claimVersion, (c) => ({ ...c, claimVersion: c.claimVersion + 1, status: "adjudicated", approvedOperatorAwardKobo: approved, unapprovedRefundKobo: refund, history: [...c.history, { action: "reviewed_decision_applied", at: this.#clock().toISOString(), commandId: command.commandId }] })); const { contract } = this.#booking(claim.reservationId); if (refund > 0) this.#refund(claim.reservationId, contract, `${claimId}:unapproved`, refund, claimId); this.#o.accounting.releaseClaim({ claimId, amountKobo: approved }); return next; }
  getAccountingSummary(reservationId: string) { return this.#o.accounting.summary(reservationId); }
  getDecisionSummary(claimId: string) { try { const decision = this.#o.decisions.get({ claimId }); return decision.valid ? { decisionId: decision.decisionId, decisionVersion: decision.decisionVersion, proposedApprovedKobo: decision.evaluations.reduce((sum, item) => sum + item.approvedAmountKobo, 0) } : null; } catch { return null; } }
  getRefundStatus(obligationId: string): string { return this.#o.accounting.refundObligation(obligationId)?.status ?? "not_created"; }
  hasReconciliation(reservationId: string): boolean { const claimId = this.#o.claims.findByReservationId(reservationId)?.claimId ?? `deposit-claim:${reservationId}`; return [`${claimId}:surplus`, `${claimId}:unapproved`, `${claimId}:no-claim`].some((id) => this.getRefundStatus(id) === "reconciliation_required"); }
  getArtifact(reservationId: string, principal: CommandPrincipal): DepositClaimProductionRecord { const claim = this.#o.claims.findByReservationId(reservationId); if (!claim || claim.status === "allocation_pending") throw new Error("Claim not available"); const { contract, reservation } = this.#booking(reservationId); if (principal.tenantId !== contract.tenantId || (principal.role === "guest" && principal.id !== reservation.primaryGuestId) || (principal.role === "operator" && principal.id !== contract.parties.operator.id)) throw new Error("ACTION_NOT_AUTHORIZED"); return claim; }
  #noClaimRecord(reservation: Reservation, contract: BookingContract, amountKobo: number, status: "no_claim_refund_pending" | "no_claim_refunded" | "reconciliation_required"): DepositClaimProductionRecord { const now = this.#clock().toISOString(); return { claimId: `deposit-claim:${reservation.reservationId}`, reservationId: reservation.reservationId, contractId: contract.contractId, tenantId: contract.tenantId ?? "", operatorId: contract.parties.operator.id, guestId: reservation.primaryGuestId, policyVersion: contract.securityDeposit?.policyVersion ?? "", evidenceVersion: "none", depositAmountKobo: amountKobo, claimedAmountKobo: 0, effectiveCheckoutIso: "", claimDeadlineIso: "", submittedAtIso: now, claimVersion: 1, status, items: [], notification: { status: "pending", notificationVersion: "0", deliveredAtIso: null, evidenceId: null }, responseWindowStartIso: null, responseWindowEndIso: null, guestResponse: null, initialReservedOperatorAwardKobo: 0, approvedOperatorAwardKobo: 0, unapprovedRefundKobo: amountKobo, history: [{ action: "no_claim_refund_initiated", at: now }] }; }
  #required(id: string): DepositClaimProductionRecord { const claim = this.#o.claims.findByClaimId(id); if (!claim) throw new Error("Claim not found"); return claim; }
  #refund(reservationId: string, contract: BookingContract, obligationId: string, amountKobo: number, claimId: string): void { if (amountKobo <= 0) return; const collection = this.#o.accounting.getByReservationId(reservationId); if (!collection) throw new Error("Held deposit not found"); const source = this.#o.accounting.getByCollectionId(collection.collectionId); if (!source?.providerReference) throw new Error("Successful deposit payment source is missing"); const obligation = this.#o.accounting.ensureRefundObligation({ obligationId, reservationId, claimId, amountKobo }); let result: ReturnType<DepositClaimRefundProvider["refundOrGet"]>; try { result = this.#o.refunds.refundOrGet({ obligationId: obligation.obligationId, offerId: source.offerId, paymentMethod: source.paymentMethod, originalPaymentReference: source.providerReference, amountKobo: obligation.amountKobo, currency: "NGN" }); if (result.amountKobo !== amountKobo || result.currency !== "NGN" || !result.refundId) throw new Error("Refund mismatch"); } catch { this.#o.accounting.markRefundResult({ obligationId, status: "reconciliation_required", settledAt: this.#clock().toISOString() }); this.#o.handoff?.request({ reservationId, reason: "refund_reconciliation" }); return; } const status = result.status === "settled" ? "settled" : result.status === "pending" ? "pending" : "reconciliation_required"; this.#o.accounting.markRefundResult({ obligationId, status, settledAt: this.#clock().toISOString() }); if (status === "reconciliation_required") this.#o.handoff?.request({ reservationId, reason: "refund_reconciliation" }); }
  #audit(action: string, claim: DepositClaimProductionRecord, principal: CommandPrincipal): void { this.#o.audit?.record({ type: action, claimId: claim.claimId, reservationId: claim.reservationId, claimVersion: claim.claimVersion, actorId: principal.id, recordedAt: this.#clock().toISOString() }); }
}
