import type { WebServerEventHandoff } from "@weaver/web";
import type { CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { DepositClaimApplication } from "./deposit-claim-application.js";
import { depositClaimArtifact, type DepositClaimArtifact, type DepositClaimActionType } from "./deposit-claim-artifact.js";
export const EVENTS = { accept: "shortlet.deposit-claim.accept", dispute: "shortlet.deposit-claim.dispute", "apply-reviewed-decision": "shortlet.deposit-claim.apply-reviewed-decision", "waive-appeal": "shortlet.deposit-claim.waive-appeal" } as const;
type Context = { artifactId: string; claimId: string; expectedClaimVersion: number; projectionVersion: string; decisionId?: string; decisionVersion?: string; evidenceVersion?: string; policyVersion?: string };
export type DepositClaimActionResult = { readonly ok: true; readonly artifact: DepositClaimArtifact } | { readonly ok: false; readonly code: "UNSUPPORTED_ACTION" | "INVALID_CONTEXT" | "STALE_ACTION" | "ACTION_NOT_AUTHORIZED"; readonly message: string };
function context(event: WebServerEventHandoff): Context | undefined { const raw: unknown = event?.message?.action?.context; if (!raw || typeof raw !== "object" || Array.isArray(raw)) return undefined; const record = raw as Record<string, unknown>; const required = ["artifactId", "claimId", "expectedClaimVersion", "projectionVersion"]; const optional = ["decisionId", "decisionVersion", "evidenceVersion", "policyVersion"]; if (Object.keys(record).some((key) => !required.includes(key) && !optional.includes(key)) || required.some((key) => typeof record[key] !== (key === "expectedClaimVersion" ? "number" : "string")) || optional.some((key) => record[key] !== undefined && typeof record[key] !== "string")) return undefined; return record as Context; }
export function resolveDepositClaimServerEvent(input: { readonly event: WebServerEventHandoff; readonly application: DepositClaimApplication; readonly principal: CommandPrincipal }): DepositClaimActionResult { const name = input.event?.message?.action?.name; const type = (Object.keys(EVENTS) as DepositClaimActionType[]).find((key) => EVENTS[key] === name); if (!type) return { ok: false, code: "UNSUPPORTED_ACTION", message: "The action is not supported." }; const c = context(input.event); if (!c) return { ok: false, code: "INVALID_CONTEXT", message: "The action context is invalid." }; try { const current = input.application.getArtifact(c.claimId.replace(/^deposit-claim:/, ""), input.principal); const artifact = depositClaimArtifact(input.application, current.reservationId, input.principal); const action = artifact.actions.find((candidate) => candidate.type === type); if (!action || c.artifactId !== artifact.id || c.claimId !== artifact.id || c.expectedClaimVersion !== artifact.facts.claimVersion || c.projectionVersion !== artifact.projectionVersion || (type === "apply-reviewed-decision" && (c.decisionId !== action.decisionId || c.decisionVersion !== action.decisionVersion || c.evidenceVersion !== action.evidenceVersion || c.policyVersion !== action.policyVersion))) return { ok: false, code: "STALE_ACTION", message: "The claim action is stale; refresh the claim." }; if (type === "accept") input.application.respond(c.claimId, input.principal, "accept"); else if (type === "dispute") input.application.respond(c.claimId, input.principal, "dispute"); else if (type === "waive-appeal") input.application.waiveAppeal(c.claimId, input.principal, { decisionId: c.decisionId ?? "", decisionVersion: c.decisionVersion ?? "" }); else input.application.applyReviewedDecision(c.claimId, input.principal, { expectedClaimVersion: c.expectedClaimVersion, decisionId: c.decisionId ?? "", decisionVersion: c.decisionVersion ?? "", evidenceVersion: c.evidenceVersion ?? "", policyVersion: c.policyVersion ?? "" }); return { ok: true, artifact: depositClaimArtifact(input.application, current.reservationId, input.principal) }; } catch (error) { const message = error instanceof Error ? error.message : ""; return { ok: false, code: message === "STALE_ACTION" ? "STALE_ACTION" : "ACTION_NOT_AUTHORIZED", message: "The claim action was rejected." }; } }
