import { createHash } from "node:crypto";
import type { CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { DepositClaimProductionRecord } from "../../../domains/shortlet/src/deposit-claim.js";
import type { DepositClaimApplication } from "./deposit-claim-application.js";
export const DEPOSIT_CLAIM_ARTIFACT_KIND = "shortlet.deposit-claim";
export const DEPOSIT_CLAIM_ARTIFACT_SCHEMA = "shortlet.deposit-claim/v1";
export type DepositClaimActionType = "accept" | "dispute" | "apply-reviewed-decision";
export interface DepositClaimArtifact { readonly id: string; readonly kind: typeof DEPOSIT_CLAIM_ARTIFACT_KIND; readonly schema: typeof DEPOSIT_CLAIM_ARTIFACT_SCHEMA; readonly projectionVersion: string; readonly facts: DepositClaimProductionRecord; readonly actions: readonly { readonly type: DepositClaimActionType; readonly artifactId: string; readonly claimId: string; readonly expectedClaimVersion: number; readonly projectionVersion: string }[]; readonly sensitivity: "booking-sensitive"; }
export function depositClaimArtifact(application: DepositClaimApplication, reservationId: string, principal: CommandPrincipal): DepositClaimArtifact { const claim = application.getArtifact(reservationId, principal); const id = claim.claimId; const markers = [claim.claimId, claim.claimVersion, claim.status, claim.claimedAmountKobo, claim.notification.status, claim.responseWindowEndIso ?? "", claim.guestResponse?.type ?? "", claim.approvedOperatorAwardKobo ?? "", claim.unapprovedRefundKobo]; const projectionVersion = createHash("sha256").update(markers.join("|")).digest("hex"); const actions: DepositClaimArtifact["actions"] = claim.status === "response_open" && principal.role === "guest" ? [{ type: "accept", artifactId: id, claimId: id, expectedClaimVersion: claim.claimVersion, projectionVersion }, { type: "dispute", artifactId: id, claimId: id, expectedClaimVersion: claim.claimVersion, projectionVersion }] : claim.status === "human_review" && (principal.role === "admin" || principal.role === "authorized_staff") ? [{ type: "apply-reviewed-decision", artifactId: id, claimId: id, expectedClaimVersion: claim.claimVersion, projectionVersion }] : []; return Object.freeze({ id, kind: DEPOSIT_CLAIM_ARTIFACT_KIND, schema: DEPOSIT_CLAIM_ARTIFACT_SCHEMA, projectionVersion, facts: claim, actions: Object.freeze(actions), sensitivity: "booking-sensitive" }); }
export const depositClaimArtifactFromApplication = depositClaimArtifact;
