import { createPlatformCommandEnvelope, type CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import { createGuestConductPolicySnapshot, GuestConductManager, type EvidenceAssessment, type GuestConductEvidenceProvider, type GuestConductIdentityProvider, type GuestConductCureVerificationProvider, type GuestConductHumanDecisionProvider, type GuestConductPolicySnapshot } from "../../../domains/shortlet/src/guest-conduct.js";
import type { BookingContract } from "../../../domains/shortlet/src/card-payment.js";
import { guestConductArtifactFromState, type GuestConductArtifact } from "./guest-conduct-artifact.js";
const DENIAL = "Access denied or resource not found";
export interface GuestConductContractRepository { getContract(contractId: string): BookingContract | null; getContractByReservation(reservationId: string): BookingContract | null; }
export interface GuestConductApplicationOptions { readonly contracts: GuestConductContractRepository; readonly manager?: GuestConductManager; readonly evidence: GuestConductEvidenceProvider; readonly identity?: GuestConductIdentityProvider; readonly cure?: GuestConductCureVerificationProvider; readonly decisions?: GuestConductHumanDecisionProvider; readonly requestHumanSupport?: (input: { reservationId: string; activeStay: boolean; safety: boolean }) => void; readonly audit?: { record(entry: Record<string, string | number | boolean>): void }; readonly clock?: () => Date; }
export class GuestConductApplication {
  readonly manager: GuestConductManager; readonly #o: GuestConductApplicationOptions; readonly #clock: () => Date;
  constructor(options: GuestConductApplicationOptions) { this.#o = options; this.manager = options.manager ?? new GuestConductManager(); this.#clock = options.clock ?? (() => new Date()); }
  #contract(reservationId: string, principal: CommandPrincipal): BookingContract { const c = this.#o.contracts.getContractByReservation(reservationId); if (!c || !principal.id || !principal.tenantId || !c.tenantId || principal.tenantId !== c.tenantId) throw new Error(DENIAL); const allowed = (principal.role === "guest" && principal.id === c.parties.primaryGuest.id && !c.parties.distinctPayer) || (principal.role === "operator" && principal.id === c.parties.operator.id) || ["authorized_staff", "admin"].includes(principal.role); if (!allowed) throw new Error(DENIAL); return c; }
  #policy(c: BookingContract): GuestConductPolicySnapshot { if (c.policies.guestConductPolicy) return c.policies.guestConductPolicy; const capacity = Array.isArray(c.occupants) ? Math.max(c.occupants.length, 1) : 1; return createGuestConductPolicySnapshot({ unitId: c.unitId, capacity }); }
  getArtifact(reservationId: string, principal: CommandPrincipal): GuestConductArtifact { const c = this.#contract(reservationId, principal); const current = this.manager.getProjectionForReservation(reservationId); return guestConductArtifactFromState({ reservationId: c.reservationId, contractId: c.contractId, policy: this.#policy(c), allegation: current, viewer: principal }); }
  reportAllegation(input: { reservationId: string; ruleId: Parameters<GuestConductManager["reportTrusted"]>[0]["ruleId"]; evidenceReferenceIds: readonly string[]; safeSummary: string; principal: CommandPrincipal; commandId: string }): GuestConductArtifact { const c = this.#contract(input.reservationId, input.principal); if (input.principal.role !== "operator" && !["authorized_staff", "admin"].includes(input.principal.role)) throw new Error(DENIAL); const evidence = this.#o.evidence.assess({ reservationId: c.reservationId, referenceIds: input.evidenceReferenceIds }); const allegation = this.manager.reportTrusted({ commandId: input.commandId, reservationId: c.reservationId, ruleId: input.ruleId, contract: this.#policy(c), evidence, safeSummary: input.safeSummary }); this.#o.audit?.record({ type: "guest_conduct.alleged", allegationId: allegation.allegationId, reservationId: c.reservationId, ruleId: allegation.ruleId, allegationVersion: allegation.allegationVersion, ruleVersion: allegation.ruleVersion, occurredAt: this.#clock().toISOString() }); return this.getArtifact(c.reservationId, input.principal); }
  issueWarning(reservationId: string, allegationId: string, commandId: string, principal: CommandPrincipal): GuestConductArtifact { const c = this.#contract(reservationId, principal); const a = this.manager.issuePolicyWarning(allegationId, commandId, this.#clock()); this.#o.audit?.record({ type: "guest_conduct.warning_issued", allegationId, reservationId: c.reservationId, allegationVersion: a.allegationVersion, ruleVersion: a.ruleVersion, occurredAt: this.#clock().toISOString() }); return this.getArtifact(reservationId, principal); }
  verifyCure(reservationId: string, allegationId: string, commandId: string, principal: CommandPrincipal): GuestConductArtifact { const c = this.#contract(reservationId, principal); if (!this.#o.cure) throw new Error("Trusted cure verification provider required"); const a = this.manager.get(allegationId); const result = this.#o.cure.verify({ allegationId, evidenceSetId: a.evidenceSetId }); this.manager.verifyCure(allegationId, commandId, result); return this.getArtifact(c.reservationId, principal); }
  applyReviewedDecision(input: { reservationId: string; allegationId: string; expectedAllegationVersion: number; ruleVersion: string; evidenceVersion: string; principal: CommandPrincipal }): GuestConductArtifact { const c = this.#contract(input.reservationId, input.principal); if (!this.#o.decisions) throw new Error("Trusted human decision provider required"); const d = this.#o.decisions.getDecision({ allegationId: input.allegationId }); const env = createPlatformCommandEnvelope({ commandName: "guest_conduct.apply_reviewed_decision", principal: input.principal, payload: { allegationId: input.allegationId, expectedAllegationVersion: input.expectedAllegationVersion, ruleVersion: input.ruleVersion, evidenceVersion: input.evidenceVersion } }); const a = this.manager.applyHumanDecision(env, d); this.#o.audit?.record({ type: "guest_conduct.human_decision_applied", allegationId: a.allegationId, reservationId: c.reservationId, allegationVersion: a.allegationVersion, ruleVersion: a.ruleVersion, occurredAt: this.#clock().toISOString() }); return this.getArtifact(c.reservationId, input.principal); }
  requestHumanSupport(reservationId: string, principal: CommandPrincipal, safety = false): GuestConductArtifact { const c = this.#contract(reservationId, principal); if (!this.#o.requestHumanSupport) throw new Error("Human handoff application is required"); this.#o.requestHumanSupport({ reservationId: c.reservationId, activeStay: true, safety }); return this.getArtifact(reservationId, principal); }
  recordTrustedIdentity(reservationId: string, principal: CommandPrincipal) { const c = this.#contract(reservationId, principal); if (!this.#o.identity) throw new Error("Trusted identity provider required"); return this.#o.identity.compare({ reservationId: c.reservationId, primaryGuestId: c.parties.primaryGuest.id }); }
}
