import type { WebServerEventHandoff } from "@weaver/web";
import type { CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { GuestConductApplication } from "./guest-conduct-application.js";
import type { GuestConductArtifact } from "./guest-conduct-artifact.js";
export const GUEST_CONDUCT_APPLY_REVIEWED_EVENT = "shortlet.guest-conduct.apply-reviewed-decision";
export const GUEST_CONDUCT_REQUEST_SUPPORT_EVENT = "shortlet.guest-conduct.request-human-support";
type Context = { readonly artifactId: string; readonly reservationId: string; readonly allegationId?: string; readonly expectedAllegationVersion?: number; readonly ruleVersion?: string; readonly evidenceVersion?: string; readonly projectionVersion: string };
export type GuestConductActionResult = { readonly ok: true; readonly artifact: GuestConductArtifact } | { readonly ok: false; readonly code: "UNSUPPORTED_ACTION" | "INVALID_CONTEXT" | "STALE_ACTION" | "ACTION_NOT_AUTHORIZED"; readonly message: string };
function contextOf(event: WebServerEventHandoff): Context | undefined { const value: unknown = event?.message?.action?.context; if (!value || typeof value !== "object" || Array.isArray(value)) return undefined; const record = value as Record<string, unknown>; const allowed = ["artifactId", "reservationId", "allegationId", "expectedAllegationVersion", "ruleVersion", "evidenceVersion", "projectionVersion"]; if (Object.keys(record).some((k) => !allowed.includes(k)) || typeof record.artifactId !== "string" || typeof record.reservationId !== "string" || typeof record.projectionVersion !== "string") return undefined; if (record.allegationId !== undefined && typeof record.allegationId !== "string") return undefined; if (record.expectedAllegationVersion !== undefined && typeof record.expectedAllegationVersion !== "number") return undefined; if (record.ruleVersion !== undefined && typeof record.ruleVersion !== "string") return undefined; if (record.evidenceVersion !== undefined && typeof record.evidenceVersion !== "string") return undefined; return record as Context; }
export function resolveGuestConductServerEvent(input: { readonly event: WebServerEventHandoff; readonly application: GuestConductApplication; readonly principal: CommandPrincipal }): GuestConductActionResult { const name = input.event?.message?.action?.name; if (name !== GUEST_CONDUCT_APPLY_REVIEWED_EVENT && name !== GUEST_CONDUCT_REQUEST_SUPPORT_EVENT) return { ok: false, code: "UNSUPPORTED_ACTION", message: "The action is not supported." }; const c = contextOf(input.event); if (!c) return { ok: false, code: "INVALID_CONTEXT", message: "The action context is invalid." }; try { const current = input.application.getArtifact(c.reservationId, input.principal); if (current.id !== c.artifactId || current.projectionVersion !== c.projectionVersion) return { ok: false, code: "STALE_ACTION", message: "The conduct action is stale; refresh the current matter." }; if (name === GUEST_CONDUCT_REQUEST_SUPPORT_EVENT) return { ok: true, artifact: input.application.requestHumanSupport(c.reservationId, input.principal) }; if (!c.allegationId || c.expectedAllegationVersion === undefined || !c.ruleVersion || !c.evidenceVersion) return { ok: false, code: "INVALID_CONTEXT", message: "The reviewed decision context is invalid." }; const refreshed = input.application.applyReviewedDecision({ reservationId: c.reservationId, allegationId: c.allegationId, expectedAllegationVersion: c.expectedAllegationVersion, ruleVersion: c.ruleVersion, evidenceVersion: c.evidenceVersion, principal: input.principal }); return { ok: true, artifact: refreshed }; } catch (error) { return { ok: false, code: error instanceof Error && error.message === "STALE_ACTION" ? "STALE_ACTION" : "ACTION_NOT_AUTHORIZED", message: "The conduct action was rejected." }; } }
