import { createHash } from "node:crypto";
import type { CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { GuestConductAllegation, GuestConductPolicySnapshot } from "../../../domains/shortlet/src/guest-conduct.js";
export const GUEST_CONDUCT_ARTIFACT_KIND = "shortlet.guest-conduct";
export const GUEST_CONDUCT_SCHEMA = "shortlet.guest-conduct/v1";
export interface GuestConductArtifact { readonly id: string; readonly kind: typeof GUEST_CONDUCT_ARTIFACT_KIND; readonly schema: typeof GUEST_CONDUCT_SCHEMA; readonly projectionVersion: string; readonly facts: { readonly reservationId: string; readonly contractId: string; readonly ruleVersion: string; readonly rules: readonly string[]; readonly visitorMode: GuestConductPolicySnapshot["visitorMode"]; readonly petsAllowed: boolean; readonly petFriendlyTerms?: string; readonly children: GuestConductPolicySnapshot["children"]; readonly quietHours: GuestConductPolicySnapshot["quietHours"]; readonly occupancyLimit: number; readonly allegation?: Omit<GuestConductAllegation, "evidenceSetId" | "evidenceVersion">; readonly humanOwned: boolean; readonly automationSuppressed: boolean }; readonly actions: readonly { readonly type: "request_human_support" | "apply_reviewed_decision"; readonly artifactId: string; readonly reservationId: string; readonly allegationId?: string; readonly expectedAllegationVersion?: number; readonly ruleVersion?: string; readonly evidenceVersion?: string; readonly projectionVersion: string }[]; readonly sensitivity: "booking-sensitive"; }
export function guestConductArtifactId(reservationId: string): string { return `guest-conduct:${reservationId}`; }
export function guestConductArtifactFromState(input: { reservationId: string; contractId: string; policy: GuestConductPolicySnapshot; allegation?: GuestConductAllegation; viewer: CommandPrincipal }): GuestConductArtifact {
  const a = input.allegation;
  const safeAllegation = a ? (({ evidenceSetId: _e, evidenceVersion: _v, ...safe }) => safe)(a) : undefined;
  const markers = [input.reservationId, input.contractId, input.policy.ruleVersion, String(a?.allegationVersion ?? 0), a?.state ?? "none", a?.warningCode ?? "", a?.cureDeadline ?? "", a?.outcome ?? "", String(a?.humanOwned ?? false)];
  const projectionVersion = createHash("sha256").update(markers.join("|"), "utf8").digest("hex").slice(0, 16);
  const id = guestConductArtifactId(input.reservationId);
  const actions = a?.humanOwned ? [] : input.viewer.role === "guest" ? [{ type: "request_human_support" as const, artifactId: id, reservationId: input.reservationId, projectionVersion }] : ["authorized_staff", "admin"].includes(input.viewer.role) && a ? [{ type: "apply_reviewed_decision" as const, artifactId: id, reservationId: input.reservationId, allegationId: a.allegationId, expectedAllegationVersion: a.allegationVersion, ruleVersion: a.ruleVersion, evidenceVersion: a.evidenceVersion, projectionVersion }] : [];
  return Object.freeze({ id, kind: GUEST_CONDUCT_ARTIFACT_KIND, schema: GUEST_CONDUCT_SCHEMA, projectionVersion, facts: Object.freeze({ reservationId: input.reservationId, contractId: input.contractId, ruleVersion: input.policy.ruleVersion, rules: Object.freeze(input.policy.rules.map((r) => r.summary)), visitorMode: input.policy.visitorMode, petsAllowed: input.policy.petsAllowed, ...(input.policy.petFriendlyTerms ? { petFriendlyTerms: input.policy.petFriendlyTerms } : {}), children: input.policy.children, quietHours: input.policy.quietHours, occupancyLimit: input.policy.occupancyLimit, ...(safeAllegation ? { allegation: safeAllegation } : {}), humanOwned: Boolean(a?.humanOwned), automationSuppressed: Boolean(a?.humanOwned) }), actions: Object.freeze(actions), sensitivity: "booking-sensitive" });
}
