import { createHash } from "node:crypto";
import type { InteractionThreadDescriptor } from "../../../packages/platform-core/src/index.js";
import type { HandoffState, InteractionControlMode, SupportPath } from "../../../packages/platform-core/src/index.js";
export const HUMAN_HANDOFF_ARTIFACT_KIND = "platform.human-handoff";
export const HUMAN_HANDOFF_SCHEMA_VERSION = "platform.human-handoff/v1";
export type HumanHandoffAction = "stop_current_run" | "request_human_support";
export interface HumanHandoffArtifact { readonly id: string; readonly kind: typeof HUMAN_HANDOFF_ARTIFACT_KIND; readonly schemaVersion: typeof HUMAN_HANDOFF_SCHEMA_VERSION; readonly projectionVersion: string; readonly facts: { readonly threadId: string; readonly mode: InteractionControlMode; readonly supportPath?: SupportPath; readonly supportLabel?: string; readonly humanOwnerAssigned: boolean; readonly automationSuppressed: boolean; readonly currentRunStatus: "running" | "stopped" | "none"; readonly committedActionCount: number; readonly lastUserNotice?: string }; readonly actions: readonly { readonly type: HumanHandoffAction; readonly artifactId: string; readonly threadId: string; readonly expectedMode: InteractionControlMode; readonly projectionVersion: string }[]; readonly sensitivity: "interaction"; }
export function humanHandoffArtifactId(threadId: string): string { return `human-handoff:${threadId}`; }
export function humanHandoffArtifactFromState(input: { state: HandoffState; thread: InteractionThreadDescriptor & { readonly currentRunStatus?: "running" | "stopped" | "none"; readonly currentRunId?: string } }): HumanHandoffArtifact { const { state, thread } = input; const currentRunStatus = thread.currentRunStatus ?? "none"; const supportLabel = state.supportPath === "general_support" ? "General Support" : state.supportPath === "active_stay_emergency_support" ? "Active-Stay Emergency Support" : undefined; const markers = [thread.threadId, thread.projectionVersion, state.handoffVersion, state.mode, state.supportPath ?? "", state.assignedOwner ? "assigned" : "unassigned", currentRunStatus, state.userNotice ?? "", thread.currentRunId ?? ""]; const projectionVersion = createHash("sha256").update(markers.join("|")).digest("hex").slice(0, 16); const actions = state.mode === "automated" ? [{ type: "request_human_support" as const, artifactId: humanHandoffArtifactId(state.threadId), threadId: state.threadId, expectedMode: state.mode, projectionVersion }, ...(currentRunStatus === "running" ? [{ type: "stop_current_run" as const, artifactId: humanHandoffArtifactId(state.threadId), threadId: state.threadId, expectedMode: state.mode, projectionVersion }] : [])] : []; return Object.freeze({ id: humanHandoffArtifactId(state.threadId), kind: HUMAN_HANDOFF_ARTIFACT_KIND, schemaVersion: HUMAN_HANDOFF_SCHEMA_VERSION, projectionVersion, facts: Object.freeze({ threadId: state.threadId, mode: state.mode, ...(state.supportPath ? { supportPath: state.supportPath, supportLabel } : {}), humanOwnerAssigned: Boolean(state.assignedOwner), automationSuppressed: state.mode !== "automated", currentRunStatus, committedActionCount: state.committedActions.length, ...(state.userNotice ? { lastUserNotice: state.userNotice } : {}) }), actions: Object.freeze(actions), sensitivity: "interaction" as const }); }
