import type { CommandPrincipal, SecurityContext, InteractionThreadManager } from "../../../packages/platform-core/src/index.js";
import { HumanHandoffManager, type HandoffCategory, type HandoffState, type HandoffTrigger, type SupportPath } from "../../../packages/platform-core/src/index.js";
import { humanHandoffArtifactFromState, type HumanHandoffArtifact } from "./human-handoff-artifact.js";

export interface ThreadAuthorityContextProvider { getSubjectContext(threadId: string): SecurityContext; }
export interface HandoffMatterContextProvider { getContext(threadId: string): { activeStay: boolean; category?: HandoffCategory }; }
export interface HumanSupportAssignmentProvider { assign(input: { threadId: string; supportPath: SupportPath }): { responderId: string; responderRole: string }; }
export interface HandoffResolutionAuthority { getResolution(input: { threadId: string; assignedResponderId: string }): { resolved: boolean; version?: number | string }; }
export interface HumanHandoffApplicationOptions { readonly threadManager: InteractionThreadManager; readonly handoffManager?: HumanHandoffManager; readonly matterContext: HandoffMatterContextProvider; readonly assignment: HumanSupportAssignmentProvider; readonly resolution: HandoffResolutionAuthority; readonly threadAuthority?: ThreadAuthorityContextProvider; readonly audit?: { record(entry: Record<string, string | number>): void }; readonly clock?: () => Date; }
export class HumanHandoffApplication {
  readonly manager: HumanHandoffManager; readonly #threads: InteractionThreadManager; readonly #matter: HandoffMatterContextProvider; readonly #assignment: HumanSupportAssignmentProvider; readonly #resolution: HandoffResolutionAuthority; readonly #subjects?: ThreadAuthorityContextProvider;
  constructor(options: HumanHandoffApplicationOptions) { this.#threads = options.threadManager; this.manager = options.handoffManager ?? new HumanHandoffManager(options.threadManager, { audit: options.audit, clock: options.clock }); this.#matter = options.matterContext; this.#assignment = options.assignment; this.#resolution = options.resolution; this.#subjects = options.threadAuthority; }
  #subject(threadId: string, context: SecurityContext): SecurityContext { this.#threads.getThread(threadId, context); return context; }
  getArtifact(threadId: string, context: SecurityContext): HumanHandoffArtifact { const subject = this.#subject(threadId, context); const run = this.#threads.getCurrentRunStatus(threadId, subject); return humanHandoffArtifactFromState({ state: this.manager.getHandoffStatus(threadId, subject), thread: { ...this.#threads.getThread(threadId, subject), currentRunStatus: run.status === "running" ? "running" : run.status === "stopped" ? "stopped" : "none", ...(run.runId ? { currentRunId: run.runId } : {}) } }); }
  stopCurrentRun(threadId: string, context: SecurityContext) { this.#subject(threadId, context); this.manager.stopCurrentAgentRun(threadId, context); return this.getArtifact(threadId, context); }
  requestHumanSupport(threadId: string, context: SecurityContext) { const matter = this.#matter.getContext(threadId); const category = matter.category ?? "general_support"; const state = this.manager.initiateHandoff(threadId, context, { trigger: "user_request", category, activeStay: matter.activeStay }); return this.getArtifact(threadId, context); }
  requestMandatoryHandoff(input: { threadId: string; trigger: HandoffTrigger; category: HandoffCategory; actor: CommandPrincipal }) { if (!["system", "admin", "authorized_staff"].includes(input.actor.role)) throw new Error("Trusted mandatory handoff actor required"); const subject = this.#subjects?.getSubjectContext(input.threadId); if (!subject) throw new Error("Subject context unavailable"); const matter = this.#matter.getContext(input.threadId); if (input.category !== "general_support" && !matter.category && !matter.activeStay) throw new Error("Authoritative matter context required"); this.manager.initiateHandoff(input.threadId, subject, { trigger: input.trigger, category: input.category, activeStay: matter.activeStay }, input.actor); return this.getArtifact(input.threadId, subject); }
  assignHumanOwner(input: { threadId: string; actor: CommandPrincipal }) { if (!this.#subjects) throw new Error("Subject context unavailable"); const subject = this.#subjects.getSubjectContext(input.threadId); const state = this.manager.getHandoffStatus(input.threadId, subject); if (!state.supportPath) throw new Error("Support path unavailable"); const assignment = this.#assignment.assign({ threadId: input.threadId, supportPath: state.supportPath }); this.manager.assignHumanOwner(input.threadId, subject, { responderId: assignment.responderId, role: assignment.responderRole }, input.actor); return this.getArtifact(input.threadId, subject); }
  prepareHandback(input: { threadId: string; actor: CommandPrincipal; userNotice: string }) { if (!this.#subjects) throw new Error("Subject context unavailable"); const subject = this.#subjects.getSubjectContext(input.threadId); const state = this.manager.getHandoffStatus(input.threadId, subject); if (!state.assignedOwner) throw new Error("No assigned responder"); const resolution = this.#resolution.getResolution({ threadId: input.threadId, assignedResponderId: state.assignedOwner }); this.manager.prepareHandback(input.threadId, subject, input.actor, resolution, input.userNotice); return this.getArtifact(input.threadId, subject); }
  completeHandback(threadId: string) { if (!this.#subjects) throw new Error("Subject context unavailable"); const subject = this.#subjects.getSubjectContext(threadId); this.manager.completeHandback(threadId, subject); return this.getArtifact(threadId, subject); }
}
