import type { WebServerEventHandoff } from "@weaver/web";
import type { SecurityContext } from "../../../packages/platform-core/src/index.js";
import type { HumanHandoffApplication } from "./human-handoff-application.js";
import type { HumanHandoffArtifact } from "./human-handoff-artifact.js";
export const HUMAN_HANDOFF_STOP_EVENT = "platform.handoff.stop-current-run";
export const HUMAN_HANDOFF_REQUEST_EVENT = "platform.handoff.request-human";
type EventName = typeof HUMAN_HANDOFF_STOP_EVENT | typeof HUMAN_HANDOFF_REQUEST_EVENT;
type Context = { readonly artifactId: string; readonly threadId: string; readonly expectedMode: "automated"; readonly projectionVersion: string };
export type HumanHandoffActionResult = { readonly ok: true; readonly artifact: HumanHandoffArtifact } | { readonly ok: false; readonly code: "UNSUPPORTED_ACTION" | "INVALID_CONTEXT" | "STALE_ACTION" | "ACTION_NOT_AUTHORIZED"; readonly message: string };
function contextOf(event: WebServerEventHandoff): Context | undefined { const value: unknown = event?.message?.action?.context; if (!value || typeof value !== "object" || Array.isArray(value)) return undefined; const record = value as Record<string, unknown>; const keys = Object.keys(record); const required = ["artifactId", "threadId", "expectedMode", "projectionVersion"]; if (keys.length !== required.length || !required.every((key) => keys.includes(key))) return undefined; if (typeof record.artifactId !== "string" || typeof record.threadId !== "string" || record.expectedMode !== "automated" || typeof record.projectionVersion !== "string") return undefined; return record as Context; }
export function resolveHumanHandoffServerEvent(input: { readonly event: WebServerEventHandoff; readonly application: HumanHandoffApplication; readonly context: SecurityContext }): HumanHandoffActionResult { const name = input.event?.message?.action?.name as EventName; if (name !== HUMAN_HANDOFF_STOP_EVENT && name !== HUMAN_HANDOFF_REQUEST_EVENT) return { ok: false, code: "UNSUPPORTED_ACTION", message: "The action is not supported." }; const eventContext = contextOf(input.event); if (!eventContext) return { ok: false, code: "INVALID_CONTEXT", message: "The action context is invalid." }; let current: HumanHandoffArtifact; try { current = input.application.getArtifact(eventContext.threadId, input.context); } catch { return { ok: false, code: "ACTION_NOT_AUTHORIZED", message: "The action is not authorized." }; } if (eventContext.artifactId !== current.id || eventContext.threadId !== current.facts.threadId || eventContext.expectedMode !== current.facts.mode || eventContext.projectionVersion !== current.projectionVersion) return { ok: false, code: "STALE_ACTION", message: "The action is stale; refresh the current interaction." }; const action = name === HUMAN_HANDOFF_STOP_EVENT ? "stop_current_run" : "request_human_support"; if (!current.actions.some((candidate) => candidate.type === action)) return { ok: false, code: "ACTION_NOT_AUTHORIZED", message: "The action is not authorized." }; try { return { ok: true, artifact: name === HUMAN_HANDOFF_STOP_EVENT ? input.application.stopCurrentRun(eventContext.threadId, input.context) : input.application.requestHumanSupport(eventContext.threadId, input.context) }; } catch { return { ok: false, code: "ACTION_NOT_AUTHORIZED", message: "The action was rejected." }; } }
