import type { WebServerEventHandoff } from "@weaver/web";
import type { CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { MidStayFailureApplication } from "./mid-stay-failure-application.js";
import type { MidStayFailureArtifact } from "./mid-stay-failure-artifact.js";
export const MID_STAY_REQUEST_SUPPORT_EVENT = "shortlet.mid-stay-failure.request-human-support";
export const MID_STAY_APPLY_REVIEWED_EVENT = "shortlet.mid-stay-failure.apply-reviewed";
export type MidStayActionResult = { readonly ok: true; readonly artifact: MidStayFailureArtifact } | { readonly ok: false; readonly code: "INVALID_CONTEXT" | "STALE_ACTION" | "ACTION_NOT_AUTHORIZED" | "UNSUPPORTED_ACTION"; readonly message: string };
type Context = { readonly artifactId: string; readonly reservationId: string; readonly incidentId: string; readonly expectedIncidentVersion: number; readonly expectedContractVersion: number; readonly activeStayVersion: string; readonly evidenceVersion: string; readonly assessmentVersion: string; readonly cureVersion: string; readonly economicsVersion: string; readonly projectionVersion: string; readonly decisionVersion?: string };
function context(event: WebServerEventHandoff): Context | undefined { const value: unknown = event?.message?.action?.context; if (!value || typeof value !== "object" || Array.isArray(value)) return undefined; const record = value as Record<string, unknown>; const allowed = ["artifactId","reservationId","incidentId","expectedIncidentVersion","expectedContractVersion","activeStayVersion","evidenceVersion","assessmentVersion","cureVersion","economicsVersion","projectionVersion","decisionVersion"]; const keys = Object.keys(record); if (keys.some((key) => !allowed.includes(key)) || !allowed.slice(0, 11).every((key) => key in record)) return undefined; if (typeof record.artifactId !== "string" || typeof record.reservationId !== "string" || typeof record.incidentId !== "string" || typeof record.projectionVersion !== "string") return undefined; return record as unknown as Context; }
export function resolveMidStayFailureServerEvent(input: { event: WebServerEventHandoff; application: MidStayFailureApplication; principal: CommandPrincipal }): MidStayActionResult { const name = input.event?.message?.action?.name; if (name !== MID_STAY_REQUEST_SUPPORT_EVENT && name !== MID_STAY_APPLY_REVIEWED_EVENT) return { ok: false, code: "UNSUPPORTED_ACTION", message: "The action is not supported." }; const c = context(input.event); if (!c) return { ok: false, code: "INVALID_CONTEXT", message: "The action context is invalid." }; let current: MidStayFailureArtifact; try { current = input.application.getArtifact(c.reservationId, input.principal); } catch { return { ok: false, code: "ACTION_NOT_AUTHORIZED", message: "The action is not authorized." }; } const i = current.facts.incident; const matches = current.id === c.artifactId && current.facts.reservationId === c.reservationId && i.incidentId === c.incidentId && current.projectionVersion === c.projectionVersion && current.facts.contractVersion === c.expectedContractVersion && current.facts.activeStayVersion === c.activeStayVersion && i.incidentVersion === c.expectedIncidentVersion && i.evidenceVersion === c.evidenceVersion && i.assessmentVersion === c.assessmentVersion && i.cureVersion === c.cureVersion; if (!matches) return { ok: false, code: "STALE_ACTION", message: "The action is stale; refresh the current incident." }; try { return { ok: true, artifact: name === MID_STAY_REQUEST_SUPPORT_EVENT ? input.application.requestHumanSupport(c.reservationId, input.principal) : input.application.applyReviewedDecision(c.reservationId, input.principal) }; } catch (error) { return { ok: false, code: error instanceof Error && error.message === "STALE_ACTION" ? "STALE_ACTION" : "ACTION_NOT_AUTHORIZED", message: "The action was rejected." }; } }
