import { createHash } from "node:crypto";
import type { MidStayIncidentRecord } from "../../../domains/shortlet/src/mid-stay-failure.js";
export const MID_STAY_FAILURE_ARTIFACT_KIND = "shortlet.mid-stay-failure" as const;
export const MID_STAY_FAILURE_SCHEMA_VERSION = "shortlet.mid-stay-failure/v1" as const;
export interface MidStayFailureArtifact { readonly id: string; readonly kind: typeof MID_STAY_FAILURE_ARTIFACT_KIND; readonly schemaVersion: typeof MID_STAY_FAILURE_SCHEMA_VERSION; readonly projectionVersion: string; readonly facts: { readonly reservationId: string; readonly contractVersion: number; readonly activeStayStatus: string; readonly activeStayVersion: string; readonly incident: Record<string, unknown>; readonly remedy?: Record<string, unknown>; readonly downstream: { readonly qualifiesForGuestChoice: boolean; readonly nextStep: "guest_choice_required" | "human_review" | "none" }; }; readonly actions: readonly { readonly type: "request_human_support" | "apply_reviewed_decision"; readonly artifactId: string; readonly reservationId: string; readonly incidentId: string; readonly expectedIncidentVersion: number; readonly expectedContractVersion: number; readonly activeStayVersion: string; readonly evidenceVersion: string; readonly assessmentVersion: string; readonly cureVersion: string; readonly economicsVersion: string; readonly projectionVersion: string; readonly decisionVersion?: string }[]; }
export function midStayFailureArtifactId(reservationId: string): string { return `mid-stay-failure:${reservationId}`; }
export function midStayFailureArtifact(input: { reservationId: string; contractVersion: number; activeStayStatus: string; activeStayVersion: string; incident: MidStayIncidentRecord; decisionVersion?: string; handoffOwned?: boolean; supportViewer?: boolean }): MidStayFailureArtifact {
  const i = input.incident; const a = i.assessment; const c = i.cure; const e = i.economics; const r = i.remedy;
  const incident = { incidentId: i.incidentId, incidentVersion: i.incidentVersion, status: i.status, category: a?.category, categoryLabel: a?.category, materialIncident: a?.materialIncident ?? false, evidenceStatus: i.evidenceStatus, evidenceVersion: i.evidenceVersion, assessmentVersion: a?.assessmentVersion, causationStatus: a?.causationStatus, causationVersion: a?.causationVersion, cureStatus: c?.status, cureVersion: c?.cureVersion, curedAt: c?.curedAt, failureStartedAt: a?.failureStartedAt, reportedAt: i.reportedAt, humanReviewRequired: i.status === "human_review" || i.status === "assessment_pending" || i.status === "cure_pending", humanOwned: input.handoffOwned ?? i.humanOwned };
  const remedy = r && e ? { percentage: r.percentage, affectedNightlyLineItems: (a?.category === "safety_access_habitability" ? [...new Set([...(a?.unusedNightDates ?? []), ...(a?.materiallyUnusableNightDates ?? [])])] : a?.affectedNightDates ?? []).map((date) => ({ date, contractedRateKobo: e.nightlyLineItems.find((x) => x.nightDateIso === date)?.rateKobo ?? 0, remedyKobo: Math.floor((e.nightlyLineItems.find((x) => x.nightDateIso === date)?.rateKobo ?? 0) * r.percentage / 100) })), attributableUndeliveredChargesKobo: r.attributableUndeliveredChargesKobo, attributableRefundableTaxKobo: r.attributableRefundableTaxKobo, totalRemedyKobo: r.totalRefundKobo, currency: "NGN", reportingDelayExcused: r.reportingDelayExcused, cureWindowExceeded: r.cureWindowExceeded } : undefined;
  const downstream = { qualifiesForGuestChoice: a?.category === "safety_access_habitability" && a.materialIncident, nextStep: a?.category === "safety_access_habitability" && a.materialIncident ? "guest_choice_required" as const : incident.humanOwned || incident.status === "human_review" ? "human_review" as const : "none" as const };
  const markers = { reservationId: input.reservationId, contractVersion: input.contractVersion, activeStayVersion: input.activeStayVersion, activeStayStatus: input.activeStayStatus, incidentVersion: i.incidentVersion, status: i.status, evidenceVersion: i.evidenceVersion, assessmentVersion: a?.assessmentVersion, causationVersion: a?.causationVersion, cureVersion: c?.cureVersion, economicsVersion: e?.economicsVersion, remedy, decisionVersion: input.decisionVersion, humanOwned: incident.humanOwned };
  const projectionVersion = createHash("sha256").update(JSON.stringify(markers)).digest("hex"); const id = midStayFailureArtifactId(input.reservationId);
  const base = { artifactId: id, reservationId: input.reservationId, incidentId: i.incidentId, expectedIncidentVersion: i.incidentVersion, expectedContractVersion: input.contractVersion, activeStayVersion: input.activeStayVersion, evidenceVersion: i.evidenceVersion, assessmentVersion: a?.assessmentVersion ?? "", cureVersion: c?.cureVersion ?? "", economicsVersion: e?.economicsVersion ?? "", projectionVersion };
  const actions = i.humanOwned ? (input.supportViewer && input.decisionVersion ? [{ type: "apply_reviewed_decision" as const, ...base, decisionVersion: input.decisionVersion }] : []) : [{ type: "request_human_support" as const, ...base }];
  return Object.freeze({ id, kind: MID_STAY_FAILURE_ARTIFACT_KIND, schemaVersion: MID_STAY_FAILURE_SCHEMA_VERSION, projectionVersion, facts: { reservationId: input.reservationId, contractVersion: input.contractVersion, activeStayStatus: input.activeStayStatus, activeStayVersion: input.activeStayVersion, incident, ...(remedy ? { remedy } : {}), downstream }, actions });
}
