import type { CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { PaymentCapabilityCertification, UssdSession } from "../../../domains/shortlet/src/index.js";
export const PAYMENT_CAPABILITY_ARTIFACT_KIND = "shortlet.payment-capabilities";
export const PAYMENT_CAPABILITY_SCHEMA_VERSION = "shortlet.payment-capabilities/v1";
export interface PaymentCapabilityAction { readonly type: "initialize_ussd"; readonly artifactId: string; readonly offerId: string; readonly capabilityId: string; readonly expectedStatus: "certified"; readonly projectionVersion: string; }
export interface PaymentCapabilityArtifact { readonly id: string; readonly kind: typeof PAYMENT_CAPABILITY_ARTIFACT_KIND; readonly schemaVersion: typeof PAYMENT_CAPABILITY_SCHEMA_VERSION; readonly projectionVersion: string; readonly facts: { readonly offerId: string; readonly availableMethods: readonly ("card" | "bank_transfer" | "ussd")[]; readonly capabilityVersions: Readonly<Record<string, number>>; readonly paymentDeadline: string; readonly livePaymentMethod?: string; readonly ussd?: { readonly code: string; readonly expiresAt: string; readonly providerSessionId: string }; }; readonly actions: readonly PaymentCapabilityAction[]; readonly sensitivity: "booking-sensitive"; }
export function paymentCapabilityArtifactId(offerId: string): string { return `payment-capabilities:${offerId}`; }
export function paymentCapabilityArtifactFromState(input: { offer: { offerId: string; paymentWindow: { expiresAt: string }; parties: { primaryGuest: { id: string }; distinctPayer?: { id: string } | null }; tenantId?: string }; viewer: CommandPrincipal; capabilities: readonly PaymentCapabilityCertification[]; session?: UssdSession; livePaymentMethod?: string; projectionVersion: string }): PaymentCapabilityArtifact {
  const { offer, viewer } = input; const id = paymentCapabilityArtifactId(offer.offerId); const methods = input.capabilities.map((c) => c.channel); const payer = offer.parties.distinctPayer?.id ?? offer.parties.primaryGuest.id;
  const authorized = viewer.role === "guest" && viewer.id === payer && !!viewer.tenantId && viewer.tenantId === offer.tenantId;
  const ussd = input.capabilities.find((c) => c.channel === "ussd"); const canInitialize = !!ussd && authorized && !input.livePaymentMethod;
  const facts: PaymentCapabilityArtifact["facts"] = { offerId: offer.offerId, availableMethods: Object.freeze([...new Set(methods)]), capabilityVersions: Object.freeze(Object.fromEntries(input.capabilities.map((c) => [c.capabilityId, c.version]))), paymentDeadline: offer.paymentWindow.expiresAt, ...(input.livePaymentMethod ? { livePaymentMethod: input.livePaymentMethod } : {}), ...(input.session && input.session.status === "active" && authorized ? { ussd: { code: input.session.ussdCode, expiresAt: input.session.expiresAt, providerSessionId: input.session.providerSessionId } } : {}) };
  const actions = canInitialize ? [{ type: "initialize_ussd" as const, artifactId: id, offerId: offer.offerId, capabilityId: ussd.capabilityId, expectedStatus: "certified" as const, projectionVersion: input.projectionVersion }] : [];
  return Object.freeze({ id, kind: PAYMENT_CAPABILITY_ARTIFACT_KIND, schemaVersion: PAYMENT_CAPABILITY_SCHEMA_VERSION, projectionVersion: input.projectionVersion, facts: Object.freeze(facts), actions: Object.freeze(actions), sensitivity: "booking-sensitive" });
}
