import { createPlatformCommandEnvelope, type CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { EarnedCommissionSource } from "../../../domains/shortlet/src/revenue-accounting.js";
import { calculateContributionRate, calculateRequiredSeedCapital, calculateTargetBalance, protectionFundJournal, PROTECTION_FUND_POLICY, type ProtectionFundAccountingRepository, type ProtectionFundCapitalProvider, type ProtectionFundMetricsProvider, type RemedyFundingRecord, type ProtectionFundSnapshot } from "../../../domains/shortlet/src/protection-fund-accounting.js";

export interface ProtectionFundFinanceAuthorization { canView(principal: CommandPrincipal): boolean; }
export interface ProtectionFundRecoveryAuthority { getRecovery(recoveryRef: string): { readonly recoveryId: string; readonly recoveryVersion: string; readonly fundingRecordId: string; readonly status: "settled" | "pending" | "failed"; readonly amountKobo: number; readonly currency: "NGN"; readonly source: "operator_settlement" | "reserve_application" | "future_payout_offset" | "contractual_recovery" }; }
export interface ProtectionFundRemedyAuthorityProvider { getRemedy(input: { readonly remedyCaseId: string }): { readonly caseVersion: number; readonly reservationId: string; readonly incidentId: string; readonly bookingId: string; readonly decisionId: string; readonly decisionVersion: string; readonly eligibilityId: string; readonly eligibilityVersion: string; readonly approvalVersion: string; readonly approvalTier: string; readonly fundingVersion: string; readonly liabilityVersion: string; readonly fundingSource: "guest_protection_fund" | "platform_capital" | "original_payment_source" | "unresolved"; readonly requiredAmountKobo: number; readonly operatorLiabilityKobo: number; readonly platformExposureKobo: number; }; }
export interface ProtectionFundApplicationOptions { readonly accounting: ProtectionFundAccountingRepository; readonly metrics: ProtectionFundMetricsProvider; readonly capital: ProtectionFundCapitalProvider; readonly commissions: EarnedCommissionSource; readonly remedies: ProtectionFundRemedyAuthorityProvider; readonly recovery: ProtectionFundRecoveryAuthority; readonly financeAuthorization?: ProtectionFundFinanceAuthorization; readonly clock?: () => Date; readonly audit?: { record(entry: Record<string, unknown>): void }; }
const trusted = new Set<CommandPrincipal["role"]>(["system", "admin", "authorized_staff"]);
function requireBackend(p: CommandPrincipal): void { if (!trusted.has(p.role) || !p.id) throw Error("Trusted backend principal is required"); }
function amount(n: number): void { if (!Number.isInteger(n) || n < 0) throw Error("Invalid NGN amount"); }
export class ProtectionFundApplication {
  readonly #o: ProtectionFundApplicationOptions;
  constructor(options: ProtectionFundApplicationOptions) { this.#o=options; }
  #now(): string { return (this.#o.clock??(()=>new Date()))().toISOString(); }
  #metrics(){const m=this.#o.metrics.getMetrics(); if(!m.metricsVersion||Object.values(m).some((v)=>typeof v!=="string"&&!Number.isInteger(v as number)||typeof v==="number"&&(v as number)<0))throw Error("Malformed protection fund metrics"); return m;}
  getPolicySnapshot(){ const m=this.#metrics(); return Object.freeze({ policyVersion:PROTECTION_FUND_POLICY.policyVersion, metricsVersion:m.metricsVersion, requiredSeedCapitalKobo:calculateRequiredSeedCapital(PROTECTION_FUND_POLICY,m), currentTargetBalanceKobo:calculateTargetBalance(PROTECTION_FUND_POLICY,m), metrics:m }); }
  seed(principal: CommandPrincipal){requireBackend(principal);const m=this.#metrics();const required=calculateRequiredSeedCapital(PROTECTION_FUND_POLICY,m);const allocation=this.#o.capital.allocateOrGet({seedId:`gpf-seed:${PROTECTION_FUND_POLICY.policyVersion}`,requiredAmountKobo:required,policyVersion:PROTECTION_FUND_POLICY.policyVersion,metricsVersion:m.metricsVersion,currency:"NGN"});if(allocation.status!=="settled"||allocation.amountKobo!==required||allocation.currency!=="NGN")return {status:"not_seeded" as const,requiredAmountKobo:required,providerStatus:allocation.status};createPlatformCommandEnvelope({commandName:"protection_fund.seed",principal,payload:{seedId:`gpf-seed:${PROTECTION_FUND_POLICY.policyVersion}`},idempotencyKey:`gpf-seed:${PROTECTION_FUND_POLICY.policyVersion}`});const result=this.#o.accounting.seed({seedId:`gpf-seed:${PROTECTION_FUND_POLICY.policyVersion}`,amountKobo:required,journal:protectionFundJournal({correlation:{fundingId:allocation.allocationId},lines:[{account:"gpf_available_balance",side:"debit",amountKobo:required,currency:"NGN"},{account:"platform_seed_capital",side:"credit",amountKobo:required,currency:"NGN"}],createdAt:this.#now()})});this.#o.audit?.record({type:"protection_fund.seeded",seedId:result.seedId,amountKobo:result.amountKobo,fundVersion:result.fundVersion,policyVersion:PROTECTION_FUND_POLICY.policyVersion});return {status:"seeded" as const,record:result};}
  contribute(releaseId:string, principal:CommandPrincipal){requireBackend(principal);const earned=this.#o.commissions.getEarnedCommission(releaseId);if(!earned||earned.currency!=="NGN"||!Number.isInteger(earned.earnedCommissionKobo)||earned.earnedCommissionKobo<0)return {status:"not_earned" as const};const contributionId=`gpf-contribution:${earned.recordId}`;const existing=this.#o.accounting.snapshot().contributions.find(x=>x.contributionId===contributionId);if(existing)return {status:"contributed" as const,record:existing};const m=this.#metrics();const before=this.#o.accounting.snapshot().availableBalanceKobo;const target=calculateTargetBalance(PROTECTION_FUND_POLICY,m);const rate=calculateContributionRate({availableBalanceKobo:before,targetBalanceKobo:target});const contributionKobo=Math.floor(earned.earnedCommissionKobo*rate);createPlatformCommandEnvelope({commandName:"protection_fund.contribute-earned-commission",principal,payload:{releaseId},idempotencyKey:contributionId});const record=this.#o.accounting.contribute({contributionId,record:{contributionId,releaseId:earned.releaseId,reservationId:earned.reservationId,earnedCommissionRecordId:earned.recordId,policyVersion:PROTECTION_FUND_POLICY.policyVersion,metricsVersion:m.metricsVersion,targetBalanceKobo:target,availableBalanceBeforeKobo:before,contributionRate:rate,earnedCommissionKobo:earned.earnedCommissionKobo,contributionKobo},journal:protectionFundJournal({correlation:{fundingId:contributionId,bookingId:earned.reservationId},lines:[{account:"gpf_available_balance",side:"debit",amountKobo:contributionKobo,currency:"NGN"},{account:"earned_commission_allocated_to_gpf",side:"credit",amountKobo:contributionKobo,currency:"NGN"}],createdAt:this.#now()})});return {status:"contributed" as const,record};}
  reserve(remedyCaseId:string, principal:CommandPrincipal){requireBackend(principal);const c=this.#o.remedies.getRemedy({remedyCaseId});if(c.fundingSource!=="guest_protection_fund")return {status:"not_gpf" as const};amount(c.requiredAmountKobo);if(c.operatorLiabilityKobo>c.requiredAmountKobo||c.platformExposureKobo>c.requiredAmountKobo)throw Error("Malformed liability");const id=`gpf-funding:${c.reservationId}`;createPlatformCommandEnvelope({commandName:"protection_fund.reserve-remedy",principal,payload:{remedyCaseId},idempotencyKey:id});const record:RemedyFundingRecord={fundingRecordId:id,reservationId:c.reservationId,remedyCaseId,caseVersion:c.caseVersion,incidentId:c.incidentId,bookingId:c.bookingId,decisionId:c.decisionId,decisionVersion:c.decisionVersion,eligibilityId:c.eligibilityId,eligibilityVersion:c.eligibilityVersion,approvalVersion:c.approvalVersion,approvalTier:c.approvalTier,fundingVersion:c.fundingVersion,liabilityVersion:c.liabilityVersion,requiredAmountKobo:c.requiredAmountKobo,reservedAmountKobo:0,settledAmountKobo:0,operatorLiabilityKobo:c.operatorLiabilityKobo,platformExposureKobo:c.platformExposureKobo,fundingSource:"guest_protection_fund",status:"reserved"};return this.#o.accounting.reserve({reservationId:c.reservationId,amountKobo:c.requiredAmountKobo,record,journal:protectionFundJournal({correlation:{incidentId:c.incidentId,bookingId:c.bookingId,decisionId:c.decisionId,fundingId:id,reservationId:c.reservationId},lines:[{account:"gpf_committed_remedy",side:"debit",amountKobo:c.requiredAmountKobo,currency:"NGN"},{account:"gpf_available_balance",side:"credit",amountKobo:c.requiredAmountKobo,currency:"NGN"}],createdAt:this.#now()})});}
  settle(fundingRecordId:string,replacementBookingReference:string,principal:CommandPrincipal){requireBackend(principal);createPlatformCommandEnvelope({commandName:"protection_fund.settle-remedy",principal,payload:{fundingRecordId,replacementBookingReference},idempotencyKey:`gpf-settle:${fundingRecordId}`});const prior=this.#o.accounting.snapshot().remedies.find(x=>x.fundingRecordId===fundingRecordId);if(!prior)throw Error("Funding record not found");const record={...prior,replacementBookingReference,settledAmountKobo:prior.reservedAmountKobo,status:"settled" as const};const recoverable=prior.operatorLiabilityKobo;return this.#o.accounting.settle({fundingRecordId,record,journal:protectionFundJournal({correlation:{incidentId:prior.incidentId,bookingId:prior.bookingId,decisionId:prior.decisionId,fundingId:fundingRecordId,reservationId:prior.reservationId},lines:[{account:"gpf_remedy_expense",side:"debit",amountKobo:prior.reservedAmountKobo,currency:"NGN"},{account:"gpf_committed_remedy",side:"credit",amountKobo:prior.reservedAmountKobo-recoverable,currency:"NGN"},{account:"operator_liability_receivable",side:"credit",amountKobo:recoverable,currency:"NGN"}],createdAt:this.#now()})});}
  release(fundingRecordId:string,principal:CommandPrincipal){requireBackend(principal);const prior=this.#o.accounting.snapshot().remedies.find(x=>x.fundingRecordId===fundingRecordId);if(!prior||prior.status!=="reserved")return prior;createPlatformCommandEnvelope({commandName:"protection_fund.release-remedy-reservation",principal,payload:{fundingRecordId},idempotencyKey:`gpf-release:${fundingRecordId}`});return this.#o.accounting.release({fundingRecordId,journal:protectionFundJournal({correlation:{incidentId:prior.incidentId,bookingId:prior.bookingId,decisionId:prior.decisionId,fundingId:fundingRecordId,reservationId:prior.reservationId},lines:[{account:"gpf_available_balance",side:"debit",amountKobo:prior.reservedAmountKobo,currency:"NGN"},{account:"gpf_committed_remedy",side:"credit",amountKobo:prior.reservedAmountKobo,currency:"NGN"}],createdAt:this.#now()})});}
  recover(recoveryRef:string,principal:CommandPrincipal){requireBackend(principal);const r=this.#o.recovery.getRecovery(recoveryRef);if(r.status!=="settled"||r.currency!=="NGN")return {status:"not_posted" as const};createPlatformCommandEnvelope({commandName:"protection_fund.record-recovery",principal,payload:{recoveryRef},idempotencyKey:`gpf-recovery:${r.recoveryId}:${r.recoveryVersion}`});const target=this.#o.accounting.snapshot().remedies.find(x=>x.fundingRecordId===r.fundingRecordId);if(!target)throw Error("Funding record not found");return this.#o.accounting.recover({recoveryKey:`${r.recoveryId}:${r.recoveryVersion}`,fundingRecordId:r.fundingRecordId,amountKobo:r.amountKobo,journal:protectionFundJournal({correlation:{incidentId:target.incidentId,bookingId:target.bookingId,decisionId:target.decisionId,fundingId:r.fundingRecordId},lines:[{account:"gpf_available_balance",side:"debit",amountKobo:r.amountKobo,currency:"NGN"},{account:"operator_liability_receivable",side:"credit",amountKobo:r.amountKobo,currency:"NGN"}],createdAt:this.#now()})});}
  getSnapshot(principal:CommandPrincipal):ProtectionFundSnapshot { if(this.#o.financeAuthorization&&!this.#o.financeAuthorization.canView(principal))throw Error("Finance access denied");return this.#o.accounting.snapshot(); }
}
