import type { WebServerEventHandoff } from "@weaver/web";
import type { CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { RelocationApplication } from "./relocation-application.js";
import type { RelocationArtifact, RelocationAction } from "./relocation-artifact.js";
export const CHOOSE_REFUND_EVENT = "shortlet.relocation.choose-refund";
export const CHOOSE_CANDIDATE_EVENT = "shortlet.relocation.choose-candidate";
export type RelocationActionResult = { readonly ok: true; readonly artifact: RelocationArtifact } | { readonly ok: false; readonly code: "INVALID_CONTEXT" | "STALE_ACTION" | "ACTION_NOT_AUTHORIZED" | "UNSUPPORTED_ACTION"; readonly message: string };
const keys = ["artifactId","reservationId","caseId","expectedCaseVersion","expectedContractVersion","eligibilityVersion","remainingStayEconomicsVersion","relocationPolicyVersion","refundObligationVersion","projectionVersion"] as const;
function record(v: unknown): v is Record<string, unknown> { return !!v && typeof v === "object" && !Array.isArray(v); }
function str(v: unknown): v is string { return typeof v === "string" && v.length > 0; }
function int(v: unknown): v is number { return typeof v === "number" && Number.isInteger(v) && v >= 1; }
function parse(event: WebServerEventHandoff, candidate: boolean): RelocationAction | undefined { const value: unknown = event?.message?.action?.context; if (!record(value)) return undefined; const allowed = candidate ? [...keys,"candidateSetVersion","candidateId","candidateVersion","termsVersion","comparabilityVersion","transportQuoteVersion","approvalVersion","availabilityVersion"] : keys; if (Object.keys(value).length !== allowed.length || Object.keys(value).some((k) => !allowed.includes(k as never))) return undefined; for (const k of keys) if (!["expectedCaseVersion","expectedContractVersion"].includes(k) && !str(value[k])) return undefined; if (!int(value.expectedCaseVersion) || !int(value.expectedContractVersion)) return undefined; if (candidate && (!str(value.candidateSetVersion) || !str(value.candidateId) || !str(value.candidateVersion) || !str(value.termsVersion) || !str(value.comparabilityVersion) || !str(value.transportQuoteVersion) || !str(value.approvalVersion) || !str(value.availabilityVersion))) return undefined; return value as unknown as RelocationAction; }
export function resolveRelocationServerEvent(input: { event: WebServerEventHandoff; application: RelocationApplication; principal: CommandPrincipal }): RelocationActionResult { const name = input.event?.message?.action?.name; const candidate = name === CHOOSE_CANDIDATE_EVENT; if (name !== CHOOSE_REFUND_EVENT && !candidate) return { ok:false, code:"UNSUPPORTED_ACTION", message:"The action is not supported." }; const context = parse(input.event, candidate); if (!context) return { ok:false, code:"INVALID_CONTEXT", message:"The action context is invalid." }; try { const current = input.application.getArtifact(context.reservationId, input.principal); const advertised = current.actions.find((a) => a.type === (candidate ? "choose_relocation_candidate" : "choose_refund") && (!candidate || a.candidateId === context.candidateId)); if (!advertised) return { ok:false, code:"STALE_ACTION", message:"Refresh the current remedy." }; if (advertised.projectionVersion !== context.projectionVersion) return { ok:false, code:"STALE_ACTION", message:"The action is stale." }; return { ok:true, artifact: candidate ? input.application.chooseRelocation(context.reservationId, input.principal, context) : input.application.chooseRefund(context.reservationId, input.principal, context) }; } catch (error) { return { ok:false, code:error instanceof Error && error.message === "STALE_ACTION" ? "STALE_ACTION" : "ACTION_NOT_AUTHORIZED", message:"The action was rejected." }; } }
