import { createHash } from "node:crypto";
import type { BookingContract, Reservation } from "../../../domains/shortlet/src/card-payment.js";
import type { ProductionRevenueReleaseRecord, AuthoritativeRevenueEconomics } from "../../../domains/shortlet/src/revenue-release.js";
import type { RevenueAdjustmentRecord } from "../../../domains/shortlet/src/revenue-accounting.js";
import type { RevenueEligibilityEvaluation } from "./revenue-release-application.js";
export const REVENUE_RELEASE_ARTIFACT_KIND = "shortlet.revenue-release";
export const REVENUE_RELEASE_ARTIFACT_SCHEMA = "shortlet.revenue-release/v1";
export interface RevenueReleaseArtifact { readonly id: string; readonly kind: typeof REVENUE_RELEASE_ARTIFACT_KIND; readonly schema: typeof REVENUE_RELEASE_ARTIFACT_SCHEMA; readonly projectionVersion: string; readonly facts: Readonly<Record<string, unknown>>; readonly actions: readonly []; readonly sensitivity: "booking-sensitive"; }
export function revenueReleaseArtifact(input: { reservation: Reservation; contract: BookingContract; release: ProductionRevenueReleaseRecord | null; evaluation?: RevenueEligibilityEvaluation; adjustments: readonly RevenueAdjustmentRecord[] }): RevenueReleaseArtifact {
  const { reservation, contract, release, evaluation } = input; const id = `revenue-release:${reservation.reservationId}`;
  const adjustmentSummary = input.adjustments.map((a) => ({ adjustmentId: a.adjustmentId, adjustmentVersion: a.adjustmentVersion, source: a.source, reasonCode: a.reasonCode, journalId: a.journal.journalId }));
  let facts: Record<string, unknown>;
  if (release) {
    facts = { reservationId: release.reservationId, reservationStatus: reservation.status, contractVersion: release.contractVersion, accessVersion: release.accessVersion, accessStatus: release.accessStatus, verifiedAccessAt: release.verifiedAccessAt, protectionWindowStartsAt: release.protectionWindowStartsAt, protectionWindowEndsAt: release.protectionWindowEndsAt, status: "released", commissionBaseKobo: release.commissionBaseKobo, commissionRate: release.commissionRate, commissionKobo: release.commissionKobo, operatorNetKobo: release.operatorNetKobo, payoutPlan: release.payoutPlan, payoutPlanVersion: release.payoutPlanVersion, payableNowKobo: release.payableNowKobo, routineReserveTrancheKobo: release.routineReserveTrancheKobo, reserveReviewEligibleAt: release.reserveReviewEligibleAt, deferredPostStayKobo: release.deferredPostStayKobo, postStayPayableEligibleAt: release.postStayPayableEligibleAt, riskHoldVersion: release.riskHoldVersion, riskHoldKobo: release.riskHoldKobo, ledgerBalanced: true, ledgerJournalId: release.ledgerJournalId, adjustmentSummary, economicsVersion: release.economicsVersion, commissionPolicyVersion: release.commissionPolicyVersion, effectiveCheckoutVersion: release.effectiveCheckoutVersion };
  } else {
    const e = evaluation!; const economics = e.economics as AuthoritativeRevenueEconomics | undefined;
    facts = { reservationId: reservation.reservationId, reservationStatus: reservation.status, contractVersion: contract.contractVersion, ...(e.access?.version ? { accessVersion: e.access.version } : {}), ...(e.access?.status ? { accessStatus: e.access.status } : {}), ...(e.access?.verifiedAt ? { verifiedAccessAt: e.access.verifiedAt } : {}), ...(e.protectionWindowStartsAt ? { protectionWindowStartsAt: e.protectionWindowStartsAt, protectionWindowEndsAt: e.protectionWindowEndsAt } : {}), status: e.status, blockerReasonCodes: e.blockerReasonCodes, ...(economics ? { commissionBaseKobo: economics.commissionableOperatorRevenueKobo, commissionRate: economics.capturedCommissionRate, economicsVersion: economics.economicsVersion, commissionPolicyVersion: economics.commissionPolicyVersion } : {}), ...(e.plan ? { payoutPlan: e.plan.plan, payoutPlanVersion: e.plan.planVersion } : {}), ...(e.account ? { accountVersion: e.account.version, accountActive: e.account.active } : {}), ...(e.hold ? { holdVersion: e.hold.holdVersion } : {}), ...(e.risk ? { riskHoldVersion: e.risk.version, riskHoldKobo: e.risk.amountKobo } : {}), ...(e.checkout ? { effectiveCheckoutVersion: e.checkout.version } : {}), adjustmentSummary };
  }
  const projectionVersion = createHash("sha256").update(JSON.stringify(facts)).digest("hex"); return Object.freeze({ id, kind: REVENUE_RELEASE_ARTIFACT_KIND, schema: REVENUE_RELEASE_ARTIFACT_SCHEMA, projectionVersion, facts: Object.freeze(facts), actions: Object.freeze([]) as [], sensitivity: "booking-sensitive" as const });
}
