import { createHash } from "node:crypto";
import type { BookingContract, Reservation } from "../../../domains/shortlet/src/card-payment.js";
import type { AuthoritativeRevenueEconomics, ProductionRevenueReleaseRecord } from "../../../domains/shortlet/src/revenue-release.js";
import type { RevenueReleaseAccessProvider, RevenueReleaseHoldProvider, OperatorPaymentAccountProvider } from "./revenue-release-application.js";
export const REVENUE_RELEASE_ARTIFACT_KIND = "shortlet.revenue-release";
export const REVENUE_RELEASE_ARTIFACT_SCHEMA = "shortlet.revenue-release/v1";
export interface RevenueReleaseArtifact { readonly id: string; readonly kind: typeof REVENUE_RELEASE_ARTIFACT_KIND; readonly schema: typeof REVENUE_RELEASE_ARTIFACT_SCHEMA; readonly projectionVersion: string; readonly facts: Readonly<Record<string, unknown>>; readonly actions: readonly []; readonly sensitivity: "booking-sensitive"; }
export function revenueReleaseArtifact(input: { reservation: Reservation; contract: BookingContract; release: ProductionRevenueReleaseRecord | null; access: ReturnType<RevenueReleaseAccessProvider["getAccess"]>; plan: { plan: "fast_payout" | "full_post_stay"; planVersion: string }; account: ReturnType<OperatorPaymentAccountProvider["getStatus"]>; economics: AuthoritativeRevenueEconomics; hold: ReturnType<RevenueReleaseHoldProvider["getHold"]>; risk: { version: string; amountKobo: number }; checkoutVersion: string; adjustments: readonly string[] }): RevenueReleaseArtifact {
  const { reservation, contract, release, access, plan, account, economics, hold, risk } = input; const id = `revenue-release:${reservation.reservationId}`;
  const facts: Record<string, unknown> = { reservationId: reservation.reservationId, reservationStatus: reservation.status, contractVersion: contract.contractVersion, accessVersion: access.version, accessStatus: access.status, ...(access.verifiedAt ? { verifiedAccessAt: access.verifiedAt, protectionWindowEndsAt: new Date(new Date(access.verifiedAt).getTime() + 86400000).toISOString() } : {}), status: release ? "released" : access.status === "awaiting_access" ? "pending_protection_window" : "eligible", commissionBaseKobo: release?.commissionBaseKobo ?? economics.commissionableOperatorRevenueKobo, commissionRate: release?.commissionRate ?? economics.capturedCommissionRate, commissionKobo: release?.commissionKobo ?? 0, operatorNetKobo: release?.operatorNetKobo ?? 0, payoutPlan: release?.payoutPlan ?? plan.plan, payoutPlanVersion: release?.payoutPlanVersion ?? plan.planVersion, payableNowKobo: release?.payableNowKobo ?? 0, routineReserveTrancheKobo: release?.routineReserveTrancheKobo ?? 0, reserveReviewEligibleAt: release?.reserveReviewEligibleAt, deferredPostStayKobo: release?.deferredPostStayKobo ?? 0, postStayPayableEligibleAt: release?.postStayPayableEligibleAt, riskHoldVersion: release?.riskHoldVersion ?? risk.version, riskHoldKobo: release?.riskHoldKobo ?? risk.amountKobo, ledgerBalanced: release ? true : undefined, ledgerJournalId: release?.ledgerJournalId, adjustmentSummary: input.adjustments, holdVersion: hold.holdVersion, accountVersion: account.version, accountActive: account.active, economicsVersion: economics.economicsVersion, commissionPolicyVersion: economics.commissionPolicyVersion, effectiveCheckoutVersion: input.checkoutVersion };
  const projectionVersion = createHash("sha256").update(JSON.stringify(facts)).digest("hex"); return Object.freeze({ id, kind: REVENUE_RELEASE_ARTIFACT_KIND, schema: REVENUE_RELEASE_ARTIFACT_SCHEMA, projectionVersion, facts: Object.freeze(facts), actions: Object.freeze([]) as [], sensitivity: "booking-sensitive" as const });
}
