import { InMemoryBookingStateRepository } from "../../domains/shortlet/src/booking-state.js";
import { InMemoryDepositClaimRepository, type DepositClaimProductionRecord } from "../../domains/shortlet/src/deposit-claim.js";
import { InMemorySecurityDepositAccountingRepository } from "../../domains/shortlet/src/security-deposit-accounting.js";
import { DepositClaimApplication } from "../../apps/web/src/deposit-claim-application.js";
import type { BookingContract, Reservation } from "../../domains/shortlet/src/card-payment.js";
import { depositClaimArtifact } from "../../apps/web/src/deposit-claim-artifact.js";

const guest = { id: "guest-27", role: "guest" as const, tenantId: "tenant-27" };

export function setupIssue27AuthorityCase(options: { readonly newEvidence?: boolean } = {}) {
  const reservation: Reservation = { reservationId: "res-27", contractId: "contract-27", unitId: "unit-27", primaryGuestId: guest.id, dates: { checkIn: "2026-09-01", checkOut: "2026-09-02" }, status: "confirmed", confirmedAt: "2026-08-01T00:00:00.000Z" };
  const contract: BookingContract = { contractId: reservation.contractId, reservationId: reservation.reservationId, offerId: "offer-27", unitId: reservation.unitId, tenantId: guest.tenantId, parties: { primaryGuest: { id: guest.id, name: "Guest" }, operator: { id: "operator-27" } }, dates: { checkIn: "2026-09-01", checkOut: "2026-09-02", nights: 1 }, occupants: [{ name: "Guest" }], quote: {}, totalAmountDueNowKobo: 1, securityDeposit: { policyVersion: "deposit-v1", amountKobo: 2_000_000, currency: "NGN", collectionId: "security-deposit:offer-27", status: "held" }, policies: { cancellationPolicy: {}, guestConductRules: [] }, paymentDetails: { paymentMethod: "fresh_card", pspReference: "stay", amountKobo: 1, currency: "NGN", paidAt: "2026-08-01T00:00:00.000Z" }, createdAt: "2026-08-01T00:00:00.000Z", contractVersion: 1, checkout: { time: "11:00", timezone: "Africa/Lagos", source: "contractual" } };
  const accounting = new InMemorySecurityDepositAccountingRepository();
  const snapshot = { policyVersion: "deposit-v1", amountKobo: 2_000_000, currency: "NGN" as const } as never;
  accounting.createOrGet({ offerId: "offer-27", snapshot, paymentMethod: "fresh_card" }); accounting.recordCollection("security-deposit:offer-27", { providerReference: "deposit-source", collectedAt: "2026-08-01T00:00:00.000Z" }); accounting.bind("security-deposit:offer-27", { reservationId: reservation.reservationId, contractId: contract.contractId });
  const claim: DepositClaimProductionRecord = { claimId: "deposit-claim:res-27", reservationId: reservation.reservationId, contractId: contract.contractId, tenantId: guest.tenantId, operatorId: "operator-27", guestId: guest.id, policyVersion: "deposit-v1", claimPolicyVersion: "deposit-v1", evidenceVersion: "evidence-v1", depositAmountKobo: 2_000_000, claimedAmountKobo: 1_000_000, effectiveCheckoutIso: "2026-09-02T10:00:00.000Z", claimDeadlineIso: "2026-09-03T10:00:00.000Z", submittedAtIso: "2026-09-02T10:00:00.000Z", claimVersion: 1, status: "adjudicated", items: [], notification: { status: "delivered", notificationVersion: "claim-notice", deliveredAtIso: "2026-09-03T10:00:00.000Z", evidenceId: "claim-delivery" }, responseWindowStartIso: "2026-09-03T10:00:00.000Z", responseWindowEndIso: "2026-09-05T10:00:00.000Z", guestResponse: null, initialReservedOperatorAwardKobo: 1_000_000, initialApprovedAmountKobo: 1_000_000, approvedOperatorAwardKobo: 1_000_000, unapprovedRefundKobo: 1_000_000, adjudicationSnapshot: { decisionId: "decision-27", decisionVersion: "v1", claimId: "deposit-claim:res-27", claimVersion: 1, policyVersion: "deposit-v1", evidenceVersion: "evidence-v1", reviewerId: "human-27", reviewerAuthorityVersion: "authority-v1", approvedOperatorAwardKobo: 1_000_000, decidedAtIso: "2026-09-03T10:00:00.000Z", evaluations: [] }, finality: { finalityVersion: 1, status: "reserved", cause: null, finalizedAtIso: null, appealWindowStartsAt: null, appealWindowEndsAt: null }, history: [] };
  const claims = new InMemoryDepositClaimRepository(); claims.createIfAbsent(claim); accounting.allocateClaim({ reservationId: reservation.reservationId, claimId: claim.claimId, amountKobo: claim.claimedAmountKobo, expectedCollectionVersion: 3 });
  let now = new Date("2026-09-03T10:00:00.000Z"); const deliveryTimes = new Map<string, string | undefined>([["guest", "2026-09-03T10:00:00.000Z"], ["operator", "2026-09-03T10:00:00.000Z"]]); const handoffs: string[] = []; let evidenceCalls = 0; let appealDecisionCalls = 0; let appealReviewer = "appeal-human"; let payoutCalls = 0; let payoutStatus: "pending" | "settled" | "failed" | "reconciliation_required" = "pending"; const app = new DepositClaimApplication({ booking: new InMemoryBookingStateRepository({ contracts: [contract], reservations: [reservation] }), accounting, claims, terms: { getTerms: () => ({ reservationId: reservation.reservationId, checkoutDate: "2026-09-02", checkoutTime: "11:00", source: "contractual", termVersion: "term" }) }, evidence: { resolve: () => { throw new Error("unused") } }, policy: { validate: () => { throw new Error("unused") } }, notifications: { resolve: () => { throw new Error("unused") } }, refunds: { refundOrGet: (input) => ({ refundId: input.obligationId, status: "settled" as const, amountKobo: input.amountKobo, currency: "NGN" }) }, decisions: { get: () => { throw new Error("unused") } }, handoff: { request: ({ reservationId }) => { handoffs.push(reservationId); } }, decisionNotices: { resolve: (input) => deliveryTimes.get(input.party) ? ({ ...input, noticeVersion: "full-v1", status: "delivered" as const, deliveredAtIso: deliveryTimes.get(input.party), deliveryEvidenceId: "full-delivery" }) : ({ ...input, noticeVersion: "full-v1", status: "failed" as const }) }, appealEvidence: { validate: (input) => { evidenceCalls += 1; return { claimId: input.claimId, party: input.party, appealGround: input.appealGround, evidenceSetId: "appeal-evidence", evidenceVersion: "appeal-evidence-v1", valid: true, genuinelyNewMaterial: options.newEvidence !== false }; } }, appealDecisions: { get: (input) => { appealDecisionCalls += 1; return { appealDecisionId: "appeal-decision-27", appealDecisionVersion: "v1", appealId: input.appealId, appealVersion: 1, claimId: claim.claimId, currentClaimVersion: claims.findByClaimId(claim.claimId)!.claimVersion, originalDecisionId: "decision-27", originalDecisionVersion: "v1", policyVersion: "deposit-v1", evidenceVersion: "evidence-v1", reviewerId: appealReviewer, reviewerAuthorityVersion: "appeal-authority-v1", independent: true, conflictFree: true, assistedOriginalDecision: false, disposition: "reduce" as const, finalApprovedOperatorAwardKobo: 500_000, rationale: "Corrected calculation", valid: true }; } }, awardPayout: { payOrGet: (input) => { payoutCalls += 1; return { status: payoutStatus, payoutId: input.awardObligationId, amountKobo: input.amountKobo, currency: "NGN" as const }; } }, clock: () => now });
  return { app, claims, accounting, claimId: claim.claimId, setNow: (iso: string) => { now = new Date(iso); }, setDelivery: (party: "guest" | "operator", iso: string | undefined) => { deliveryTimes.set(party, iso); }, evidenceCalls: () => evidenceCalls, appealDecisionCalls: () => appealDecisionCalls, payoutCalls: () => payoutCalls, handoffs: () => handoffs.length, setPayoutStatus: (status: "pending" | "settled" | "failed" | "reconciliation_required") => { payoutStatus = status; }, setAppealReviewer: (id: string) => { appealReviewer = id; }, artifact: (party: "guest" | "operator") => depositClaimArtifact(app, "res-27", { id: party === "guest" ? "guest-27" : "operator-27", role: party, tenantId: "tenant-27" }) };
}
