import { createHash } from "node:crypto";
import type { PlatformCommandEnvelope, CommandPrincipal } from "../../../packages/platform-core/src/index.js";
import type { BookingContract } from "./card-payment.js";

export interface BookingAmendmentChanges { readonly dates?: { readonly checkIn: string; readonly checkOut: string }; readonly occupants?: readonly { readonly name: string }[]; readonly checkoutTime?: string; readonly primaryGuestId?: string; readonly lateFirstAccessTime?: string; }
export interface FinancialAdjustment { readonly type: "additional_collection" | "refund" | "none"; readonly amountKobo: number; readonly currency: "NGN"; }
export interface AmendmentQuote { readonly quoteId: string; readonly quoteVersion: string | number; readonly currency: "NGN"; readonly revisedAllInStayTotalKobo: number; readonly financialAdjustment: FinancialAdjustment; readonly policyVersions?: Readonly<Record<string, string>>; }
export interface AmendmentSettlement { readonly settlementId: string; readonly amendmentId: string; readonly contractId: string; readonly type: FinancialAdjustment["type"]; readonly amountKobo: number; readonly currency: "NGN"; readonly status: "settled" | "pending" | "failed"; readonly quoteId: string; readonly quoteVersion: string | number; readonly settledAt?: string; }
export interface LateAccessApproval { readonly approvalId: string; readonly approvalVersion: string; readonly approvedTime: string; readonly approved: true; }
export interface PendingAmendment { readonly amendmentId: string; readonly amendmentVersion: number; readonly contractId: string; readonly requestedBy: string; readonly changes: BookingAmendmentChanges; readonly financialAdjustment: FinancialAdjustment; readonly quote: AmendmentQuote; readonly originalContractVersion: number; readonly validationVersions: Readonly<Record<string, string>>; readonly completionDeadline?: string; readonly createdAt: string; readonly lateAccessApproval?: LateAccessApproval; status: "proposed" | "accepted" | "awaiting_financial_settlement" | "committed" | "rejected" | "expired"; lifecycleStatus: "proposed" | "accepted" | "awaiting_financial_settlement" | "committed" | "rejected" | "expired"; }
export interface BookingAmendmentResult { readonly amendmentId: string; readonly contractId: string; readonly previousVersion: number; readonly newVersion: number; readonly status: "committed"; readonly financialAdjustment: FinancialAdjustment; readonly updatedContract: BookingContract; }

interface AuthorityMarker { readonly valid: boolean; readonly version?: string; }
export interface BookingAmendmentDependencies {
 readonly contractRepository: { getContract(id: string): BookingContract; mutateContract(id: string, expectedVersion: number, mutation: (current: BookingContract) => BookingContract): BookingContract };
 readonly calendar: { getAuthoritativeAvailability(unitId: string, checkIn: string, checkOut: string): { isAvailable: boolean; version?: string }; hasSameDayCheckInOnDate?(unitId: string, date: string): boolean };
 readonly inspectionRepository: { isPassedAndValidThrough(unitId: string, checkout: string): AuthorityMarker };
 readonly authorityRepository: { isValidThrough(unitId: string, checkout: string): AuthorityMarker };
 readonly quoteProvider: { quote(input: { contract: BookingContract; changes: BookingAmendmentChanges; resultingDates: { checkIn: string; checkOut: string; nights: number } }): AmendmentQuote };
 readonly settlementProvider?: { settle(input: { amendmentId: string; contractId: string; adjustment: FinancialAdjustment; quote: AmendmentQuote; principal: { id: string } }): AmendmentSettlement };
 readonly lateAccessAuthority?: { approve(input: { contractId: string; requestedTime: string }): { approved: boolean; approvalId?: string; approvedTime?: string; version?: string }; validate?(input: { contractId: string; requestedTime: string; approval: LateAccessApproval }): boolean };
 readonly lateCheckoutAuthority?: { validate(input: { contract: BookingContract; requestedTime: "12:00" | "13:00" | "14:00" }): AuthorityMarker };
 readonly audit?: { record(entry: Record<string, unknown>): void };
 readonly maxOccupants?: number;
}
function dateOnly(value: string): number { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return NaN; const n = Date.parse(`${value}T00:00:00Z`); return Number.isFinite(n) ? n : NaN; }
function nightsBetween(a: string, b: string): number { return (dateOnly(b) - dateOnly(a)) / 86400000; }
function lagosTimestamp(date: string, time: string): number { const [h, m] = time.split(":").map(Number); return Date.UTC(Number(date.slice(0, 4)), Number(date.slice(5, 7)) - 1, Number(date.slice(8, 10)), h - 1, m); }
function authorized(contract: BookingContract, principal: CommandPrincipal): boolean { return principal.role === "guest" && !!principal.id && principal.id === contract.parties.primaryGuest.id && !!contract.tenantId && !!principal.tenantId && principal.tenantId === contract.tenantId; }
function stableId(input: string): string { return createHash("sha256").update(input).digest("hex").slice(0, 20); }
function isLateAccess(changes: BookingAmendmentChanges): boolean { const time = changes.lateFirstAccessTime; if (!time) return false; const [h, m] = time.split(":").map(Number); return h > 22 || (h === 22 && m > 0); }

export class BookingAmendmentManager {
 readonly #deps: BookingAmendmentDependencies; readonly #pending = new Map<string, PendingAmendment>(); readonly #versions = new Map<string, number>();
 constructor(deps: BookingAmendmentDependencies) { if (!deps.contractRepository?.mutateContract) throw new Error("atomic mutateContract is required for BookingAmendmentManager"); if (!deps.quoteProvider) throw new Error("quoteProvider is required for BookingAmendmentManager"); this.#deps = deps; }
 #contract(id: string, principal: CommandPrincipal): BookingContract { let contract: BookingContract; try { contract = this.#deps.contractRepository.getContract(id); } catch { throw new Error("Booking amendment is not authorized"); } if (!authorized(contract, principal)) throw new Error("Booking amendment is not authorized"); return contract; }
 #validate(p: PendingAmendment, contract: BookingContract): { quote: AmendmentQuote; versions: Readonly<Record<string, string>> } {
  if (contract.contractVersion !== p.originalContractVersion) throw new Error("STALE_ACTION");
  const checkIn = p.changes.dates?.checkIn ?? contract.dates.checkIn, checkOut = p.changes.dates?.checkOut ?? contract.dates.checkOut, nights = nightsBetween(checkIn, checkOut);
  if (!Number.isInteger(nights) || nights < 1 || nights > 14) throw new Error("STALE_ACTION");
  const availability = this.#deps.calendar.getAuthoritativeAvailability(contract.unitId, checkIn, checkOut); if (!availability.isAvailable) throw new Error("STALE_ACTION");
  const inspection = this.#deps.inspectionRepository.isPassedAndValidThrough(contract.unitId, checkOut); if (!inspection.valid) throw new Error("STALE_ACTION");
  const authority = this.#deps.authorityRepository.isValidThrough(contract.unitId, checkOut); if (!authority.valid) throw new Error("STALE_ACTION");
  if (p.changes.occupants) { if (!p.changes.occupants.length || p.changes.occupants.some((o) => !o.name.trim()) || !p.changes.occupants.some((o) => o.name === contract.parties.primaryGuest.name) || p.changes.occupants.length > (this.#deps.maxOccupants ?? 10)) throw new Error("STALE_ACTION"); }
  if (p.changes.checkoutTime && p.changes.checkoutTime !== "11:00") { if (this.#deps.calendar.hasSameDayCheckInOnDate?.(contract.unitId, checkOut)) throw new Error("STALE_ACTION"); const result = this.#deps.lateCheckoutAuthority?.validate({ contract, requestedTime: p.changes.checkoutTime as "12:00" | "13:00" | "14:00" }); if (!result?.valid) throw new Error("STALE_ACTION"); }
  if (isLateAccess(p.changes)) { const approval = p.lateAccessApproval; if (!approval || !this.#deps.lateAccessAuthority) throw new Error("STALE_ACTION"); const valid = this.#deps.lateAccessAuthority.validate ? this.#deps.lateAccessAuthority.validate({ contractId: p.contractId, requestedTime: p.changes.lateFirstAccessTime!, approval }) : (() => { const current = this.#deps.lateAccessAuthority.approve({ contractId: p.contractId, requestedTime: p.changes.lateFirstAccessTime! }); return current.approved === true && current.approvalId === approval.approvalId && String(current.version) === approval.approvalVersion; })(); if (!valid) throw new Error("STALE_ACTION"); }
  const quote = this.#deps.quoteProvider.quote({ contract, changes: p.changes, resultingDates: { checkIn, checkOut, nights } });
  if (quote.quoteId !== p.quote.quoteId || String(quote.quoteVersion) !== String(p.quote.quoteVersion) || quote.revisedAllInStayTotalKobo !== p.quote.revisedAllInStayTotalKobo || JSON.stringify(quote.financialAdjustment) !== JSON.stringify(p.financialAdjustment) || quote.currency !== p.quote.currency) throw new Error("STALE_ACTION");
  const versions = Object.freeze({ contract: String(contract.contractVersion), availability: availability.version ?? "", inspection: inspection.version ?? "", authority: authority.version ?? "", quote: String(quote.quoteVersion), ...(quote.policyVersions ?? {}) }); if (Object.keys(p.validationVersions).length && Object.keys(versions).some((key) => versions[key as keyof typeof versions] !== p.validationVersions[key])) throw new Error("STALE_ACTION"); return { quote, versions };
 }
 requestAmendment(envelope: PlatformCommandEnvelope<{ contractId: string; changes: BookingAmendmentChanges }>, clock: () => Date = () => new Date()): PendingAmendment {
  if (!envelope || envelope.commandName !== "booking_amendment.request") throw new Error("Invalid envelope: commandName must be 'booking_amendment.request'"); const { contractId, changes } = envelope.payload; const allowed = new Set(["dates", "occupants", "checkoutTime", "lateFirstAccessTime", "primaryGuestId"]); if (!changes || typeof changes !== "object" || Object.keys(changes).some((key) => !allowed.has(key))) throw new Error("Unsupported amendment input"); const contract = this.#contract(contractId, envelope.principal); if (changes.primaryGuestId !== undefined) throw new Error("Primary Guest replacement is prohibited"); const now = clock(); const checkIn = changes.dates?.checkIn ?? contract.dates.checkIn, checkOut = changes.dates?.checkOut ?? contract.dates.checkOut, n = nightsBetween(checkIn, checkOut); if (!Number.isInteger(n) || n <= 0) throw new Error("Stay dates must be valid and checkout must be after check-in"); if (n > 14) throw new Error("Stay length exceeds the maximum launch limit of 14 nights"); const horizon = dateOnly(now.toLocaleDateString("en-CA", { timeZone: "Africa/Lagos" })) + 90 * 86400000; if (dateOnly(checkIn) > horizon) throw new Error("Check-in date exceeds the 90-day booking horizon"); if (changes.dates?.checkIn && changes.dates.checkIn !== contract.dates.checkIn && now.getTime() > lagosTimestamp(contract.dates.checkIn, "14:00") - 86400000) throw new Error("Date changes must begin at least 24 hours before check-in"); const extension = dateOnly(checkOut) > dateOnly(contract.dates.checkOut); if (extension && now.getTime() > lagosTimestamp(contract.dates.checkOut, "18:00") - 86400000) throw new Error("Extension request must begin by 6:00 PM (18:00 WAT) the day before checkout"); if (changes.checkoutTime && !["11:00", "12:00", "13:00", "14:00"].includes(changes.checkoutTime)) throw new Error("Late checkout cannot exceed 14:00 WAT"); if (changes.occupants && (!changes.occupants.length || !changes.occupants.some((o) => o.name === contract.parties.primaryGuest.name))) throw new Error("Primary Guest must remain an occupant");
  let lateAccessApproval: LateAccessApproval | undefined; if (isLateAccess(changes)) { const result = this.#deps.lateAccessAuthority?.approve({ contractId, requestedTime: changes.lateFirstAccessTime! }); if (!result?.approved || !result.approvalId || !result.version || !result.approvedTime) throw new Error("Late first access after 22:00 WAT is a human-approved exception only"); lateAccessApproval = { approvalId: result.approvalId, approvalVersion: String(result.version), approvedTime: result.approvedTime, approved: true }; }
  const quote = this.#deps.quoteProvider.quote({ contract, changes, resultingDates: { checkIn, checkOut, nights: n } }); if (!Number.isInteger(quote.revisedAllInStayTotalKobo) || quote.revisedAllInStayTotalKobo < 0) throw new Error("Authoritative quote is invalid");
  const version = (this.#versions.get(contractId) ?? 0) + 1; this.#versions.set(contractId, version); const amendmentId = `amendment:${contractId}:${version}:${stableId(JSON.stringify({ changes, quote: quote.quoteId }))}`; const draft: PendingAmendment = { amendmentId, amendmentVersion: version, contractId, requestedBy: envelope.principal.id, changes, financialAdjustment: quote.financialAdjustment, quote, originalContractVersion: contract.contractVersion, validationVersions: Object.freeze({}), createdAt: now.toISOString(), status: "proposed", lifecycleStatus: "proposed", ...(lateAccessApproval ? { lateAccessApproval } : {}), ...(extension ? { completionDeadline: new Date(lagosTimestamp(contract.dates.checkOut, "20:00") - 86400000).toISOString() } : {}) }; const validated = this.#validate(draft, contract); const pending: PendingAmendment = { ...draft, validationVersions: validated.versions }; this.#pending.set(amendmentId, pending); this.#deps.audit?.record({ type: "booking_amendment.proposed", amendmentId, contractId, originalContractVersion: contract.contractVersion, amendmentVersion: version, quoteId: quote.quoteId, quoteVersion: quote.quoteVersion, financialAdjustment: quote.financialAdjustment }); return pending;
 }
 acceptAmendment(amendmentId: string, principal: CommandPrincipal, clock: () => Date = () => new Date()): PendingAmendment { const p = this.#pending.get(amendmentId); if (!p || p.status !== "proposed") throw new Error("STALE_ACTION"); const c = this.#contract(p.contractId, principal); this.#validate(p, c); p.status = "accepted"; p.lifecycleStatus = "accepted"; if (p.financialAdjustment.type !== "none") { p.status = "awaiting_financial_settlement"; p.lifecycleStatus = "awaiting_financial_settlement"; } this.#deps.audit?.record({ type: "booking_amendment.accepted", amendmentId, contractId: p.contractId, oldContractVersion: c.contractVersion, trustedActorId: principal.id, serverTimestamp: clock().toISOString() }); return { ...p }; }
 commitAmendment(envelope: PlatformCommandEnvelope<{ amendmentId: string }>, clock: () => Date = () => new Date()): BookingAmendmentResult { if (!envelope || envelope.commandName !== "booking_amendment.commit") throw new Error("Invalid envelope: commandName must be 'booking_amendment.commit'"); if (!envelope.payload || Object.keys(envelope.payload).length !== 1 || typeof envelope.payload.amendmentId !== "string") throw new Error("Invalid amendment commit payload"); const p = this.#pending.get(envelope.payload.amendmentId); if (!p || p.status === "committed" || p.status === "rejected") throw new Error("STALE_ACTION"); if (p.status === "proposed") throw new Error("Explicit guest acceptance is required"); if (!["system", "authorized_staff", "admin"].includes(envelope.principal.role) || !envelope.principal.id) throw new Error("Trusted backend principal required"); const c = this.#deps.contractRepository.getContract(p.contractId); const now = clock(); if (p.completionDeadline && now.getTime() > new Date(p.completionDeadline).getTime()) { p.status = "expired"; p.lifecycleStatus = "expired"; throw new Error("Amendment completion deadline has passed"); } this.#validate(p, c);
  let settlementId: string | undefined; if (p.financialAdjustment.type !== "none") { if (!this.#deps.settlementProvider) throw new Error("Trusted amendment settlement provider is required"); const s = this.#deps.settlementProvider.settle({ amendmentId: p.amendmentId, contractId: p.contractId, adjustment: p.financialAdjustment, quote: p.quote, principal: envelope.principal }); if (s.status !== "settled" || s.amendmentId !== p.amendmentId || s.contractId !== p.contractId || s.type !== p.financialAdjustment.type || s.amountKobo !== p.financialAdjustment.amountKobo || s.currency !== p.financialAdjustment.currency || s.quoteId !== p.quote.quoteId || String(s.quoteVersion) !== String(p.quote.quoteVersion)) { if (s.status === "pending") { p.status = "awaiting_financial_settlement"; p.lifecycleStatus = p.status; } else if (s.status === "failed") { p.status = "rejected"; p.lifecycleStatus = p.status; } throw new Error(s.status === "pending" ? "Authoritative amendment settlement is pending" : "Authoritative amendment settlement was not successful"); } settlementId = s.settlementId; }
  this.#validate(p, this.#deps.contractRepository.getContract(p.contractId)); const latest = this.#deps.contractRepository.getContract(p.contractId); const nextCheckIn = p.changes.dates?.checkIn ?? latest.dates.checkIn, nextCheckOut = p.changes.dates?.checkOut ?? latest.dates.checkOut; const nextQuote = { ...(latest.quote && typeof latest.quote === "object" ? latest.quote as Record<string, unknown> : {}), allInStayTotalKobo: p.quote.revisedAllInStayTotalKobo, currency: p.quote.currency }; const next: BookingContract = { ...latest, dates: { checkIn: nextCheckIn, checkOut: nextCheckOut, nights: nightsBetween(nextCheckIn, nextCheckOut) }, occupants: p.changes.occupants ? [...p.changes.occupants] : latest.occupants, checkout: p.changes.checkoutTime ? { time: p.changes.checkoutTime as "11:00" | "12:00" | "13:00" | "14:00", timezone: "Africa/Lagos", source: "checkout_amendment", amendmentId: p.amendmentId, amendmentVersion: p.amendmentVersion } : latest.checkout, quote: nextQuote, totalAmountDueNowKobo: p.quote.revisedAllInStayTotalKobo, contractVersion: latest.contractVersion + 1, financialSummary: { originalBookingTotalKobo: latest.financialSummary?.originalBookingTotalKobo ?? latest.totalAmountDueNowKobo, currentContractTotalKobo: p.quote.revisedAllInStayTotalKobo, currency: "NGN", amendmentAdjustments: [...(latest.financialSummary?.amendmentAdjustments ?? []), { amendmentId: p.amendmentId, type: p.financialAdjustment.type, amountKobo: p.financialAdjustment.amountKobo, currency: "NGN", ...(settlementId ? { settlementId, settledAt: now.toISOString() } : {}), quoteId: p.quote.quoteId, quoteVersion: p.quote.quoteVersion }] } }; const committed = this.#deps.contractRepository.mutateContract(latest.contractId, latest.contractVersion, () => next); p.status = "committed"; p.lifecycleStatus = "committed"; this.#deps.audit?.record({ type: "booking_amendment.committed", amendmentId: p.amendmentId, contractId: latest.contractId, oldContractVersion: latest.contractVersion, newContractVersion: committed.contractVersion, settlementId, committedAt: now.toISOString() }); return { amendmentId: p.amendmentId, contractId: p.contractId, previousVersion: latest.contractVersion, newVersion: committed.contractVersion, status: "committed", financialAdjustment: p.financialAdjustment, updatedContract: committed }; }
 getAmendment(id: string): PendingAmendment | undefined { const p = this.#pending.get(id); return p ? { ...p } : undefined; }
 getLatestForContract(contractId: string): PendingAmendment | undefined { return [...this.#pending.values()].filter((p) => p.contractId === contractId).sort((a, b) => b.amendmentVersion - a.amendmentVersion)[0]; }
 rejectInformalChatAlteration(_envelope: PlatformCommandEnvelope<{ chatMessage: string }>): { readonly rejected: true; readonly reason: string } { return { rejected: true, reason: "Informal chat messages or operator promises cannot alter contractual state" }; }
}
