import { createHash } from "node:crypto";

export const GPF_POLICY_VERSION = "gpf-v1.0-launch";
export interface ProtectionFundAccountingPolicy { readonly policyVersion: string; readonly minSeedCapitalKobo: number; readonly minTargetBalanceKobo: number; readonly contributionRateBeforeTarget: number; readonly contributionRateAfterTarget: number; }
export const PROTECTION_FUND_POLICY: ProtectionFundAccountingPolicy = Object.freeze({ policyVersion: GPF_POLICY_VERSION, minSeedCapitalKobo: 500_000_000, minTargetBalanceKobo: 1_000_000_000, contributionRateBeforeTarget: .10, contributionRateAfterTarget: .02 });
export interface ProtectionFundMetrics { readonly metricsVersion: string; readonly projectedP95NetRemedyExposureKobo: number; readonly projectedNext90DayGbvKobo: number; readonly trailing90DayGbvKobo: number; readonly trailingP95NetRemedyExposureKobo: number; }
export interface ProtectionFundMetricsProvider { getMetrics(): ProtectionFundMetrics; }
export interface ProtectionFundCapitalProvider { allocateOrGet(input: { readonly seedId: string; readonly requiredAmountKobo: number; readonly policyVersion: string; readonly metricsVersion: string; readonly currency: "NGN" }): { readonly allocationId: string; readonly allocationVersion: string; readonly status: "settled" | "pending" | "failed"; readonly amountKobo: number; readonly currency: "NGN" }; }
export interface FundJournalLine { readonly account: string; readonly side: "debit" | "credit"; readonly amountKobo: number; readonly currency: "NGN"; }
export interface ProtectionFundJournal { readonly journalId: string; readonly correlation: { readonly incidentId?: string; readonly bookingId?: string; readonly decisionId?: string; readonly fundingId?: string; readonly reservationId?: string; }; readonly lines: readonly FundJournalLine[]; readonly balanced: true; readonly createdAt: string; }
export interface ProtectionFundAccountingRepository { seed(input: { seedId: string; amountKobo: number; journal: ProtectionFundJournal }): SeedCapitalRecord; contribute(input: { contributionId: string; record: CommissionContributionRecord; journal: ProtectionFundJournal }): CommissionContributionRecord; reserve(input: { reservationId: string; amountKobo: number; record: RemedyFundingRecord; journal: ProtectionFundJournal }): ReserveResult; release(input: { fundingRecordId: string; journal: ProtectionFundJournal }): RemedyFundingRecord; settle(input: { fundingRecordId: string; record: RemedyFundingRecord; journal: ProtectionFundJournal }): RemedyFundingRecord; recover(input: { recoveryKey: string; amountKobo: number; fundingRecordId: string; journal: ProtectionFundJournal }): OperatorRecoveryRecord; snapshot(): ProtectionFundSnapshot; journals(): readonly ProtectionFundJournal[]; }
export interface SeedCapitalRecord { readonly seedId: string; readonly amountKobo: number; readonly fundVersion: number; }
export interface CommissionContributionRecord { readonly contributionId: string; readonly releaseId: string; readonly reservationId: string; readonly earnedCommissionRecordId: string; readonly policyVersion: string; readonly metricsVersion: string; readonly targetBalanceKobo: number; readonly availableBalanceBeforeKobo: number; readonly contributionRate: number; readonly earnedCommissionKobo: number; readonly contributionKobo: number; readonly fundVersion?: number; }
export interface RemedyFundingRecord { readonly fundingRecordId: string; readonly reservationId: string; readonly remedyCaseId: string; readonly caseVersion: number; readonly incidentId: string; readonly bookingId: string; readonly decisionId: string; readonly decisionVersion: string; readonly eligibilityId: string; readonly eligibilityVersion: string; readonly approvalVersion: string; readonly approvalTier: string; readonly fundingVersion: string; readonly liabilityVersion: string; readonly requiredAmountKobo: number; readonly reservedAmountKobo: number; readonly settledAmountKobo: number; readonly operatorLiabilityKobo: number; readonly platformExposureKobo: number; readonly fundingSource: "guest_protection_fund"; readonly status: "reserved" | "settled" | "released" | "insufficient" | "reconciliation_required"; readonly replacementBookingReference?: string; readonly shortfallKobo?: number; readonly fundVersion?: number; }
export interface OperatorRecoveryRecord { readonly recoveryKey: string; readonly fundingRecordId: string; readonly amountKobo: number; readonly fundVersion: number; }
export interface ProtectionFundSnapshot { readonly fundVersion: number; readonly availableBalanceKobo: number; readonly committedBalanceKobo: number; readonly totalContributionKobo: number; readonly totalFundedRemediesKobo: number; readonly totalRecoveredKobo: number; readonly outstandingOperatorLiabilityKobo: number; readonly platformAbsorbedExposureKobo: number; readonly fundingShortfallKobo: number; readonly contributions: readonly CommissionContributionRecord[]; readonly remedies: readonly RemedyFundingRecord[]; readonly recoveries: readonly OperatorRecoveryRecord[]; }
export type ReserveResult = { readonly status: "reserved"; readonly record: RemedyFundingRecord } | { readonly status: "insufficient"; readonly shortfallKobo: number; readonly record: RemedyFundingRecord };
function validAmount(n: number): boolean { return Number.isInteger(n) && n >= 0; }
export function assertBalancedFundJournal(lines: readonly FundJournalLine[]): void { if (!lines.length || lines.some(l => !validAmount(l.amountKobo) || l.currency !== "NGN")) throw new Error("Invalid protection fund journal"); const d=lines.filter(l=>l.side==="debit").reduce((s,l)=>s+l.amountKobo,0); const c=lines.filter(l=>l.side==="credit").reduce((s,l)=>s+l.amountKobo,0); if(d!==c) throw new Error("Protection fund journal is unbalanced"); }
export function protectionFundJournal(input: { readonly correlation: ProtectionFundJournal["correlation"]; readonly lines: readonly FundJournalLine[]; readonly createdAt: string }): ProtectionFundJournal { assertBalancedFundJournal(input.lines); const journalId=`gpf-journal:${createHash("sha256").update(JSON.stringify(input)).digest("hex").slice(0,16)}`; return Object.freeze({ journalId, correlation: Object.freeze({...input.correlation}), lines: Object.freeze(input.lines.map(l=>Object.freeze({...l}))), balanced:true as const, createdAt:input.createdAt }); }
export function calculateRequiredSeedCapital(policy: ProtectionFundAccountingPolicy, metrics: ProtectionFundMetrics): number { return Math.max(policy.minSeedCapitalKobo, metrics.projectedP95NetRemedyExposureKobo*3, Math.floor(metrics.projectedNext90DayGbvKobo*.01)); }
export function calculateTargetBalance(policy: ProtectionFundAccountingPolicy, metrics: ProtectionFundMetrics): number { return Math.max(policy.minTargetBalanceKobo, Math.floor(metrics.trailing90DayGbvKobo*.01), metrics.trailingP95NetRemedyExposureKobo*3); }
export function calculateContributionRate(input: { readonly availableBalanceKobo: number; readonly targetBalanceKobo: number; readonly policy?: ProtectionFundAccountingPolicy }): number { const p=input.policy??PROTECTION_FUND_POLICY; return input.availableBalanceKobo < input.targetBalanceKobo ? p.contributionRateBeforeTarget : p.contributionRateAfterTarget; }
export class InMemoryProtectionFundAccountingRepository implements ProtectionFundAccountingRepository {
  #available=0; #committed=0; #version=0; readonly #seeds=new Map<string,SeedCapitalRecord>(); readonly #contributions=new Map<string,CommissionContributionRecord>(); readonly #remedies=new Map<string,RemedyFundingRecord>(); readonly #recoveries=new Map<string,OperatorRecoveryRecord>(); readonly #journals: ProtectionFundJournal[]=[];
  #post(j:ProtectionFundJournal, amount:number, direction:"in"|"out"){ if(amount<0||!validAmount(amount))throw Error("Invalid fund amount"); if(direction==="out"&&this.#available<amount)throw Error("Insufficient protection fund balance"); assertBalancedFundJournal(j.lines); this.#available += direction==="in"?amount:-amount; this.#version++; this.#journals.push(j); }
  seed(i:{seedId:string;amountKobo:number;journal:ProtectionFundJournal}){const e=this.#seeds.get(i.seedId);if(e)return e;this.#post(i.journal,i.amountKobo,"in");const r=Object.freeze({seedId:i.seedId,amountKobo:i.amountKobo,fundVersion:this.#version});this.#seeds.set(i.seedId,r);return r;}
  contribute(i:{contributionId:string;record:CommissionContributionRecord;journal:ProtectionFundJournal}){const e=this.#contributions.get(i.contributionId);if(e){if(JSON.stringify(e)!==JSON.stringify(i.record))throw Error("Contribution identity conflict");return e;}this.#post(i.journal,i.record.contributionKobo,"in");const r=Object.freeze({...i.record,fundVersion:this.#version});this.#contributions.set(i.contributionId,r);return r;}
  reserve(i:{reservationId:string;amountKobo:number;record:RemedyFundingRecord;journal:ProtectionFundJournal}):ReserveResult {const e=this.#remedies.get(i.reservationId);if(e&&e.status==="reserved")return {status:"reserved",record:e};if(this.#available<i.amountKobo){const r=Object.freeze({...i.record,status:"insufficient" as const,reservedAmountKobo:0,settledAmountKobo:0,shortfallKobo:i.amountKobo-this.#available});this.#remedies.set(i.reservationId,r);return {status:"insufficient",shortfallKobo:i.amountKobo-this.#available,record:r};}this.#post(i.journal,i.amountKobo,"out");const r=Object.freeze({...i.record,status:"reserved" as const,reservedAmountKobo:i.amountKobo,settledAmountKobo:0,fundVersion:this.#version});this.#committed+=i.amountKobo;this.#remedies.set(i.reservationId,r);return {status:"reserved",record:r};}
  release(i:{fundingRecordId:string;journal:ProtectionFundJournal}){const r=[...this.#remedies.values()].find(x=>x.fundingRecordId===i.fundingRecordId);if(!r||r.status==="released")return r??(()=>{throw Error("Funding record not found")})();if(r.status!=="reserved")return r;this.#post(i.journal,r.reservedAmountKobo,"in");this.#committed-=r.reservedAmountKobo;const n=Object.freeze({...r,status:"released" as const,reservedAmountKobo:0});this.#remedies.set(r.reservationId,n);return n;}
  settle(i:{fundingRecordId:string;record:RemedyFundingRecord;journal:ProtectionFundJournal}){const r=[...this.#remedies.values()].find(x=>x.fundingRecordId===i.fundingRecordId);if(r?.status==="settled")return r;if(!r||r.status!=="reserved")throw Error("Funding reservation is not open");this.#committed-=r.reservedAmountKobo;this.#journals.push(i.journal);assertBalancedFundJournal(i.journal.lines);this.#version++;const n=Object.freeze({...i.record,status:"settled" as const,reservedAmountKobo:0,settledAmountKobo:r.reservedAmountKobo,fundVersion:this.#version});this.#remedies.set(r.reservationId,n);return n;}
  recover(i:{recoveryKey:string;amountKobo:number;fundingRecordId:string;journal:ProtectionFundJournal}){const e=this.#recoveries.get(i.recoveryKey);if(e)return e;const r=[...this.#remedies.values()].find(x=>x.fundingRecordId===i.fundingRecordId);if(!r||i.amountKobo>r.operatorLiabilityKobo)throw Error("Recovery exceeds operator liability");const prior=[...this.#recoveries.values()].filter(x=>x.fundingRecordId===i.fundingRecordId).reduce((s,x)=>s+x.amountKobo,0);if(prior+i.amountKobo>r.operatorLiabilityKobo)throw Error("Recovery exceeds outstanding operator liability");this.#post(i.journal,i.amountKobo,"in");const x=Object.freeze({recoveryKey:i.recoveryKey,fundingRecordId:i.fundingRecordId,amountKobo:i.amountKobo,fundVersion:this.#version});this.#recoveries.set(i.recoveryKey,x);return x;}
  snapshot():ProtectionFundSnapshot{return Object.freeze({fundVersion:this.#version,availableBalanceKobo:this.#available,committedBalanceKobo:this.#committed,totalContributionKobo:[...this.#contributions.values()].reduce((s,x)=>s+x.contributionKobo,0),totalFundedRemediesKobo:[...this.#remedies.values()].reduce((s,x)=>s+x.settledAmountKobo,0),totalRecoveredKobo:[...this.#recoveries.values()].reduce((s,x)=>s+x.amountKobo,0),outstandingOperatorLiabilityKobo:[...this.#remedies.values()].reduce((s,x)=>s+Math.max(0,x.settledAmountKobo>0?x.operatorLiabilityKobo-[...this.#recoveries.values()].filter(y=>y.fundingRecordId===x.fundingRecordId).reduce((a,y)=>a+y.amountKobo,0):0),0),platformAbsorbedExposureKobo:[...this.#remedies.values()].reduce((s,x)=>s+x.platformExposureKobo,0),fundingShortfallKobo:[...this.#remedies.values()].reduce((s,x)=>s+(x.shortfallKobo??0),0),contributions:Object.freeze([...this.#contributions.values()]),remedies:Object.freeze([...this.#remedies.values()]),recoveries:Object.freeze([...this.#recoveries.values()])});}
  journals(){return Object.freeze([...this.#journals]);}
}
