export type RelocationTier = "routine" | "senior" | "executive";
export interface TrustedRelocationApproval { readonly approvalId: string; readonly personId: string; readonly authority: "routine_operations" | "senior_operations" | "finance" | "executive"; readonly valid: boolean; }
export interface RelocationApprovalDecision { readonly policyVersion: string; readonly approvalVersion: string; readonly tier: RelocationTier; readonly approved: boolean; readonly approvals: readonly TrustedRelocationApproval[]; readonly reason?: string; }
export interface RelocationFundingRoute { readonly fundingVersion: string; readonly source: "guest_protection_fund" | "platform_capital" | "original_payment_source" | "unresolved"; readonly status: "required" | "authorized" | "pending_accounting" | "unresolved"; }
export function relocationFundingRoute(input: { readonly failureActor: "operator" | "platform" | "guest" | "unknown"; readonly fundingVersion?: string }): RelocationFundingRoute { const version=input.fundingVersion??ISSUE_23_RELOCATION_POLICY.policyVersion; if(input.failureActor==="operator")return {fundingVersion:version,source:"guest_protection_fund",status:"pending_accounting"}; if(input.failureActor==="platform")return {fundingVersion:version,source:"platform_capital",status:"pending_accounting"}; return {fundingVersion:version,source:"unresolved",status:"unresolved"}; }
export interface RelocationApprovalPolicy { readonly policyVersion: string; readonly routinePriceRatio: number; readonly routineExposureKobo: number; readonly routineTransportKobo: number; readonly seniorPriceRatio: number; readonly seniorExposureKobo: number; readonly seniorTransportKobo: number; }
export const ISSUE_23_RELOCATION_POLICY: RelocationApprovalPolicy = Object.freeze({ policyVersion: "adr-0063-provisional-v1", routinePriceRatio: 0.25, routineExposureKobo: 15_000_000, routineTransportKobo: 5_000_000, seniorPriceRatio: 0.5, seniorExposureKobo: 50_000_000, seniorTransportKobo: 10_000_000 });
export function relocationTier(input: { readonly originalRemainingStayAccommodationKobo: number; readonly priceDiffKobo: number; readonly transportCostKobo: number; readonly policy?: RelocationApprovalPolicy }): RelocationTier { const p=input.policy??ISSUE_23_RELOCATION_POLICY; const ratio=input.originalRemainingStayAccommodationKobo>0?input.priceDiffKobo/input.originalRemainingStayAccommodationKobo:0; const exposure=input.priceDiffKobo+input.transportCostKobo; return ratio>p.seniorPriceRatio||exposure>p.seniorExposureKobo||input.transportCostKobo>p.seniorTransportKobo?"executive":ratio>p.routinePriceRatio||exposure>p.routineExposureKobo||input.transportCostKobo>p.routineTransportKobo?"senior":"routine"; }
export interface TrustedRelocationApprovalSource { getApprovals(input: { readonly reservationId: string; readonly candidateId: string }): readonly TrustedRelocationApproval[]; }
export class VersionedRelocationApprovalProvider {
  constructor(private readonly source: TrustedRelocationApprovalSource, private readonly policy: RelocationApprovalPolicy = ISSUE_23_RELOCATION_POLICY) {}
  getApprovalState(input: { readonly reservationId: string; readonly candidateId: string; readonly originalRemainingStayAccommodationKobo: number; readonly priceDiffKobo: number; readonly transportCostKobo: number; readonly policyVersion: string }): RelocationApprovalDecision {
    if (input.policyVersion !== this.policy.policyVersion) throw new Error("STALE_ACTION");
    return evaluateTrustedRelocationApproval({ ...input, approvals: this.source.getApprovals(input), policy: this.policy });
  }
}
export function evaluateTrustedRelocationApproval(input: { readonly originalRemainingStayAccommodationKobo: number; readonly priceDiffKobo: number; readonly transportCostKobo: number; readonly approvals: readonly TrustedRelocationApproval[]; readonly policy?: RelocationApprovalPolicy }): RelocationApprovalDecision { const p=input.policy??ISSUE_23_RELOCATION_POLICY; const tier=relocationTier(input); const valid=input.approvals.filter(a=>a.valid); const people=new Set(valid.map(a=>a.personId)); const has=(authority:TrustedRelocationApproval["authority"])=>valid.some(a=>a.authority===authority); const approved=tier==="routine"?has("routine_operations"):tier==="senior"?has("senior_operations")&&has("finance")&&valid.filter(a=>a.authority==="senior_operations"||a.authority==="finance").map(a=>a.personId).filter((x,i,all)=>all.indexOf(x)===i).length>=2:people.size>=2&&valid.filter(a=>a.authority==="executive").length>=2; return { policyVersion:p.policyVersion,approvalVersion:p.policyVersion,tier,approved,approvals:valid, ...(approved?{}:{reason:`Trusted ${tier} approval is incomplete`}) }; }
