import { createHash } from "node:crypto";
import type { SecurityDepositPolicySnapshot } from "./security-deposit.js";

export type SecurityDepositCollectionStatus = "awaiting_payment" | "collected_unbound" | "held" | "refund_pending" | "refunded" | "reconciliation_required";
export interface SecurityDepositJournalLine { readonly account: "security_deposit_payment_clearing" | "refundable_security_deposit_liability"; readonly side: "debit" | "credit"; readonly amountKobo: number; readonly currency: "NGN"; }
export interface SecurityDepositJournal { readonly journalId: string; readonly collectionId: string; readonly obligationId?: string; readonly lines: readonly SecurityDepositJournalLine[]; readonly balanced: true; readonly createdAt: string; }
export interface SecurityDepositCollectionRecord { readonly collectionId: string; readonly offerId: string; readonly reservationId?: string; readonly contractId?: string; readonly policyVersion: string; readonly amountKobo: number; readonly currency: "NGN"; readonly paymentMethod: "fresh_card" | "bank_transfer"; readonly providerReference?: string; readonly capabilityVersion?: string; readonly collectionVersion: number; readonly status: SecurityDepositCollectionStatus; readonly collectedAt?: string; readonly refundedAt?: string; readonly collectionJournalId?: string; readonly refundJournalId?: string; }
export interface HeldSecurityDeposit { readonly collectionId: string; readonly collectionVersion: number; readonly reservationId: string; readonly policyVersion: string; readonly amountKobo: number; readonly refundableBalanceKobo: number; readonly status: "held" | "refund_pending" | "refunded" | "reconciliation_required"; readonly currency: "NGN"; }
export interface SecurityDepositAllocationSummary { readonly originalCollectedKobo: number; readonly claimReservedKobo: number; readonly refundPendingKobo: number; readonly refundSettledKobo: number; readonly refundReconciliationKobo: number; readonly operatorAwardPaidKobo: number; readonly unallocatedHeldKobo: number; readonly remainingOperatorReserveKobo: number; readonly collectionId: string; }
export type RefundObligationStatus = "pending" | "settled" | "reconciliation_required";
export interface SecurityDepositRefundObligation { readonly obligationId: string; readonly collectionId: string; readonly claimId: string | null; readonly amountKobo: number; readonly status: RefundObligationStatus; readonly version: number; readonly journalId?: string; }
export type SecurityDepositAwardStatus = "reserved" | "internally_final" | "payout_pending" | "paid" | "failed" | "reconciliation_required" | "externally_disputed";
export interface SecurityDepositAwardObligation { readonly obligationId: string; readonly collectionId: string; readonly reservationId: string; readonly claimId: string; readonly operatorId: string; readonly tenantId: string; readonly amountKobo: number; readonly currency: "NGN"; readonly status: SecurityDepositAwardStatus; readonly version: number; readonly journalId?: string; }
export interface HeldSecurityDepositSource { getByReservationId(reservationId: string): HeldSecurityDeposit | null; }
function validAmount(n: number): boolean { return Number.isInteger(n) && n >= 0; }
export function createSecurityDepositJournal(input: { collectionId: string; amountKobo: number; direction: "collection" | "refund"; createdAt: string; obligationId?: string }): SecurityDepositJournal { if (!validAmount(input.amountKobo) || input.amountKobo === 0) throw new RangeError("Deposit journal amount must be a positive integer kobo amount"); const debit = input.direction === "collection" ? "security_deposit_payment_clearing" : "refundable_security_deposit_liability"; const credit = input.direction === "collection" ? "refundable_security_deposit_liability" : "security_deposit_payment_clearing"; const lines: readonly SecurityDepositJournalLine[] = Object.freeze([{ account: debit, side: "debit", amountKobo: input.amountKobo, currency: "NGN" }, { account: credit, side: "credit", amountKobo: input.amountKobo, currency: "NGN" }]); return Object.freeze({ journalId: `security-deposit-journal:${createHash("sha256").update(JSON.stringify(input)).digest("hex").slice(0, 24)}`, collectionId: input.collectionId, ...(input.obligationId ? { obligationId: input.obligationId } : {}), lines, balanced: true, createdAt: input.createdAt }); }
export interface SecurityDepositAccountingRepository extends HeldSecurityDepositSource {
  createOrGet(input: { offerId: string; snapshot: SecurityDepositPolicySnapshot; paymentMethod: "fresh_card" | "bank_transfer"; providerReference?: string; capabilityVersion?: string }): SecurityDepositCollectionRecord;
  recordCollection(collectionId: string, collectedAt: string): SecurityDepositCollectionRecord;
  recordCollection(collectionId: string, input: { providerReference: string; capabilityVersion?: string; collectedAt: string }): SecurityDepositCollectionRecord;
  bind(collectionId: string, input: { reservationId: string; contractId: string }): SecurityDepositCollectionRecord;
  refund(collectionId: string, input: { refundedAt: string; refundSucceeded: boolean }): SecurityDepositCollectionRecord;
  markRefundPending(collectionId: string): SecurityDepositCollectionRecord;
  getByOfferId(offerId: string): SecurityDepositCollectionRecord | null; getByCollectionId(collectionId: string): SecurityDepositCollectionRecord | null; journals(): readonly SecurityDepositJournal[];
  allocateClaim(input: { reservationId: string; claimId: string; amountKobo: number; expectedCollectionVersion: number }): { readonly claimId: string; readonly amountKobo: number; readonly collectionVersion: number };
  releaseClaim(input: { claimId: string; amountKobo: number }): SecurityDepositAllocationSummary;
  prepareClaimOutcome(input: { claimId: string; approvedReserveKobo: number; refundObligationId: string; refundAmountKobo: number }): SecurityDepositAllocationSummary;
  allocation(claimId: string): { readonly claimId: string; readonly reservationId: string; readonly amountKobo: number } | null;
  summary(reservationId: string): SecurityDepositAllocationSummary | null;
  ensureRefundObligation(input: { obligationId: string; reservationId: string; claimId: string | null; amountKobo: number }): SecurityDepositRefundObligation;
  markRefundResult(input: { obligationId: string; status: RefundObligationStatus; settledAt: string }): SecurityDepositRefundObligation;
  refundPartial(input: { claimId: string | null; obligationId: string; amountKobo: number; refundedAt: string; settled: boolean; failed?: boolean }): SecurityDepositRefundObligation;
  refundObligation(obligationId: string): SecurityDepositRefundObligation | null;
  ensureAwardObligation(input: { obligationId: string; reservationId: string; claimId: string; operatorId: string; tenantId: string; amountKobo: number }): SecurityDepositAwardObligation;
  markAwardStatus(input: { obligationId: string; status: SecurityDepositAwardStatus; settledAt: string }): SecurityDepositAwardObligation;
  awardObligation(obligationId: string): SecurityDepositAwardObligation | null;
  awardObligations(): readonly SecurityDepositAwardObligation[];
}
export class InMemorySecurityDepositAccountingRepository implements SecurityDepositAccountingRepository {
  readonly #records = new Map<string, SecurityDepositCollectionRecord>(); readonly #journals: SecurityDepositJournal[] = []; readonly #allocations = new Map<string, { reservationId: string; amountKobo: number }>(); readonly #refunds = new Map<string, SecurityDepositRefundObligation>(); readonly #awards = new Map<string, SecurityDepositAwardObligation>();
  createOrGet(input: { offerId: string; snapshot: SecurityDepositPolicySnapshot; paymentMethod: "fresh_card" | "bank_transfer"; providerReference?: string; capabilityVersion?: string }): SecurityDepositCollectionRecord { if (input.snapshot.amountKobo <= 0) throw new RangeError("Zero deposits have no collection record"); const id = `security-deposit:${input.offerId}`; const old = this.#records.get(id); if (old) { if (old.amountKobo !== input.snapshot.amountKobo || old.policyVersion !== input.snapshot.policyVersion || old.paymentMethod !== input.paymentMethod) throw new Error("Deposit collection identity conflict"); return old; } const record = Object.freeze({ collectionId: id, offerId: input.offerId, policyVersion: input.snapshot.policyVersion, amountKobo: input.snapshot.amountKobo, currency: "NGN" as const, paymentMethod: input.paymentMethod, ...(input.providerReference ? { providerReference: input.providerReference } : {}), ...(input.capabilityVersion ? { capabilityVersion: input.capabilityVersion } : {}), collectionVersion: 1, status: "awaiting_payment" as const }); this.#records.set(id, record); return record; }
  recordCollection(id: string, atOrInput: string | { providerReference: string; capabilityVersion?: string; collectedAt: string }): SecurityDepositCollectionRecord { const r = this.#required(id); const input: { providerReference?: string; capabilityVersion?: string; collectedAt: string } = typeof atOrInput === "string" ? { collectedAt: atOrInput, providerReference: r.providerReference } : atOrInput; if (r.status === "held" || r.status === "refunded") { if (input.providerReference && r.providerReference && input.providerReference !== r.providerReference) throw new Error("Deposit collection identity conflict"); return r; } if (r.status !== "awaiting_payment" && r.status !== "collected_unbound") throw new Error("Deposit collection is not collectible"); if (!input.providerReference) throw new Error("Successful deposit provider reference is required"); if (r.providerReference && r.providerReference !== input.providerReference) throw new Error("Deposit collection identity conflict"); if (r.status === "collected_unbound") return r; const journal = createSecurityDepositJournal({ collectionId: id, amountKobo: r.amountKobo, direction: "collection", createdAt: input.collectedAt }); this.#journals.push(journal); const next = Object.freeze({ ...r, providerReference: input.providerReference, ...(input.capabilityVersion ? { capabilityVersion: input.capabilityVersion } : {}), collectionVersion: r.collectionVersion + 1, status: "collected_unbound" as const, collectedAt: input.collectedAt, collectionJournalId: journal.journalId }); this.#records.set(id, next); return next; }
  bind(id: string, input: { reservationId: string; contractId: string }): SecurityDepositCollectionRecord { const r = this.#required(id); if (r.reservationId && (r.reservationId !== input.reservationId || r.contractId !== input.contractId)) throw new Error("Deposit collection binding identity conflict"); if (r.status !== "collected_unbound" && r.status !== "held") throw new Error("Deposit must be collected before binding"); const next = Object.freeze({ ...r, ...input, collectionVersion: r.status === "held" ? r.collectionVersion : r.collectionVersion + 1, status: "held" as const }); this.#records.set(id, next); return next; }
  markRefundPending(id: string): SecurityDepositCollectionRecord { const r = this.#required(id); if (r.status === "refunded" || r.status === "refund_pending") return r; if (r.status !== "held" && r.status !== "collected_unbound") throw new Error("Deposit is not refundable"); const next = Object.freeze({ ...r, collectionVersion: r.collectionVersion + 1, status: "refund_pending" as const }); this.#records.set(id, next); return next; }
  refund(id: string, input: { refundedAt: string; refundSucceeded: boolean }): SecurityDepositCollectionRecord { const r = this.#required(id); if (r.status === "awaiting_payment") throw new Error("Cannot refund an uncollected deposit"); if (r.status === "refunded" || (r.status === "reconciliation_required" && !input.refundSucceeded)) return r; if (!input.refundSucceeded) { const next = Object.freeze({ ...r, collectionVersion: r.collectionVersion + 1, status: "reconciliation_required" as const }); this.#records.set(id, next); return next; } if (!["held", "collected_unbound", "refund_pending", "reconciliation_required"].includes(r.status)) throw new Error("Deposit is not refundable"); const journal = createSecurityDepositJournal({ collectionId: id, amountKobo: r.amountKobo, direction: "refund", createdAt: input.refundedAt }); this.#journals.push(journal); const next = Object.freeze({ ...r, collectionVersion: r.collectionVersion + 1, status: "refunded" as const, refundedAt: input.refundedAt, refundJournalId: journal.journalId }); this.#records.set(id, next); return next; }
  getByOfferId(offerId: string): SecurityDepositCollectionRecord | null { return [...this.#records.values()].find((r) => r.offerId === offerId) ?? null; } getByCollectionId(id: string): SecurityDepositCollectionRecord | null { return this.#records.get(id) ?? null; }
  getByReservationId(reservationId: string): HeldSecurityDeposit | null { const r = [...this.#records.values()].find((x) => x.reservationId === reservationId); if (!r || !["held", "refund_pending", "refunded", "reconciliation_required"].includes(r.status)) return null; const summary = this.summary(reservationId); return Object.freeze({ collectionId: r.collectionId, collectionVersion: r.collectionVersion, reservationId, policyVersion: r.policyVersion, amountKobo: r.amountKobo, refundableBalanceKobo: r.status === "refunded" ? 0 : summary?.unallocatedHeldKobo ?? r.amountKobo, status: r.status as HeldSecurityDeposit["status"], currency: "NGN" }); }
  journals(): readonly SecurityDepositJournal[] { return Object.freeze([...this.#journals]); }
  allocateClaim(input: { reservationId: string; claimId: string; amountKobo: number; expectedCollectionVersion: number }): { readonly claimId: string; readonly amountKobo: number; readonly collectionVersion: number } { if (!Number.isInteger(input.amountKobo) || input.amountKobo <= 0) throw new Error("Claim reservation must be positive integer kobo"); const old = this.#allocations.get(input.claimId); if (old) { if (old.reservationId !== input.reservationId || old.amountKobo !== input.amountKobo) throw new Error("Claim reservation identity conflict"); const current = this.getByReservationId(input.reservationId); if (!current) throw new Error("Held deposit not found"); return { claimId: input.claimId, amountKobo: old.amountKobo, collectionVersion: current.collectionVersion }; } const current = this.getByReservationId(input.reservationId); if (!current || current.status !== "held" || current.collectionVersion !== input.expectedCollectionVersion) throw new Error("STALE_ACTION"); const summary = this.summary(input.reservationId); if (!summary || input.amountKobo > summary.unallocatedHeldKobo) throw new Error("Claim reservation exceeds held deposit"); this.#allocations.set(input.claimId, { reservationId: input.reservationId, amountKobo: input.amountKobo }); return { claimId: input.claimId, amountKobo: input.amountKobo, collectionVersion: current.collectionVersion }; }
  prepareClaimOutcome(input: { claimId: string; approvedReserveKobo: number; refundObligationId: string; refundAmountKobo: number }): SecurityDepositAllocationSummary { const allocation = this.#allocations.get(input.claimId); if (!allocation || !Number.isInteger(input.approvedReserveKobo) || input.approvedReserveKobo < 0 || input.approvedReserveKobo > allocation.amountKobo || !Number.isInteger(input.refundAmountKobo) || input.refundAmountKobo !== allocation.amountKobo - input.approvedReserveKobo) throw new Error("Invalid claim outcome"); const existing = this.#refunds.get(input.refundObligationId); if (existing) { if (existing.amountKobo !== input.refundAmountKobo || existing.claimId !== input.claimId) throw new Error("Refund identity conflict"); if (allocation.amountKobo !== input.approvedReserveKobo) throw new Error("Claim outcome conflict"); const summary = this.summary(allocation.reservationId); if (!summary) throw new Error("Held deposit not found"); return summary; } const before = allocation.amountKobo; this.#allocations.set(input.claimId, { ...allocation, amountKobo: input.approvedReserveKobo }); try { const obligation = this.ensureRefundObligation({ obligationId: input.refundObligationId, reservationId: allocation.reservationId, claimId: input.claimId, amountKobo: input.refundAmountKobo }); if (obligation.amountKobo !== input.refundAmountKobo) throw new Error("Refund identity conflict"); const summary = this.summary(allocation.reservationId); if (!summary) throw new Error("Held deposit not found"); return summary; } catch (error) { this.#allocations.set(input.claimId, { ...allocation, amountKobo: before }); throw error; } }
  releaseClaim(input: { claimId: string; amountKobo: number }): SecurityDepositAllocationSummary { const allocation = this.#allocations.get(input.claimId); if (!allocation || input.amountKobo < 0 || input.amountKobo > allocation.amountKobo) throw new Error("Claim release exceeds reservation"); if (input.amountKobo === 0) this.#allocations.delete(input.claimId); else this.#allocations.set(input.claimId, { ...allocation, amountKobo: input.amountKobo }); const result = this.summary(allocation.reservationId); if (!result) throw new Error("Held deposit not found"); return result; }
  allocation(claimId: string) { const a = this.#allocations.get(claimId); return a ? { claimId, ...a } : null; }
  summary(reservationId: string): SecurityDepositAllocationSummary | null { const r = [...this.#records.values()].find((x) => x.reservationId === reservationId); if (!r) return null; const allocations = [...this.#allocations.values()].filter((a) => a.reservationId === reservationId).reduce((s, a) => s + a.amountKobo, 0); const paidAwards = [...this.#awards.values()].filter((a) => a.reservationId === reservationId && a.status === "paid").reduce((s, a) => s + a.amountKobo, 0); const refunds = [...this.#refunds.values()].filter((x) => x.collectionId === r.collectionId); const pending = refunds.filter((x) => x.status === "pending").reduce((s, x) => s + x.amountKobo, 0); const settled = refunds.filter((x) => x.status === "settled").reduce((s, x) => s + x.amountKobo, 0); const reconciliation = refunds.filter((x) => x.status === "reconciliation_required").reduce((s, x) => s + x.amountKobo, 0); const claimReserved = allocations - paidAwards; const unallocated = r.amountKobo - claimReserved - pending - settled - reconciliation - paidAwards; if ([claimReserved, pending, settled, reconciliation, paidAwards, unallocated].some((n) => n < 0)) throw new Error("Security deposit accounting invariant failed"); return Object.freeze({ originalCollectedKobo: r.amountKobo, claimReservedKobo: claimReserved, refundPendingKobo: pending, refundSettledKobo: settled, refundReconciliationKobo: reconciliation, operatorAwardPaidKobo: paidAwards, unallocatedHeldKobo: unallocated, remainingOperatorReserveKobo: claimReserved, collectionId: r.collectionId }); }
  ensureRefundObligation(input: { obligationId: string; reservationId: string; claimId: string | null; amountKobo: number }): SecurityDepositRefundObligation { if (!Number.isInteger(input.amountKobo) || input.amountKobo <= 0) throw new Error("Refund obligation must be positive integer"); const collection = [...this.#records.values()].find((r) => r.reservationId === input.reservationId); if (!collection) throw new Error("Held deposit not found"); const old = this.#refunds.get(input.obligationId); if (old) { if (old.amountKobo !== input.amountKobo || old.collectionId !== collection.collectionId) throw new Error("Refund identity conflict"); return old; } const current = this.summary(input.reservationId); if (!current || input.amountKobo > current.unallocatedHeldKobo) throw new Error("Refund obligation exceeds available deposit"); const obligation = Object.freeze({ obligationId: input.obligationId, collectionId: collection.collectionId, claimId: input.claimId, amountKobo: input.amountKobo, status: "pending" as const, version: 1 }); this.#refunds.set(input.obligationId, obligation); return obligation; }
  markRefundResult(input: { obligationId: string; status: RefundObligationStatus; settledAt: string }): SecurityDepositRefundObligation { const old = this.#refunds.get(input.obligationId); if (!old) throw new Error("Refund obligation not found"); if (old.status === "settled") return old; if (old.status === "reconciliation_required") return old; if (input.status === "settled") { const journal = createSecurityDepositJournal({ collectionId: old.collectionId, obligationId: old.obligationId, amountKobo: old.amountKobo, direction: "refund", createdAt: input.settledAt }); this.#journals.push(journal); const next = Object.freeze({ ...old, status: "settled" as const, version: old.version + 1, journalId: journal.journalId }); this.#refunds.set(old.obligationId, next); if (old.claimId === null) { const collection = this.#records.get(old.collectionId); if (collection && old.amountKobo === collection.amountKobo) this.#records.set(old.collectionId, Object.freeze({ ...collection, status: "refunded" as const, collectionVersion: collection.collectionVersion + 1, refundedAt: input.settledAt, refundJournalId: journal.journalId })); } return next; } const next = Object.freeze({ ...old, status: input.status, version: old.version + 1 }); this.#refunds.set(old.obligationId, next); return next; }
  refundPartial(input: { claimId: string | null; obligationId: string; amountKobo: number; refundedAt: string; settled: boolean; failed?: boolean }): SecurityDepositRefundObligation { const old = this.ensureRefundObligation({ obligationId: input.obligationId, reservationId: input.claimId ? this.#allocations.get(input.claimId)?.reservationId ?? "" : "", claimId: input.claimId, amountKobo: input.amountKobo }); return this.markRefundResult({ obligationId: old.obligationId, status: input.failed ? "reconciliation_required" : input.settled ? "settled" : "pending", settledAt: input.refundedAt }); }
  refundObligation(id: string): SecurityDepositRefundObligation | null { return this.#refunds.get(id) ?? null; }
  ensureAwardObligation(input: { obligationId: string; reservationId: string; claimId: string; operatorId: string; tenantId: string; amountKobo: number }): SecurityDepositAwardObligation { if (!Number.isInteger(input.amountKobo) || input.amountKobo < 0) throw new Error("Award amount must be a non-negative integer"); const existing = this.#awards.get(input.obligationId); if (existing) { if (existing.amountKobo !== input.amountKobo || existing.claimId !== input.claimId || existing.tenantId !== input.tenantId) throw new Error("Award identity conflict"); return existing; } const allocation = this.#allocations.get(input.claimId); if (!allocation || allocation.reservationId !== input.reservationId || input.amountKobo > allocation.amountKobo) throw new Error("Award exceeds legitimate claim reserve"); const collection = [...this.#records.values()].find((r) => r.reservationId === input.reservationId); if (!collection) throw new Error("Held deposit not found"); const award = Object.freeze({ obligationId: input.obligationId, collectionId: collection.collectionId, reservationId: input.reservationId, claimId: input.claimId, operatorId: input.operatorId, tenantId: input.tenantId, amountKobo: input.amountKobo, currency: "NGN" as const, status: "reserved" as const, version: 1 }); this.#awards.set(input.obligationId, award); return award; }
  markAwardStatus(input: { obligationId: string; status: SecurityDepositAwardStatus; settledAt: string }): SecurityDepositAwardObligation { const old = this.#awards.get(input.obligationId); if (!old) throw new Error("Award obligation not found"); if (old.status === "paid" || old.status === "reconciliation_required" || old.status === "externally_disputed") return old; if (input.status === "paid") { const journal = createSecurityDepositJournal({ collectionId: old.collectionId, obligationId: old.obligationId, amountKobo: old.amountKobo, direction: "refund", createdAt: input.settledAt }); this.#journals.push(journal); const next = Object.freeze({ ...old, status: "paid" as const, version: old.version + 1, journalId: journal.journalId }); this.#awards.set(old.obligationId, next); return next; } const next = Object.freeze({ ...old, status: input.status, version: old.version + 1 }); this.#awards.set(old.obligationId, next); return next; }
  awardObligation(id: string): SecurityDepositAwardObligation | null { return this.#awards.get(id) ?? null; }
  awardObligations(): readonly SecurityDepositAwardObligation[] { return Object.freeze([...this.#awards.values()]); }
  #required(id: string): SecurityDepositCollectionRecord { const r = this.#records.get(id); if (!r) throw new Error("Security deposit collection not found"); return r; }
}
