import { createHash } from "node:crypto";
import type { SecurityDepositPolicySnapshot } from "./security-deposit.js";

export type SecurityDepositCollectionStatus = "awaiting_payment" | "collected_unbound" | "held" | "refund_pending" | "refunded" | "reconciliation_required";
export interface SecurityDepositJournalLine { readonly account: "security_deposit_payment_clearing" | "refundable_security_deposit_liability"; readonly side: "debit" | "credit"; readonly amountKobo: number; readonly currency: "NGN"; }
export interface SecurityDepositJournal { readonly journalId: string; readonly collectionId: string; readonly lines: readonly SecurityDepositJournalLine[]; readonly balanced: true; readonly createdAt: string; }
export interface SecurityDepositCollectionRecord { readonly collectionId: string; readonly offerId: string; readonly reservationId?: string; readonly contractId?: string; readonly policyVersion: string; readonly amountKobo: number; readonly currency: "NGN"; readonly paymentMethod: "fresh_card" | "bank_transfer"; readonly providerReference?: string; readonly capabilityVersion?: string; readonly collectionVersion: number; readonly status: SecurityDepositCollectionStatus; readonly collectedAt?: string; readonly refundedAt?: string; readonly collectionJournalId?: string; readonly refundJournalId?: string; }
export interface HeldSecurityDeposit { readonly collectionId: string; readonly collectionVersion: number; readonly reservationId: string; readonly policyVersion: string; readonly amountKobo: number; readonly refundableBalanceKobo: number; readonly status: "held" | "refunded" | "reconciliation_required"; readonly currency: "NGN"; }
export interface HeldSecurityDepositSource { getByReservationId(reservationId: string): HeldSecurityDeposit | null; }
function validAmount(n: number): boolean { return Number.isInteger(n) && n >= 0; }
export function createSecurityDepositJournal(input: { collectionId: string; amountKobo: number; direction: "collection" | "refund"; createdAt: string }): SecurityDepositJournal { if (!validAmount(input.amountKobo) || input.amountKobo === 0) throw new RangeError("Deposit journal amount must be a positive integer kobo amount"); const debit = input.direction === "collection" ? "security_deposit_payment_clearing" : "refundable_security_deposit_liability"; const credit = input.direction === "collection" ? "refundable_security_deposit_liability" : "security_deposit_payment_clearing"; const lines: readonly SecurityDepositJournalLine[] = Object.freeze([{ account: debit as SecurityDepositJournalLine["account"], side: "debit" as const, amountKobo: input.amountKobo, currency: "NGN" as const }, { account: credit as SecurityDepositJournalLine["account"], side: "credit" as const, amountKobo: input.amountKobo, currency: "NGN" as const }]); return Object.freeze({ journalId: `security-deposit-journal:${createHash("sha256").update(JSON.stringify(input)).digest("hex").slice(0, 24)}`, collectionId: input.collectionId, lines, balanced: true as const, createdAt: input.createdAt }); }
export interface SecurityDepositAccountingRepository extends HeldSecurityDepositSource { createOrGet(input: { offerId: string; snapshot: SecurityDepositPolicySnapshot; paymentMethod: "fresh_card" | "bank_transfer"; providerReference?: string; capabilityVersion?: string }): SecurityDepositCollectionRecord; recordCollection(collectionId: string, collectedAt: string): SecurityDepositCollectionRecord; recordCollection(collectionId: string, input: { providerReference: string; capabilityVersion?: string; collectedAt: string }): SecurityDepositCollectionRecord; bind(collectionId: string, input: { reservationId: string; contractId: string }): SecurityDepositCollectionRecord; refund(collectionId: string, input: { refundedAt: string; refundSucceeded: boolean }): SecurityDepositCollectionRecord;
  markRefundPending(collectionId: string): SecurityDepositCollectionRecord; getByOfferId(offerId: string): SecurityDepositCollectionRecord | null;
  getByCollectionId(collectionId: string): SecurityDepositCollectionRecord | null;
  journals(): readonly SecurityDepositJournal[]; }
export class InMemorySecurityDepositAccountingRepository implements SecurityDepositAccountingRepository {
  readonly #records = new Map<string, SecurityDepositCollectionRecord>(); readonly #journals: SecurityDepositJournal[] = [];
  createOrGet(input: { offerId: string; snapshot: SecurityDepositPolicySnapshot; paymentMethod: "fresh_card" | "bank_transfer"; providerReference?: string; capabilityVersion?: string }): SecurityDepositCollectionRecord { if (input.snapshot.amountKobo <= 0) throw new RangeError("Zero deposits have no collection record"); const collectionId = `security-deposit:${input.offerId}`; const old = this.#records.get(collectionId); if (old) { if (old.amountKobo !== input.snapshot.amountKobo || old.policyVersion !== input.snapshot.policyVersion || old.paymentMethod !== input.paymentMethod) throw new Error("Deposit collection identity conflict"); return old; } const record = Object.freeze({ collectionId, offerId: input.offerId, policyVersion: input.snapshot.policyVersion, amountKobo: input.snapshot.amountKobo, currency: "NGN" as const, paymentMethod: input.paymentMethod, ...(input.providerReference ? { providerReference: input.providerReference } : {}), ...(input.capabilityVersion ? { capabilityVersion: input.capabilityVersion } : {}), collectionVersion: 1, status: "awaiting_payment" as const }); this.#records.set(collectionId, record); return record; }
  recordCollection(id: string, atOrInput: string | { providerReference: string; capabilityVersion?: string; collectedAt: string }): SecurityDepositCollectionRecord { const r = this.#required(id); const input: { providerReference?: string; capabilityVersion?: string; collectedAt: string } = typeof atOrInput === "string" ? { collectedAt: atOrInput, providerReference: r.providerReference } : atOrInput; if (r.status === "held" || r.status === "refunded") { if (input.providerReference && r.providerReference && input.providerReference !== r.providerReference) throw new Error("Deposit collection identity conflict"); return r; } if (r.status !== "awaiting_payment" && r.status !== "collected_unbound") throw new Error("Deposit collection is not collectible"); if (!input.providerReference) throw new Error("Successful deposit provider reference is required"); if (r.providerReference && r.providerReference !== input.providerReference) throw new Error("Deposit collection identity conflict"); if (r.status === "collected_unbound") return r; const journal = createSecurityDepositJournal({ collectionId: id, amountKobo: r.amountKobo, direction: "collection", createdAt: input.collectedAt }); this.#journals.push(journal); const n = Object.freeze({ ...r, providerReference: input.providerReference, ...(input.capabilityVersion ? { capabilityVersion: input.capabilityVersion } : {}), collectionVersion: r.collectionVersion + 1, status: "collected_unbound" as const, collectedAt: input.collectedAt, collectionJournalId: journal.journalId }); this.#records.set(id, n); return n; }
  bind(id: string, input: { reservationId: string; contractId: string }): SecurityDepositCollectionRecord { const r = this.#required(id); if (r.reservationId && (r.reservationId !== input.reservationId || r.contractId !== input.contractId)) throw new Error("Deposit collection binding identity conflict"); if (r.status !== "collected_unbound" && r.status !== "held") throw new Error("Deposit must be collected before binding"); const n = Object.freeze({ ...r, ...input, collectionVersion: r.status === "held" ? r.collectionVersion : r.collectionVersion + 1, status: "held" as const }); this.#records.set(id, n); return n; }
  markRefundPending(id: string): SecurityDepositCollectionRecord { const r = this.#required(id); if (r.status === "refunded" || r.status === "refund_pending") return r; if (r.status !== "held" && r.status !== "collected_unbound") throw new Error("Deposit is not refundable"); const n = Object.freeze({ ...r, collectionVersion: r.collectionVersion + 1, status: "refund_pending" as const }); this.#records.set(id, n); return n; }
  refund(id: string, input: { refundedAt: string; refundSucceeded: boolean }): SecurityDepositCollectionRecord { const r = this.#required(id); if (r.status === "awaiting_payment") throw new Error("Cannot refund an uncollected deposit"); if (r.status === "refunded" || r.status === "reconciliation_required" && !input.refundSucceeded) return r; if (!input.refundSucceeded) { const n = Object.freeze({ ...r, collectionVersion: r.collectionVersion + 1, status: "reconciliation_required" as const }); this.#records.set(id, n); return n; } if (r.status !== "held" && r.status !== "collected_unbound" && r.status !== "refund_pending" && r.status !== "reconciliation_required") throw new Error("Deposit is not refundable"); const journal = createSecurityDepositJournal({ collectionId: id, amountKobo: r.amountKobo, direction: "refund", createdAt: input.refundedAt }); this.#journals.push(journal); const n = Object.freeze({ ...r, collectionVersion: r.collectionVersion + 1, status: "refunded" as const, refundedAt: input.refundedAt, refundJournalId: journal.journalId }); this.#records.set(id, n); return n; }
  getByOfferId(offerId: string): SecurityDepositCollectionRecord | null { return [...this.#records.values()].find((r) => r.offerId === offerId) ?? null; }
  getByCollectionId(collectionId: string): SecurityDepositCollectionRecord | null { return this.#records.get(collectionId) ?? null; }
  getByReservationId(reservationId: string): HeldSecurityDeposit | null { const r = [...this.#records.values()].find((x) => x.reservationId === reservationId); if (!r || (r.status !== "held" && r.status !== "refunded" && r.status !== "reconciliation_required")) return null; return Object.freeze({ collectionId: r.collectionId, collectionVersion: r.collectionVersion, reservationId, policyVersion: r.policyVersion, amountKobo: r.amountKobo, refundableBalanceKobo: r.status === "refunded" ? 0 : r.amountKobo, status: r.status, currency: "NGN" }); }
  journals(): readonly SecurityDepositJournal[] { return Object.freeze([...this.#journals]); }
  #required(id: string): SecurityDepositCollectionRecord { const r = this.#records.get(id); if (!r) throw new Error("Security deposit collection not found"); return r; }
}
