import { A2UI_V091_BASIC_CATALOG_ID, type A2UIComponent, type A2UIServerMessage } from "@weaver/core";
import type { CancellationArtifact } from "../../web/src/cancellation-artifact.js";
import { CANCELLATION_CANCEL_EVENT, CANCELLATION_NO_SHOW_EVENT, CANCELLATION_REVIEW_EVENT, cancellationActionContext } from "../../web/src/cancellation-actions.js";
export function cancellationArtifactToA2UI({ artifact, surfaceId }: { readonly artifact: CancellationArtifact; readonly surfaceId: string }): readonly A2UIServerMessage[] {
  const f = artifact.facts; const r = f.currentRefundEstimate; const components: A2UIComponent[] = [
    { id: "cancellation-root", component: "Column", children: ["cancellation-title", "cancellation-policy", "cancellation-effect", "cancellation-components", "cancellation-status", ...(artifact.actions.length ? ["cancellation-action", "cancellation-action-label"] : [])] },
    { id: "cancellation-title", component: "Text", text: "Cancellation", variant: "h2" },
    { id: "cancellation-policy", component: "Text", text: `Captured policy: ${f.policy.type} (${f.policy.version}). Check-in timing: Africa/Lagos.` },
    { id: "cancellation-effect", component: "Text", text: `Current refund: ${r.refundPercentage}% of Cancellation Base; NGN ${(r.cancellationBaseRefundKobo / 100).toLocaleString("en-NG")} base refund; total NGN ${(r.totalRefundKobo / 100).toLocaleString("en-NG")}.` },
    { id: "cancellation-components", component: "Text", text: `Stay refund: NGN ${(r.cancellationBaseRefundKobo / 100).toLocaleString("en-NG")}. Refundable Security Deposit: NGN ${(r.securityDepositRefundKobo / 100).toLocaleString("en-NG")} — ${f.case?.depositRefundStatus ?? "not_applicable"}. Cleaning, unprovided services, tax and duplicate payment remain separate. Refunds return to their original payment sources.` },
    { id: "cancellation-status", component: "Text", text: f.case ? `Reservation ${f.reservationStatus}; stay refund status: ${f.case.refundStatus}; deposit refund status: ${f.case.depositRefundStatus ?? "not_applicable"}.` : "No cancellation has been committed." }
  ];
  for (const [index, action] of artifact.actions.entries()) { const event = action.type === "confirm_no_show" ? CANCELLATION_NO_SHOW_EVENT : action.type === "apply_reviewed_cancellation" ? CANCELLATION_REVIEW_EVENT : CANCELLATION_CANCEL_EVENT; const label = action.type === "confirm_no_show" ? "Confirm No-Show" : action.type === "apply_reviewed_cancellation" ? "Apply reviewed cancellation" : "Cancel booking"; components.push({ id: `cancellation-action-${index}`, component: "Button", child: `cancellation-action-label-${index}`, variant: "primary", action: { event: { name: event, context: cancellationActionContext(action) } }, accessibility: { label } }, { id: `cancellation-action-label-${index}`, component: "Text", text: label }); }
  return Object.freeze([{ version: "v0.9.1", createSurface: { surfaceId, catalogId: A2UI_V091_BASIC_CATALOG_ID } }, { version: "v0.9.1", updateComponents: { surfaceId, components } }]);
}
