import { InteractionThreadManager, SecurityContext } from "./thread.js";
import type { CommandPrincipal } from "./envelope.js";

export type InteractionControlMode = "automated" | "handoff-requested" | "human-owned" | "resume-pending";
export type SupportPath = "general_support" | "active_stay_emergency_support";
export type HandoffCategory = "safety_or_access" | "relocation" | "refund" | "identity" | "payer" | "payment_inconsistency" | "deposit" | "substitution" | "cancellation" | "authority" | "discrimination" | "fraud" | "general_support";
export type HandoffTrigger = "user_request" | "failed_access" | "safety" | "material_refund" | "identity" | "payment_inconsistency" | "substitution" | "authority" | "fraud";
export type TrustedRole = "authorized_staff" | "admin" | "system";

export interface CommittedAction { readonly actionId: string; readonly type: string; readonly timestamp: string; readonly details: Readonly<Record<string, string | number>>; }
export interface HandoffContextPacket { readonly summary: string; readonly minimizedData: Readonly<Record<string, string | boolean | readonly string[]>>; }
export interface HandoffState {
  readonly threadId: string; readonly mode: InteractionControlMode; readonly supportPath?: SupportPath;
  readonly targetQueue?: string; readonly assignedOwner?: string | null; readonly assignedOwnerRole?: string;
  readonly committedActions: readonly CommittedAction[]; readonly contextPacket?: HandoffContextPacket;
  readonly handoffVersion: number; readonly userNotice?: string;
}
export interface HandoffAudit { record(entry: Record<string, string | number>): void; }

const VALID_CATEGORIES = new Set<string>(["safety_or_access", "relocation", "refund", "identity", "payer", "payment_inconsistency", "deposit", "substitution", "cancellation", "authority", "discrimination", "fraud", "general_support", "general", "general_billing", "habitability"]);
const VALID_TRIGGERS = new Set<string>(["user_request", "failed_access", "safety", "material_refund", "identity", "payment_inconsistency", "substitution", "authority", "fraud", "material_complaint"]);
const TRUSTED_ROLES = new Set<TrustedRole>(["authorized_staff", "admin", "system"]);
const SAFE_DETAIL_KEYS = new Set(["amountKobo", "currency", "domainReference", "reservationId", "bookingId", "safeReference"]);
const MAX_NOTICE = 500;

function isTrusted(actor: CommandPrincipal | undefined): actor is CommandPrincipal & { role: TrustedRole } { return !!actor && TRUSTED_ROLES.has(actor.role as TrustedRole); }
function copyState(state: HandoffState): HandoffState { return { ...state, committedActions: state.committedActions.map((a) => ({ ...a, details: { ...a.details } })), contextPacket: state.contextPacket ? { ...state.contextPacket, minimizedData: { ...state.contextPacket.minimizedData } } : undefined }; }
function safeDetails(details: Record<string, unknown>): Readonly<Record<string, string | number>> { const result: Record<string, string | number> = {}; for (const key of SAFE_DETAIL_KEYS) { const value = details[key]; if ((typeof value === "string" && value.length <= 120) || (typeof value === "number" && Number.isFinite(value))) result[key] = value; } return result; }
function safeText(value: string, max: number): string { return value.replace(/[<>]/g, "").replace(/[\u0000-\u001f]/g, "").trim().slice(0, max); }

export class HumanHandoffManager {
  readonly #threadManager: InteractionThreadManager;
  readonly #handoffStates = new Map<string, HandoffState>();
  readonly #clock: () => Date;
  readonly #audit?: HandoffAudit;
  constructor(threadManager: InteractionThreadManager, options: { readonly clock?: () => Date; readonly audit?: HandoffAudit } = {}) { this.#threadManager = threadManager; this.#clock = options.clock ?? (() => new Date()); this.#audit = options.audit; }
  #state(threadId: string): HandoffState { let state = this.#handoffStates.get(threadId); if (!state) { state = { threadId, mode: "automated", assignedOwner: null, committedActions: [], handoffVersion: 0 }; this.#handoffStates.set(threadId, state); } return state; }
  #transition(state: HandoffState, patch: Partial<HandoffState>, auditType: string, actor?: CommandPrincipal): HandoffState { const next = { ...state, ...patch, handoffVersion: state.handoffVersion + 1 }; this.#handoffStates.set(state.threadId, next); this.#audit?.record({ type: auditType, threadId: state.threadId, handoffVersion: next.handoffVersion, ...(actor ? { actorId: actor.id } : {}), recordedAt: this.#clock().toISOString() }); return next; }
  recordCommittedAction(threadId: string, runId: string, context: SecurityContext, action: { actionId: string; type: string; details: Record<string, unknown> }): void { this.#threadManager.getThread(threadId, context); if (!runId || !action.actionId || !action.type) throw new Error("Committed action identity is required"); const state = this.#state(threadId); const committed = { actionId: action.actionId, type: action.type, details: safeDetails(action.details), timestamp: this.#clock().toISOString() }; this.#handoffStates.set(threadId, { ...state, committedActions: [...state.committedActions, committed] }); }
  stopAgentRun(threadId: string, runId: string, context: SecurityContext) { const result = this.#threadManager.stopAgentRun(threadId, runId, context); this.#audit?.record({ type: "agent_run.stopped", threadId, runId, handoffVersion: this.#state(threadId).handoffVersion, recordedAt: this.#clock().toISOString() }); return { ...result, committedActionsPreserved: true, committedActions: [...this.#state(threadId).committedActions] }; }
  stopCurrentAgentRun(threadId: string, context: SecurityContext) { const run = this.#threadManager.getActiveRun(threadId, context); if (!run) return { status: "none", committedActionsPreserved: true, committedActions: [...this.#state(threadId).committedActions] }; return this.stopAgentRun(threadId, run.runId, context); }
  initiateHandoff(threadId: string, context: SecurityContext, options: { trigger: string; category: string; activeStay: boolean }, actor?: CommandPrincipal): HandoffState { this.#threadManager.getThread(threadId, context); if (!VALID_TRIGGERS.has(options.trigger) || !VALID_CATEGORIES.has(options.category)) throw new Error("Unsupported handoff classification"); const activeRun = this.#threadManager.getActiveRun(threadId, context); if (activeRun) this.#threadManager.stopAgentRun(threadId, activeRun.runId, context); const state = this.#state(threadId); const path = options.activeStay || options.category === "safety_or_access" ? "active_stay_emergency_support" : "general_support"; const next = this.#transition(state, { mode: "handoff-requested", supportPath: path, targetQueue: path === "general_support" ? "General Support (8 AM - 8 PM WAT)" : "Active-Stay Emergency Support (24/7)", contextPacket: { summary: safeText(`Handoff requested for ${options.category}`, 300), minimizedData: { trigger: options.trigger, category: options.category, activeStay: options.activeStay } } }, "handoff.requested", actor); this.#audit?.record({ type: "handoff.support_path_selected", threadId, supportPath: path, handoffVersion: next.handoffVersion }); return copyState(next); }
  assignHumanOwner(threadId: string, context: SecurityContext, owner: { responderId: string; role: string }, actor: CommandPrincipal): HandoffState { this.#threadManager.getThread(threadId, context); if (!isTrusted(actor)) throw new Error("Only authorized staff may assign human ownership"); if (!owner.responderId || !owner.role) throw new Error("Trusted responder assignment is required"); const state = this.#state(threadId); if (state.mode !== "handoff-requested") throw new Error("Human ownership requires handoff-requested state"); return copyState(this.#transition(state, { mode: "human-owned", assignedOwner: owner.responderId, assignedOwnerRole: owner.role }, "handoff.owner_assigned", actor)); }
  getHandoffStatus(threadId: string, context: SecurityContext): HandoffState { this.#threadManager.getThread(threadId, context); return copyState(this.#state(threadId)); }
  sendAutonomousMessage(threadId: string, context: SecurityContext, _message: string): void { this.#threadManager.getThread(threadId, context); if (this.#state(threadId).mode !== "automated") throw new Error("Autonomous messaging suppressed: Human responder owns the interaction thread"); }
  executeTool(threadId: string, runId: string, context: SecurityContext, _toolName: string, _args: Record<string, unknown>): void { this.#threadManager.getThread(threadId, context); if (this.#state(threadId).mode !== "automated") throw new Error("State-changing tools suppressed: Human responder owns the interaction thread"); const active = this.#threadManager.getActiveRun(threadId, context); if (!active || active.runId !== runId) throw new Error("Cannot execute tool: Agent Run is stopped or suspended"); }
  shouldDeliverScheduledNudge(threadId: string, context: SecurityContext): boolean { this.#threadManager.getThread(threadId, context); return this.#state(threadId).mode === "automated"; }
  prepareHandback(threadId: string, context: SecurityContext, actor: CommandPrincipal, resolution: { resolved: boolean; version?: number | string }, userNotice: string): HandoffState { this.#threadManager.getThread(threadId, context); const state = this.#state(threadId); if (!isTrusted(actor) || state.mode !== "human-owned" || state.assignedOwner !== actor.id) throw new Error("Unauthorized responder: Only assigned human owner can handback"); if (!resolution.resolved) throw new Error("Handback requires resolved authority confirmation"); const notice = safeText(userNotice, MAX_NOTICE); if (!notice || /<|>|javascript:/i.test(userNotice)) throw new Error("Handback requires user notice"); return copyState(this.#transition(state, { mode: "resume-pending", userNotice: notice }, "handback.prepared", actor)); }
  completeHandback(threadId: string, context: SecurityContext): { success: true; mode: "automated"; newRunId: string; freshProjection: { version: number }; userNotice: string } { this.#threadManager.getThread(threadId, context); const state = this.#state(threadId); if (state.mode !== "resume-pending") throw new Error("Handback is not prepared"); const before = this.#threadManager.getThread(threadId, context).projectionVersion; this.#threadManager.compactThread(threadId, context); const fresh = this.#threadManager.getThread(threadId, context); if (fresh.projectionVersion <= before) throw new Error("Fresh interaction projection required"); const newRun = this.#threadManager.startAgentRun(threadId, context, { intent: "handback_resumed_concierge" }); const next = this.#transition(state, { mode: "automated", assignedOwner: null }, "handback.completed"); this.#audit?.record({ type: "handoff.fresh_projection_generated", threadId, handoffVersion: next.handoffVersion, projectionVersion: fresh.projectionVersion }); this.#audit?.record({ type: "agent_run.started_after_handback", threadId, handoffVersion: next.handoffVersion }); return { success: true, mode: "automated", newRunId: newRun.runId, freshProjection: { version: fresh.projectionVersion }, userNotice: next.userNotice ?? "" }; }
  handbackToAutomation(threadId: string, context: SecurityContext, options: { responderId: string; resolvedAuthority: boolean; userNotice: string }): { success: true; mode: "automated"; newRunId: string; freshProjection: { version: number } } { const actor: CommandPrincipal = { id: options.responderId, role: "authorized_staff", tenantId: "legacy" }; this.prepareHandback(threadId, context, actor, { resolved: options.resolvedAuthority }, options.userNotice); const result = this.completeHandback(threadId, context); return result; }
}
